// Generated by jextract

package com.github.tornaia.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class cfapi_h$constants$4 extends cfapi_h$constants$3 {

    /* package-private */ cfapi_h$constants$4() {}
    static final int PFD_DIRECT3D_ACCELERATED() { return (int)16384L; }

    static final int PFD_SUPPORT_COMPOSITION() { return (int)32768L; }

    static final int PFD_DEPTH_DONTCARE() { return (int)536870912L; }

    static final int PFD_DOUBLEBUFFER_DONTCARE() { return (int)1073741824L; }

    static final int DC_BINADJUST() { return (int)19L; }

    static final int DC_EMF_COMPLIANT() { return (int)20L; }

    static final int DC_DATATYPE_PRODUCED() { return (int)21L; }

    static final int DC_COLLATE() { return (int)22L; }

    static final int DC_MANUFACTURER() { return (int)23L; }

    static final int DC_MODEL() { return (int)24L; }

    static final int DC_PERSONALITY() { return (int)25L; }

    static final int DC_PRINTRATE() { return (int)26L; }

    static final int DC_PRINTRATEUNIT() { return (int)27L; }

    static final int PRINTRATEUNIT_PPM() { return (int)1L; }

    static final int PRINTRATEUNIT_CPS() { return (int)2L; }

    static final int PRINTRATEUNIT_LPM() { return (int)3L; }

    static final int PRINTRATEUNIT_IPM() { return (int)4L; }

    static final int DC_PRINTERMEM() { return (int)28L; }

    static final int DC_MEDIAREADY() { return (int)29L; }

    static final int DC_STAPLE() { return (int)30L; }

    static final int DC_PRINTRATEPPM() { return (int)31L; }

    static final int DC_COLORDEVICE() { return (int)32L; }

    static final int DC_NUP() { return (int)33L; }

    static final int DC_MEDIATYPENAMES() { return (int)34L; }

    static final int DC_MEDIATYPES() { return (int)35L; }

    static final int DCBA_FACEUPNONE() { return (int)0L; }

    static final int DCBA_FACEUPCENTER() { return (int)1L; }

    static final int DCBA_FACEUPLEFT() { return (int)2L; }

    static final int DCBA_FACEUPRIGHT() { return (int)3L; }

    static final int DCBA_FACEDOWNNONE() { return (int)256L; }

    static final int DCBA_FACEDOWNCENTER() { return (int)257L; }

    static final int DCBA_FACEDOWNLEFT() { return (int)258L; }

    static final int DCBA_FACEDOWNRIGHT() { return (int)259L; }

    static final int GS_8BIT_INDICES() { return (int)1L; }

    static final int GGI_MARK_NONEXISTING_GLYPHS() { return (int)1L; }

    static final int MM_MAX_NUMAXES() { return (int)16L; }

    static final int FR_PRIVATE() { return (int)16L; }

    static final int FR_NOT_ENUM() { return (int)32L; }

    static final int MM_MAX_AXES_NAMELEN() { return (int)16L; }

    static final int AC_SRC_OVER() { return (int)0L; }

    static final int AC_SRC_ALPHA() { return (int)1L; }

    static final int GRADIENT_FILL_RECT_H() { return (int)0L; }

    static final int GRADIENT_FILL_RECT_V() { return (int)1L; }

    static final int GRADIENT_FILL_TRIANGLE() { return (int)2L; }

    static final int GRADIENT_FILL_OP_FLAG() { return (int)255L; }

    static final int CA_NEGATIVE() { return (int)1L; }

    static final int CA_LOG_FILTER() { return (int)2L; }

    static final int ILLUMINANT_DEVICE_DEFAULT() { return (int)0L; }

    static final int ILLUMINANT_A() { return (int)1L; }

    static final int ILLUMINANT_B() { return (int)2L; }

    static final int ILLUMINANT_C() { return (int)3L; }

    static final int ILLUMINANT_D50() { return (int)4L; }

    static final int ILLUMINANT_D55() { return (int)5L; }

    static final int ILLUMINANT_D65() { return (int)6L; }

    static final int ILLUMINANT_D75() { return (int)7L; }

    static final int ILLUMINANT_F2() { return (int)8L; }

    static final int DI_APPBANDING() { return (int)1L; }

    static final int DI_ROPS_READ_DESTINATION() { return (int)2L; }

    static final int FONTMAPPER_MAX() { return (int)10L; }

    static final int ICM_OFF() { return (int)1L; }

    static final int ICM_ON() { return (int)2L; }

    static final int ICM_QUERY() { return (int)3L; }

    static final int ICM_DONE_OUTSIDEDC() { return (int)4L; }

    static final int ENHMETA_SIGNATURE() { return (int)1179469088L; }

    static final int EMR_HEADER() { return (int)1L; }

    static final int EMR_POLYBEZIER() { return (int)2L; }

    static final int EMR_POLYGON() { return (int)3L; }

    static final int EMR_POLYLINE() { return (int)4L; }

    static final int EMR_POLYBEZIERTO() { return (int)5L; }

    static final int EMR_POLYLINETO() { return (int)6L; }

    static final int EMR_POLYPOLYLINE() { return (int)7L; }

    static final int EMR_POLYPOLYGON() { return (int)8L; }

    static final int EMR_SETWINDOWEXTEX() { return (int)9L; }

    static final int EMR_SETWINDOWORGEX() { return (int)10L; }

    static final int EMR_SETVIEWPORTEXTEX() { return (int)11L; }

    static final int EMR_SETVIEWPORTORGEX() { return (int)12L; }

    static final int EMR_SETBRUSHORGEX() { return (int)13L; }

    static final int EMR_EOF() { return (int)14L; }

    static final int EMR_SETPIXELV() { return (int)15L; }

    static final int EMR_SETMAPPERFLAGS() { return (int)16L; }

    static final int EMR_SETMAPMODE() { return (int)17L; }

    static final int EMR_SETBKMODE() { return (int)18L; }

    static final int EMR_SETPOLYFILLMODE() { return (int)19L; }

    static final int EMR_SETROP2() { return (int)20L; }

    static final int EMR_SETSTRETCHBLTMODE() { return (int)21L; }

    static final int EMR_SETTEXTALIGN() { return (int)22L; }

    static final int EMR_SETCOLORADJUSTMENT() { return (int)23L; }

    static final int EMR_SETTEXTCOLOR() { return (int)24L; }

    static final int EMR_SETBKCOLOR() { return (int)25L; }

    static final int EMR_OFFSETCLIPRGN() { return (int)26L; }

    static final int EMR_MOVETOEX() { return (int)27L; }

    static final int EMR_SETMETARGN() { return (int)28L; }

    static final int EMR_EXCLUDECLIPRECT() { return (int)29L; }

    static final int EMR_INTERSECTCLIPRECT() { return (int)30L; }

    static final int EMR_SCALEVIEWPORTEXTEX() { return (int)31L; }

    static final int EMR_SCALEWINDOWEXTEX() { return (int)32L; }

    static final int EMR_SAVEDC() { return (int)33L; }

    static final int EMR_RESTOREDC() { return (int)34L; }

    static final int EMR_SETWORLDTRANSFORM() { return (int)35L; }

    static final int EMR_MODIFYWORLDTRANSFORM() { return (int)36L; }

    static final int EMR_SELECTOBJECT() { return (int)37L; }

    static final int EMR_CREATEPEN() { return (int)38L; }

    static final int EMR_CREATEBRUSHINDIRECT() { return (int)39L; }

    static final int EMR_DELETEOBJECT() { return (int)40L; }

    static final int EMR_ANGLEARC() { return (int)41L; }

    static final int EMR_ELLIPSE() { return (int)42L; }

    static final int EMR_RECTANGLE() { return (int)43L; }

    static final int EMR_ROUNDRECT() { return (int)44L; }

    static final int EMR_ARC() { return (int)45L; }

    static final int EMR_CHORD() { return (int)46L; }

    static final int EMR_PIE() { return (int)47L; }

    static final int EMR_SELECTPALETTE() { return (int)48L; }

    static final int EMR_CREATEPALETTE() { return (int)49L; }

    static final int EMR_SETPALETTEENTRIES() { return (int)50L; }

    static final int EMR_RESIZEPALETTE() { return (int)51L; }

    static final int EMR_REALIZEPALETTE() { return (int)52L; }

    static final int EMR_EXTFLOODFILL() { return (int)53L; }

    static final int EMR_LINETO() { return (int)54L; }

    static final int EMR_ARCTO() { return (int)55L; }

    static final int EMR_POLYDRAW() { return (int)56L; }

    static final int EMR_SETARCDIRECTION() { return (int)57L; }

    static final int EMR_SETMITERLIMIT() { return (int)58L; }

    static final int EMR_BEGINPATH() { return (int)59L; }

    static final int EMR_ENDPATH() { return (int)60L; }

    static final int EMR_CLOSEFIGURE() { return (int)61L; }

    static final int EMR_FILLPATH() { return (int)62L; }

    static final int EMR_STROKEANDFILLPATH() { return (int)63L; }

    static final int EMR_STROKEPATH() { return (int)64L; }

    static final int EMR_FLATTENPATH() { return (int)65L; }

    static final int EMR_WIDENPATH() { return (int)66L; }

    static final int EMR_SELECTCLIPPATH() { return (int)67L; }

    static final int EMR_ABORTPATH() { return (int)68L; }

    static final int EMR_GDICOMMENT() { return (int)70L; }

    static final int EMR_FILLRGN() { return (int)71L; }

    static final int EMR_FRAMERGN() { return (int)72L; }

    static final int EMR_INVERTRGN() { return (int)73L; }

    static final int EMR_PAINTRGN() { return (int)74L; }

    static final int EMR_EXTSELECTCLIPRGN() { return (int)75L; }

    static final int EMR_BITBLT() { return (int)76L; }

    static final int EMR_STRETCHBLT() { return (int)77L; }

    static final int EMR_MASKBLT() { return (int)78L; }

    static final int EMR_PLGBLT() { return (int)79L; }

    static final int EMR_SETDIBITSTODEVICE() { return (int)80L; }

    static final int EMR_STRETCHDIBITS() { return (int)81L; }

    static final int EMR_EXTCREATEFONTINDIRECTW() { return (int)82L; }

    static final int EMR_EXTTEXTOUTA() { return (int)83L; }

    static final int EMR_EXTTEXTOUTW() { return (int)84L; }

    static final int EMR_POLYBEZIER16() { return (int)85L; }

    static final int EMR_POLYGON16() { return (int)86L; }

    static final int EMR_POLYLINE16() { return (int)87L; }

    static final int EMR_POLYBEZIERTO16() { return (int)88L; }

    static final int EMR_POLYLINETO16() { return (int)89L; }

    static final int EMR_POLYPOLYLINE16() { return (int)90L; }

    static final int EMR_POLYPOLYGON16() { return (int)91L; }

    static final int EMR_POLYDRAW16() { return (int)92L; }

    static final int EMR_CREATEMONOBRUSH() { return (int)93L; }

    static final int EMR_CREATEDIBPATTERNBRUSHPT() { return (int)94L; }

    static final int EMR_EXTCREATEPEN() { return (int)95L; }

    static final int EMR_POLYTEXTOUTA() { return (int)96L; }

    static final int EMR_POLYTEXTOUTW() { return (int)97L; }

    static final int EMR_SETICMMODE() { return (int)98L; }

    static final int EMR_CREATECOLORSPACE() { return (int)99L; }

    static final int EMR_SETCOLORSPACE() { return (int)100L; }

    static final int EMR_DELETECOLORSPACE() { return (int)101L; }

    static final int EMR_GLSRECORD() { return (int)102L; }

    static final int EMR_GLSBOUNDEDRECORD() { return (int)103L; }

    static final int EMR_PIXELFORMAT() { return (int)104L; }

    static final int EMR_RESERVED_105() { return (int)105L; }

    static final int EMR_RESERVED_106() { return (int)106L; }

    static final int EMR_RESERVED_107() { return (int)107L; }

    static final int EMR_RESERVED_108() { return (int)108L; }

    static final int EMR_RESERVED_109() { return (int)109L; }

    static final int EMR_RESERVED_110() { return (int)110L; }

    static final int EMR_COLORCORRECTPALETTE() { return (int)111L; }

    static final int EMR_SETICMPROFILEA() { return (int)112L; }

    static final int EMR_SETICMPROFILEW() { return (int)113L; }

    static final int EMR_ALPHABLEND() { return (int)114L; }

    static final int EMR_SETLAYOUT() { return (int)115L; }

    static final int EMR_TRANSPARENTBLT() { return (int)116L; }

    static final int EMR_RESERVED_117() { return (int)117L; }

    static final int EMR_GRADIENTFILL() { return (int)118L; }

    static final int EMR_RESERVED_119() { return (int)119L; }

    static final int EMR_RESERVED_120() { return (int)120L; }

    static final int EMR_COLORMATCHTOTARGETW() { return (int)121L; }

    static final int EMR_CREATECOLORSPACEW() { return (int)122L; }

    static final int EMR_MIN() { return (int)1L; }

    static final int EMR_MAX() { return (int)122L; }

    static final int SETICMPROFILE_EMBEDED() { return (int)1L; }

    static final int CREATECOLORSPACE_EMBEDED() { return (int)1L; }

    static final int COLORMATCHTOTARGET_EMBEDED() { return (int)1L; }

    static final int GDICOMMENT_IDENTIFIER() { return (int)1128875079L; }

    static final int GDICOMMENT_BEGINGROUP() { return (int)2L; }

    static final int GDICOMMENT_ENDGROUP() { return (int)3L; }

    static final int GDICOMMENT_MULTIFORMATS() { return (int)1073741828L; }

    static final int EPS_SIGNATURE() { return (int)1179865157L; }

    static final int GDICOMMENT_UNICODE_STRING() { return (int)64L; }

    static final int GDICOMMENT_UNICODE_END() { return (int)128L; }

    static final int WGL_FONT_LINES() { return (int)0L; }

    static final int WGL_FONT_POLYGONS() { return (int)1L; }

    static final int LPD_DOUBLEBUFFER() { return (int)1L; }

    static final int LPD_STEREO() { return (int)2L; }

    static final int LPD_SUPPORT_GDI() { return (int)16L; }

    static final int LPD_SUPPORT_OPENGL() { return (int)32L; }

    static final int LPD_SHARE_DEPTH() { return (int)64L; }

    static final int LPD_SHARE_STENCIL() { return (int)128L; }

    static final int LPD_SHARE_ACCUM() { return (int)256L; }

    static final int LPD_SWAP_EXCHANGE() { return (int)512L; }

    static final int LPD_SWAP_COPY() { return (int)1024L; }

    static final int LPD_TRANSPARENT() { return (int)4096L; }

    static final int LPD_TYPE_RGBA() { return (int)0L; }

    static final int LPD_TYPE_COLORINDEX() { return (int)1L; }

    static final int WGL_SWAP_MAIN_PLANE() { return (int)1L; }

    static final int WGL_SWAP_OVERLAY1() { return (int)2L; }

    static final int WGL_SWAP_OVERLAY2() { return (int)4L; }

    static final int WGL_SWAP_OVERLAY3() { return (int)8L; }

    static final int WGL_SWAP_OVERLAY4() { return (int)16L; }

    static final int WGL_SWAP_OVERLAY5() { return (int)32L; }

    static final int WGL_SWAP_OVERLAY6() { return (int)64L; }

    static final int WGL_SWAP_OVERLAY7() { return (int)128L; }

    static final int WGL_SWAP_OVERLAY8() { return (int)256L; }

    static final int WGL_SWAP_OVERLAY9() { return (int)512L; }

    static final int WGL_SWAP_OVERLAY10() { return (int)1024L; }

    static final int WGL_SWAP_OVERLAY11() { return (int)2048L; }

    static final int WGL_SWAP_OVERLAY12() { return (int)4096L; }

    static final int WGL_SWAP_OVERLAY13() { return (int)8192L; }

    static final int WGL_SWAP_OVERLAY14() { return (int)16384L; }

    static final int WGL_SWAP_OVERLAY15() { return (int)32768L; }

    static final int WGL_SWAP_UNDERLAY1() { return (int)65536L; }

    static final int WGL_SWAP_UNDERLAY2() { return (int)131072L; }

    static final int WGL_SWAP_UNDERLAY3() { return (int)262144L; }

    static final int WGL_SWAP_UNDERLAY4() { return (int)524288L; }

    static final int WGL_SWAP_UNDERLAY5() { return (int)1048576L; }

    static final int WGL_SWAP_UNDERLAY6() { return (int)2097152L; }

    static final int WGL_SWAP_UNDERLAY7() { return (int)4194304L; }

    static final int WGL_SWAP_UNDERLAY8() { return (int)8388608L; }

    static final int WGL_SWAP_UNDERLAY9() { return (int)16777216L; }

    static final int WGL_SWAP_UNDERLAY10() { return (int)33554432L; }

    static final int WGL_SWAP_UNDERLAY11() { return (int)67108864L; }

    static final int WGL_SWAP_UNDERLAY12() { return (int)134217728L; }

    static final int WGL_SWAP_UNDERLAY13() { return (int)268435456L; }

    static final int WGL_SWAP_UNDERLAY14() { return (int)536870912L; }

    static final int WGL_SWAP_UNDERLAY15() { return (int)1073741824L; }

    static final int WGL_SWAPMULTIPLE_MAX() { return (int)16L; }

    static final int DIFFERENCE() { return (int)11L; }

    static final int SB_HORZ() { return (int)0L; }

    static final int SB_VERT() { return (int)1L; }

    static final int SB_CTL() { return (int)2L; }

    static final int SB_BOTH() { return (int)3L; }

    static final int SB_LINEUP() { return (int)0L; }

    static final int SB_LINELEFT() { return (int)0L; }

    static final int SB_LINEDOWN() { return (int)1L; }

    static final int SB_LINERIGHT() { return (int)1L; }

    static final int SB_PAGEUP() { return (int)2L; }

    static final int SB_PAGELEFT() { return (int)2L; }

    static final int SB_PAGEDOWN() { return (int)3L; }

    static final int SB_PAGERIGHT() { return (int)3L; }

    static final int SB_THUMBPOSITION() { return (int)4L; }

    static final int SB_THUMBTRACK() { return (int)5L; }

    static final int SB_TOP() { return (int)6L; }

    static final int SB_LEFT() { return (int)6L; }

    static final int SB_BOTTOM() { return (int)7L; }

    static final int SB_RIGHT() { return (int)7L; }

    static final int SB_ENDSCROLL() { return (int)8L; }

    static final int SW_HIDE() { return (int)0L; }

    static final int SW_SHOWNORMAL() { return (int)1L; }

    static final int SW_NORMAL() { return (int)1L; }

    static final int SW_SHOWMINIMIZED() { return (int)2L; }

    static final int SW_SHOWMAXIMIZED() { return (int)3L; }

    static final int SW_MAXIMIZE() { return (int)3L; }

    static final int SW_SHOWNOACTIVATE() { return (int)4L; }

    static final int SW_SHOW() { return (int)5L; }

    static final int SW_MINIMIZE() { return (int)6L; }

    static final int SW_SHOWMINNOACTIVE() { return (int)7L; }

    static final int SW_SHOWNA() { return (int)8L; }

    static final int SW_RESTORE() { return (int)9L; }

    static final int SW_SHOWDEFAULT() { return (int)10L; }

    static final int SW_FORCEMINIMIZE() { return (int)11L; }

    static final int SW_MAX() { return (int)11L; }

    static final int HIDE_WINDOW() { return (int)0L; }

    static final int SHOW_OPENWINDOW() { return (int)1L; }

    static final int SHOW_ICONWINDOW() { return (int)2L; }

    static final int SHOW_FULLSCREEN() { return (int)3L; }

    static final int SHOW_OPENNOACTIVATE() { return (int)4L; }

    static final int SW_PARENTCLOSING() { return (int)1L; }

    static final int SW_OTHERZOOM() { return (int)2L; }

    static final int SW_PARENTOPENING() { return (int)3L; }

    static final int SW_OTHERUNZOOM() { return (int)4L; }

    static final int AW_HOR_POSITIVE() { return (int)1L; }

    static final int AW_HOR_NEGATIVE() { return (int)2L; }

    static final int AW_VER_POSITIVE() { return (int)4L; }

    static final int AW_VER_NEGATIVE() { return (int)8L; }

    static final int AW_CENTER() { return (int)16L; }

    static final int AW_HIDE() { return (int)65536L; }

    static final int AW_ACTIVATE() { return (int)131072L; }

    static final int AW_SLIDE() { return (int)262144L; }

    static final int AW_BLEND() { return (int)524288L; }

    static final int KF_EXTENDED() { return (int)256L; }

    static final int KF_DLGMODE() { return (int)2048L; }

    static final int KF_MENUMODE() { return (int)4096L; }

    static final int KF_ALTDOWN() { return (int)8192L; }

    static final int KF_REPEAT() { return (int)16384L; }

    static final int KF_UP() { return (int)32768L; }

    static final int VK_LBUTTON() { return (int)1L; }

    static final int VK_RBUTTON() { return (int)2L; }

    static final int VK_CANCEL() { return (int)3L; }

    static final int VK_MBUTTON() { return (int)4L; }

    static final int VK_XBUTTON1() { return (int)5L; }

    static final int VK_XBUTTON2() { return (int)6L; }

    static final int VK_BACK() { return (int)8L; }

    static final int VK_TAB() { return (int)9L; }

    static final int VK_CLEAR() { return (int)12L; }

    static final int VK_RETURN() { return (int)13L; }

    static final int VK_SHIFT() { return (int)16L; }

    static final int VK_CONTROL() { return (int)17L; }

    static final int VK_MENU() { return (int)18L; }

    static final int VK_PAUSE() { return (int)19L; }

    static final int VK_CAPITAL() { return (int)20L; }

    static final int VK_KANA() { return (int)21L; }

    static final int VK_HANGEUL() { return (int)21L; }

    static final int VK_HANGUL() { return (int)21L; }

    static final int VK_JUNJA() { return (int)23L; }

    static final int VK_FINAL() { return (int)24L; }

    static final int VK_HANJA() { return (int)25L; }

    static final int VK_KANJI() { return (int)25L; }

    static final int VK_ESCAPE() { return (int)27L; }

    static final int VK_CONVERT() { return (int)28L; }

    static final int VK_NONCONVERT() { return (int)29L; }

    static final int VK_ACCEPT() { return (int)30L; }

    static final int VK_MODECHANGE() { return (int)31L; }

    static final int VK_SPACE() { return (int)32L; }

    static final int VK_PRIOR() { return (int)33L; }

    static final int VK_NEXT() { return (int)34L; }

    static final int VK_END() { return (int)35L; }

    static final int VK_HOME() { return (int)36L; }

    static final int VK_LEFT() { return (int)37L; }

    static final int VK_UP() { return (int)38L; }

    static final int VK_RIGHT() { return (int)39L; }

    static final int VK_DOWN() { return (int)40L; }

    static final int VK_SELECT() { return (int)41L; }

    static final int VK_PRINT() { return (int)42L; }

    static final int VK_EXECUTE() { return (int)43L; }

    static final int VK_SNAPSHOT() { return (int)44L; }

    static final int VK_INSERT() { return (int)45L; }

    static final int VK_DELETE() { return (int)46L; }

    static final int VK_HELP() { return (int)47L; }

    static final int VK_LWIN() { return (int)91L; }

    static final int VK_RWIN() { return (int)92L; }

    static final int VK_APPS() { return (int)93L; }

    static final int VK_SLEEP() { return (int)95L; }

    static final int VK_NUMPAD0() { return (int)96L; }

    static final int VK_NUMPAD1() { return (int)97L; }

    static final int VK_NUMPAD2() { return (int)98L; }

    static final int VK_NUMPAD3() { return (int)99L; }

    static final int VK_NUMPAD4() { return (int)100L; }

    static final int VK_NUMPAD5() { return (int)101L; }

    static final int VK_NUMPAD6() { return (int)102L; }

    static final int VK_NUMPAD7() { return (int)103L; }

    static final int VK_NUMPAD8() { return (int)104L; }

    static final int VK_NUMPAD9() { return (int)105L; }

    static final int VK_MULTIPLY() { return (int)106L; }

    static final int VK_ADD() { return (int)107L; }

    static final int VK_SEPARATOR() { return (int)108L; }

    static final int VK_SUBTRACT() { return (int)109L; }

    static final int VK_DECIMAL() { return (int)110L; }

    static final int VK_DIVIDE() { return (int)111L; }

    static final int VK_F1() { return (int)112L; }

    static final int VK_F2() { return (int)113L; }

    static final int VK_F3() { return (int)114L; }

    static final int VK_F4() { return (int)115L; }

    static final int VK_F5() { return (int)116L; }

    static final int VK_F6() { return (int)117L; }

    static final int VK_F7() { return (int)118L; }

    static final int VK_F8() { return (int)119L; }

    static final int VK_F9() { return (int)120L; }

    static final int VK_F10() { return (int)121L; }

    static final int VK_F11() { return (int)122L; }

    static final int VK_F12() { return (int)123L; }

    static final int VK_F13() { return (int)124L; }

    static final int VK_F14() { return (int)125L; }

    static final int VK_F15() { return (int)126L; }

    static final int VK_F16() { return (int)127L; }

    static final int VK_F17() { return (int)128L; }

    static final int VK_F18() { return (int)129L; }

    static final int VK_F19() { return (int)130L; }

    static final int VK_F20() { return (int)131L; }

    static final int VK_F21() { return (int)132L; }

    static final int VK_F22() { return (int)133L; }

    static final int VK_F23() { return (int)134L; }

    static final int VK_F24() { return (int)135L; }

    static final int VK_NAVIGATION_VIEW() { return (int)136L; }

    static final int VK_NAVIGATION_MENU() { return (int)137L; }

    static final int VK_NAVIGATION_UP() { return (int)138L; }

    static final int VK_NAVIGATION_DOWN() { return (int)139L; }

    static final int VK_NAVIGATION_LEFT() { return (int)140L; }

    static final int VK_NAVIGATION_RIGHT() { return (int)141L; }

    static final int VK_NAVIGATION_ACCEPT() { return (int)142L; }

    static final int VK_NAVIGATION_CANCEL() { return (int)143L; }

    static final int VK_NUMLOCK() { return (int)144L; }

    static final int VK_SCROLL() { return (int)145L; }

    static final int VK_OEM_NEC_EQUAL() { return (int)146L; }

    static final int VK_OEM_FJ_JISHO() { return (int)146L; }

    static final int VK_OEM_FJ_MASSHOU() { return (int)147L; }

    static final int VK_OEM_FJ_TOUROKU() { return (int)148L; }

    static final int VK_OEM_FJ_LOYA() { return (int)149L; }

    static final int VK_OEM_FJ_ROYA() { return (int)150L; }

    static final int VK_LSHIFT() { return (int)160L; }

    static final int VK_RSHIFT() { return (int)161L; }

    static final int VK_LCONTROL() { return (int)162L; }

    static final int VK_RCONTROL() { return (int)163L; }

    static final int VK_LMENU() { return (int)164L; }

    static final int VK_RMENU() { return (int)165L; }

    static final int VK_BROWSER_BACK() { return (int)166L; }

    static final int VK_BROWSER_FORWARD() { return (int)167L; }

    static final int VK_BROWSER_REFRESH() { return (int)168L; }

    static final int VK_BROWSER_STOP() { return (int)169L; }

    static final int VK_BROWSER_SEARCH() { return (int)170L; }

    static final int VK_BROWSER_FAVORITES() { return (int)171L; }

    static final int VK_BROWSER_HOME() { return (int)172L; }

    static final int VK_VOLUME_MUTE() { return (int)173L; }

    static final int VK_VOLUME_DOWN() { return (int)174L; }

    static final int VK_VOLUME_UP() { return (int)175L; }

    static final int VK_MEDIA_NEXT_TRACK() { return (int)176L; }

    static final int VK_MEDIA_PREV_TRACK() { return (int)177L; }

    static final int VK_MEDIA_STOP() { return (int)178L; }

    static final int VK_MEDIA_PLAY_PAUSE() { return (int)179L; }

    static final int VK_LAUNCH_MAIL() { return (int)180L; }

    static final int VK_LAUNCH_MEDIA_SELECT() { return (int)181L; }

    static final int VK_LAUNCH_APP1() { return (int)182L; }

    static final int VK_LAUNCH_APP2() { return (int)183L; }

    static final int VK_OEM_1() { return (int)186L; }

    static final int VK_OEM_PLUS() { return (int)187L; }

    static final int VK_OEM_COMMA() { return (int)188L; }

    static final int VK_OEM_MINUS() { return (int)189L; }

    static final int VK_OEM_PERIOD() { return (int)190L; }

    static final int VK_OEM_2() { return (int)191L; }

    static final int VK_OEM_3() { return (int)192L; }

    static final int VK_GAMEPAD_A() { return (int)195L; }

    static final int VK_GAMEPAD_B() { return (int)196L; }

    static final int VK_GAMEPAD_X() { return (int)197L; }

    static final int VK_GAMEPAD_Y() { return (int)198L; }

    static final int VK_GAMEPAD_RIGHT_SHOULDER() { return (int)199L; }

    static final int VK_GAMEPAD_LEFT_SHOULDER() { return (int)200L; }

    static final int VK_GAMEPAD_LEFT_TRIGGER() { return (int)201L; }

    static final int VK_GAMEPAD_RIGHT_TRIGGER() { return (int)202L; }

    static final int VK_GAMEPAD_DPAD_UP() { return (int)203L; }

    static final int VK_GAMEPAD_DPAD_DOWN() { return (int)204L; }

    static final int VK_GAMEPAD_DPAD_LEFT() { return (int)205L; }

    static final int VK_GAMEPAD_DPAD_RIGHT() { return (int)206L; }

    static final int VK_GAMEPAD_MENU() { return (int)207L; }

    static final int VK_GAMEPAD_VIEW() { return (int)208L; }

    static final int VK_GAMEPAD_LEFT_THUMBSTICK_BUTTON() { return (int)209L; }

    static final int VK_GAMEPAD_RIGHT_THUMBSTICK_BUTTON() { return (int)210L; }

    static final int VK_GAMEPAD_LEFT_THUMBSTICK_UP() { return (int)211L; }

    static final int VK_GAMEPAD_LEFT_THUMBSTICK_DOWN() { return (int)212L; }

    static final int VK_GAMEPAD_LEFT_THUMBSTICK_RIGHT() { return (int)213L; }

    static final int VK_GAMEPAD_LEFT_THUMBSTICK_LEFT() { return (int)214L; }

    static final int VK_GAMEPAD_RIGHT_THUMBSTICK_UP() { return (int)215L; }

    static final int VK_GAMEPAD_RIGHT_THUMBSTICK_DOWN() { return (int)216L; }

    static final int VK_GAMEPAD_RIGHT_THUMBSTICK_RIGHT() { return (int)217L; }

    static final int VK_GAMEPAD_RIGHT_THUMBSTICK_LEFT() { return (int)218L; }

    static final int VK_OEM_4() { return (int)219L; }

    static final int VK_OEM_5() { return (int)220L; }

    static final int VK_OEM_6() { return (int)221L; }

    static final int VK_OEM_7() { return (int)222L; }

    static final int VK_OEM_8() { return (int)223L; }

    static final int VK_OEM_AX() { return (int)225L; }

    static final int VK_OEM_102() { return (int)226L; }

    static final int VK_ICO_HELP() { return (int)227L; }

    static final int VK_ICO_00() { return (int)228L; }

    static final int VK_PROCESSKEY() { return (int)229L; }

    static final int VK_ICO_CLEAR() { return (int)230L; }

    static final int VK_PACKET() { return (int)231L; }

    static final int VK_OEM_RESET() { return (int)233L; }

    static final int VK_OEM_JUMP() { return (int)234L; }

    static final int VK_OEM_PA1() { return (int)235L; }

    static final int VK_OEM_PA2() { return (int)236L; }

    static final int VK_OEM_PA3() { return (int)237L; }

    static final int VK_OEM_WSCTRL() { return (int)238L; }

    static final int VK_OEM_CUSEL() { return (int)239L; }

    static final int VK_OEM_ATTN() { return (int)240L; }

    static final int VK_OEM_FINISH() { return (int)241L; }

    static final int VK_OEM_COPY() { return (int)242L; }

    static final int VK_OEM_AUTO() { return (int)243L; }

    static final int VK_OEM_ENLW() { return (int)244L; }

    static final int VK_OEM_BACKTAB() { return (int)245L; }

    static final int VK_ATTN() { return (int)246L; }

    static final int VK_CRSEL() { return (int)247L; }

    static final int VK_EXSEL() { return (int)248L; }

    static final int VK_EREOF() { return (int)249L; }

    static final int VK_PLAY() { return (int)250L; }

    static final int VK_ZOOM() { return (int)251L; }

    static final int VK_NONAME() { return (int)252L; }

    static final int VK_PA1() { return (int)253L; }

    static final int VK_OEM_CLEAR() { return (int)254L; }

    static final int WH_JOURNALRECORD() { return (int)0L; }

    static final int WH_JOURNALPLAYBACK() { return (int)1L; }

    static final int WH_KEYBOARD() { return (int)2L; }

    static final int WH_GETMESSAGE() { return (int)3L; }

    static final int WH_CALLWNDPROC() { return (int)4L; }

    static final int WH_CBT() { return (int)5L; }

    static final int WH_SYSMSGFILTER() { return (int)6L; }

    static final int WH_MOUSE() { return (int)7L; }

    static final int WH_DEBUG() { return (int)9L; }

    static final int WH_SHELL() { return (int)10L; }

    static final int WH_FOREGROUNDIDLE() { return (int)11L; }

    static final int WH_CALLWNDPROCRET() { return (int)12L; }

    static final int WH_KEYBOARD_LL() { return (int)13L; }

    static final int WH_MOUSE_LL() { return (int)14L; }

    static final int WH_MAX() { return (int)14L; }

    static final int HC_ACTION() { return (int)0L; }

    static final int HC_GETNEXT() { return (int)1L; }

    static final int HC_SKIP() { return (int)2L; }

    static final int HC_NOREMOVE() { return (int)3L; }

    static final int HC_SYSMODALON() { return (int)4L; }

    static final int HC_SYSMODALOFF() { return (int)5L; }

    static final int HCBT_MOVESIZE() { return (int)0L; }

    static final int HCBT_MINMAX() { return (int)1L; }

    static final int HCBT_QS() { return (int)2L; }

    static final int HCBT_CREATEWND() { return (int)3L; }

    static final int HCBT_DESTROYWND() { return (int)4L; }

    static final int HCBT_ACTIVATE() { return (int)5L; }

    static final int HCBT_CLICKSKIPPED() { return (int)6L; }

    static final int HCBT_KEYSKIPPED() { return (int)7L; }

    static final int HCBT_SYSCOMMAND() { return (int)8L; }

    static final int HCBT_SETFOCUS() { return (int)9L; }

    static final int WTS_CONSOLE_CONNECT() { return (int)1L; }

    static final int WTS_CONSOLE_DISCONNECT() { return (int)2L; }

    static final int WTS_REMOTE_CONNECT() { return (int)3L; }

    static final int WTS_REMOTE_DISCONNECT() { return (int)4L; }

    static final int WTS_SESSION_LOGON() { return (int)5L; }

    static final int WTS_SESSION_LOGOFF() { return (int)6L; }

    static final int WTS_SESSION_LOCK() { return (int)7L; }

    static final int WTS_SESSION_UNLOCK() { return (int)8L; }

    static final int WTS_SESSION_REMOTE_CONTROL() { return (int)9L; }

    static final int WTS_SESSION_CREATE() { return (int)10L; }

    static final int WTS_SESSION_TERMINATE() { return (int)11L; }

    static final int MSGF_DIALOGBOX() { return (int)0L; }

    static final int MSGF_MESSAGEBOX() { return (int)1L; }

    static final int MSGF_MENU() { return (int)2L; }

    static final int MSGF_SCROLLBAR() { return (int)5L; }

    static final int MSGF_NEXTWINDOW() { return (int)6L; }

    static final int MSGF_MAX() { return (int)8L; }

    static final int MSGF_USER() { return (int)4096L; }

    static final int HSHELL_WINDOWCREATED() { return (int)1L; }

    static final int HSHELL_WINDOWDESTROYED() { return (int)2L; }

    static final int HSHELL_ACTIVATESHELLWINDOW() { return (int)3L; }

    static final int HSHELL_WINDOWACTIVATED() { return (int)4L; }

    static final int HSHELL_GETMINRECT() { return (int)5L; }

    static final int HSHELL_REDRAW() { return (int)6L; }

    static final int HSHELL_TASKMAN() { return (int)7L; }

    static final int HSHELL_LANGUAGE() { return (int)8L; }

    static final int HSHELL_SYSMENU() { return (int)9L; }

    static final int HSHELL_ENDTASK() { return (int)10L; }

    static final int HSHELL_ACCESSIBILITYSTATE() { return (int)11L; }

    static final int HSHELL_APPCOMMAND() { return (int)12L; }

    static final int HSHELL_WINDOWREPLACED() { return (int)13L; }

    static final int HSHELL_WINDOWREPLACING() { return (int)14L; }

    static final int HSHELL_MONITORCHANGED() { return (int)16L; }

    static final int HSHELL_HIGHBIT() { return (int)32768L; }

    static final int APPCOMMAND_BROWSER_BACKWARD() { return (int)1L; }

    static final int APPCOMMAND_BROWSER_FORWARD() { return (int)2L; }

    static final int APPCOMMAND_BROWSER_REFRESH() { return (int)3L; }

    static final int APPCOMMAND_BROWSER_STOP() { return (int)4L; }

    static final int APPCOMMAND_BROWSER_SEARCH() { return (int)5L; }

    static final int APPCOMMAND_BROWSER_FAVORITES() { return (int)6L; }

    static final int APPCOMMAND_BROWSER_HOME() { return (int)7L; }

    static final int APPCOMMAND_VOLUME_MUTE() { return (int)8L; }

    static final int APPCOMMAND_VOLUME_DOWN() { return (int)9L; }

    static final int APPCOMMAND_VOLUME_UP() { return (int)10L; }

    static final int APPCOMMAND_MEDIA_NEXTTRACK() { return (int)11L; }

    static final int APPCOMMAND_MEDIA_PREVIOUSTRACK() { return (int)12L; }

    static final int APPCOMMAND_MEDIA_STOP() { return (int)13L; }

    static final int APPCOMMAND_MEDIA_PLAY_PAUSE() { return (int)14L; }

    static final int APPCOMMAND_LAUNCH_MAIL() { return (int)15L; }

    static final int APPCOMMAND_LAUNCH_MEDIA_SELECT() { return (int)16L; }

    static final int APPCOMMAND_LAUNCH_APP1() { return (int)17L; }

    static final int APPCOMMAND_LAUNCH_APP2() { return (int)18L; }

    static final int APPCOMMAND_BASS_DOWN() { return (int)19L; }

    static final int APPCOMMAND_BASS_BOOST() { return (int)20L; }

    static final int APPCOMMAND_BASS_UP() { return (int)21L; }

    static final int APPCOMMAND_TREBLE_DOWN() { return (int)22L; }

    static final int APPCOMMAND_TREBLE_UP() { return (int)23L; }

    static final int APPCOMMAND_MICROPHONE_VOLUME_MUTE() { return (int)24L; }

    static final int APPCOMMAND_MICROPHONE_VOLUME_DOWN() { return (int)25L; }

    static final int APPCOMMAND_MICROPHONE_VOLUME_UP() { return (int)26L; }

    static final int APPCOMMAND_HELP() { return (int)27L; }

    static final int APPCOMMAND_FIND() { return (int)28L; }

    static final int APPCOMMAND_NEW() { return (int)29L; }

    static final int APPCOMMAND_OPEN() { return (int)30L; }

    static final int APPCOMMAND_CLOSE() { return (int)31L; }

    static final int APPCOMMAND_SAVE() { return (int)32L; }

    static final int APPCOMMAND_PRINT() { return (int)33L; }

    static final int APPCOMMAND_UNDO() { return (int)34L; }

    static final int APPCOMMAND_REDO() { return (int)35L; }

    static final int APPCOMMAND_COPY() { return (int)36L; }

    static final int APPCOMMAND_CUT() { return (int)37L; }

    static final int APPCOMMAND_PASTE() { return (int)38L; }

    static final int APPCOMMAND_REPLY_TO_MAIL() { return (int)39L; }

    static final int APPCOMMAND_FORWARD_MAIL() { return (int)40L; }

    static final int APPCOMMAND_SEND_MAIL() { return (int)41L; }

    static final int APPCOMMAND_SPELL_CHECK() { return (int)42L; }

    static final int APPCOMMAND_DICTATE_OR_COMMAND_CONTROL_TOGGLE() { return (int)43L; }

    static final int APPCOMMAND_MIC_ON_OFF_TOGGLE() { return (int)44L; }

    static final int APPCOMMAND_CORRECTION_LIST() { return (int)45L; }

    static final int APPCOMMAND_MEDIA_PLAY() { return (int)46L; }

    static final int APPCOMMAND_MEDIA_PAUSE() { return (int)47L; }

    static final int APPCOMMAND_MEDIA_RECORD() { return (int)48L; }

    static final int APPCOMMAND_MEDIA_FAST_FORWARD() { return (int)49L; }

    static final int APPCOMMAND_MEDIA_REWIND() { return (int)50L; }

    static final int APPCOMMAND_MEDIA_CHANNEL_UP() { return (int)51L; }

    static final int APPCOMMAND_MEDIA_CHANNEL_DOWN() { return (int)52L; }

    static final int APPCOMMAND_DELETE() { return (int)53L; }

    static final int APPCOMMAND_DWM_FLIP3D() { return (int)54L; }

    static final int FAPPCOMMAND_MOUSE() { return (int)32768L; }

    static final int FAPPCOMMAND_KEY() { return (int)0L; }

    static final int FAPPCOMMAND_OEM() { return (int)4096L; }

    static final int FAPPCOMMAND_MASK() { return (int)61440L; }

    static final int LLKHF_INJECTED() { return (int)16L; }

    static final int LLKHF_LOWER_IL_INJECTED() { return (int)2L; }

    static final int LLMHF_INJECTED() { return (int)1L; }

    static final int LLMHF_LOWER_IL_INJECTED() { return (int)2L; }

    static final int HKL_PREV() { return (int)0L; }

    static final int HKL_NEXT() { return (int)1L; }

    static final int KLF_ACTIVATE() { return (int)1L; }

    static final int KLF_SUBSTITUTE_OK() { return (int)2L; }

    static final int KLF_REORDER() { return (int)8L; }

    static final int KLF_REPLACELANG() { return (int)16L; }

    static final int KLF_NOTELLSHELL() { return (int)128L; }

    static final int KLF_SETFORPROCESS() { return (int)256L; }

    static final int KLF_SHIFTLOCK() { return (int)65536L; }

    static final int KLF_RESET() { return (int)1073741824L; }

    static final int INPUTLANGCHANGE_SYSCHARSET() { return (int)1L; }

    static final int INPUTLANGCHANGE_FORWARD() { return (int)2L; }

    static final int INPUTLANGCHANGE_BACKWARD() { return (int)4L; }

    static final int KL_NAMELENGTH() { return (int)9L; }

    static final int GMMP_USE_DISPLAY_POINTS() { return (int)1L; }

    static final int GMMP_USE_HIGH_RESOLUTION_POINTS() { return (int)2L; }

    static final int CWF_CREATE_ONLY() { return (int)1L; }

    static final int UOI_FLAGS() { return (int)1L; }

    static final int UOI_NAME() { return (int)2L; }

    static final int UOI_TYPE() { return (int)3L; }

    static final int UOI_USER_SID() { return (int)4L; }

    static final int UOI_HEAPSIZE() { return (int)5L; }

    static final int UOI_IO() { return (int)6L; }

    static final int UOI_TIMERPROC_EXCEPTION_SUPPRESSION() { return (int)7L; }

    static final int WM_NULL() { return (int)0L; }

    static final int WM_CREATE() { return (int)1L; }

    static final int WM_DESTROY() { return (int)2L; }

    static final int WM_MOVE() { return (int)3L; }

    static final int WM_SIZE() { return (int)5L; }

    static final int WM_ACTIVATE() { return (int)6L; }

    static final int WA_INACTIVE() { return (int)0L; }

    static final int WA_ACTIVE() { return (int)1L; }

    static final int WA_CLICKACTIVE() { return (int)2L; }

    static final int WM_SETFOCUS() { return (int)7L; }

    static final int WM_KILLFOCUS() { return (int)8L; }

    static final int WM_ENABLE() { return (int)10L; }

    static final int WM_SETREDRAW() { return (int)11L; }

    static final int WM_SETTEXT() { return (int)12L; }

    static final int WM_GETTEXT() { return (int)13L; }

    static final int WM_GETTEXTLENGTH() { return (int)14L; }

    static final int WM_PAINT() { return (int)15L; }

    static final int WM_CLOSE() { return (int)16L; }

    static final int WM_QUERYENDSESSION() { return (int)17L; }

    static final int WM_QUERYOPEN() { return (int)19L; }

    static final int WM_ENDSESSION() { return (int)22L; }

    static final int WM_QUIT() { return (int)18L; }

    static final int WM_ERASEBKGND() { return (int)20L; }

    static final int WM_SYSCOLORCHANGE() { return (int)21L; }

    static final int WM_SHOWWINDOW() { return (int)24L; }

    static final int WM_WININICHANGE() { return (int)26L; }

    static final int WM_DEVMODECHANGE() { return (int)27L; }

    static final int WM_ACTIVATEAPP() { return (int)28L; }

    static final int WM_FONTCHANGE() { return (int)29L; }

    static final int WM_TIMECHANGE() { return (int)30L; }

    static final int WM_CANCELMODE() { return (int)31L; }

    static final int WM_SETCURSOR() { return (int)32L; }

    static final int WM_MOUSEACTIVATE() { return (int)33L; }

    static final int WM_CHILDACTIVATE() { return (int)34L; }

    static final int WM_QUEUESYNC() { return (int)35L; }

    static final int WM_GETMINMAXINFO() { return (int)36L; }

    static final int WM_PAINTICON() { return (int)38L; }

    static final int WM_ICONERASEBKGND() { return (int)39L; }

    static final int WM_NEXTDLGCTL() { return (int)40L; }

    static final int WM_SPOOLERSTATUS() { return (int)42L; }

    static final int WM_DRAWITEM() { return (int)43L; }

    static final int WM_MEASUREITEM() { return (int)44L; }

    static final int WM_DELETEITEM() { return (int)45L; }

    static final int WM_VKEYTOITEM() { return (int)46L; }

    static final int WM_CHARTOITEM() { return (int)47L; }

    static final int WM_SETFONT() { return (int)48L; }

    static final int WM_GETFONT() { return (int)49L; }

    static final int WM_SETHOTKEY() { return (int)50L; }

    static final int WM_GETHOTKEY() { return (int)51L; }

    static final int WM_QUERYDRAGICON() { return (int)55L; }

    static final int WM_COMPAREITEM() { return (int)57L; }

    static final int WM_GETOBJECT() { return (int)61L; }

    static final int WM_COMPACTING() { return (int)65L; }

    static final int WM_COMMNOTIFY() { return (int)68L; }

    static final int WM_WINDOWPOSCHANGING() { return (int)70L; }

    static final int WM_WINDOWPOSCHANGED() { return (int)71L; }

    static final int WM_POWER() { return (int)72L; }

    static final int PWR_OK() { return (int)1L; }

    static final int PWR_SUSPENDREQUEST() { return (int)1L; }

    static final int PWR_SUSPENDRESUME() { return (int)2L; }

    static final int PWR_CRITICALRESUME() { return (int)3L; }

    static final int WM_COPYDATA() { return (int)74L; }

    static final int WM_CANCELJOURNAL() { return (int)75L; }

    static final int WM_NOTIFY() { return (int)78L; }

    static final int WM_INPUTLANGCHANGEREQUEST() { return (int)80L; }

    static final int WM_INPUTLANGCHANGE() { return (int)81L; }

    static final int WM_TCARD() { return (int)82L; }

    static final int WM_HELP() { return (int)83L; }

    static final int WM_USERCHANGED() { return (int)84L; }

    static final int WM_NOTIFYFORMAT() { return (int)85L; }

    static final int NFR_ANSI() { return (int)1L; }

    static final int NFR_UNICODE() { return (int)2L; }

    static final int NF_QUERY() { return (int)3L; }

    static final int NF_REQUERY() { return (int)4L; }

    static final int WM_CONTEXTMENU() { return (int)123L; }

    static final int WM_STYLECHANGING() { return (int)124L; }

    static final int WM_STYLECHANGED() { return (int)125L; }

    static final int WM_DISPLAYCHANGE() { return (int)126L; }

    static final int WM_GETICON() { return (int)127L; }

    static final int WM_SETICON() { return (int)128L; }

    static final int WM_NCCREATE() { return (int)129L; }

    static final int WM_NCDESTROY() { return (int)130L; }

    static final int WM_NCCALCSIZE() { return (int)131L; }

    static final int WM_NCHITTEST() { return (int)132L; }

    static final int WM_NCPAINT() { return (int)133L; }

    static final int WM_NCACTIVATE() { return (int)134L; }

    static final int WM_GETDLGCODE() { return (int)135L; }

    static final int WM_SYNCPAINT() { return (int)136L; }

    static final int WM_NCMOUSEMOVE() { return (int)160L; }

    static final int WM_NCLBUTTONDOWN() { return (int)161L; }

    static final int WM_NCLBUTTONUP() { return (int)162L; }

    static final int WM_NCLBUTTONDBLCLK() { return (int)163L; }

    static final int WM_NCRBUTTONDOWN() { return (int)164L; }

    static final int WM_NCRBUTTONUP() { return (int)165L; }

    static final int WM_NCRBUTTONDBLCLK() { return (int)166L; }

    static final int WM_NCMBUTTONDOWN() { return (int)167L; }

    static final int WM_NCMBUTTONUP() { return (int)168L; }

    static final int WM_NCMBUTTONDBLCLK() { return (int)169L; }

    static final int WM_NCXBUTTONDOWN() { return (int)171L; }

    static final int WM_NCXBUTTONUP() { return (int)172L; }

    static final int WM_NCXBUTTONDBLCLK() { return (int)173L; }

    static final int WM_INPUT_DEVICE_CHANGE() { return (int)254L; }

    static final int WM_INPUT() { return (int)255L; }

    static final int WM_KEYFIRST() { return (int)256L; }

    static final int WM_KEYDOWN() { return (int)256L; }

    static final int WM_KEYUP() { return (int)257L; }

    static final int WM_CHAR() { return (int)258L; }

    static final int WM_DEADCHAR() { return (int)259L; }

    static final int WM_SYSKEYDOWN() { return (int)260L; }

    static final int WM_SYSKEYUP() { return (int)261L; }

    static final int WM_SYSCHAR() { return (int)262L; }

    static final int WM_SYSDEADCHAR() { return (int)263L; }

    static final int WM_UNICHAR() { return (int)265L; }

    static final int WM_KEYLAST() { return (int)265L; }

    static final int UNICODE_NOCHAR() { return (int)65535L; }

    static final int WM_IME_STARTCOMPOSITION() { return (int)269L; }

    static final int WM_IME_ENDCOMPOSITION() { return (int)270L; }

    static final int WM_IME_COMPOSITION() { return (int)271L; }

    static final int WM_IME_KEYLAST() { return (int)271L; }

    static final int WM_INITDIALOG() { return (int)272L; }

    static final int WM_COMMAND() { return (int)273L; }

    static final int WM_SYSCOMMAND() { return (int)274L; }

    static final int WM_TIMER() { return (int)275L; }

    static final int WM_HSCROLL() { return (int)276L; }

    static final int WM_VSCROLL() { return (int)277L; }

    static final int WM_INITMENU() { return (int)278L; }

    static final int WM_INITMENUPOPUP() { return (int)279L; }

    static final int WM_GESTURE() { return (int)281L; }

    static final int WM_GESTURENOTIFY() { return (int)282L; }

    static final int WM_MENUSELECT() { return (int)287L; }

    static final int WM_MENUCHAR() { return (int)288L; }

    static final int WM_ENTERIDLE() { return (int)289L; }

    static final int WM_MENURBUTTONUP() { return (int)290L; }

    static final int WM_MENUDRAG() { return (int)291L; }

    static final int WM_MENUGETOBJECT() { return (int)292L; }

    static final int WM_UNINITMENUPOPUP() { return (int)293L; }

    static final int WM_MENUCOMMAND() { return (int)294L; }

    static final int WM_CHANGEUISTATE() { return (int)295L; }

    static final int WM_UPDATEUISTATE() { return (int)296L; }

    static final int WM_QUERYUISTATE() { return (int)297L; }

    static final int UIS_SET() { return (int)1L; }

    static final int UIS_CLEAR() { return (int)2L; }

    static final int UIS_INITIALIZE() { return (int)3L; }

    static final int UISF_HIDEFOCUS() { return (int)1L; }

    static final int UISF_HIDEACCEL() { return (int)2L; }

    static final int UISF_ACTIVE() { return (int)4L; }

    static final int WM_CTLCOLORMSGBOX() { return (int)306L; }

    static final int WM_CTLCOLOREDIT() { return (int)307L; }

    static final int WM_CTLCOLORLISTBOX() { return (int)308L; }

    static final int WM_CTLCOLORBTN() { return (int)309L; }

    static final int WM_CTLCOLORDLG() { return (int)310L; }

    static final int WM_CTLCOLORSCROLLBAR() { return (int)311L; }

    static final int WM_CTLCOLORSTATIC() { return (int)312L; }

    static final int MN_GETHMENU() { return (int)481L; }

    static final int WM_MOUSEFIRST() { return (int)512L; }

    static final int WM_MOUSEMOVE() { return (int)512L; }

    static final int WM_LBUTTONDOWN() { return (int)513L; }

    static final int WM_LBUTTONUP() { return (int)514L; }

    static final int WM_LBUTTONDBLCLK() { return (int)515L; }

    static final int WM_RBUTTONDOWN() { return (int)516L; }

    static final int WM_RBUTTONUP() { return (int)517L; }

    static final int WM_RBUTTONDBLCLK() { return (int)518L; }

    static final int WM_MBUTTONDOWN() { return (int)519L; }

    static final int WM_MBUTTONUP() { return (int)520L; }

    static final int WM_MBUTTONDBLCLK() { return (int)521L; }

    static final int WM_MOUSEWHEEL() { return (int)522L; }

    static final int WM_XBUTTONDOWN() { return (int)523L; }

    static final int WM_XBUTTONUP() { return (int)524L; }

    static final int WM_XBUTTONDBLCLK() { return (int)525L; }

    static final int WM_MOUSEHWHEEL() { return (int)526L; }

    static final int WM_MOUSELAST() { return (int)526L; }

    static final int WHEEL_DELTA() { return (int)120L; }

    static final int XBUTTON1() { return (int)1L; }

    static final int XBUTTON2() { return (int)2L; }

    static final int WM_PARENTNOTIFY() { return (int)528L; }

    static final int WM_ENTERMENULOOP() { return (int)529L; }

    static final int WM_EXITMENULOOP() { return (int)530L; }

    static final int WM_NEXTMENU() { return (int)531L; }

    static final int WM_SIZING() { return (int)532L; }

    static final int WM_CAPTURECHANGED() { return (int)533L; }

    static final int WM_MOVING() { return (int)534L; }

    static final int WM_POWERBROADCAST() { return (int)536L; }

    static final int PBT_APMQUERYSUSPEND() { return (int)0L; }

    static final int PBT_APMQUERYSTANDBY() { return (int)1L; }

    static final int PBT_APMQUERYSUSPENDFAILED() { return (int)2L; }

    static final int PBT_APMQUERYSTANDBYFAILED() { return (int)3L; }

    static final int PBT_APMSUSPEND() { return (int)4L; }

    static final int PBT_APMSTANDBY() { return (int)5L; }

    static final int PBT_APMRESUMECRITICAL() { return (int)6L; }

    static final int PBT_APMRESUMESUSPEND() { return (int)7L; }

    static final int PBT_APMRESUMESTANDBY() { return (int)8L; }

    static final int PBTF_APMRESUMEFROMFAILURE() { return (int)1L; }

    static final int PBT_APMBATTERYLOW() { return (int)9L; }

    static final int PBT_APMPOWERSTATUSCHANGE() { return (int)10L; }

    static final int PBT_APMOEMEVENT() { return (int)11L; }

    static final int PBT_APMRESUMEAUTOMATIC() { return (int)18L; }

    static final int PBT_POWERSETTINGCHANGE() { return (int)32787L; }

    static final int WM_DEVICECHANGE() { return (int)537L; }

    static final int WM_MDICREATE() { return (int)544L; }

    static final int WM_MDIDESTROY() { return (int)545L; }

    static final int WM_MDIACTIVATE() { return (int)546L; }

    static final int WM_MDIRESTORE() { return (int)547L; }

    static final int WM_MDINEXT() { return (int)548L; }

    static final int WM_MDIMAXIMIZE() { return (int)549L; }

    static final int WM_MDITILE() { return (int)550L; }

    static final int WM_MDICASCADE() { return (int)551L; }

    static final int WM_MDIICONARRANGE() { return (int)552L; }

    static final int WM_MDIGETACTIVE() { return (int)553L; }

    static final int WM_MDISETMENU() { return (int)560L; }

    static final int WM_ENTERSIZEMOVE() { return (int)561L; }

    static final int WM_EXITSIZEMOVE() { return (int)562L; }

    static final int WM_DROPFILES() { return (int)563L; }

    static final int WM_MDIREFRESHMENU() { return (int)564L; }

    static final int WM_POINTERDEVICECHANGE() { return (int)568L; }

    static final int WM_POINTERDEVICEINRANGE() { return (int)569L; }

    static final int WM_POINTERDEVICEOUTOFRANGE() { return (int)570L; }

    static final int WM_TOUCH() { return (int)576L; }

    static final int WM_NCPOINTERUPDATE() { return (int)577L; }

    static final int WM_NCPOINTERDOWN() { return (int)578L; }

    static final int WM_NCPOINTERUP() { return (int)579L; }

    static final int WM_POINTERUPDATE() { return (int)581L; }

    static final int WM_POINTERDOWN() { return (int)582L; }

    static final int WM_POINTERUP() { return (int)583L; }

    static final int WM_POINTERENTER() { return (int)585L; }

    static final int WM_POINTERLEAVE() { return (int)586L; }

    static final int WM_POINTERACTIVATE() { return (int)587L; }

    static final int WM_POINTERCAPTURECHANGED() { return (int)588L; }

    static final int WM_TOUCHHITTESTING() { return (int)589L; }

    static final int WM_POINTERWHEEL() { return (int)590L; }

    static final int WM_POINTERHWHEEL() { return (int)591L; }

    static final int DM_POINTERHITTEST() { return (int)592L; }

    static final int WM_POINTERROUTEDTO() { return (int)593L; }

    static final int WM_POINTERROUTEDAWAY() { return (int)594L; }

    static final int WM_POINTERROUTEDRELEASED() { return (int)595L; }

    static final int WM_IME_SETCONTEXT() { return (int)641L; }

    static final int WM_IME_NOTIFY() { return (int)642L; }

    static final int WM_IME_CONTROL() { return (int)643L; }

    static final int WM_IME_COMPOSITIONFULL() { return (int)644L; }

    static final int WM_IME_SELECT() { return (int)645L; }

    static final int WM_IME_CHAR() { return (int)646L; }

    static final int WM_IME_REQUEST() { return (int)648L; }

    static final int WM_IME_KEYDOWN() { return (int)656L; }

    static final int WM_IME_KEYUP() { return (int)657L; }

    static final int WM_MOUSEHOVER() { return (int)673L; }

    static final int WM_MOUSELEAVE() { return (int)675L; }

    static final int WM_NCMOUSEHOVER() { return (int)672L; }

    static final int WM_NCMOUSELEAVE() { return (int)674L; }

    static final int WM_WTSSESSION_CHANGE() { return (int)689L; }

    static final int WM_TABLET_FIRST() { return (int)704L; }

    static final int WM_TABLET_LAST() { return (int)735L; }

    static final int WM_DPICHANGED() { return (int)736L; }

    static final int WM_DPICHANGED_BEFOREPARENT() { return (int)738L; }

    static final int WM_DPICHANGED_AFTERPARENT() { return (int)739L; }

    static final int WM_GETDPISCALEDSIZE() { return (int)740L; }

    static final int WM_CUT() { return (int)768L; }

    static final int WM_COPY() { return (int)769L; }

    static final int WM_PASTE() { return (int)770L; }

    static final int WM_CLEAR() { return (int)771L; }

    static final int WM_UNDO() { return (int)772L; }

    static final int WM_RENDERFORMAT() { return (int)773L; }

    static final int WM_RENDERALLFORMATS() { return (int)774L; }

    static final int WM_DESTROYCLIPBOARD() { return (int)775L; }

    static final int WM_DRAWCLIPBOARD() { return (int)776L; }

    static final int WM_PAINTCLIPBOARD() { return (int)777L; }

    static final int WM_VSCROLLCLIPBOARD() { return (int)778L; }

    static final int WM_SIZECLIPBOARD() { return (int)779L; }

    static final int WM_ASKCBFORMATNAME() { return (int)780L; }

    static final int WM_CHANGECBCHAIN() { return (int)781L; }

    static final int WM_HSCROLLCLIPBOARD() { return (int)782L; }

    static final int WM_QUERYNEWPALETTE() { return (int)783L; }

    static final int WM_PALETTEISCHANGING() { return (int)784L; }

    static final int WM_PALETTECHANGED() { return (int)785L; }

    static final int WM_HOTKEY() { return (int)786L; }

    static final int WM_PRINT() { return (int)791L; }

    static final int WM_PRINTCLIENT() { return (int)792L; }

    static final int WM_APPCOMMAND() { return (int)793L; }

    static final int WM_THEMECHANGED() { return (int)794L; }

    static final int WM_CLIPBOARDUPDATE() { return (int)797L; }

    static final int WM_DWMCOMPOSITIONCHANGED() { return (int)798L; }

    static final int WM_DWMNCRENDERINGCHANGED() { return (int)799L; }

    static final int WM_DWMCOLORIZATIONCOLORCHANGED() { return (int)800L; }

    static final int WM_DWMWINDOWMAXIMIZEDCHANGE() { return (int)801L; }

    static final int WM_DWMSENDICONICTHUMBNAIL() { return (int)803L; }

    static final int WM_DWMSENDICONICLIVEPREVIEWBITMAP() { return (int)806L; }

    static final int WM_GETTITLEBARINFOEX() { return (int)831L; }

    static final int WM_HANDHELDFIRST() { return (int)856L; }

    static final int WM_HANDHELDLAST() { return (int)863L; }

    static final int WM_AFXFIRST() { return (int)864L; }

    static final int WM_AFXLAST() { return (int)895L; }

    static final int WM_PENWINFIRST() { return (int)896L; }

    static final int WM_PENWINLAST() { return (int)911L; }

    static final int WM_APP() { return (int)32768L; }

    static final int WM_USER() { return (int)1024L; }

    static final int WMSZ_LEFT() { return (int)1L; }

    static final int WMSZ_RIGHT() { return (int)2L; }

    static final int WMSZ_TOP() { return (int)3L; }

    static final int WMSZ_TOPLEFT() { return (int)4L; }

    static final int WMSZ_TOPRIGHT() { return (int)5L; }

    static final int WMSZ_BOTTOM() { return (int)6L; }

    static final int WMSZ_BOTTOMLEFT() { return (int)7L; }

    static final int WMSZ_BOTTOMRIGHT() { return (int)8L; }

    static final int HTNOWHERE() { return (int)0L; }

    static final int HTCLIENT() { return (int)1L; }

    static final int HTCAPTION() { return (int)2L; }

    static final int HTSYSMENU() { return (int)3L; }

    static final int HTGROWBOX() { return (int)4L; }

    static final int HTMENU() { return (int)5L; }

    static final int HTHSCROLL() { return (int)6L; }

    static final int HTVSCROLL() { return (int)7L; }

    static final int HTMINBUTTON() { return (int)8L; }

    static final int HTMAXBUTTON() { return (int)9L; }

    static final int HTLEFT() { return (int)10L; }

    static final int HTRIGHT() { return (int)11L; }

    static final int HTTOP() { return (int)12L; }

    static final int HTTOPLEFT() { return (int)13L; }

    static final int HTTOPRIGHT() { return (int)14L; }

    static final int HTBOTTOM() { return (int)15L; }

    static final int HTBOTTOMLEFT() { return (int)16L; }

    static final int HTBOTTOMRIGHT() { return (int)17L; }

    static final int HTBORDER() { return (int)18L; }

    static final int HTOBJECT() { return (int)19L; }

    static final int HTCLOSE() { return (int)20L; }

    static final int HTHELP() { return (int)21L; }

    static final int SMTO_NORMAL() { return (int)0L; }

    static final int SMTO_BLOCK() { return (int)1L; }

    static final int SMTO_ABORTIFHUNG() { return (int)2L; }

    static final int SMTO_NOTIMEOUTIFNOTHUNG() { return (int)8L; }

    static final int SMTO_ERRORONEXIT() { return (int)32L; }

    static final int MA_ACTIVATE() { return (int)1L; }

    static final int MA_ACTIVATEANDEAT() { return (int)2L; }

    static final int MA_NOACTIVATE() { return (int)3L; }

    static final int MA_NOACTIVATEANDEAT() { return (int)4L; }

    static final int ICON_SMALL() { return (int)0L; }

    static final int ICON_BIG() { return (int)1L; }

    static final int ICON_SMALL2() { return (int)2L; }

    static final int SIZE_RESTORED() { return (int)0L; }

    static final int SIZE_MINIMIZED() { return (int)1L; }

    static final int SIZE_MAXIMIZED() { return (int)2L; }

    static final int SIZE_MAXSHOW() { return (int)3L; }

    static final int SIZE_MAXHIDE() { return (int)4L; }

    static final int WVR_ALIGNTOP() { return (int)16L; }

    static final int WVR_ALIGNLEFT() { return (int)32L; }

    static final int WVR_ALIGNBOTTOM() { return (int)64L; }

    static final int WVR_ALIGNRIGHT() { return (int)128L; }

    static final int WVR_HREDRAW() { return (int)256L; }

    static final int WVR_VREDRAW() { return (int)512L; }

    static final int WVR_VALIDRECTS() { return (int)1024L; }

    static final int MK_LBUTTON() { return (int)1L; }

    static final int MK_RBUTTON() { return (int)2L; }

    static final int MK_SHIFT() { return (int)4L; }

    static final int MK_CONTROL() { return (int)8L; }

    static final int MK_MBUTTON() { return (int)16L; }

    static final int MK_XBUTTON1() { return (int)32L; }

    static final int MK_XBUTTON2() { return (int)64L; }

    static final int TME_HOVER() { return (int)1L; }

    static final int TME_LEAVE() { return (int)2L; }

}

