// Generated by jextract

package com.github.tornaia.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class cfapi_h$constants$103 extends cfapi_h$constants$102 {

    /* package-private */ cfapi_h$constants$103() {}
    static final int ERROR_QUORUM_OWNER_ALIVE() { return (int)5034L; }

    static final int ERROR_NETWORK_NOT_AVAILABLE() { return (int)5035L; }

    static final int ERROR_NODE_NOT_AVAILABLE() { return (int)5036L; }

    static final int ERROR_ALL_NODES_NOT_AVAILABLE() { return (int)5037L; }

    static final int ERROR_RESOURCE_FAILED() { return (int)5038L; }

    static final int ERROR_CLUSTER_INVALID_NODE() { return (int)5039L; }

    static final int ERROR_CLUSTER_NODE_EXISTS() { return (int)5040L; }

    static final int ERROR_CLUSTER_JOIN_IN_PROGRESS() { return (int)5041L; }

    static final int ERROR_CLUSTER_NODE_NOT_FOUND() { return (int)5042L; }

    static final int ERROR_CLUSTER_LOCAL_NODE_NOT_FOUND() { return (int)5043L; }

    static final int ERROR_CLUSTER_NETWORK_EXISTS() { return (int)5044L; }

    static final int ERROR_CLUSTER_NETWORK_NOT_FOUND() { return (int)5045L; }

    static final int ERROR_CLUSTER_NETINTERFACE_EXISTS() { return (int)5046L; }

    static final int ERROR_CLUSTER_NETINTERFACE_NOT_FOUND() { return (int)5047L; }

    static final int ERROR_CLUSTER_INVALID_REQUEST() { return (int)5048L; }

    static final int ERROR_CLUSTER_INVALID_NETWORK_PROVIDER() { return (int)5049L; }

    static final int ERROR_CLUSTER_NODE_DOWN() { return (int)5050L; }

    static final int ERROR_CLUSTER_NODE_UNREACHABLE() { return (int)5051L; }

    static final int ERROR_CLUSTER_NODE_NOT_MEMBER() { return (int)5052L; }

    static final int ERROR_CLUSTER_JOIN_NOT_IN_PROGRESS() { return (int)5053L; }

    static final int ERROR_CLUSTER_INVALID_NETWORK() { return (int)5054L; }

    static final int ERROR_CLUSTER_NODE_UP() { return (int)5056L; }

    static final int ERROR_CLUSTER_IPADDR_IN_USE() { return (int)5057L; }

    static final int ERROR_CLUSTER_NODE_NOT_PAUSED() { return (int)5058L; }

    static final int ERROR_CLUSTER_NO_SECURITY_CONTEXT() { return (int)5059L; }

    static final int ERROR_CLUSTER_NETWORK_NOT_INTERNAL() { return (int)5060L; }

    static final int ERROR_CLUSTER_NODE_ALREADY_UP() { return (int)5061L; }

    static final int ERROR_CLUSTER_NODE_ALREADY_DOWN() { return (int)5062L; }

    static final int ERROR_CLUSTER_NETWORK_ALREADY_ONLINE() { return (int)5063L; }

    static final int ERROR_CLUSTER_NETWORK_ALREADY_OFFLINE() { return (int)5064L; }

    static final int ERROR_CLUSTER_NODE_ALREADY_MEMBER() { return (int)5065L; }

    static final int ERROR_CLUSTER_LAST_INTERNAL_NETWORK() { return (int)5066L; }

    static final int ERROR_CLUSTER_NETWORK_HAS_DEPENDENTS() { return (int)5067L; }

    static final int ERROR_INVALID_OPERATION_ON_QUORUM() { return (int)5068L; }

    static final int ERROR_DEPENDENCY_NOT_ALLOWED() { return (int)5069L; }

    static final int ERROR_CLUSTER_NODE_PAUSED() { return (int)5070L; }

    static final int ERROR_NODE_CANT_HOST_RESOURCE() { return (int)5071L; }

    static final int ERROR_CLUSTER_NODE_NOT_READY() { return (int)5072L; }

    static final int ERROR_CLUSTER_NODE_SHUTTING_DOWN() { return (int)5073L; }

    static final int ERROR_CLUSTER_JOIN_ABORTED() { return (int)5074L; }

    static final int ERROR_CLUSTER_INCOMPATIBLE_VERSIONS() { return (int)5075L; }

    static final int ERROR_CLUSTER_MAXNUM_OF_RESOURCES_EXCEEDED() { return (int)5076L; }

    static final int ERROR_CLUSTER_SYSTEM_CONFIG_CHANGED() { return (int)5077L; }

    static final int ERROR_CLUSTER_RESOURCE_TYPE_NOT_FOUND() { return (int)5078L; }

    static final int ERROR_CLUSTER_RESTYPE_NOT_SUPPORTED() { return (int)5079L; }

    static final int ERROR_CLUSTER_RESNAME_NOT_FOUND() { return (int)5080L; }

    static final int ERROR_CLUSTER_NO_RPC_PACKAGES_REGISTERED() { return (int)5081L; }

    static final int ERROR_CLUSTER_OWNER_NOT_IN_PREFLIST() { return (int)5082L; }

    static final int ERROR_CLUSTER_DATABASE_SEQMISMATCH() { return (int)5083L; }

    static final int ERROR_RESMON_INVALID_STATE() { return (int)5084L; }

    static final int ERROR_CLUSTER_GUM_NOT_LOCKER() { return (int)5085L; }

    static final int ERROR_QUORUM_DISK_NOT_FOUND() { return (int)5086L; }

    static final int ERROR_DATABASE_BACKUP_CORRUPT() { return (int)5087L; }

    static final int ERROR_CLUSTER_NODE_ALREADY_HAS_DFS_ROOT() { return (int)5088L; }

    static final int ERROR_RESOURCE_PROPERTY_UNCHANGEABLE() { return (int)5089L; }

    static final int ERROR_NO_ADMIN_ACCESS_POINT() { return (int)5090L; }

    static final int ERROR_CLUSTER_MEMBERSHIP_INVALID_STATE() { return (int)5890L; }

    static final int ERROR_CLUSTER_QUORUMLOG_NOT_FOUND() { return (int)5891L; }

    static final int ERROR_CLUSTER_MEMBERSHIP_HALT() { return (int)5892L; }

    static final int ERROR_CLUSTER_INSTANCE_ID_MISMATCH() { return (int)5893L; }

    static final int ERROR_CLUSTER_NETWORK_NOT_FOUND_FOR_IP() { return (int)5894L; }

    static final int ERROR_CLUSTER_PROPERTY_DATA_TYPE_MISMATCH() { return (int)5895L; }

    static final int ERROR_CLUSTER_EVICT_WITHOUT_CLEANUP() { return (int)5896L; }

    static final int ERROR_CLUSTER_PARAMETER_MISMATCH() { return (int)5897L; }

    static final int ERROR_NODE_CANNOT_BE_CLUSTERED() { return (int)5898L; }

    static final int ERROR_CLUSTER_WRONG_OS_VERSION() { return (int)5899L; }

    static final int ERROR_CLUSTER_CANT_CREATE_DUP_CLUSTER_NAME() { return (int)5900L; }

    static final int ERROR_CLUSCFG_ALREADY_COMMITTED() { return (int)5901L; }

    static final int ERROR_CLUSCFG_ROLLBACK_FAILED() { return (int)5902L; }

    static final int ERROR_CLUSCFG_SYSTEM_DISK_DRIVE_LETTER_CONFLICT() { return (int)5903L; }

    static final int ERROR_CLUSTER_OLD_VERSION() { return (int)5904L; }

    static final int ERROR_CLUSTER_MISMATCHED_COMPUTER_ACCT_NAME() { return (int)5905L; }

    static final int ERROR_CLUSTER_NO_NET_ADAPTERS() { return (int)5906L; }

    static final int ERROR_CLUSTER_POISONED() { return (int)5907L; }

    static final int ERROR_CLUSTER_GROUP_MOVING() { return (int)5908L; }

    static final int ERROR_CLUSTER_RESOURCE_TYPE_BUSY() { return (int)5909L; }

    static final int ERROR_RESOURCE_CALL_TIMED_OUT() { return (int)5910L; }

    static final int ERROR_INVALID_CLUSTER_IPV6_ADDRESS() { return (int)5911L; }

    static final int ERROR_CLUSTER_INTERNAL_INVALID_FUNCTION() { return (int)5912L; }

    static final int ERROR_CLUSTER_PARAMETER_OUT_OF_BOUNDS() { return (int)5913L; }

    static final int ERROR_CLUSTER_PARTIAL_SEND() { return (int)5914L; }

    static final int ERROR_CLUSTER_REGISTRY_INVALID_FUNCTION() { return (int)5915L; }

    static final int ERROR_CLUSTER_INVALID_STRING_TERMINATION() { return (int)5916L; }

    static final int ERROR_CLUSTER_INVALID_STRING_FORMAT() { return (int)5917L; }

    static final int ERROR_CLUSTER_DATABASE_TRANSACTION_IN_PROGRESS() { return (int)5918L; }

    static final int ERROR_CLUSTER_DATABASE_TRANSACTION_NOT_IN_PROGRESS() { return (int)5919L; }

    static final int ERROR_CLUSTER_NULL_DATA() { return (int)5920L; }

    static final int ERROR_CLUSTER_PARTIAL_READ() { return (int)5921L; }

    static final int ERROR_CLUSTER_PARTIAL_WRITE() { return (int)5922L; }

    static final int ERROR_CLUSTER_CANT_DESERIALIZE_DATA() { return (int)5923L; }

    static final int ERROR_DEPENDENT_RESOURCE_PROPERTY_CONFLICT() { return (int)5924L; }

    static final int ERROR_CLUSTER_NO_QUORUM() { return (int)5925L; }

    static final int ERROR_CLUSTER_INVALID_IPV6_NETWORK() { return (int)5926L; }

    static final int ERROR_CLUSTER_INVALID_IPV6_TUNNEL_NETWORK() { return (int)5927L; }

    static final int ERROR_QUORUM_NOT_ALLOWED_IN_THIS_GROUP() { return (int)5928L; }

    static final int ERROR_DEPENDENCY_TREE_TOO_COMPLEX() { return (int)5929L; }

    static final int ERROR_EXCEPTION_IN_RESOURCE_CALL() { return (int)5930L; }

    static final int ERROR_CLUSTER_RHS_FAILED_INITIALIZATION() { return (int)5931L; }

    static final int ERROR_CLUSTER_NOT_INSTALLED() { return (int)5932L; }

    static final int ERROR_CLUSTER_RESOURCES_MUST_BE_ONLINE_ON_THE_SAME_NODE() { return (int)5933L; }

    static final int ERROR_CLUSTER_MAX_NODES_IN_CLUSTER() { return (int)5934L; }

    static final int ERROR_CLUSTER_TOO_MANY_NODES() { return (int)5935L; }

    static final int ERROR_CLUSTER_OBJECT_ALREADY_USED() { return (int)5936L; }

    static final int ERROR_NONCORE_GROUPS_FOUND() { return (int)5937L; }

    static final int ERROR_FILE_SHARE_RESOURCE_CONFLICT() { return (int)5938L; }

    static final int ERROR_CLUSTER_EVICT_INVALID_REQUEST() { return (int)5939L; }

    static final int ERROR_CLUSTER_SINGLETON_RESOURCE() { return (int)5940L; }

    static final int ERROR_CLUSTER_GROUP_SINGLETON_RESOURCE() { return (int)5941L; }

    static final int ERROR_CLUSTER_RESOURCE_PROVIDER_FAILED() { return (int)5942L; }

    static final int ERROR_CLUSTER_RESOURCE_CONFIGURATION_ERROR() { return (int)5943L; }

    static final int ERROR_CLUSTER_GROUP_BUSY() { return (int)5944L; }

    static final int ERROR_CLUSTER_NOT_SHARED_VOLUME() { return (int)5945L; }

    static final int ERROR_CLUSTER_INVALID_SECURITY_DESCRIPTOR() { return (int)5946L; }

    static final int ERROR_CLUSTER_SHARED_VOLUMES_IN_USE() { return (int)5947L; }

    static final int ERROR_CLUSTER_USE_SHARED_VOLUMES_API() { return (int)5948L; }

    static final int ERROR_CLUSTER_BACKUP_IN_PROGRESS() { return (int)5949L; }

    static final int ERROR_NON_CSV_PATH() { return (int)5950L; }

    static final int ERROR_CSV_VOLUME_NOT_LOCAL() { return (int)5951L; }

    static final int ERROR_CLUSTER_WATCHDOG_TERMINATING() { return (int)5952L; }

    static final int ERROR_CLUSTER_RESOURCE_VETOED_MOVE_INCOMPATIBLE_NODES() { return (int)5953L; }

    static final int ERROR_CLUSTER_INVALID_NODE_WEIGHT() { return (int)5954L; }

    static final int ERROR_CLUSTER_RESOURCE_VETOED_CALL() { return (int)5955L; }

    static final int ERROR_RESMON_SYSTEM_RESOURCES_LACKING() { return (int)5956L; }

    static final int ERROR_CLUSTER_RESOURCE_VETOED_MOVE_NOT_ENOUGH_RESOURCES_ON_DESTINATION() { return (int)5957L; }

    static final int ERROR_CLUSTER_RESOURCE_VETOED_MOVE_NOT_ENOUGH_RESOURCES_ON_SOURCE() { return (int)5958L; }

    static final int ERROR_CLUSTER_GROUP_QUEUED() { return (int)5959L; }

    static final int ERROR_CLUSTER_RESOURCE_LOCKED_STATUS() { return (int)5960L; }

    static final int ERROR_CLUSTER_SHARED_VOLUME_FAILOVER_NOT_ALLOWED() { return (int)5961L; }

    static final int ERROR_CLUSTER_NODE_DRAIN_IN_PROGRESS() { return (int)5962L; }

    static final int ERROR_CLUSTER_DISK_NOT_CONNECTED() { return (int)5963L; }

    static final int ERROR_DISK_NOT_CSV_CAPABLE() { return (int)5964L; }

    static final int ERROR_RESOURCE_NOT_IN_AVAILABLE_STORAGE() { return (int)5965L; }

    static final int ERROR_CLUSTER_SHARED_VOLUME_REDIRECTED() { return (int)5966L; }

    static final int ERROR_CLUSTER_SHARED_VOLUME_NOT_REDIRECTED() { return (int)5967L; }

    static final int ERROR_CLUSTER_CANNOT_RETURN_PROPERTIES() { return (int)5968L; }

    static final int ERROR_CLUSTER_RESOURCE_CONTAINS_UNSUPPORTED_DIFF_AREA_FOR_SHARED_VOLUMES() { return (int)5969L; }

    static final int ERROR_CLUSTER_RESOURCE_IS_IN_MAINTENANCE_MODE() { return (int)5970L; }

    static final int ERROR_CLUSTER_AFFINITY_CONFLICT() { return (int)5971L; }

    static final int ERROR_CLUSTER_RESOURCE_IS_REPLICA_VIRTUAL_MACHINE() { return (int)5972L; }

    static final int ERROR_CLUSTER_UPGRADE_INCOMPATIBLE_VERSIONS() { return (int)5973L; }

    static final int ERROR_CLUSTER_UPGRADE_FIX_QUORUM_NOT_SUPPORTED() { return (int)5974L; }

    static final int ERROR_CLUSTER_UPGRADE_RESTART_REQUIRED() { return (int)5975L; }

    static final int ERROR_CLUSTER_UPGRADE_IN_PROGRESS() { return (int)5976L; }

    static final int ERROR_CLUSTER_UPGRADE_INCOMPLETE() { return (int)5977L; }

    static final int ERROR_CLUSTER_NODE_IN_GRACE_PERIOD() { return (int)5978L; }

    static final int ERROR_CLUSTER_CSV_IO_PAUSE_TIMEOUT() { return (int)5979L; }

    static final int ERROR_NODE_NOT_ACTIVE_CLUSTER_MEMBER() { return (int)5980L; }

    static final int ERROR_CLUSTER_RESOURCE_NOT_MONITORED() { return (int)5981L; }

    static final int ERROR_CLUSTER_RESOURCE_DOES_NOT_SUPPORT_UNMONITORED() { return (int)5982L; }

    static final int ERROR_CLUSTER_RESOURCE_IS_REPLICATED() { return (int)5983L; }

    static final int ERROR_CLUSTER_NODE_ISOLATED() { return (int)5984L; }

    static final int ERROR_CLUSTER_NODE_QUARANTINED() { return (int)5985L; }

    static final int ERROR_CLUSTER_DATABASE_UPDATE_CONDITION_FAILED() { return (int)5986L; }

    static final int ERROR_CLUSTER_SPACE_DEGRADED() { return (int)5987L; }

    static final int ERROR_CLUSTER_TOKEN_DELEGATION_NOT_SUPPORTED() { return (int)5988L; }

    static final int ERROR_CLUSTER_CSV_INVALID_HANDLE() { return (int)5989L; }

    static final int ERROR_CLUSTER_CSV_SUPPORTED_ONLY_ON_COORDINATOR() { return (int)5990L; }

    static final int ERROR_GROUPSET_NOT_AVAILABLE() { return (int)5991L; }

    static final int ERROR_GROUPSET_NOT_FOUND() { return (int)5992L; }

    static final int ERROR_GROUPSET_CANT_PROVIDE() { return (int)5993L; }

    static final int ERROR_CLUSTER_FAULT_DOMAIN_PARENT_NOT_FOUND() { return (int)5994L; }

    static final int ERROR_CLUSTER_FAULT_DOMAIN_INVALID_HIERARCHY() { return (int)5995L; }

    static final int ERROR_CLUSTER_FAULT_DOMAIN_FAILED_S2D_VALIDATION() { return (int)5996L; }

    static final int ERROR_CLUSTER_FAULT_DOMAIN_S2D_CONNECTIVITY_LOSS() { return (int)5997L; }

    static final int ERROR_CLUSTER_INVALID_INFRASTRUCTURE_FILESERVER_NAME() { return (int)5998L; }

    static final int ERROR_CLUSTERSET_MANAGEMENT_CLUSTER_UNREACHABLE() { return (int)5999L; }

    static final int ERROR_ENCRYPTION_FAILED() { return (int)6000L; }

    static final int ERROR_DECRYPTION_FAILED() { return (int)6001L; }

    static final int ERROR_FILE_ENCRYPTED() { return (int)6002L; }

    static final int ERROR_NO_RECOVERY_POLICY() { return (int)6003L; }

    static final int ERROR_NO_EFS() { return (int)6004L; }

    static final int ERROR_WRONG_EFS() { return (int)6005L; }

    static final int ERROR_NO_USER_KEYS() { return (int)6006L; }

    static final int ERROR_FILE_NOT_ENCRYPTED() { return (int)6007L; }

    static final int ERROR_NOT_EXPORT_FORMAT() { return (int)6008L; }

    static final int ERROR_FILE_READ_ONLY() { return (int)6009L; }

    static final int ERROR_DIR_EFS_DISALLOWED() { return (int)6010L; }

    static final int ERROR_EFS_SERVER_NOT_TRUSTED() { return (int)6011L; }

    static final int ERROR_BAD_RECOVERY_POLICY() { return (int)6012L; }

    static final int ERROR_EFS_ALG_BLOB_TOO_BIG() { return (int)6013L; }

    static final int ERROR_VOLUME_NOT_SUPPORT_EFS() { return (int)6014L; }

    static final int ERROR_EFS_DISABLED() { return (int)6015L; }

    static final int ERROR_EFS_VERSION_NOT_SUPPORT() { return (int)6016L; }

    static final int ERROR_CS_ENCRYPTION_INVALID_SERVER_RESPONSE() { return (int)6017L; }

    static final int ERROR_CS_ENCRYPTION_UNSUPPORTED_SERVER() { return (int)6018L; }

    static final int ERROR_CS_ENCRYPTION_EXISTING_ENCRYPTED_FILE() { return (int)6019L; }

    static final int ERROR_CS_ENCRYPTION_NEW_ENCRYPTED_FILE() { return (int)6020L; }

    static final int ERROR_CS_ENCRYPTION_FILE_NOT_CSE() { return (int)6021L; }

    static final int ERROR_ENCRYPTION_POLICY_DENIES_OPERATION() { return (int)6022L; }

    static final int ERROR_WIP_ENCRYPTION_FAILED() { return (int)6023L; }

    static final int ERROR_NO_BROWSER_SERVERS_FOUND() { return (int)6118L; }

    static final int SCHED_E_SERVICE_NOT_LOCALSYSTEM() { return (int)6200L; }

    static final int ERROR_CLUSTER_OBJECT_IS_CLUSTER_SET_VM() { return (int)6250L; }

    static final int ERROR_LOG_SECTOR_INVALID() { return (int)6600L; }

    static final int ERROR_LOG_SECTOR_PARITY_INVALID() { return (int)6601L; }

    static final int ERROR_LOG_SECTOR_REMAPPED() { return (int)6602L; }

    static final int ERROR_LOG_BLOCK_INCOMPLETE() { return (int)6603L; }

    static final int ERROR_LOG_INVALID_RANGE() { return (int)6604L; }

    static final int ERROR_LOG_BLOCKS_EXHAUSTED() { return (int)6605L; }

    static final int ERROR_LOG_READ_CONTEXT_INVALID() { return (int)6606L; }

    static final int ERROR_LOG_RESTART_INVALID() { return (int)6607L; }

    static final int ERROR_LOG_BLOCK_VERSION() { return (int)6608L; }

    static final int ERROR_LOG_BLOCK_INVALID() { return (int)6609L; }

    static final int ERROR_LOG_READ_MODE_INVALID() { return (int)6610L; }

    static final int ERROR_LOG_NO_RESTART() { return (int)6611L; }

    static final int ERROR_LOG_METADATA_CORRUPT() { return (int)6612L; }

    static final int ERROR_LOG_METADATA_INVALID() { return (int)6613L; }

    static final int ERROR_LOG_METADATA_INCONSISTENT() { return (int)6614L; }

    static final int ERROR_LOG_RESERVATION_INVALID() { return (int)6615L; }

    static final int ERROR_LOG_CANT_DELETE() { return (int)6616L; }

    static final int ERROR_LOG_CONTAINER_LIMIT_EXCEEDED() { return (int)6617L; }

    static final int ERROR_LOG_START_OF_LOG() { return (int)6618L; }

    static final int ERROR_LOG_POLICY_ALREADY_INSTALLED() { return (int)6619L; }

    static final int ERROR_LOG_POLICY_NOT_INSTALLED() { return (int)6620L; }

    static final int ERROR_LOG_POLICY_INVALID() { return (int)6621L; }

    static final int ERROR_LOG_POLICY_CONFLICT() { return (int)6622L; }

    static final int ERROR_LOG_PINNED_ARCHIVE_TAIL() { return (int)6623L; }

    static final int ERROR_LOG_RECORD_NONEXISTENT() { return (int)6624L; }

    static final int ERROR_LOG_RECORDS_RESERVED_INVALID() { return (int)6625L; }

    static final int ERROR_LOG_SPACE_RESERVED_INVALID() { return (int)6626L; }

    static final int ERROR_LOG_TAIL_INVALID() { return (int)6627L; }

    static final int ERROR_LOG_FULL() { return (int)6628L; }

    static final int ERROR_COULD_NOT_RESIZE_LOG() { return (int)6629L; }

    static final int ERROR_LOG_MULTIPLEXED() { return (int)6630L; }

    static final int ERROR_LOG_DEDICATED() { return (int)6631L; }

    static final int ERROR_LOG_ARCHIVE_NOT_IN_PROGRESS() { return (int)6632L; }

    static final int ERROR_LOG_ARCHIVE_IN_PROGRESS() { return (int)6633L; }

    static final int ERROR_LOG_EPHEMERAL() { return (int)6634L; }

    static final int ERROR_LOG_NOT_ENOUGH_CONTAINERS() { return (int)6635L; }

    static final int ERROR_LOG_CLIENT_ALREADY_REGISTERED() { return (int)6636L; }

    static final int ERROR_LOG_CLIENT_NOT_REGISTERED() { return (int)6637L; }

    static final int ERROR_LOG_FULL_HANDLER_IN_PROGRESS() { return (int)6638L; }

    static final int ERROR_LOG_CONTAINER_READ_FAILED() { return (int)6639L; }

    static final int ERROR_LOG_CONTAINER_WRITE_FAILED() { return (int)6640L; }

    static final int ERROR_LOG_CONTAINER_OPEN_FAILED() { return (int)6641L; }

    static final int ERROR_LOG_CONTAINER_STATE_INVALID() { return (int)6642L; }

    static final int ERROR_LOG_STATE_INVALID() { return (int)6643L; }

    static final int ERROR_LOG_PINNED() { return (int)6644L; }

    static final int ERROR_LOG_METADATA_FLUSH_FAILED() { return (int)6645L; }

    static final int ERROR_LOG_INCONSISTENT_SECURITY() { return (int)6646L; }

    static final int ERROR_LOG_APPENDED_FLUSH_FAILED() { return (int)6647L; }

    static final int ERROR_LOG_PINNED_RESERVATION() { return (int)6648L; }

    static final int ERROR_INVALID_TRANSACTION() { return (int)6700L; }

    static final int ERROR_TRANSACTION_NOT_ACTIVE() { return (int)6701L; }

    static final int ERROR_TRANSACTION_REQUEST_NOT_VALID() { return (int)6702L; }

    static final int ERROR_TRANSACTION_NOT_REQUESTED() { return (int)6703L; }

    static final int ERROR_TRANSACTION_ALREADY_ABORTED() { return (int)6704L; }

    static final int ERROR_TRANSACTION_ALREADY_COMMITTED() { return (int)6705L; }

    static final int ERROR_TM_INITIALIZATION_FAILED() { return (int)6706L; }

    static final int ERROR_RESOURCEMANAGER_READ_ONLY() { return (int)6707L; }

    static final int ERROR_TRANSACTION_NOT_JOINED() { return (int)6708L; }

    static final int ERROR_TRANSACTION_SUPERIOR_EXISTS() { return (int)6709L; }

    static final int ERROR_CRM_PROTOCOL_ALREADY_EXISTS() { return (int)6710L; }

    static final int ERROR_TRANSACTION_PROPAGATION_FAILED() { return (int)6711L; }

    static final int ERROR_CRM_PROTOCOL_NOT_FOUND() { return (int)6712L; }

    static final int ERROR_TRANSACTION_INVALID_MARSHALL_BUFFER() { return (int)6713L; }

    static final int ERROR_CURRENT_TRANSACTION_NOT_VALID() { return (int)6714L; }

    static final int ERROR_TRANSACTION_NOT_FOUND() { return (int)6715L; }

    static final int ERROR_RESOURCEMANAGER_NOT_FOUND() { return (int)6716L; }

    static final int ERROR_ENLISTMENT_NOT_FOUND() { return (int)6717L; }

    static final int ERROR_TRANSACTIONMANAGER_NOT_FOUND() { return (int)6718L; }

    static final int ERROR_TRANSACTIONMANAGER_NOT_ONLINE() { return (int)6719L; }

    static final int ERROR_TRANSACTIONMANAGER_RECOVERY_NAME_COLLISION() { return (int)6720L; }

    static final int ERROR_TRANSACTION_NOT_ROOT() { return (int)6721L; }

    static final int ERROR_TRANSACTION_OBJECT_EXPIRED() { return (int)6722L; }

    static final int ERROR_TRANSACTION_RESPONSE_NOT_ENLISTED() { return (int)6723L; }

    static final int ERROR_TRANSACTION_RECORD_TOO_LONG() { return (int)6724L; }

    static final int ERROR_IMPLICIT_TRANSACTION_NOT_SUPPORTED() { return (int)6725L; }

    static final int ERROR_TRANSACTION_INTEGRITY_VIOLATED() { return (int)6726L; }

    static final int ERROR_TRANSACTIONMANAGER_IDENTITY_MISMATCH() { return (int)6727L; }

    static final int ERROR_RM_CANNOT_BE_FROZEN_FOR_SNAPSHOT() { return (int)6728L; }

    static final int ERROR_TRANSACTION_MUST_WRITETHROUGH() { return (int)6729L; }

    static final int ERROR_TRANSACTION_NO_SUPERIOR() { return (int)6730L; }

    static final int ERROR_HEURISTIC_DAMAGE_POSSIBLE() { return (int)6731L; }

    static final int ERROR_TRANSACTIONAL_CONFLICT() { return (int)6800L; }

    static final int ERROR_RM_NOT_ACTIVE() { return (int)6801L; }

    static final int ERROR_RM_METADATA_CORRUPT() { return (int)6802L; }

    static final int ERROR_DIRECTORY_NOT_RM() { return (int)6803L; }

    static final int ERROR_TRANSACTIONS_UNSUPPORTED_REMOTE() { return (int)6805L; }

    static final int ERROR_LOG_RESIZE_INVALID_SIZE() { return (int)6806L; }

    static final int ERROR_OBJECT_NO_LONGER_EXISTS() { return (int)6807L; }

    static final int ERROR_STREAM_MINIVERSION_NOT_FOUND() { return (int)6808L; }

    static final int ERROR_STREAM_MINIVERSION_NOT_VALID() { return (int)6809L; }

    static final int ERROR_MINIVERSION_INACCESSIBLE_FROM_SPECIFIED_TRANSACTION() { return (int)6810L; }

    static final int ERROR_CANT_OPEN_MINIVERSION_WITH_MODIFY_INTENT() { return (int)6811L; }

    static final int ERROR_CANT_CREATE_MORE_STREAM_MINIVERSIONS() { return (int)6812L; }

    static final int ERROR_REMOTE_FILE_VERSION_MISMATCH() { return (int)6814L; }

    static final int ERROR_HANDLE_NO_LONGER_VALID() { return (int)6815L; }

    static final int ERROR_NO_TXF_METADATA() { return (int)6816L; }

    static final int ERROR_LOG_CORRUPTION_DETECTED() { return (int)6817L; }

    static final int ERROR_CANT_RECOVER_WITH_HANDLE_OPEN() { return (int)6818L; }

    static final int ERROR_RM_DISCONNECTED() { return (int)6819L; }

    static final int ERROR_ENLISTMENT_NOT_SUPERIOR() { return (int)6820L; }

    static final int ERROR_RECOVERY_NOT_NEEDED() { return (int)6821L; }

    static final int ERROR_RM_ALREADY_STARTED() { return (int)6822L; }

    static final int ERROR_FILE_IDENTITY_NOT_PERSISTENT() { return (int)6823L; }

    static final int ERROR_CANT_BREAK_TRANSACTIONAL_DEPENDENCY() { return (int)6824L; }

    static final int ERROR_CANT_CROSS_RM_BOUNDARY() { return (int)6825L; }

    static final int ERROR_TXF_DIR_NOT_EMPTY() { return (int)6826L; }

    static final int ERROR_INDOUBT_TRANSACTIONS_EXIST() { return (int)6827L; }

    static final int ERROR_TM_VOLATILE() { return (int)6828L; }

    static final int ERROR_ROLLBACK_TIMER_EXPIRED() { return (int)6829L; }

    static final int ERROR_TXF_ATTRIBUTE_CORRUPT() { return (int)6830L; }

    static final int ERROR_EFS_NOT_ALLOWED_IN_TRANSACTION() { return (int)6831L; }

    static final int ERROR_TRANSACTIONAL_OPEN_NOT_ALLOWED() { return (int)6832L; }

    static final int ERROR_LOG_GROWTH_FAILED() { return (int)6833L; }

    static final int ERROR_TRANSACTED_MAPPING_UNSUPPORTED_REMOTE() { return (int)6834L; }

    static final int ERROR_TXF_METADATA_ALREADY_PRESENT() { return (int)6835L; }

    static final int ERROR_TRANSACTION_SCOPE_CALLBACKS_NOT_SET() { return (int)6836L; }

    static final int ERROR_TRANSACTION_REQUIRED_PROMOTION() { return (int)6837L; }

    static final int ERROR_CANNOT_EXECUTE_FILE_IN_TRANSACTION() { return (int)6838L; }

    static final int ERROR_TRANSACTIONS_NOT_FROZEN() { return (int)6839L; }

    static final int ERROR_TRANSACTION_FREEZE_IN_PROGRESS() { return (int)6840L; }

    static final int ERROR_NOT_SNAPSHOT_VOLUME() { return (int)6841L; }

    static final int ERROR_NO_SAVEPOINT_WITH_OPEN_FILES() { return (int)6842L; }

    static final int ERROR_DATA_LOST_REPAIR() { return (int)6843L; }

    static final int ERROR_SPARSE_NOT_ALLOWED_IN_TRANSACTION() { return (int)6844L; }

    static final int ERROR_TM_IDENTITY_MISMATCH() { return (int)6845L; }

    static final int ERROR_FLOATED_SECTION() { return (int)6846L; }

    static final int ERROR_CANNOT_ACCEPT_TRANSACTED_WORK() { return (int)6847L; }

    static final int ERROR_CANNOT_ABORT_TRANSACTIONS() { return (int)6848L; }

    static final int ERROR_BAD_CLUSTERS() { return (int)6849L; }

    static final int ERROR_COMPRESSION_NOT_ALLOWED_IN_TRANSACTION() { return (int)6850L; }

    static final int ERROR_VOLUME_DIRTY() { return (int)6851L; }

    static final int ERROR_NO_LINK_TRACKING_IN_TRANSACTION() { return (int)6852L; }

    static final int ERROR_OPERATION_NOT_SUPPORTED_IN_TRANSACTION() { return (int)6853L; }

    static final int ERROR_EXPIRED_HANDLE() { return (int)6854L; }

    static final int ERROR_TRANSACTION_NOT_ENLISTED() { return (int)6855L; }

    static final int ERROR_CTX_WINSTATION_NAME_INVALID() { return (int)7001L; }

    static final int ERROR_CTX_INVALID_PD() { return (int)7002L; }

    static final int ERROR_CTX_PD_NOT_FOUND() { return (int)7003L; }

    static final int ERROR_CTX_WD_NOT_FOUND() { return (int)7004L; }

    static final int ERROR_CTX_CANNOT_MAKE_EVENTLOG_ENTRY() { return (int)7005L; }

    static final int ERROR_CTX_SERVICE_NAME_COLLISION() { return (int)7006L; }

    static final int ERROR_CTX_CLOSE_PENDING() { return (int)7007L; }

    static final int ERROR_CTX_NO_OUTBUF() { return (int)7008L; }

    static final int ERROR_CTX_MODEM_INF_NOT_FOUND() { return (int)7009L; }

    static final int ERROR_CTX_INVALID_MODEMNAME() { return (int)7010L; }

    static final int ERROR_CTX_MODEM_RESPONSE_ERROR() { return (int)7011L; }

    static final int ERROR_CTX_MODEM_RESPONSE_TIMEOUT() { return (int)7012L; }

    static final int ERROR_CTX_MODEM_RESPONSE_NO_CARRIER() { return (int)7013L; }

    static final int ERROR_CTX_MODEM_RESPONSE_NO_DIALTONE() { return (int)7014L; }

    static final int ERROR_CTX_MODEM_RESPONSE_BUSY() { return (int)7015L; }

    static final int ERROR_CTX_MODEM_RESPONSE_VOICE() { return (int)7016L; }

    static final int ERROR_CTX_TD_ERROR() { return (int)7017L; }

    static final int ERROR_CTX_WINSTATION_NOT_FOUND() { return (int)7022L; }

    static final int ERROR_CTX_WINSTATION_ALREADY_EXISTS() { return (int)7023L; }

    static final int ERROR_CTX_WINSTATION_BUSY() { return (int)7024L; }

    static final int ERROR_CTX_BAD_VIDEO_MODE() { return (int)7025L; }

    static final int ERROR_CTX_GRAPHICS_INVALID() { return (int)7035L; }

    static final int ERROR_CTX_LOGON_DISABLED() { return (int)7037L; }

    static final int ERROR_CTX_NOT_CONSOLE() { return (int)7038L; }

    static final int ERROR_CTX_CLIENT_QUERY_TIMEOUT() { return (int)7040L; }

    static final int ERROR_CTX_CONSOLE_DISCONNECT() { return (int)7041L; }

    static final int ERROR_CTX_CONSOLE_CONNECT() { return (int)7042L; }

    static final int ERROR_CTX_SHADOW_DENIED() { return (int)7044L; }

    static final int ERROR_CTX_WINSTATION_ACCESS_DENIED() { return (int)7045L; }

    static final int ERROR_CTX_INVALID_WD() { return (int)7049L; }

    static final int ERROR_CTX_SHADOW_INVALID() { return (int)7050L; }

    static final int ERROR_CTX_SHADOW_DISABLED() { return (int)7051L; }

    static final int ERROR_CTX_CLIENT_LICENSE_IN_USE() { return (int)7052L; }

    static final int ERROR_CTX_CLIENT_LICENSE_NOT_SET() { return (int)7053L; }

    static final int ERROR_CTX_LICENSE_NOT_AVAILABLE() { return (int)7054L; }

    static final int ERROR_CTX_LICENSE_CLIENT_INVALID() { return (int)7055L; }

    static final int ERROR_CTX_LICENSE_EXPIRED() { return (int)7056L; }

    static final int ERROR_CTX_SHADOW_NOT_RUNNING() { return (int)7057L; }

    static final int ERROR_CTX_SHADOW_ENDED_BY_MODE_CHANGE() { return (int)7058L; }

    static final int ERROR_ACTIVATION_COUNT_EXCEEDED() { return (int)7059L; }

    static final int ERROR_CTX_WINSTATIONS_DISABLED() { return (int)7060L; }

    static final int ERROR_CTX_ENCRYPTION_LEVEL_REQUIRED() { return (int)7061L; }

    static final int ERROR_CTX_SESSION_IN_USE() { return (int)7062L; }

    static final int ERROR_CTX_NO_FORCE_LOGOFF() { return (int)7063L; }

    static final int ERROR_CTX_ACCOUNT_RESTRICTION() { return (int)7064L; }

    static final int ERROR_RDP_PROTOCOL_ERROR() { return (int)7065L; }

    static final int ERROR_CTX_CDM_CONNECT() { return (int)7066L; }

    static final int ERROR_CTX_CDM_DISCONNECT() { return (int)7067L; }

    static final int ERROR_CTX_SECURITY_LAYER_ERROR() { return (int)7068L; }

    static final int ERROR_TS_INCOMPATIBLE_SESSIONS() { return (int)7069L; }

    static final int ERROR_TS_VIDEO_SUBSYSTEM_ERROR() { return (int)7070L; }

    static final int FRS_ERR_INVALID_API_SEQUENCE() { return (int)8001L; }

    static final int FRS_ERR_STARTING_SERVICE() { return (int)8002L; }

    static final int FRS_ERR_STOPPING_SERVICE() { return (int)8003L; }

    static final int FRS_ERR_INTERNAL_API() { return (int)8004L; }

    static final int FRS_ERR_INTERNAL() { return (int)8005L; }

    static final int FRS_ERR_SERVICE_COMM() { return (int)8006L; }

    static final int FRS_ERR_INSUFFICIENT_PRIV() { return (int)8007L; }

    static final int FRS_ERR_AUTHENTICATION() { return (int)8008L; }

    static final int FRS_ERR_PARENT_INSUFFICIENT_PRIV() { return (int)8009L; }

    static final int FRS_ERR_PARENT_AUTHENTICATION() { return (int)8010L; }

    static final int FRS_ERR_CHILD_TO_PARENT_COMM() { return (int)8011L; }

    static final int FRS_ERR_PARENT_TO_CHILD_COMM() { return (int)8012L; }

    static final int FRS_ERR_SYSVOL_POPULATE() { return (int)8013L; }

    static final int FRS_ERR_SYSVOL_POPULATE_TIMEOUT() { return (int)8014L; }

    static final int FRS_ERR_SYSVOL_IS_BUSY() { return (int)8015L; }

    static final int FRS_ERR_SYSVOL_DEMOTE() { return (int)8016L; }

    static final int FRS_ERR_INVALID_SERVICE_PARAMETER() { return (int)8017L; }

    static final int DS_S_SUCCESS() { return (int)0L; }

    static final int ERROR_DS_NOT_INSTALLED() { return (int)8200L; }

    static final int ERROR_DS_MEMBERSHIP_EVALUATED_LOCALLY() { return (int)8201L; }

    static final int ERROR_DS_NO_ATTRIBUTE_OR_VALUE() { return (int)8202L; }

    static final int ERROR_DS_INVALID_ATTRIBUTE_SYNTAX() { return (int)8203L; }

    static final int ERROR_DS_ATTRIBUTE_TYPE_UNDEFINED() { return (int)8204L; }

    static final int ERROR_DS_ATTRIBUTE_OR_VALUE_EXISTS() { return (int)8205L; }

    static final int ERROR_DS_BUSY() { return (int)8206L; }

    static final int ERROR_DS_UNAVAILABLE() { return (int)8207L; }

    static final int ERROR_DS_NO_RIDS_ALLOCATED() { return (int)8208L; }

    static final int ERROR_DS_NO_MORE_RIDS() { return (int)8209L; }

    static final int ERROR_DS_INCORRECT_ROLE_OWNER() { return (int)8210L; }

    static final int ERROR_DS_RIDMGR_INIT_ERROR() { return (int)8211L; }

    static final int ERROR_DS_OBJ_CLASS_VIOLATION() { return (int)8212L; }

    static final int ERROR_DS_CANT_ON_NON_LEAF() { return (int)8213L; }

    static final int ERROR_DS_CANT_ON_RDN() { return (int)8214L; }

    static final int ERROR_DS_CANT_MOD_OBJ_CLASS() { return (int)8215L; }

    static final int ERROR_DS_CROSS_DOM_MOVE_ERROR() { return (int)8216L; }

    static final int ERROR_DS_GC_NOT_AVAILABLE() { return (int)8217L; }

    static final int ERROR_SHARED_POLICY() { return (int)8218L; }

    static final int ERROR_POLICY_OBJECT_NOT_FOUND() { return (int)8219L; }

    static final int ERROR_POLICY_ONLY_IN_DS() { return (int)8220L; }

    static final int ERROR_PROMOTION_ACTIVE() { return (int)8221L; }

    static final int ERROR_NO_PROMOTION_ACTIVE() { return (int)8222L; }

    static final int ERROR_DS_OPERATIONS_ERROR() { return (int)8224L; }

    static final int ERROR_DS_PROTOCOL_ERROR() { return (int)8225L; }

    static final int ERROR_DS_TIMELIMIT_EXCEEDED() { return (int)8226L; }

    static final int ERROR_DS_SIZELIMIT_EXCEEDED() { return (int)8227L; }

    static final int ERROR_DS_ADMIN_LIMIT_EXCEEDED() { return (int)8228L; }

    static final int ERROR_DS_COMPARE_FALSE() { return (int)8229L; }

    static final int ERROR_DS_COMPARE_TRUE() { return (int)8230L; }

    static final int ERROR_DS_AUTH_METHOD_NOT_SUPPORTED() { return (int)8231L; }

    static final int ERROR_DS_STRONG_AUTH_REQUIRED() { return (int)8232L; }

    static final int ERROR_DS_INAPPROPRIATE_AUTH() { return (int)8233L; }

    static final int ERROR_DS_AUTH_UNKNOWN() { return (int)8234L; }

    static final int ERROR_DS_REFERRAL() { return (int)8235L; }

    static final int ERROR_DS_UNAVAILABLE_CRIT_EXTENSION() { return (int)8236L; }

    static final int ERROR_DS_CONFIDENTIALITY_REQUIRED() { return (int)8237L; }

    static final int ERROR_DS_INAPPROPRIATE_MATCHING() { return (int)8238L; }

    static final int ERROR_DS_CONSTRAINT_VIOLATION() { return (int)8239L; }

    static final int ERROR_DS_NO_SUCH_OBJECT() { return (int)8240L; }

    static final int ERROR_DS_ALIAS_PROBLEM() { return (int)8241L; }

    static final int ERROR_DS_INVALID_DN_SYNTAX() { return (int)8242L; }

    static final int ERROR_DS_IS_LEAF() { return (int)8243L; }

    static final int ERROR_DS_ALIAS_DEREF_PROBLEM() { return (int)8244L; }

    static final int ERROR_DS_UNWILLING_TO_PERFORM() { return (int)8245L; }

    static final int ERROR_DS_LOOP_DETECT() { return (int)8246L; }

    static final int ERROR_DS_NAMING_VIOLATION() { return (int)8247L; }

    static final int ERROR_DS_OBJECT_RESULTS_TOO_LARGE() { return (int)8248L; }

    static final int ERROR_DS_AFFECTS_MULTIPLE_DSAS() { return (int)8249L; }

    static final int ERROR_DS_SERVER_DOWN() { return (int)8250L; }

    static final int ERROR_DS_LOCAL_ERROR() { return (int)8251L; }

    static final int ERROR_DS_ENCODING_ERROR() { return (int)8252L; }

    static final int ERROR_DS_DECODING_ERROR() { return (int)8253L; }

    static final int ERROR_DS_FILTER_UNKNOWN() { return (int)8254L; }

    static final int ERROR_DS_PARAM_ERROR() { return (int)8255L; }

    static final int ERROR_DS_NOT_SUPPORTED() { return (int)8256L; }

    static final int ERROR_DS_NO_RESULTS_RETURNED() { return (int)8257L; }

    static final int ERROR_DS_CONTROL_NOT_FOUND() { return (int)8258L; }

    static final int ERROR_DS_CLIENT_LOOP() { return (int)8259L; }

    static final int ERROR_DS_REFERRAL_LIMIT_EXCEEDED() { return (int)8260L; }

    static final int ERROR_DS_SORT_CONTROL_MISSING() { return (int)8261L; }

    static final int ERROR_DS_OFFSET_RANGE_ERROR() { return (int)8262L; }

    static final int ERROR_DS_RIDMGR_DISABLED() { return (int)8263L; }

    static final int ERROR_DS_ROOT_MUST_BE_NC() { return (int)8301L; }

    static final int ERROR_DS_ADD_REPLICA_INHIBITED() { return (int)8302L; }

    static final int ERROR_DS_ATT_NOT_DEF_IN_SCHEMA() { return (int)8303L; }

    static final int ERROR_DS_MAX_OBJ_SIZE_EXCEEDED() { return (int)8304L; }

    static final int ERROR_DS_OBJ_STRING_NAME_EXISTS() { return (int)8305L; }

    static final int ERROR_DS_NO_RDN_DEFINED_IN_SCHEMA() { return (int)8306L; }

    static final int ERROR_DS_RDN_DOESNT_MATCH_SCHEMA() { return (int)8307L; }

    static final int ERROR_DS_NO_REQUESTED_ATTS_FOUND() { return (int)8308L; }

    static final int ERROR_DS_USER_BUFFER_TO_SMALL() { return (int)8309L; }

    static final int ERROR_DS_ATT_IS_NOT_ON_OBJ() { return (int)8310L; }

    static final int ERROR_DS_ILLEGAL_MOD_OPERATION() { return (int)8311L; }

    static final int ERROR_DS_OBJ_TOO_LARGE() { return (int)8312L; }

    static final int ERROR_DS_BAD_INSTANCE_TYPE() { return (int)8313L; }

    static final int ERROR_DS_MASTERDSA_REQUIRED() { return (int)8314L; }

    static final int ERROR_DS_OBJECT_CLASS_REQUIRED() { return (int)8315L; }

    static final int ERROR_DS_MISSING_REQUIRED_ATT() { return (int)8316L; }

    static final int ERROR_DS_ATT_NOT_DEF_FOR_CLASS() { return (int)8317L; }

    static final int ERROR_DS_ATT_ALREADY_EXISTS() { return (int)8318L; }

    static final int ERROR_DS_CANT_ADD_ATT_VALUES() { return (int)8320L; }

    static final int ERROR_DS_SINGLE_VALUE_CONSTRAINT() { return (int)8321L; }

    static final int ERROR_DS_RANGE_CONSTRAINT() { return (int)8322L; }

    static final int ERROR_DS_ATT_VAL_ALREADY_EXISTS() { return (int)8323L; }

    static final int ERROR_DS_CANT_REM_MISSING_ATT() { return (int)8324L; }

    static final int ERROR_DS_CANT_REM_MISSING_ATT_VAL() { return (int)8325L; }

    static final int ERROR_DS_ROOT_CANT_BE_SUBREF() { return (int)8326L; }

    static final int ERROR_DS_NO_CHAINING() { return (int)8327L; }

    static final int ERROR_DS_NO_CHAINED_EVAL() { return (int)8328L; }

    static final int ERROR_DS_NO_PARENT_OBJECT() { return (int)8329L; }

    static final int ERROR_DS_PARENT_IS_AN_ALIAS() { return (int)8330L; }

    static final int ERROR_DS_CANT_MIX_MASTER_AND_REPS() { return (int)8331L; }

    static final int ERROR_DS_CHILDREN_EXIST() { return (int)8332L; }

    static final int ERROR_DS_OBJ_NOT_FOUND() { return (int)8333L; }

    static final int ERROR_DS_ALIASED_OBJ_MISSING() { return (int)8334L; }

    static final int ERROR_DS_BAD_NAME_SYNTAX() { return (int)8335L; }

    static final int ERROR_DS_ALIAS_POINTS_TO_ALIAS() { return (int)8336L; }

    static final int ERROR_DS_CANT_DEREF_ALIAS() { return (int)8337L; }

    static final int ERROR_DS_OUT_OF_SCOPE() { return (int)8338L; }

    static final int ERROR_DS_OBJECT_BEING_REMOVED() { return (int)8339L; }

    static final int ERROR_DS_CANT_DELETE_DSA_OBJ() { return (int)8340L; }

    static final int ERROR_DS_GENERIC_ERROR() { return (int)8341L; }

    static final int ERROR_DS_DSA_MUST_BE_INT_MASTER() { return (int)8342L; }

    static final int ERROR_DS_CLASS_NOT_DSA() { return (int)8343L; }

    static final int ERROR_DS_INSUFF_ACCESS_RIGHTS() { return (int)8344L; }

    static final int ERROR_DS_ILLEGAL_SUPERIOR() { return (int)8345L; }

    static final int ERROR_DS_ATTRIBUTE_OWNED_BY_SAM() { return (int)8346L; }

    static final int ERROR_DS_NAME_TOO_MANY_PARTS() { return (int)8347L; }

    static final int ERROR_DS_NAME_TOO_LONG() { return (int)8348L; }

    static final int ERROR_DS_NAME_VALUE_TOO_LONG() { return (int)8349L; }

    static final int ERROR_DS_NAME_UNPARSEABLE() { return (int)8350L; }

    static final int ERROR_DS_NAME_TYPE_UNKNOWN() { return (int)8351L; }

    static final int ERROR_DS_NOT_AN_OBJECT() { return (int)8352L; }

    static final int ERROR_DS_SEC_DESC_TOO_SHORT() { return (int)8353L; }

    static final int ERROR_DS_SEC_DESC_INVALID() { return (int)8354L; }

    static final int ERROR_DS_NO_DELETED_NAME() { return (int)8355L; }

    static final int ERROR_DS_SUBREF_MUST_HAVE_PARENT() { return (int)8356L; }

    static final int ERROR_DS_NCNAME_MUST_BE_NC() { return (int)8357L; }

    static final int ERROR_DS_CANT_ADD_SYSTEM_ONLY() { return (int)8358L; }

    static final int ERROR_DS_CLASS_MUST_BE_CONCRETE() { return (int)8359L; }

    static final int ERROR_DS_INVALID_DMD() { return (int)8360L; }

    static final int ERROR_DS_OBJ_GUID_EXISTS() { return (int)8361L; }

    static final int ERROR_DS_NOT_ON_BACKLINK() { return (int)8362L; }

    static final int ERROR_DS_NO_CROSSREF_FOR_NC() { return (int)8363L; }

    static final int ERROR_DS_SHUTTING_DOWN() { return (int)8364L; }

    static final int ERROR_DS_UNKNOWN_OPERATION() { return (int)8365L; }

    static final int ERROR_DS_INVALID_ROLE_OWNER() { return (int)8366L; }

    static final int ERROR_DS_COULDNT_CONTACT_FSMO() { return (int)8367L; }

    static final int ERROR_DS_CROSS_NC_DN_RENAME() { return (int)8368L; }

    static final int ERROR_DS_CANT_MOD_SYSTEM_ONLY() { return (int)8369L; }

    static final int ERROR_DS_REPLICATOR_ONLY() { return (int)8370L; }

    static final int ERROR_DS_OBJ_CLASS_NOT_DEFINED() { return (int)8371L; }

    static final int ERROR_DS_OBJ_CLASS_NOT_SUBCLASS() { return (int)8372L; }

    static final int ERROR_DS_NAME_REFERENCE_INVALID() { return (int)8373L; }

    static final int ERROR_DS_CROSS_REF_EXISTS() { return (int)8374L; }

    static final int ERROR_DS_CANT_DEL_MASTER_CROSSREF() { return (int)8375L; }

    static final int ERROR_DS_SUBTREE_NOTIFY_NOT_NC_HEAD() { return (int)8376L; }

    static final int ERROR_DS_NOTIFY_FILTER_TOO_COMPLEX() { return (int)8377L; }

    static final int ERROR_DS_DUP_RDN() { return (int)8378L; }

    static final int ERROR_DS_DUP_OID() { return (int)8379L; }

    static final int ERROR_DS_DUP_MAPI_ID() { return (int)8380L; }

    static final int ERROR_DS_DUP_SCHEMA_ID_GUID() { return (int)8381L; }

    static final int ERROR_DS_DUP_LDAP_DISPLAY_NAME() { return (int)8382L; }

    static final int ERROR_DS_SEMANTIC_ATT_TEST() { return (int)8383L; }

    static final int ERROR_DS_SYNTAX_MISMATCH() { return (int)8384L; }

    static final int ERROR_DS_EXISTS_IN_MUST_HAVE() { return (int)8385L; }

    static final int ERROR_DS_EXISTS_IN_MAY_HAVE() { return (int)8386L; }

    static final int ERROR_DS_NONEXISTENT_MAY_HAVE() { return (int)8387L; }

    static final int ERROR_DS_NONEXISTENT_MUST_HAVE() { return (int)8388L; }

    static final int ERROR_DS_AUX_CLS_TEST_FAIL() { return (int)8389L; }

    static final int ERROR_DS_NONEXISTENT_POSS_SUP() { return (int)8390L; }

    static final int ERROR_DS_SUB_CLS_TEST_FAIL() { return (int)8391L; }

    static final int ERROR_DS_BAD_RDN_ATT_ID_SYNTAX() { return (int)8392L; }

    static final int ERROR_DS_EXISTS_IN_AUX_CLS() { return (int)8393L; }

    static final int ERROR_DS_EXISTS_IN_SUB_CLS() { return (int)8394L; }

    static final int ERROR_DS_EXISTS_IN_POSS_SUP() { return (int)8395L; }

    static final int ERROR_DS_RECALCSCHEMA_FAILED() { return (int)8396L; }

    static final int ERROR_DS_TREE_DELETE_NOT_FINISHED() { return (int)8397L; }

    static final int ERROR_DS_CANT_DELETE() { return (int)8398L; }

    static final int ERROR_DS_ATT_SCHEMA_REQ_ID() { return (int)8399L; }

    static final int ERROR_DS_BAD_ATT_SCHEMA_SYNTAX() { return (int)8400L; }

    static final int ERROR_DS_CANT_CACHE_ATT() { return (int)8401L; }

    static final int ERROR_DS_CANT_CACHE_CLASS() { return (int)8402L; }

    static final int ERROR_DS_CANT_REMOVE_ATT_CACHE() { return (int)8403L; }

    static final int ERROR_DS_CANT_REMOVE_CLASS_CACHE() { return (int)8404L; }

    static final int ERROR_DS_CANT_RETRIEVE_DN() { return (int)8405L; }

    static final int ERROR_DS_MISSING_SUPREF() { return (int)8406L; }

    static final int ERROR_DS_CANT_RETRIEVE_INSTANCE() { return (int)8407L; }

    static final int ERROR_DS_CODE_INCONSISTENCY() { return (int)8408L; }

    static final int ERROR_DS_DATABASE_ERROR() { return (int)8409L; }

    static final int ERROR_DS_GOVERNSID_MISSING() { return (int)8410L; }

    static final int ERROR_DS_MISSING_EXPECTED_ATT() { return (int)8411L; }

    static final int ERROR_DS_NCNAME_MISSING_CR_REF() { return (int)8412L; }

    static final int ERROR_DS_SECURITY_CHECKING_ERROR() { return (int)8413L; }

    static final int ERROR_DS_SCHEMA_NOT_LOADED() { return (int)8414L; }

    static final int ERROR_DS_SCHEMA_ALLOC_FAILED() { return (int)8415L; }

    static final int ERROR_DS_ATT_SCHEMA_REQ_SYNTAX() { return (int)8416L; }

    static final int ERROR_DS_GCVERIFY_ERROR() { return (int)8417L; }

    static final int ERROR_DS_DRA_SCHEMA_MISMATCH() { return (int)8418L; }

    static final int ERROR_DS_CANT_FIND_DSA_OBJ() { return (int)8419L; }

    static final int ERROR_DS_CANT_FIND_EXPECTED_NC() { return (int)8420L; }

    static final int ERROR_DS_CANT_FIND_NC_IN_CACHE() { return (int)8421L; }

    static final int ERROR_DS_CANT_RETRIEVE_CHILD() { return (int)8422L; }

    static final int ERROR_DS_SECURITY_ILLEGAL_MODIFY() { return (int)8423L; }

    static final int ERROR_DS_CANT_REPLACE_HIDDEN_REC() { return (int)8424L; }

    static final int ERROR_DS_BAD_HIERARCHY_FILE() { return (int)8425L; }

    static final int ERROR_DS_BUILD_HIERARCHY_TABLE_FAILED() { return (int)8426L; }

    static final int ERROR_DS_CONFIG_PARAM_MISSING() { return (int)8427L; }

    static final int ERROR_DS_COUNTING_AB_INDICES_FAILED() { return (int)8428L; }

    static final int ERROR_DS_HIERARCHY_TABLE_MALLOC_FAILED() { return (int)8429L; }

    static final int ERROR_DS_INTERNAL_FAILURE() { return (int)8430L; }

    static final int ERROR_DS_UNKNOWN_ERROR() { return (int)8431L; }

    static final int ERROR_DS_ROOT_REQUIRES_CLASS_TOP() { return (int)8432L; }

    static final int ERROR_DS_REFUSING_FSMO_ROLES() { return (int)8433L; }

    static final int ERROR_DS_MISSING_FSMO_SETTINGS() { return (int)8434L; }

    static final int ERROR_DS_UNABLE_TO_SURRENDER_ROLES() { return (int)8435L; }

    static final int ERROR_DS_DRA_GENERIC() { return (int)8436L; }

    static final int ERROR_DS_DRA_INVALID_PARAMETER() { return (int)8437L; }

    static final int ERROR_DS_DRA_BUSY() { return (int)8438L; }

    static final int ERROR_DS_DRA_BAD_DN() { return (int)8439L; }

    static final int ERROR_DS_DRA_BAD_NC() { return (int)8440L; }

    static final int ERROR_DS_DRA_DN_EXISTS() { return (int)8441L; }

    static final int ERROR_DS_DRA_INTERNAL_ERROR() { return (int)8442L; }

    static final int ERROR_DS_DRA_INCONSISTENT_DIT() { return (int)8443L; }

    static final int ERROR_DS_DRA_CONNECTION_FAILED() { return (int)8444L; }

    static final int ERROR_DS_DRA_BAD_INSTANCE_TYPE() { return (int)8445L; }

    static final int ERROR_DS_DRA_OUT_OF_MEM() { return (int)8446L; }

    static final int ERROR_DS_DRA_MAIL_PROBLEM() { return (int)8447L; }

    static final int ERROR_DS_DRA_REF_ALREADY_EXISTS() { return (int)8448L; }

    static final int ERROR_DS_DRA_REF_NOT_FOUND() { return (int)8449L; }

    static final int ERROR_DS_DRA_OBJ_IS_REP_SOURCE() { return (int)8450L; }

    static final int ERROR_DS_DRA_DB_ERROR() { return (int)8451L; }

    static final int ERROR_DS_DRA_NO_REPLICA() { return (int)8452L; }

    static final int ERROR_DS_DRA_ACCESS_DENIED() { return (int)8453L; }

    static final int ERROR_DS_DRA_NOT_SUPPORTED() { return (int)8454L; }

    static final int ERROR_DS_DRA_RPC_CANCELLED() { return (int)8455L; }

    static final int ERROR_DS_DRA_SOURCE_DISABLED() { return (int)8456L; }

    static final int ERROR_DS_DRA_SINK_DISABLED() { return (int)8457L; }

    static final int ERROR_DS_DRA_NAME_COLLISION() { return (int)8458L; }

    static final int ERROR_DS_DRA_SOURCE_REINSTALLED() { return (int)8459L; }

    static final int ERROR_DS_DRA_MISSING_PARENT() { return (int)8460L; }

    static final int ERROR_DS_DRA_PREEMPTED() { return (int)8461L; }

    static final int ERROR_DS_DRA_ABANDON_SYNC() { return (int)8462L; }

    static final int ERROR_DS_DRA_SHUTDOWN() { return (int)8463L; }

    static final int ERROR_DS_DRA_INCOMPATIBLE_PARTIAL_SET() { return (int)8464L; }

    static final int ERROR_DS_DRA_SOURCE_IS_PARTIAL_REPLICA() { return (int)8465L; }

    static final int ERROR_DS_DRA_EXTN_CONNECTION_FAILED() { return (int)8466L; }

    static final int ERROR_DS_INSTALL_SCHEMA_MISMATCH() { return (int)8467L; }

    static final int ERROR_DS_DUP_LINK_ID() { return (int)8468L; }

    static final int ERROR_DS_NAME_ERROR_RESOLVING() { return (int)8469L; }

    static final int ERROR_DS_NAME_ERROR_NOT_FOUND() { return (int)8470L; }

    static final int ERROR_DS_NAME_ERROR_NOT_UNIQUE() { return (int)8471L; }

    static final int ERROR_DS_NAME_ERROR_NO_MAPPING() { return (int)8472L; }

    static final int ERROR_DS_NAME_ERROR_DOMAIN_ONLY() { return (int)8473L; }

    static final int ERROR_DS_NAME_ERROR_NO_SYNTACTICAL_MAPPING() { return (int)8474L; }

    static final int ERROR_DS_CONSTRUCTED_ATT_MOD() { return (int)8475L; }

    static final int ERROR_DS_WRONG_OM_OBJ_CLASS() { return (int)8476L; }

    static final int ERROR_DS_DRA_REPL_PENDING() { return (int)8477L; }

    static final int ERROR_DS_DS_REQUIRED() { return (int)8478L; }

    static final int ERROR_DS_INVALID_LDAP_DISPLAY_NAME() { return (int)8479L; }

    static final int ERROR_DS_NON_BASE_SEARCH() { return (int)8480L; }

    static final int ERROR_DS_CANT_RETRIEVE_ATTS() { return (int)8481L; }

    static final int ERROR_DS_BACKLINK_WITHOUT_LINK() { return (int)8482L; }

    static final int ERROR_DS_EPOCH_MISMATCH() { return (int)8483L; }

    static final int ERROR_DS_SRC_NAME_MISMATCH() { return (int)8484L; }

    static final int ERROR_DS_SRC_AND_DST_NC_IDENTICAL() { return (int)8485L; }

    static final int ERROR_DS_DST_NC_MISMATCH() { return (int)8486L; }

    static final int ERROR_DS_NOT_AUTHORITIVE_FOR_DST_NC() { return (int)8487L; }

    static final int ERROR_DS_SRC_GUID_MISMATCH() { return (int)8488L; }

    static final int ERROR_DS_CANT_MOVE_DELETED_OBJECT() { return (int)8489L; }

    static final int ERROR_DS_PDC_OPERATION_IN_PROGRESS() { return (int)8490L; }

    static final int ERROR_DS_CROSS_DOMAIN_CLEANUP_REQD() { return (int)8491L; }

    static final int ERROR_DS_ILLEGAL_XDOM_MOVE_OPERATION() { return (int)8492L; }

    static final int ERROR_DS_CANT_WITH_ACCT_GROUP_MEMBERSHPS() { return (int)8493L; }

    static final int ERROR_DS_NC_MUST_HAVE_NC_PARENT() { return (int)8494L; }

    static final int ERROR_DS_CR_IMPOSSIBLE_TO_VALIDATE() { return (int)8495L; }

    static final int ERROR_DS_DST_DOMAIN_NOT_NATIVE() { return (int)8496L; }

    static final int ERROR_DS_MISSING_INFRASTRUCTURE_CONTAINER() { return (int)8497L; }

    static final int ERROR_DS_CANT_MOVE_ACCOUNT_GROUP() { return (int)8498L; }

    static final int ERROR_DS_CANT_MOVE_RESOURCE_GROUP() { return (int)8499L; }

    static final int ERROR_DS_INVALID_SEARCH_FLAG() { return (int)8500L; }

    static final int ERROR_DS_NO_TREE_DELETE_ABOVE_NC() { return (int)8501L; }

    static final int ERROR_DS_COULDNT_LOCK_TREE_FOR_DELETE() { return (int)8502L; }

    static final int ERROR_DS_COULDNT_IDENTIFY_OBJECTS_FOR_TREE_DELETE() { return (int)8503L; }

    static final int ERROR_DS_SAM_INIT_FAILURE() { return (int)8504L; }

    static final int ERROR_DS_SENSITIVE_GROUP_VIOLATION() { return (int)8505L; }

    static final int ERROR_DS_CANT_MOD_PRIMARYGROUPID() { return (int)8506L; }

    static final int ERROR_DS_ILLEGAL_BASE_SCHEMA_MOD() { return (int)8507L; }

    static final int ERROR_DS_NONSAFE_SCHEMA_CHANGE() { return (int)8508L; }

    static final int ERROR_DS_SCHEMA_UPDATE_DISALLOWED() { return (int)8509L; }

    static final int ERROR_DS_CANT_CREATE_UNDER_SCHEMA() { return (int)8510L; }

    static final int ERROR_DS_INSTALL_NO_SRC_SCH_VERSION() { return (int)8511L; }

    static final int ERROR_DS_INSTALL_NO_SCH_VERSION_IN_INIFILE() { return (int)8512L; }

    static final int ERROR_DS_INVALID_GROUP_TYPE() { return (int)8513L; }

    static final int ERROR_DS_NO_NEST_GLOBALGROUP_IN_MIXEDDOMAIN() { return (int)8514L; }

    static final int ERROR_DS_NO_NEST_LOCALGROUP_IN_MIXEDDOMAIN() { return (int)8515L; }

    static final int ERROR_DS_GLOBAL_CANT_HAVE_LOCAL_MEMBER() { return (int)8516L; }

    static final int ERROR_DS_GLOBAL_CANT_HAVE_UNIVERSAL_MEMBER() { return (int)8517L; }

    static final int ERROR_DS_UNIVERSAL_CANT_HAVE_LOCAL_MEMBER() { return (int)8518L; }

    static final int ERROR_DS_GLOBAL_CANT_HAVE_CROSSDOMAIN_MEMBER() { return (int)8519L; }

    static final int ERROR_DS_LOCAL_CANT_HAVE_CROSSDOMAIN_LOCAL_MEMBER() { return (int)8520L; }

    static final int ERROR_DS_HAVE_PRIMARY_MEMBERS() { return (int)8521L; }

    static final int ERROR_DS_STRING_SD_CONVERSION_FAILED() { return (int)8522L; }

    static final int ERROR_DS_NAMING_MASTER_GC() { return (int)8523L; }

    static final int ERROR_DS_DNS_LOOKUP_FAILURE() { return (int)8524L; }

    static final int ERROR_DS_COULDNT_UPDATE_SPNS() { return (int)8525L; }

    static final int ERROR_DS_CANT_RETRIEVE_SD() { return (int)8526L; }

    static final int ERROR_DS_KEY_NOT_UNIQUE() { return (int)8527L; }

    static final int ERROR_DS_WRONG_LINKED_ATT_SYNTAX() { return (int)8528L; }

    static final int ERROR_DS_SAM_NEED_BOOTKEY_PASSWORD() { return (int)8529L; }

    static final int ERROR_DS_SAM_NEED_BOOTKEY_FLOPPY() { return (int)8530L; }

    static final int ERROR_DS_CANT_START() { return (int)8531L; }

    static final int ERROR_DS_INIT_FAILURE() { return (int)8532L; }

    static final int ERROR_DS_NO_PKT_PRIVACY_ON_CONNECTION() { return (int)8533L; }

    static final int ERROR_DS_SOURCE_DOMAIN_IN_FOREST() { return (int)8534L; }

    static final int ERROR_DS_DESTINATION_DOMAIN_NOT_IN_FOREST() { return (int)8535L; }

    static final int ERROR_DS_DESTINATION_AUDITING_NOT_ENABLED() { return (int)8536L; }

    static final int ERROR_DS_CANT_FIND_DC_FOR_SRC_DOMAIN() { return (int)8537L; }

    static final int ERROR_DS_SRC_OBJ_NOT_GROUP_OR_USER() { return (int)8538L; }

    static final int ERROR_DS_SRC_SID_EXISTS_IN_FOREST() { return (int)8539L; }

    static final int ERROR_DS_SRC_AND_DST_OBJECT_CLASS_MISMATCH() { return (int)8540L; }

    static final int ERROR_SAM_INIT_FAILURE() { return (int)8541L; }

    static final int ERROR_DS_DRA_SCHEMA_INFO_SHIP() { return (int)8542L; }

    static final int ERROR_DS_DRA_SCHEMA_CONFLICT() { return (int)8543L; }

    static final int ERROR_DS_DRA_EARLIER_SCHEMA_CONFLICT() { return (int)8544L; }

    static final int ERROR_DS_DRA_OBJ_NC_MISMATCH() { return (int)8545L; }

    static final int ERROR_DS_NC_STILL_HAS_DSAS() { return (int)8546L; }

    static final int ERROR_DS_GC_REQUIRED() { return (int)8547L; }

    static final int ERROR_DS_LOCAL_MEMBER_OF_LOCAL_ONLY() { return (int)8548L; }

    static final int ERROR_DS_NO_FPO_IN_UNIVERSAL_GROUPS() { return (int)8549L; }

    static final int ERROR_DS_CANT_ADD_TO_GC() { return (int)8550L; }

    static final int ERROR_DS_NO_CHECKPOINT_WITH_PDC() { return (int)8551L; }

    static final int ERROR_DS_SOURCE_AUDITING_NOT_ENABLED() { return (int)8552L; }

    static final int ERROR_DS_CANT_CREATE_IN_NONDOMAIN_NC() { return (int)8553L; }

    static final int ERROR_DS_INVALID_NAME_FOR_SPN() { return (int)8554L; }

    static final int ERROR_DS_FILTER_USES_CONTRUCTED_ATTRS() { return (int)8555L; }

    static final int ERROR_DS_UNICODEPWD_NOT_IN_QUOTES() { return (int)8556L; }

    static final int ERROR_DS_MACHINE_ACCOUNT_QUOTA_EXCEEDED() { return (int)8557L; }

    static final int ERROR_DS_MUST_BE_RUN_ON_DST_DC() { return (int)8558L; }

    static final int ERROR_DS_SRC_DC_MUST_BE_SP4_OR_GREATER() { return (int)8559L; }

    static final int ERROR_DS_CANT_TREE_DELETE_CRITICAL_OBJ() { return (int)8560L; }

    static final int ERROR_DS_INIT_FAILURE_CONSOLE() { return (int)8561L; }

    static final int ERROR_DS_SAM_INIT_FAILURE_CONSOLE() { return (int)8562L; }

    static final int ERROR_DS_FOREST_VERSION_TOO_HIGH() { return (int)8563L; }

    static final int ERROR_DS_DOMAIN_VERSION_TOO_HIGH() { return (int)8564L; }

    static final int ERROR_DS_FOREST_VERSION_TOO_LOW() { return (int)8565L; }

    static final int ERROR_DS_DOMAIN_VERSION_TOO_LOW() { return (int)8566L; }

    static final int ERROR_DS_INCOMPATIBLE_VERSION() { return (int)8567L; }

    static final int ERROR_DS_LOW_DSA_VERSION() { return (int)8568L; }

    static final int ERROR_DS_NO_BEHAVIOR_VERSION_IN_MIXEDDOMAIN() { return (int)8569L; }

    static final int ERROR_DS_NOT_SUPPORTED_SORT_ORDER() { return (int)8570L; }

    static final int ERROR_DS_NAME_NOT_UNIQUE() { return (int)8571L; }

    static final int ERROR_DS_MACHINE_ACCOUNT_CREATED_PRENT4() { return (int)8572L; }

    static final int ERROR_DS_OUT_OF_VERSION_STORE() { return (int)8573L; }

    static final int ERROR_DS_INCOMPATIBLE_CONTROLS_USED() { return (int)8574L; }

    static final int ERROR_DS_NO_REF_DOMAIN() { return (int)8575L; }

    static final int ERROR_DS_RESERVED_LINK_ID() { return (int)8576L; }

    static final int ERROR_DS_LINK_ID_NOT_AVAILABLE() { return (int)8577L; }

    static final int ERROR_DS_AG_CANT_HAVE_UNIVERSAL_MEMBER() { return (int)8578L; }

    static final int ERROR_DS_MODIFYDN_DISALLOWED_BY_INSTANCE_TYPE() { return (int)8579L; }

    static final int ERROR_DS_NO_OBJECT_MOVE_IN_SCHEMA_NC() { return (int)8580L; }

    static final int ERROR_DS_MODIFYDN_DISALLOWED_BY_FLAG() { return (int)8581L; }

    static final int ERROR_DS_MODIFYDN_WRONG_GRANDPARENT() { return (int)8582L; }

    static final int ERROR_DS_NAME_ERROR_TRUST_REFERRAL() { return (int)8583L; }

    static final int ERROR_NOT_SUPPORTED_ON_STANDARD_SERVER() { return (int)8584L; }

    static final int ERROR_DS_CANT_ACCESS_REMOTE_PART_OF_AD() { return (int)8585L; }

    static final int ERROR_DS_CR_IMPOSSIBLE_TO_VALIDATE_V2() { return (int)8586L; }

    static final int ERROR_DS_THREAD_LIMIT_EXCEEDED() { return (int)8587L; }

    static final int ERROR_DS_NOT_CLOSEST() { return (int)8588L; }

    static final int ERROR_DS_CANT_DERIVE_SPN_WITHOUT_SERVER_REF() { return (int)8589L; }

    static final int ERROR_DS_SINGLE_USER_MODE_FAILED() { return (int)8590L; }

    static final int ERROR_DS_NTDSCRIPT_SYNTAX_ERROR() { return (int)8591L; }

    static final int ERROR_DS_NTDSCRIPT_PROCESS_ERROR() { return (int)8592L; }

    static final int ERROR_DS_DIFFERENT_REPL_EPOCHS() { return (int)8593L; }

    static final int ERROR_DS_DRS_EXTENSIONS_CHANGED() { return (int)8594L; }

    static final int ERROR_DS_REPLICA_SET_CHANGE_NOT_ALLOWED_ON_DISABLED_CR() { return (int)8595L; }

    static final int ERROR_DS_NO_MSDS_INTID() { return (int)8596L; }

    static final int ERROR_DS_DUP_MSDS_INTID() { return (int)8597L; }

    static final int ERROR_DS_EXISTS_IN_RDNATTID() { return (int)8598L; }

    static final int ERROR_DS_AUTHORIZATION_FAILED() { return (int)8599L; }

    static final int ERROR_DS_INVALID_SCRIPT() { return (int)8600L; }

    static final int ERROR_DS_REMOTE_CROSSREF_OP_FAILED() { return (int)8601L; }

    static final int ERROR_DS_CROSS_REF_BUSY() { return (int)8602L; }

    static final int ERROR_DS_CANT_DERIVE_SPN_FOR_DELETED_DOMAIN() { return (int)8603L; }

    static final int ERROR_DS_CANT_DEMOTE_WITH_WRITEABLE_NC() { return (int)8604L; }

    static final int ERROR_DS_DUPLICATE_ID_FOUND() { return (int)8605L; }

    static final int ERROR_DS_INSUFFICIENT_ATTR_TO_CREATE_OBJECT() { return (int)8606L; }

    static final int ERROR_DS_GROUP_CONVERSION_ERROR() { return (int)8607L; }

    static final int ERROR_DS_CANT_MOVE_APP_BASIC_GROUP() { return (int)8608L; }

    static final int ERROR_DS_CANT_MOVE_APP_QUERY_GROUP() { return (int)8609L; }

    static final int ERROR_DS_ROLE_NOT_VERIFIED() { return (int)8610L; }

    static final int ERROR_DS_WKO_CONTAINER_CANNOT_BE_SPECIAL() { return (int)8611L; }

    static final int ERROR_DS_DOMAIN_RENAME_IN_PROGRESS() { return (int)8612L; }

    static final int ERROR_DS_EXISTING_AD_CHILD_NC() { return (int)8613L; }

    static final int ERROR_DS_REPL_LIFETIME_EXCEEDED() { return (int)8614L; }

    static final int ERROR_DS_DISALLOWED_IN_SYSTEM_CONTAINER() { return (int)8615L; }

    static final int ERROR_DS_LDAP_SEND_QUEUE_FULL() { return (int)8616L; }

    static final int ERROR_DS_DRA_OUT_SCHEDULE_WINDOW() { return (int)8617L; }

    static final int ERROR_DS_POLICY_NOT_KNOWN() { return (int)8618L; }

    static final int ERROR_NO_SITE_SETTINGS_OBJECT() { return (int)8619L; }

    static final int ERROR_NO_SECRETS() { return (int)8620L; }

    static final int ERROR_NO_WRITABLE_DC_FOUND() { return (int)8621L; }

    static final int ERROR_DS_NO_SERVER_OBJECT() { return (int)8622L; }

    static final int ERROR_DS_NO_NTDSA_OBJECT() { return (int)8623L; }

    static final int ERROR_DS_NON_ASQ_SEARCH() { return (int)8624L; }

    static final int ERROR_DS_AUDIT_FAILURE() { return (int)8625L; }

    static final int ERROR_DS_INVALID_SEARCH_FLAG_SUBTREE() { return (int)8626L; }

    static final int ERROR_DS_INVALID_SEARCH_FLAG_TUPLE() { return (int)8627L; }

    static final int ERROR_DS_HIERARCHY_TABLE_TOO_DEEP() { return (int)8628L; }

    static final int ERROR_DS_DRA_CORRUPT_UTD_VECTOR() { return (int)8629L; }

    static final int ERROR_DS_DRA_SECRETS_DENIED() { return (int)8630L; }

    static final int ERROR_DS_RESERVED_MAPI_ID() { return (int)8631L; }

    static final int ERROR_DS_MAPI_ID_NOT_AVAILABLE() { return (int)8632L; }

    static final int ERROR_DS_DRA_MISSING_KRBTGT_SECRET() { return (int)8633L; }

    static final int ERROR_DS_DOMAIN_NAME_EXISTS_IN_FOREST() { return (int)8634L; }

    static final int ERROR_DS_FLAT_NAME_EXISTS_IN_FOREST() { return (int)8635L; }

    static final int ERROR_INVALID_USER_PRINCIPAL_NAME() { return (int)8636L; }

    static final int ERROR_DS_OID_MAPPED_GROUP_CANT_HAVE_MEMBERS() { return (int)8637L; }

    static final int ERROR_DS_OID_NOT_FOUND() { return (int)8638L; }

    static final int ERROR_DS_DRA_RECYCLED_TARGET() { return (int)8639L; }

    static final int ERROR_DS_DISALLOWED_NC_REDIRECT() { return (int)8640L; }

    static final int ERROR_DS_HIGH_ADLDS_FFL() { return (int)8641L; }

    static final int ERROR_DS_HIGH_DSA_VERSION() { return (int)8642L; }

    static final int ERROR_DS_LOW_ADLDS_FFL() { return (int)8643L; }

    static final int ERROR_DOMAIN_SID_SAME_AS_LOCAL_WORKSTATION() { return (int)8644L; }

    static final int ERROR_DS_UNDELETE_SAM_VALIDATION_FAILED() { return (int)8645L; }

    static final int ERROR_INCORRECT_ACCOUNT_TYPE() { return (int)8646L; }

    static final int ERROR_DS_SPN_VALUE_NOT_UNIQUE_IN_FOREST() { return (int)8647L; }

    static final int ERROR_DS_UPN_VALUE_NOT_UNIQUE_IN_FOREST() { return (int)8648L; }

    static final int ERROR_DS_MISSING_FOREST_TRUST() { return (int)8649L; }

    static final int ERROR_DS_VALUE_KEY_NOT_UNIQUE() { return (int)8650L; }

    static final int DNS_ERROR_RCODE_NO_ERROR() { return (int)0L; }

    static final int DNS_ERROR_RCODE_FORMAT_ERROR() { return (int)9001L; }

    static final int DNS_ERROR_RCODE_SERVER_FAILURE() { return (int)9002L; }

    static final int DNS_ERROR_RCODE_NAME_ERROR() { return (int)9003L; }

    static final int DNS_ERROR_RCODE_NOT_IMPLEMENTED() { return (int)9004L; }

    static final int DNS_ERROR_RCODE_REFUSED() { return (int)9005L; }

    static final int DNS_ERROR_RCODE_YXDOMAIN() { return (int)9006L; }

    static final int DNS_ERROR_RCODE_YXRRSET() { return (int)9007L; }

    static final int DNS_ERROR_RCODE_NXRRSET() { return (int)9008L; }

    static final int DNS_ERROR_RCODE_NOTAUTH() { return (int)9009L; }

    static final int DNS_ERROR_RCODE_NOTZONE() { return (int)9010L; }

    static final int DNS_ERROR_RCODE_BADSIG() { return (int)9016L; }

    static final int DNS_ERROR_RCODE_BADKEY() { return (int)9017L; }

    static final int DNS_ERROR_RCODE_BADTIME() { return (int)9018L; }

    static final int DNS_ERROR_RCODE_LAST() { return (int)9018L; }

    static final int DNS_ERROR_KEYMASTER_REQUIRED() { return (int)9101L; }

    static final int DNS_ERROR_NOT_ALLOWED_ON_SIGNED_ZONE() { return (int)9102L; }

    static final int DNS_ERROR_NSEC3_INCOMPATIBLE_WITH_RSA_SHA1() { return (int)9103L; }

    static final int DNS_ERROR_NOT_ENOUGH_SIGNING_KEY_DESCRIPTORS() { return (int)9104L; }

    static final int DNS_ERROR_UNSUPPORTED_ALGORITHM() { return (int)9105L; }

    static final int DNS_ERROR_INVALID_KEY_SIZE() { return (int)9106L; }

    static final int DNS_ERROR_SIGNING_KEY_NOT_ACCESSIBLE() { return (int)9107L; }

    static final int DNS_ERROR_KSP_DOES_NOT_SUPPORT_PROTECTION() { return (int)9108L; }

    static final int DNS_ERROR_UNEXPECTED_DATA_PROTECTION_ERROR() { return (int)9109L; }

    static final int DNS_ERROR_UNEXPECTED_CNG_ERROR() { return (int)9110L; }

    static final int DNS_ERROR_UNKNOWN_SIGNING_PARAMETER_VERSION() { return (int)9111L; }

    static final int DNS_ERROR_KSP_NOT_ACCESSIBLE() { return (int)9112L; }

    static final int DNS_ERROR_TOO_MANY_SKDS() { return (int)9113L; }

    static final int DNS_ERROR_INVALID_ROLLOVER_PERIOD() { return (int)9114L; }

    static final int DNS_ERROR_INVALID_INITIAL_ROLLOVER_OFFSET() { return (int)9115L; }

    static final int DNS_ERROR_ROLLOVER_IN_PROGRESS() { return (int)9116L; }

    static final int DNS_ERROR_STANDBY_KEY_NOT_PRESENT() { return (int)9117L; }

    static final int DNS_ERROR_NOT_ALLOWED_ON_ZSK() { return (int)9118L; }

    static final int DNS_ERROR_NOT_ALLOWED_ON_ACTIVE_SKD() { return (int)9119L; }

    static final int DNS_ERROR_ROLLOVER_ALREADY_QUEUED() { return (int)9120L; }

    static final int DNS_ERROR_NOT_ALLOWED_ON_UNSIGNED_ZONE() { return (int)9121L; }

    static final int DNS_ERROR_BAD_KEYMASTER() { return (int)9122L; }

    static final int DNS_ERROR_INVALID_SIGNATURE_VALIDITY_PERIOD() { return (int)9123L; }

    static final int DNS_ERROR_INVALID_NSEC3_ITERATION_COUNT() { return (int)9124L; }

    static final int DNS_ERROR_DNSSEC_IS_DISABLED() { return (int)9125L; }

    static final int DNS_ERROR_INVALID_XML() { return (int)9126L; }

    static final int DNS_ERROR_NO_VALID_TRUST_ANCHORS() { return (int)9127L; }

    static final int DNS_ERROR_ROLLOVER_NOT_POKEABLE() { return (int)9128L; }

    static final int DNS_ERROR_NSEC3_NAME_COLLISION() { return (int)9129L; }

    static final int DNS_ERROR_NSEC_INCOMPATIBLE_WITH_NSEC3_RSA_SHA1() { return (int)9130L; }

    static final int DNS_INFO_NO_RECORDS() { return (int)9501L; }

    static final int DNS_ERROR_BAD_PACKET() { return (int)9502L; }

    static final int DNS_ERROR_NO_PACKET() { return (int)9503L; }

    static final int DNS_ERROR_RCODE() { return (int)9504L; }

    static final int DNS_ERROR_UNSECURE_PACKET() { return (int)9505L; }

    static final int DNS_STATUS_PACKET_UNSECURE() { return (int)9505L; }

    static final int DNS_REQUEST_PENDING() { return (int)9506L; }

    static final int DNS_ERROR_NO_MEMORY() { return (int)14L; }

    static final int DNS_ERROR_INVALID_NAME() { return (int)123L; }

    static final int DNS_ERROR_INVALID_DATA() { return (int)13L; }

    static final int DNS_ERROR_INVALID_TYPE() { return (int)9551L; }

    static final int DNS_ERROR_INVALID_IP_ADDRESS() { return (int)9552L; }

    static final int DNS_ERROR_INVALID_PROPERTY() { return (int)9553L; }

    static final int DNS_ERROR_TRY_AGAIN_LATER() { return (int)9554L; }

    static final int DNS_ERROR_NOT_UNIQUE() { return (int)9555L; }

    static final int DNS_ERROR_NON_RFC_NAME() { return (int)9556L; }

    static final int DNS_STATUS_FQDN() { return (int)9557L; }

    static final int DNS_STATUS_DOTTED_NAME() { return (int)9558L; }

    static final int DNS_STATUS_SINGLE_PART_NAME() { return (int)9559L; }

    static final int DNS_ERROR_INVALID_NAME_CHAR() { return (int)9560L; }

    static final int DNS_ERROR_NUMERIC_NAME() { return (int)9561L; }

    static final int DNS_ERROR_NOT_ALLOWED_ON_ROOT_SERVER() { return (int)9562L; }

    static final int DNS_ERROR_NOT_ALLOWED_UNDER_DELEGATION() { return (int)9563L; }

    static final int DNS_ERROR_CANNOT_FIND_ROOT_HINTS() { return (int)9564L; }

    static final int DNS_ERROR_INCONSISTENT_ROOT_HINTS() { return (int)9565L; }

    static final int DNS_ERROR_DWORD_VALUE_TOO_SMALL() { return (int)9566L; }

    static final int DNS_ERROR_DWORD_VALUE_TOO_LARGE() { return (int)9567L; }

    static final int DNS_ERROR_BACKGROUND_LOADING() { return (int)9568L; }

    static final int DNS_ERROR_NOT_ALLOWED_ON_RODC() { return (int)9569L; }

    static final int DNS_ERROR_NOT_ALLOWED_UNDER_DNAME() { return (int)9570L; }

    static final int DNS_ERROR_DELEGATION_REQUIRED() { return (int)9571L; }

    static final int DNS_ERROR_INVALID_POLICY_TABLE() { return (int)9572L; }

    static final int DNS_ERROR_ADDRESS_REQUIRED() { return (int)9573L; }

    static final int DNS_ERROR_ZONE_DOES_NOT_EXIST() { return (int)9601L; }

    static final int DNS_ERROR_NO_ZONE_INFO() { return (int)9602L; }

    static final int DNS_ERROR_INVALID_ZONE_OPERATION() { return (int)9603L; }

    static final int DNS_ERROR_ZONE_CONFIGURATION_ERROR() { return (int)9604L; }

    static final int DNS_ERROR_ZONE_HAS_NO_SOA_RECORD() { return (int)9605L; }

    static final int DNS_ERROR_ZONE_HAS_NO_NS_RECORDS() { return (int)9606L; }

    static final int DNS_ERROR_ZONE_LOCKED() { return (int)9607L; }

    static final int DNS_ERROR_ZONE_CREATION_FAILED() { return (int)9608L; }

    static final int DNS_ERROR_ZONE_ALREADY_EXISTS() { return (int)9609L; }

    static final int DNS_ERROR_AUTOZONE_ALREADY_EXISTS() { return (int)9610L; }

    static final int DNS_ERROR_INVALID_ZONE_TYPE() { return (int)9611L; }

    static final int DNS_ERROR_SECONDARY_REQUIRES_MASTER_IP() { return (int)9612L; }

    static final int DNS_ERROR_ZONE_NOT_SECONDARY() { return (int)9613L; }

    static final int DNS_ERROR_NEED_SECONDARY_ADDRESSES() { return (int)9614L; }

    static final int DNS_ERROR_WINS_INIT_FAILED() { return (int)9615L; }

    static final int DNS_ERROR_NEED_WINS_SERVERS() { return (int)9616L; }

    static final int DNS_ERROR_NBSTAT_INIT_FAILED() { return (int)9617L; }

    static final int DNS_ERROR_SOA_DELETE_INVALID() { return (int)9618L; }

    static final int DNS_ERROR_FORWARDER_ALREADY_EXISTS() { return (int)9619L; }

    static final int DNS_ERROR_ZONE_REQUIRES_MASTER_IP() { return (int)9620L; }

    static final int DNS_ERROR_ZONE_IS_SHUTDOWN() { return (int)9621L; }

    static final int DNS_ERROR_ZONE_LOCKED_FOR_SIGNING() { return (int)9622L; }

    static final int DNS_ERROR_PRIMARY_REQUIRES_DATAFILE() { return (int)9651L; }

    static final int DNS_ERROR_INVALID_DATAFILE_NAME() { return (int)9652L; }

    static final int DNS_ERROR_DATAFILE_OPEN_FAILURE() { return (int)9653L; }

    static final int DNS_ERROR_FILE_WRITEBACK_FAILED() { return (int)9654L; }

    static final int DNS_ERROR_DATAFILE_PARSING() { return (int)9655L; }

    static final int DNS_ERROR_RECORD_DOES_NOT_EXIST() { return (int)9701L; }

    static final int DNS_ERROR_RECORD_FORMAT() { return (int)9702L; }

    static final int DNS_ERROR_NODE_CREATION_FAILED() { return (int)9703L; }

    static final int DNS_ERROR_UNKNOWN_RECORD_TYPE() { return (int)9704L; }

    static final int DNS_ERROR_RECORD_TIMED_OUT() { return (int)9705L; }

    static final int DNS_ERROR_NAME_NOT_IN_ZONE() { return (int)9706L; }

    static final int DNS_ERROR_CNAME_LOOP() { return (int)9707L; }

    static final int DNS_ERROR_NODE_IS_CNAME() { return (int)9708L; }

    static final int DNS_ERROR_CNAME_COLLISION() { return (int)9709L; }

    static final int DNS_ERROR_RECORD_ONLY_AT_ZONE_ROOT() { return (int)9710L; }

    static final int DNS_ERROR_RECORD_ALREADY_EXISTS() { return (int)9711L; }

    static final int DNS_ERROR_SECONDARY_DATA() { return (int)9712L; }

    static final int DNS_ERROR_NO_CREATE_CACHE_DATA() { return (int)9713L; }

    static final int DNS_ERROR_NAME_DOES_NOT_EXIST() { return (int)9714L; }

    static final int DNS_WARNING_PTR_CREATE_FAILED() { return (int)9715L; }

    static final int DNS_WARNING_DOMAIN_UNDELETED() { return (int)9716L; }

    static final int DNS_ERROR_DS_UNAVAILABLE() { return (int)9717L; }

    static final int DNS_ERROR_DS_ZONE_ALREADY_EXISTS() { return (int)9718L; }

    static final int DNS_ERROR_NO_BOOTFILE_IF_DS_ZONE() { return (int)9719L; }

    static final int DNS_ERROR_NODE_IS_DNAME() { return (int)9720L; }

    static final int DNS_ERROR_DNAME_COLLISION() { return (int)9721L; }

    static final int DNS_ERROR_ALIAS_LOOP() { return (int)9722L; }

    static final int DNS_INFO_AXFR_COMPLETE() { return (int)9751L; }

    static final int DNS_ERROR_AXFR() { return (int)9752L; }

    static final int DNS_INFO_ADDED_LOCAL_WINS() { return (int)9753L; }

    static final int DNS_STATUS_CONTINUE_NEEDED() { return (int)9801L; }

    static final int DNS_ERROR_NO_TCPIP() { return (int)9851L; }

    static final int DNS_ERROR_NO_DNS_SERVERS() { return (int)9852L; }

    static final int DNS_ERROR_DP_DOES_NOT_EXIST() { return (int)9901L; }

    static final int DNS_ERROR_DP_ALREADY_EXISTS() { return (int)9902L; }

    static final int DNS_ERROR_DP_NOT_ENLISTED() { return (int)9903L; }

    static final int DNS_ERROR_DP_ALREADY_ENLISTED() { return (int)9904L; }

    static final int DNS_ERROR_DP_NOT_AVAILABLE() { return (int)9905L; }

    static final int DNS_ERROR_DP_FSMO_ERROR() { return (int)9906L; }

    static final int DNS_ERROR_RRL_NOT_ENABLED() { return (int)9911L; }

    static final int DNS_ERROR_RRL_INVALID_WINDOW_SIZE() { return (int)9912L; }

    static final int DNS_ERROR_RRL_INVALID_IPV4_PREFIX() { return (int)9913L; }

    static final int DNS_ERROR_RRL_INVALID_IPV6_PREFIX() { return (int)9914L; }

    static final int DNS_ERROR_RRL_INVALID_TC_RATE() { return (int)9915L; }

    static final int DNS_ERROR_RRL_INVALID_LEAK_RATE() { return (int)9916L; }

    static final int DNS_ERROR_RRL_LEAK_RATE_LESSTHAN_TC_RATE() { return (int)9917L; }

    static final int DNS_ERROR_VIRTUALIZATION_INSTANCE_ALREADY_EXISTS() { return (int)9921L; }

    static final int DNS_ERROR_VIRTUALIZATION_INSTANCE_DOES_NOT_EXIST() { return (int)9922L; }

    static final int DNS_ERROR_VIRTUALIZATION_TREE_LOCKED() { return (int)9923L; }

    static final int DNS_ERROR_INVAILD_VIRTUALIZATION_INSTANCE_NAME() { return (int)9924L; }

    static final int DNS_ERROR_DEFAULT_VIRTUALIZATION_INSTANCE() { return (int)9925L; }

    static final int DNS_ERROR_ZONESCOPE_ALREADY_EXISTS() { return (int)9951L; }

    static final int DNS_ERROR_ZONESCOPE_DOES_NOT_EXIST() { return (int)9952L; }

    static final int DNS_ERROR_DEFAULT_ZONESCOPE() { return (int)9953L; }

    static final int DNS_ERROR_INVALID_ZONESCOPE_NAME() { return (int)9954L; }

    static final int DNS_ERROR_NOT_ALLOWED_WITH_ZONESCOPES() { return (int)9955L; }

    static final int DNS_ERROR_LOAD_ZONESCOPE_FAILED() { return (int)9956L; }

    static final int DNS_ERROR_ZONESCOPE_FILE_WRITEBACK_FAILED() { return (int)9957L; }

    static final int DNS_ERROR_INVALID_SCOPE_NAME() { return (int)9958L; }

    static final int DNS_ERROR_SCOPE_DOES_NOT_EXIST() { return (int)9959L; }

    static final int DNS_ERROR_DEFAULT_SCOPE() { return (int)9960L; }

    static final int DNS_ERROR_INVALID_SCOPE_OPERATION() { return (int)9961L; }

    static final int DNS_ERROR_SCOPE_LOCKED() { return (int)9962L; }

    static final int DNS_ERROR_SCOPE_ALREADY_EXISTS() { return (int)9963L; }

    static final int DNS_ERROR_POLICY_ALREADY_EXISTS() { return (int)9971L; }

    static final int DNS_ERROR_POLICY_DOES_NOT_EXIST() { return (int)9972L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA() { return (int)9973L; }

    static final int DNS_ERROR_POLICY_INVALID_SETTINGS() { return (int)9974L; }

    static final int DNS_ERROR_CLIENT_SUBNET_IS_ACCESSED() { return (int)9975L; }

    static final int DNS_ERROR_CLIENT_SUBNET_DOES_NOT_EXIST() { return (int)9976L; }

    static final int DNS_ERROR_CLIENT_SUBNET_ALREADY_EXISTS() { return (int)9977L; }

    static final int DNS_ERROR_SUBNET_DOES_NOT_EXIST() { return (int)9978L; }

    static final int DNS_ERROR_SUBNET_ALREADY_EXISTS() { return (int)9979L; }

    static final int DNS_ERROR_POLICY_LOCKED() { return (int)9980L; }

    static final int DNS_ERROR_POLICY_INVALID_WEIGHT() { return (int)9981L; }

    static final int DNS_ERROR_POLICY_INVALID_NAME() { return (int)9982L; }

    static final int DNS_ERROR_POLICY_MISSING_CRITERIA() { return (int)9983L; }

    static final int DNS_ERROR_INVALID_CLIENT_SUBNET_NAME() { return (int)9984L; }

    static final int DNS_ERROR_POLICY_PROCESSING_ORDER_INVALID() { return (int)9985L; }

    static final int DNS_ERROR_POLICY_SCOPE_MISSING() { return (int)9986L; }

    static final int DNS_ERROR_POLICY_SCOPE_NOT_ALLOWED() { return (int)9987L; }

    static final int DNS_ERROR_SERVERSCOPE_IS_REFERENCED() { return (int)9988L; }

    static final int DNS_ERROR_ZONESCOPE_IS_REFERENCED() { return (int)9989L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_CLIENT_SUBNET() { return (int)9990L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_TRANSPORT_PROTOCOL() { return (int)9991L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_NETWORK_PROTOCOL() { return (int)9992L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_INTERFACE() { return (int)9993L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_FQDN() { return (int)9994L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_QUERY_TYPE() { return (int)9995L; }

    static final int DNS_ERROR_POLICY_INVALID_CRITERIA_TIME_OF_DAY() { return (int)9996L; }

    static final int WSAEINTR() { return (int)10004L; }

    static final int WSAEBADF() { return (int)10009L; }

}

