// Generated by jextract

package com.github.tornaia.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class cfapi_h$constants$1 extends cfapi_h$constants$0 {

    /* package-private */ cfapi_h$constants$1() {}
    static final int PROCESSOR_INTEL_386() { return (int)386L; }

    static final int PROCESSOR_INTEL_486() { return (int)486L; }

    static final int PROCESSOR_INTEL_PENTIUM() { return (int)586L; }

    static final int PROCESSOR_INTEL_IA64() { return (int)2200L; }

    static final int PROCESSOR_AMD_X8664() { return (int)8664L; }

    static final int PROCESSOR_MIPS_R4000() { return (int)4000L; }

    static final int PROCESSOR_ALPHA_21064() { return (int)21064L; }

    static final int PROCESSOR_PPC_601() { return (int)601L; }

    static final int PROCESSOR_PPC_603() { return (int)603L; }

    static final int PROCESSOR_PPC_604() { return (int)604L; }

    static final int PROCESSOR_PPC_620() { return (int)620L; }

    static final int PROCESSOR_HITACHI_SH3() { return (int)10003L; }

    static final int PROCESSOR_HITACHI_SH3E() { return (int)10004L; }

    static final int PROCESSOR_HITACHI_SH4() { return (int)10005L; }

    static final int PROCESSOR_MOTOROLA_821() { return (int)821L; }

    static final int PROCESSOR_SHx_SH3() { return (int)103L; }

    static final int PROCESSOR_SHx_SH4() { return (int)104L; }

    static final int PROCESSOR_STRONGARM() { return (int)2577L; }

    static final int PROCESSOR_ARM720() { return (int)1824L; }

    static final int PROCESSOR_ARM820() { return (int)2080L; }

    static final int PROCESSOR_ARM920() { return (int)2336L; }

    static final int PROCESSOR_ARM_7TDMI() { return (int)70001L; }

    static final int PROCESSOR_OPTIL() { return (int)18767L; }

    static final int PROCESSOR_ARCHITECTURE_INTEL() { return (int)0L; }

    static final int PROCESSOR_ARCHITECTURE_MIPS() { return (int)1L; }

    static final int PROCESSOR_ARCHITECTURE_ALPHA() { return (int)2L; }

    static final int PROCESSOR_ARCHITECTURE_PPC() { return (int)3L; }

    static final int PROCESSOR_ARCHITECTURE_SHX() { return (int)4L; }

    static final int PROCESSOR_ARCHITECTURE_ARM() { return (int)5L; }

    static final int PROCESSOR_ARCHITECTURE_IA64() { return (int)6L; }

    static final int PROCESSOR_ARCHITECTURE_ALPHA64() { return (int)7L; }

    static final int PROCESSOR_ARCHITECTURE_MSIL() { return (int)8L; }

    static final int PROCESSOR_ARCHITECTURE_AMD64() { return (int)9L; }

    static final int PROCESSOR_ARCHITECTURE_IA32_ON_WIN64() { return (int)10L; }

    static final int PROCESSOR_ARCHITECTURE_NEUTRAL() { return (int)11L; }

    static final int PROCESSOR_ARCHITECTURE_ARM64() { return (int)12L; }

    static final int PROCESSOR_ARCHITECTURE_ARM32_ON_WIN64() { return (int)13L; }

    static final int PROCESSOR_ARCHITECTURE_IA32_ON_ARM64() { return (int)14L; }

    static final int PROCESSOR_ARCHITECTURE_UNKNOWN() { return (int)65535L; }

    static final int PF_FLOATING_POINT_PRECISION_ERRATA() { return (int)0L; }

    static final int PF_FLOATING_POINT_EMULATED() { return (int)1L; }

    static final int PF_COMPARE_EXCHANGE_DOUBLE() { return (int)2L; }

    static final int PF_MMX_INSTRUCTIONS_AVAILABLE() { return (int)3L; }

    static final int PF_PPC_MOVEMEM_64BIT_OK() { return (int)4L; }

    static final int PF_ALPHA_BYTE_INSTRUCTIONS() { return (int)5L; }

    static final int PF_XMMI_INSTRUCTIONS_AVAILABLE() { return (int)6L; }

    static final int PF_3DNOW_INSTRUCTIONS_AVAILABLE() { return (int)7L; }

    static final int PF_RDTSC_INSTRUCTION_AVAILABLE() { return (int)8L; }

    static final int PF_PAE_ENABLED() { return (int)9L; }

    static final int PF_XMMI64_INSTRUCTIONS_AVAILABLE() { return (int)10L; }

    static final int PF_SSE_DAZ_MODE_AVAILABLE() { return (int)11L; }

    static final int PF_NX_ENABLED() { return (int)12L; }

    static final int PF_SSE3_INSTRUCTIONS_AVAILABLE() { return (int)13L; }

    static final int PF_COMPARE_EXCHANGE128() { return (int)14L; }

    static final int PF_COMPARE64_EXCHANGE128() { return (int)15L; }

    static final int PF_CHANNELS_ENABLED() { return (int)16L; }

    static final int PF_XSAVE_ENABLED() { return (int)17L; }

    static final int PF_ARM_VFP_32_REGISTERS_AVAILABLE() { return (int)18L; }

    static final int PF_ARM_NEON_INSTRUCTIONS_AVAILABLE() { return (int)19L; }

    static final int PF_SECOND_LEVEL_ADDRESS_TRANSLATION() { return (int)20L; }

    static final int PF_VIRT_FIRMWARE_ENABLED() { return (int)21L; }

    static final int PF_RDWRFSGSBASE_AVAILABLE() { return (int)22L; }

    static final int PF_FASTFAIL_AVAILABLE() { return (int)23L; }

    static final int PF_ARM_DIVIDE_INSTRUCTION_AVAILABLE() { return (int)24L; }

    static final int PF_ARM_64BIT_LOADSTORE_ATOMIC() { return (int)25L; }

    static final int PF_ARM_EXTERNAL_CACHE_AVAILABLE() { return (int)26L; }

    static final int PF_ARM_FMAC_INSTRUCTIONS_AVAILABLE() { return (int)27L; }

    static final int PF_RDRAND_INSTRUCTION_AVAILABLE() { return (int)28L; }

    static final int PF_ARM_V8_INSTRUCTIONS_AVAILABLE() { return (int)29L; }

    static final int PF_ARM_V8_CRYPTO_INSTRUCTIONS_AVAILABLE() { return (int)30L; }

    static final int PF_ARM_V8_CRC32_INSTRUCTIONS_AVAILABLE() { return (int)31L; }

    static final int PF_RDTSCP_INSTRUCTION_AVAILABLE() { return (int)32L; }

    static final int PF_RDPID_INSTRUCTION_AVAILABLE() { return (int)33L; }

    static final int PF_ARM_V81_ATOMIC_INSTRUCTIONS_AVAILABLE() { return (int)34L; }

    static final int PF_MONITORX_INSTRUCTION_AVAILABLE() { return (int)35L; }

    static final int PF_SSSE3_INSTRUCTIONS_AVAILABLE() { return (int)36L; }

    static final int PF_SSE4_1_INSTRUCTIONS_AVAILABLE() { return (int)37L; }

    static final int PF_SSE4_2_INSTRUCTIONS_AVAILABLE() { return (int)38L; }

    static final int PF_AVX_INSTRUCTIONS_AVAILABLE() { return (int)39L; }

    static final int PF_AVX2_INSTRUCTIONS_AVAILABLE() { return (int)40L; }

    static final int PF_AVX512F_INSTRUCTIONS_AVAILABLE() { return (int)41L; }

    static final int SECTION_QUERY() { return (int)1L; }

    static final int SECTION_MAP_WRITE() { return (int)2L; }

    static final int SECTION_MAP_READ() { return (int)4L; }

    static final int SECTION_MAP_EXECUTE() { return (int)8L; }

    static final int SECTION_EXTEND_SIZE() { return (int)16L; }

    static final int SECTION_MAP_EXECUTE_EXPLICIT() { return (int)32L; }

    static final int SESSION_QUERY_ACCESS() { return (int)1L; }

    static final int SESSION_MODIFY_ACCESS() { return (int)2L; }

    static final int PAGE_NOACCESS() { return (int)1L; }

    static final int PAGE_READONLY() { return (int)2L; }

    static final int PAGE_READWRITE() { return (int)4L; }

    static final int PAGE_WRITECOPY() { return (int)8L; }

    static final int PAGE_EXECUTE() { return (int)16L; }

    static final int PAGE_EXECUTE_READ() { return (int)32L; }

    static final int PAGE_EXECUTE_READWRITE() { return (int)64L; }

    static final int PAGE_EXECUTE_WRITECOPY() { return (int)128L; }

    static final int PAGE_GUARD() { return (int)256L; }

    static final int PAGE_NOCACHE() { return (int)512L; }

    static final int PAGE_WRITECOMBINE() { return (int)1024L; }

    static final int PAGE_GRAPHICS_NOACCESS() { return (int)2048L; }

    static final int PAGE_GRAPHICS_READONLY() { return (int)4096L; }

    static final int PAGE_GRAPHICS_READWRITE() { return (int)8192L; }

    static final int PAGE_GRAPHICS_EXECUTE() { return (int)16384L; }

    static final int PAGE_GRAPHICS_EXECUTE_READ() { return (int)32768L; }

    static final int PAGE_GRAPHICS_EXECUTE_READWRITE() { return (int)65536L; }

    static final int PAGE_GRAPHICS_COHERENT() { return (int)131072L; }

    static final int PAGE_GRAPHICS_NOCACHE() { return (int)262144L; }

    static final int PAGE_TARGETS_NO_UPDATE() { return (int)1073741824L; }

    static final int PAGE_TARGETS_INVALID() { return (int)1073741824L; }

    static final int PAGE_ENCLAVE_UNVALIDATED() { return (int)536870912L; }

    static final int PAGE_ENCLAVE_MASK() { return (int)268435456L; }

    static final int MEM_COMMIT() { return (int)4096L; }

    static final int MEM_RESERVE() { return (int)8192L; }

    static final int MEM_REPLACE_PLACEHOLDER() { return (int)16384L; }

    static final int MEM_RESERVE_PLACEHOLDER() { return (int)262144L; }

    static final int MEM_RESET() { return (int)524288L; }

    static final int MEM_TOP_DOWN() { return (int)1048576L; }

    static final int MEM_WRITE_WATCH() { return (int)2097152L; }

    static final int MEM_PHYSICAL() { return (int)4194304L; }

    static final int MEM_ROTATE() { return (int)8388608L; }

    static final int MEM_DIFFERENT_IMAGE_BASE_OK() { return (int)8388608L; }

    static final int MEM_RESET_UNDO() { return (int)16777216L; }

    static final int MEM_LARGE_PAGES() { return (int)536870912L; }

    static final int MEM_UNMAP_WITH_TRANSIENT_BOOST() { return (int)1L; }

    static final int MEM_COALESCE_PLACEHOLDERS() { return (int)1L; }

    static final int MEM_PRESERVE_PLACEHOLDER() { return (int)2L; }

    static final int MEM_DECOMMIT() { return (int)16384L; }

    static final int MEM_RELEASE() { return (int)32768L; }

    static final int MEM_FREE() { return (int)65536L; }

    static final int MEM_EXTENDED_PARAMETER_GRAPHICS() { return (int)1L; }

    static final int MEM_EXTENDED_PARAMETER_NONPAGED() { return (int)2L; }

    static final int MEM_EXTENDED_PARAMETER_ZERO_PAGES_OPTIONAL() { return (int)4L; }

    static final int MEM_EXTENDED_PARAMETER_NONPAGED_LARGE() { return (int)8L; }

    static final int MEM_EXTENDED_PARAMETER_NONPAGED_HUGE() { return (int)16L; }

    static final int MEM_EXTENDED_PARAMETER_SOFT_FAULT_PAGES() { return (int)32L; }

    static final int MEM_EXTENDED_PARAMETER_TYPE_BITS() { return (int)8L; }

    static final int SEC_PARTITION_OWNER_HANDLE() { return (int)262144L; }

    static final int SEC_64K_PAGES() { return (int)524288L; }

    static final int SEC_FILE() { return (int)8388608L; }

    static final int SEC_IMAGE() { return (int)16777216L; }

    static final int SEC_PROTECTED_IMAGE() { return (int)33554432L; }

    static final int SEC_RESERVE() { return (int)67108864L; }

    static final int SEC_COMMIT() { return (int)134217728L; }

    static final int SEC_NOCACHE() { return (int)268435456L; }

    static final int SEC_WRITECOMBINE() { return (int)1073741824L; }

    static final int MEM_PRIVATE() { return (int)131072L; }

    static final int MEM_MAPPED() { return (int)262144L; }

    static final int MEM_IMAGE() { return (int)16777216L; }

    static final int WRITE_WATCH_FLAG_RESET() { return (int)1L; }

    static final int ENCLAVE_TYPE_SGX() { return (int)1L; }

    static final int ENCLAVE_TYPE_SGX2() { return (int)2L; }

    static final int ENCLAVE_TYPE_VBS() { return (int)16L; }

    static final int ENCLAVE_VBS_FLAG_DEBUG() { return (int)1L; }

    static final int ENCLAVE_TYPE_VBS_BASIC() { return (int)17L; }

    static final int VBS_BASIC_PAGE_MEASURED_DATA() { return (int)1L; }

    static final int VBS_BASIC_PAGE_UNMEASURED_DATA() { return (int)2L; }

    static final int VBS_BASIC_PAGE_ZERO_FILL() { return (int)3L; }

    static final int VBS_BASIC_PAGE_THREAD_DESCRIPTOR() { return (int)4L; }

    static final int VBS_BASIC_PAGE_SYSTEM_CALL() { return (int)5L; }

    static final int FILE_SHARE_READ() { return (int)1L; }

    static final int FILE_SHARE_WRITE() { return (int)2L; }

    static final int FILE_SHARE_DELETE() { return (int)4L; }

    static final int FILE_ATTRIBUTE_READONLY() { return (int)1L; }

    static final int FILE_ATTRIBUTE_HIDDEN() { return (int)2L; }

    static final int FILE_ATTRIBUTE_SYSTEM() { return (int)4L; }

    static final int FILE_ATTRIBUTE_DIRECTORY() { return (int)16L; }

    static final int FILE_ATTRIBUTE_ARCHIVE() { return (int)32L; }

    static final int FILE_ATTRIBUTE_DEVICE() { return (int)64L; }

    static final int FILE_ATTRIBUTE_NORMAL() { return (int)128L; }

    static final int FILE_ATTRIBUTE_TEMPORARY() { return (int)256L; }

    static final int FILE_ATTRIBUTE_SPARSE_FILE() { return (int)512L; }

    static final int FILE_ATTRIBUTE_REPARSE_POINT() { return (int)1024L; }

    static final int FILE_ATTRIBUTE_COMPRESSED() { return (int)2048L; }

    static final int FILE_ATTRIBUTE_OFFLINE() { return (int)4096L; }

    static final int FILE_ATTRIBUTE_NOT_CONTENT_INDEXED() { return (int)8192L; }

    static final int FILE_ATTRIBUTE_ENCRYPTED() { return (int)16384L; }

    static final int FILE_ATTRIBUTE_INTEGRITY_STREAM() { return (int)32768L; }

    static final int FILE_ATTRIBUTE_VIRTUAL() { return (int)65536L; }

    static final int FILE_ATTRIBUTE_NO_SCRUB_DATA() { return (int)131072L; }

    static final int FILE_ATTRIBUTE_EA() { return (int)262144L; }

    static final int FILE_ATTRIBUTE_PINNED() { return (int)524288L; }

    static final int FILE_ATTRIBUTE_UNPINNED() { return (int)1048576L; }

    static final int FILE_ATTRIBUTE_RECALL_ON_OPEN() { return (int)262144L; }

    static final int FILE_ATTRIBUTE_RECALL_ON_DATA_ACCESS() { return (int)4194304L; }

    static final int TREE_CONNECT_ATTRIBUTE_PRIVACY() { return (int)16384L; }

    static final int TREE_CONNECT_ATTRIBUTE_INTEGRITY() { return (int)32768L; }

    static final int TREE_CONNECT_ATTRIBUTE_GLOBAL() { return (int)4L; }

    static final int TREE_CONNECT_ATTRIBUTE_PINNED() { return (int)2L; }

    static final int FILE_ATTRIBUTE_STRICTLY_SEQUENTIAL() { return (int)536870912L; }

    static final int FILE_NOTIFY_CHANGE_FILE_NAME() { return (int)1L; }

    static final int FILE_NOTIFY_CHANGE_DIR_NAME() { return (int)2L; }

    static final int FILE_NOTIFY_CHANGE_ATTRIBUTES() { return (int)4L; }

    static final int FILE_NOTIFY_CHANGE_SIZE() { return (int)8L; }

    static final int FILE_NOTIFY_CHANGE_LAST_WRITE() { return (int)16L; }

    static final int FILE_NOTIFY_CHANGE_LAST_ACCESS() { return (int)32L; }

    static final int FILE_NOTIFY_CHANGE_CREATION() { return (int)64L; }

    static final int FILE_NOTIFY_CHANGE_SECURITY() { return (int)256L; }

    static final int FILE_ACTION_ADDED() { return (int)1L; }

    static final int FILE_ACTION_REMOVED() { return (int)2L; }

    static final int FILE_ACTION_MODIFIED() { return (int)3L; }

    static final int FILE_ACTION_RENAMED_OLD_NAME() { return (int)4L; }

    static final int FILE_ACTION_RENAMED_NEW_NAME() { return (int)5L; }

    static final int FILE_CASE_SENSITIVE_SEARCH() { return (int)1L; }

    static final int FILE_CASE_PRESERVED_NAMES() { return (int)2L; }

    static final int FILE_UNICODE_ON_DISK() { return (int)4L; }

    static final int FILE_PERSISTENT_ACLS() { return (int)8L; }

    static final int FILE_FILE_COMPRESSION() { return (int)16L; }

    static final int FILE_VOLUME_QUOTAS() { return (int)32L; }

    static final int FILE_SUPPORTS_SPARSE_FILES() { return (int)64L; }

    static final int FILE_SUPPORTS_REPARSE_POINTS() { return (int)128L; }

    static final int FILE_SUPPORTS_REMOTE_STORAGE() { return (int)256L; }

    static final int FILE_RETURNS_CLEANUP_RESULT_INFO() { return (int)512L; }

    static final int FILE_SUPPORTS_POSIX_UNLINK_RENAME() { return (int)1024L; }

    static final int FILE_VOLUME_IS_COMPRESSED() { return (int)32768L; }

    static final int FILE_SUPPORTS_OBJECT_IDS() { return (int)65536L; }

    static final int FILE_SUPPORTS_ENCRYPTION() { return (int)131072L; }

    static final int FILE_NAMED_STREAMS() { return (int)262144L; }

    static final int FILE_READ_ONLY_VOLUME() { return (int)524288L; }

    static final int FILE_SEQUENTIAL_WRITE_ONCE() { return (int)1048576L; }

    static final int FILE_SUPPORTS_TRANSACTIONS() { return (int)2097152L; }

    static final int FILE_SUPPORTS_HARD_LINKS() { return (int)4194304L; }

    static final int FILE_SUPPORTS_EXTENDED_ATTRIBUTES() { return (int)8388608L; }

    static final int FILE_SUPPORTS_OPEN_BY_FILE_ID() { return (int)16777216L; }

    static final int FILE_SUPPORTS_USN_JOURNAL() { return (int)33554432L; }

    static final int FILE_SUPPORTS_INTEGRITY_STREAMS() { return (int)67108864L; }

    static final int FILE_SUPPORTS_BLOCK_REFCOUNTING() { return (int)134217728L; }

    static final int FILE_SUPPORTS_SPARSE_VDL() { return (int)268435456L; }

    static final int FILE_DAX_VOLUME() { return (int)536870912L; }

    static final int FILE_SUPPORTS_GHOSTING() { return (int)1073741824L; }

    static final int FILE_CS_FLAG_CASE_SENSITIVE_DIR() { return (int)1L; }

    static final int FLUSH_FLAGS_FILE_DATA_ONLY() { return (int)1L; }

    static final int FLUSH_FLAGS_NO_SYNC() { return (int)2L; }

    static final int FLUSH_FLAGS_FILE_DATA_SYNC_ONLY() { return (int)4L; }

    static final int SCRUB_DATA_INPUT_FLAG_RESUME() { return (int)1L; }

    static final int SCRUB_DATA_INPUT_FLAG_SKIP_IN_SYNC() { return (int)2L; }

    static final int SCRUB_DATA_INPUT_FLAG_SKIP_NON_INTEGRITY_DATA() { return (int)4L; }

    static final int SCRUB_DATA_INPUT_FLAG_IGNORE_REDUNDANCY() { return (int)8L; }

    static final int SCRUB_DATA_INPUT_FLAG_SKIP_DATA() { return (int)16L; }

    static final int SCRUB_DATA_INPUT_FLAG_SCRUB_BY_OBJECT_ID() { return (int)32L; }

    static final int SCRUB_DATA_INPUT_FLAG_OPLOCK_NOT_ACQUIRED() { return (int)64L; }

    static final int SCRUB_DATA_OUTPUT_FLAG_INCOMPLETE() { return (int)1L; }

    static final int SCRUB_DATA_OUTPUT_FLAG_NON_USER_DATA_RANGE() { return (int)65536L; }

    static final int SCRUB_DATA_OUTPUT_FLAG_PARITY_EXTENT_DATA_RETURNED() { return (int)131072L; }

    static final int SCRUB_DATA_OUTPUT_FLAG_RESUME_CONTEXT_LENGTH_SPECIFIED() { return (int)262144L; }

    static final int IO_COMPLETION_MODIFY_STATE() { return (int)2L; }

    static final int NETWORK_APP_INSTANCE_CSV_FLAGS_VALID_ONLY_IF_CSV_COORDINATOR() { return (int)1L; }

    static final int DUPLICATE_CLOSE_SOURCE() { return (int)1L; }

    static final int DUPLICATE_SAME_ACCESS() { return (int)2L; }

    static final int POWERBUTTON_ACTION_INDEX_NOTHING() { return (int)0L; }

    static final int POWERBUTTON_ACTION_INDEX_SLEEP() { return (int)1L; }

    static final int POWERBUTTON_ACTION_INDEX_HIBERNATE() { return (int)2L; }

    static final int POWERBUTTON_ACTION_INDEX_SHUTDOWN() { return (int)3L; }

    static final int POWERBUTTON_ACTION_INDEX_TURN_OFF_THE_DISPLAY() { return (int)4L; }

    static final int POWERBUTTON_ACTION_VALUE_NOTHING() { return (int)0L; }

    static final int POWERBUTTON_ACTION_VALUE_SLEEP() { return (int)2L; }

    static final int POWERBUTTON_ACTION_VALUE_HIBERNATE() { return (int)3L; }

    static final int POWERBUTTON_ACTION_VALUE_SHUTDOWN() { return (int)6L; }

    static final int POWERBUTTON_ACTION_VALUE_TURN_OFF_THE_DISPLAY() { return (int)8L; }

    static final int PERFSTATE_POLICY_CHANGE_IDEAL() { return (int)0L; }

    static final int PERFSTATE_POLICY_CHANGE_SINGLE() { return (int)1L; }

    static final int PERFSTATE_POLICY_CHANGE_ROCKET() { return (int)2L; }

    static final int PERFSTATE_POLICY_CHANGE_IDEAL_AGGRESSIVE() { return (int)3L; }

    static final int PROCESSOR_THROTTLE_DISABLED() { return (int)0L; }

    static final int PROCESSOR_THROTTLE_ENABLED() { return (int)1L; }

    static final int PROCESSOR_THROTTLE_AUTOMATIC() { return (int)2L; }

    static final int PROCESSOR_PERF_BOOST_POLICY_DISABLED() { return (int)0L; }

    static final int PROCESSOR_PERF_BOOST_POLICY_MAX() { return (int)100L; }

    static final int PROCESSOR_PERF_BOOST_MODE_DISABLED() { return (int)0L; }

    static final int PROCESSOR_PERF_BOOST_MODE_ENABLED() { return (int)1L; }

    static final int PROCESSOR_PERF_BOOST_MODE_AGGRESSIVE() { return (int)2L; }

    static final int PROCESSOR_PERF_BOOST_MODE_EFFICIENT_ENABLED() { return (int)3L; }

    static final int PROCESSOR_PERF_BOOST_MODE_EFFICIENT_AGGRESSIVE() { return (int)4L; }

    static final int PROCESSOR_PERF_BOOST_MODE_AGGRESSIVE_AT_GUARANTEED() { return (int)5L; }

    static final int PROCESSOR_PERF_BOOST_MODE_EFFICIENT_AGGRESSIVE_AT_GUARANTEED() { return (int)6L; }

    static final int PROCESSOR_PERF_AUTONOMOUS_MODE_DISABLED() { return (int)0L; }

    static final int PROCESSOR_PERF_AUTONOMOUS_MODE_ENABLED() { return (int)1L; }

    static final int PROCESSOR_PERF_PERFORMANCE_PREFERENCE() { return (int)255L; }

    static final int PROCESSOR_PERF_ENERGY_PREFERENCE() { return (int)0L; }

    static final int PROCESSOR_PERF_MINIMUM_ACTIVITY_WINDOW() { return (int)0L; }

    static final int PROCESSOR_PERF_MAXIMUM_ACTIVITY_WINDOW() { return (int)1270000000L; }

    static final int PROCESSOR_DUTY_CYCLING_DISABLED() { return (int)0L; }

    static final int PROCESSOR_DUTY_CYCLING_ENABLED() { return (int)1L; }

    static final int CORE_PARKING_POLICY_CHANGE_IDEAL() { return (int)0L; }

    static final int CORE_PARKING_POLICY_CHANGE_SINGLE() { return (int)1L; }

    static final int CORE_PARKING_POLICY_CHANGE_ROCKET() { return (int)2L; }

    static final int CORE_PARKING_POLICY_CHANGE_MULTISTEP() { return (int)3L; }

    static final int POWER_DEVICE_IDLE_POLICY_PERFORMANCE() { return (int)0L; }

    static final int POWER_DEVICE_IDLE_POLICY_CONSERVATIVE() { return (int)1L; }

    static final int POWER_CONNECTIVITY_IN_STANDBY_DISABLED() { return (int)0L; }

    static final int POWER_CONNECTIVITY_IN_STANDBY_ENABLED() { return (int)1L; }

    static final int POWER_CONNECTIVITY_IN_STANDBY_SYSTEM_MANAGED() { return (int)2L; }

    static final int POWER_DISCONNECTED_STANDBY_MODE_NORMAL() { return (int)0L; }

    static final int POWER_DISCONNECTED_STANDBY_MODE_AGGRESSIVE() { return (int)1L; }

    static final int POWER_SYSTEM_MAXIMUM() { return (int)7L; }

    static final int DIAGNOSTIC_REASON_VERSION() { return (int)0L; }

    static final int DIAGNOSTIC_REASON_SIMPLE_STRING() { return (int)1L; }

    static final int DIAGNOSTIC_REASON_DETAILED_STRING() { return (int)2L; }

    static final int PDCAP_D0_SUPPORTED() { return (int)1L; }

    static final int PDCAP_D1_SUPPORTED() { return (int)2L; }

    static final int PDCAP_D2_SUPPORTED() { return (int)4L; }

    static final int PDCAP_D3_SUPPORTED() { return (int)8L; }

    static final int PDCAP_WAKE_FROM_D0_SUPPORTED() { return (int)16L; }

    static final int PDCAP_WAKE_FROM_D1_SUPPORTED() { return (int)32L; }

    static final int PDCAP_WAKE_FROM_D2_SUPPORTED() { return (int)64L; }

    static final int PDCAP_WAKE_FROM_D3_SUPPORTED() { return (int)128L; }

    static final int PDCAP_WARM_EJECT_SUPPORTED() { return (int)256L; }

    static final int PROC_IDLE_BUCKET_COUNT() { return (int)6L; }

    static final int PROC_IDLE_BUCKET_COUNT_EX() { return (int)16L; }

    static final int ACPI_PPM_SOFTWARE_ALL() { return (int)252L; }

    static final int ACPI_PPM_SOFTWARE_ANY() { return (int)253L; }

    static final int ACPI_PPM_HARDWARE_ALL() { return (int)254L; }

    static final int MS_PPM_SOFTWARE_ALL() { return (int)1L; }

    static final int PPM_FIRMWARE_ACPI1C2() { return (int)1L; }

    static final int PPM_FIRMWARE_ACPI1C3() { return (int)2L; }

    static final int PPM_FIRMWARE_ACPI1TSTATES() { return (int)4L; }

    static final int PPM_FIRMWARE_CST() { return (int)8L; }

    static final int PPM_FIRMWARE_CSD() { return (int)16L; }

    static final int PPM_FIRMWARE_PCT() { return (int)32L; }

    static final int PPM_FIRMWARE_PSS() { return (int)64L; }

    static final int PPM_FIRMWARE_XPSS() { return (int)128L; }

    static final int PPM_FIRMWARE_PPC() { return (int)256L; }

    static final int PPM_FIRMWARE_PSD() { return (int)512L; }

    static final int PPM_FIRMWARE_PTC() { return (int)1024L; }

    static final int PPM_FIRMWARE_TSS() { return (int)2048L; }

    static final int PPM_FIRMWARE_TPC() { return (int)4096L; }

    static final int PPM_FIRMWARE_TSD() { return (int)8192L; }

    static final int PPM_FIRMWARE_PCCH() { return (int)16384L; }

    static final int PPM_FIRMWARE_PCCP() { return (int)32768L; }

    static final int PPM_FIRMWARE_OSC() { return (int)65536L; }

    static final int PPM_FIRMWARE_PDC() { return (int)131072L; }

    static final int PPM_FIRMWARE_CPC() { return (int)262144L; }

    static final int PPM_FIRMWARE_LPI() { return (int)524288L; }

    static final int PPM_PERFORMANCE_IMPLEMENTATION_NONE() { return (int)0L; }

    static final int PPM_PERFORMANCE_IMPLEMENTATION_PSTATES() { return (int)1L; }

    static final int PPM_PERFORMANCE_IMPLEMENTATION_PCCV1() { return (int)2L; }

    static final int PPM_PERFORMANCE_IMPLEMENTATION_CPPC() { return (int)3L; }

    static final int PPM_PERFORMANCE_IMPLEMENTATION_PEP() { return (int)4L; }

    static final int PPM_IDLE_IMPLEMENTATION_NONE() { return (int)0L; }

    static final int PPM_IDLE_IMPLEMENTATION_CSTATES() { return (int)1L; }

    static final int PPM_IDLE_IMPLEMENTATION_PEP() { return (int)2L; }

    static final int PPM_IDLE_IMPLEMENTATION_MICROPEP() { return (int)3L; }

    static final int PPM_IDLE_IMPLEMENTATION_LPISTATES() { return (int)4L; }

    static final int POWER_ACTION_QUERY_ALLOWED() { return (int)1L; }

    static final int POWER_ACTION_UI_ALLOWED() { return (int)2L; }

    static final int POWER_ACTION_OVERRIDE_APPS() { return (int)4L; }

    static final int POWER_ACTION_HIBERBOOT() { return (int)8L; }

    static final int POWER_ACTION_USER_NOTIFY() { return (int)16L; }

    static final int POWER_ACTION_DOZE_TO_HIBERNATE() { return (int)32L; }

    static final int POWER_ACTION_ACPI_CRITICAL() { return (int)16777216L; }

    static final int POWER_ACTION_ACPI_USER_NOTIFY() { return (int)33554432L; }

    static final int POWER_ACTION_DIRECTED_DRIPS() { return (int)67108864L; }

    static final int POWER_ACTION_PSEUDO_TRANSITION() { return (int)134217728L; }

    static final int POWER_ACTION_LIGHTEST_FIRST() { return (int)268435456L; }

    static final int POWER_ACTION_LOCK_CONSOLE() { return (int)536870912L; }

    static final int POWER_ACTION_DISABLE_WAKES() { return (int)1073741824L; }

    static final int POWER_LEVEL_USER_NOTIFY_TEXT() { return (int)1L; }

    static final int POWER_LEVEL_USER_NOTIFY_SOUND() { return (int)2L; }

    static final int POWER_LEVEL_USER_NOTIFY_EXEC() { return (int)4L; }

    static final int POWER_USER_NOTIFY_BUTTON() { return (int)8L; }

    static final int POWER_USER_NOTIFY_SHUTDOWN() { return (int)16L; }

    static final int POWER_USER_NOTIFY_FORCED_SHUTDOWN() { return (int)32L; }

    static final int BATTERY_DISCHARGE_FLAGS_EVENTCODE_MASK() { return (int)7L; }

    static final int NUM_DISCHARGE_POLICIES() { return (int)4L; }

    static final int DISCHARGE_POLICY_CRITICAL() { return (int)0L; }

    static final int DISCHARGE_POLICY_LOW() { return (int)1L; }

    static final int PROCESSOR_IDLESTATE_POLICY_COUNT() { return (int)3L; }

    static final int PO_THROTTLE_NONE() { return (int)0L; }

    static final int PO_THROTTLE_CONSTANT() { return (int)1L; }

    static final int PO_THROTTLE_DEGRADE() { return (int)2L; }

    static final int PO_THROTTLE_ADAPTIVE() { return (int)3L; }

    static final int PO_THROTTLE_MAXIMUM() { return (int)4L; }

    static final int HIBERFILE_TYPE_NONE() { return (int)0L; }

    static final int HIBERFILE_TYPE_REDUCED() { return (int)1L; }

    static final int HIBERFILE_TYPE_FULL() { return (int)2L; }

    static final int HIBERFILE_TYPE_MAX() { return (int)3L; }

    static final int IMAGE_DOS_SIGNATURE() { return (int)23117L; }

    static final int IMAGE_OS2_SIGNATURE() { return (int)17742L; }

    static final int IMAGE_OS2_SIGNATURE_LE() { return (int)17740L; }

    static final int IMAGE_VXD_SIGNATURE() { return (int)17740L; }

    static final int IMAGE_NT_SIGNATURE() { return (int)17744L; }

    static final int IMAGE_SIZEOF_FILE_HEADER() { return (int)20L; }

    static final int IMAGE_FILE_RELOCS_STRIPPED() { return (int)1L; }

    static final int IMAGE_FILE_EXECUTABLE_IMAGE() { return (int)2L; }

    static final int IMAGE_FILE_LINE_NUMS_STRIPPED() { return (int)4L; }

    static final int IMAGE_FILE_LOCAL_SYMS_STRIPPED() { return (int)8L; }

    static final int IMAGE_FILE_AGGRESIVE_WS_TRIM() { return (int)16L; }

    static final int IMAGE_FILE_LARGE_ADDRESS_AWARE() { return (int)32L; }

    static final int IMAGE_FILE_BYTES_REVERSED_LO() { return (int)128L; }

    static final int IMAGE_FILE_32BIT_MACHINE() { return (int)256L; }

    static final int IMAGE_FILE_DEBUG_STRIPPED() { return (int)512L; }

    static final int IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP() { return (int)1024L; }

    static final int IMAGE_FILE_NET_RUN_FROM_SWAP() { return (int)2048L; }

    static final int IMAGE_FILE_SYSTEM() { return (int)4096L; }

    static final int IMAGE_FILE_DLL() { return (int)8192L; }

    static final int IMAGE_FILE_UP_SYSTEM_ONLY() { return (int)16384L; }

    static final int IMAGE_FILE_BYTES_REVERSED_HI() { return (int)32768L; }

    static final int IMAGE_FILE_MACHINE_UNKNOWN() { return (int)0L; }

    static final int IMAGE_FILE_MACHINE_TARGET_HOST() { return (int)1L; }

    static final int IMAGE_FILE_MACHINE_I386() { return (int)332L; }

    static final int IMAGE_FILE_MACHINE_R3000() { return (int)354L; }

    static final int IMAGE_FILE_MACHINE_R4000() { return (int)358L; }

    static final int IMAGE_FILE_MACHINE_R10000() { return (int)360L; }

    static final int IMAGE_FILE_MACHINE_WCEMIPSV2() { return (int)361L; }

    static final int IMAGE_FILE_MACHINE_ALPHA() { return (int)388L; }

    static final int IMAGE_FILE_MACHINE_SH3() { return (int)418L; }

    static final int IMAGE_FILE_MACHINE_SH3DSP() { return (int)419L; }

    static final int IMAGE_FILE_MACHINE_SH3E() { return (int)420L; }

    static final int IMAGE_FILE_MACHINE_SH4() { return (int)422L; }

    static final int IMAGE_FILE_MACHINE_SH5() { return (int)424L; }

    static final int IMAGE_FILE_MACHINE_ARM() { return (int)448L; }

    static final int IMAGE_FILE_MACHINE_THUMB() { return (int)450L; }

    static final int IMAGE_FILE_MACHINE_ARMNT() { return (int)452L; }

    static final int IMAGE_FILE_MACHINE_AM33() { return (int)467L; }

    static final int IMAGE_FILE_MACHINE_POWERPC() { return (int)496L; }

    static final int IMAGE_FILE_MACHINE_POWERPCFP() { return (int)497L; }

    static final int IMAGE_FILE_MACHINE_IA64() { return (int)512L; }

    static final int IMAGE_FILE_MACHINE_MIPS16() { return (int)614L; }

    static final int IMAGE_FILE_MACHINE_ALPHA64() { return (int)644L; }

    static final int IMAGE_FILE_MACHINE_MIPSFPU() { return (int)870L; }

    static final int IMAGE_FILE_MACHINE_MIPSFPU16() { return (int)1126L; }

    static final int IMAGE_FILE_MACHINE_TRICORE() { return (int)1312L; }

    static final int IMAGE_FILE_MACHINE_CEF() { return (int)3311L; }

    static final int IMAGE_FILE_MACHINE_EBC() { return (int)3772L; }

    static final int IMAGE_FILE_MACHINE_AMD64() { return (int)34404L; }

    static final int IMAGE_FILE_MACHINE_M32R() { return (int)36929L; }

    static final int IMAGE_FILE_MACHINE_ARM64() { return (int)43620L; }

    static final int IMAGE_FILE_MACHINE_CEE() { return (int)49390L; }

    static final int IMAGE_NUMBEROF_DIRECTORY_ENTRIES() { return (int)16L; }

    static final int IMAGE_NT_OPTIONAL_HDR32_MAGIC() { return (int)267L; }

    static final int IMAGE_NT_OPTIONAL_HDR64_MAGIC() { return (int)523L; }

    static final int IMAGE_ROM_OPTIONAL_HDR_MAGIC() { return (int)263L; }

    static final int IMAGE_SUBSYSTEM_UNKNOWN() { return (int)0L; }

    static final int IMAGE_SUBSYSTEM_NATIVE() { return (int)1L; }

    static final int IMAGE_SUBSYSTEM_WINDOWS_GUI() { return (int)2L; }

    static final int IMAGE_SUBSYSTEM_WINDOWS_CUI() { return (int)3L; }

    static final int IMAGE_SUBSYSTEM_OS2_CUI() { return (int)5L; }

    static final int IMAGE_SUBSYSTEM_POSIX_CUI() { return (int)7L; }

    static final int IMAGE_SUBSYSTEM_NATIVE_WINDOWS() { return (int)8L; }

    static final int IMAGE_SUBSYSTEM_WINDOWS_CE_GUI() { return (int)9L; }

    static final int IMAGE_SUBSYSTEM_EFI_APPLICATION() { return (int)10L; }

    static final int IMAGE_SUBSYSTEM_EFI_BOOT_SERVICE_DRIVER() { return (int)11L; }

    static final int IMAGE_SUBSYSTEM_EFI_RUNTIME_DRIVER() { return (int)12L; }

    static final int IMAGE_SUBSYSTEM_EFI_ROM() { return (int)13L; }

    static final int IMAGE_SUBSYSTEM_XBOX() { return (int)14L; }

    static final int IMAGE_SUBSYSTEM_WINDOWS_BOOT_APPLICATION() { return (int)16L; }

    static final int IMAGE_SUBSYSTEM_XBOX_CODE_CATALOG() { return (int)17L; }

    static final int IMAGE_DLLCHARACTERISTICS_HIGH_ENTROPY_VA() { return (int)32L; }

    static final int IMAGE_DLLCHARACTERISTICS_DYNAMIC_BASE() { return (int)64L; }

    static final int IMAGE_DLLCHARACTERISTICS_FORCE_INTEGRITY() { return (int)128L; }

    static final int IMAGE_DLLCHARACTERISTICS_NX_COMPAT() { return (int)256L; }

    static final int IMAGE_DLLCHARACTERISTICS_NO_ISOLATION() { return (int)512L; }

    static final int IMAGE_DLLCHARACTERISTICS_NO_SEH() { return (int)1024L; }

    static final int IMAGE_DLLCHARACTERISTICS_NO_BIND() { return (int)2048L; }

    static final int IMAGE_DLLCHARACTERISTICS_APPCONTAINER() { return (int)4096L; }

    static final int IMAGE_DLLCHARACTERISTICS_WDM_DRIVER() { return (int)8192L; }

    static final int IMAGE_DLLCHARACTERISTICS_GUARD_CF() { return (int)16384L; }

    static final int IMAGE_DLLCHARACTERISTICS_TERMINAL_SERVER_AWARE() { return (int)32768L; }

    static final int IMAGE_DIRECTORY_ENTRY_EXPORT() { return (int)0L; }

    static final int IMAGE_DIRECTORY_ENTRY_IMPORT() { return (int)1L; }

    static final int IMAGE_DIRECTORY_ENTRY_RESOURCE() { return (int)2L; }

    static final int IMAGE_DIRECTORY_ENTRY_EXCEPTION() { return (int)3L; }

    static final int IMAGE_DIRECTORY_ENTRY_SECURITY() { return (int)4L; }

    static final int IMAGE_DIRECTORY_ENTRY_BASERELOC() { return (int)5L; }

    static final int IMAGE_DIRECTORY_ENTRY_DEBUG() { return (int)6L; }

    static final int IMAGE_DIRECTORY_ENTRY_ARCHITECTURE() { return (int)7L; }

    static final int IMAGE_DIRECTORY_ENTRY_GLOBALPTR() { return (int)8L; }

    static final int IMAGE_DIRECTORY_ENTRY_TLS() { return (int)9L; }

    static final int IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG() { return (int)10L; }

    static final int IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT() { return (int)11L; }

    static final int IMAGE_DIRECTORY_ENTRY_IAT() { return (int)12L; }

    static final int IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT() { return (int)13L; }

    static final int IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR() { return (int)14L; }

    static final int IMAGE_SIZEOF_SHORT_NAME() { return (int)8L; }

    static final int IMAGE_SIZEOF_SECTION_HEADER() { return (int)40L; }

    static final int IMAGE_SCN_TYPE_NO_PAD() { return (int)8L; }

    static final int IMAGE_SCN_CNT_CODE() { return (int)32L; }

    static final int IMAGE_SCN_CNT_INITIALIZED_DATA() { return (int)64L; }

    static final int IMAGE_SCN_CNT_UNINITIALIZED_DATA() { return (int)128L; }

    static final int IMAGE_SCN_LNK_OTHER() { return (int)256L; }

    static final int IMAGE_SCN_LNK_INFO() { return (int)512L; }

    static final int IMAGE_SCN_LNK_REMOVE() { return (int)2048L; }

    static final int IMAGE_SCN_LNK_COMDAT() { return (int)4096L; }

    static final int IMAGE_SCN_NO_DEFER_SPEC_EXC() { return (int)16384L; }

    static final int IMAGE_SCN_GPREL() { return (int)32768L; }

    static final int IMAGE_SCN_MEM_FARDATA() { return (int)32768L; }

    static final int IMAGE_SCN_MEM_PURGEABLE() { return (int)131072L; }

    static final int IMAGE_SCN_MEM_16BIT() { return (int)131072L; }

    static final int IMAGE_SCN_MEM_LOCKED() { return (int)262144L; }

    static final int IMAGE_SCN_MEM_PRELOAD() { return (int)524288L; }

    static final int IMAGE_SCN_ALIGN_1BYTES() { return (int)1048576L; }

    static final int IMAGE_SCN_ALIGN_2BYTES() { return (int)2097152L; }

    static final int IMAGE_SCN_ALIGN_4BYTES() { return (int)3145728L; }

    static final int IMAGE_SCN_ALIGN_8BYTES() { return (int)4194304L; }

    static final int IMAGE_SCN_ALIGN_16BYTES() { return (int)5242880L; }

    static final int IMAGE_SCN_ALIGN_32BYTES() { return (int)6291456L; }

    static final int IMAGE_SCN_ALIGN_64BYTES() { return (int)7340032L; }

    static final int IMAGE_SCN_ALIGN_128BYTES() { return (int)8388608L; }

    static final int IMAGE_SCN_ALIGN_256BYTES() { return (int)9437184L; }

    static final int IMAGE_SCN_ALIGN_512BYTES() { return (int)10485760L; }

    static final int IMAGE_SCN_ALIGN_1024BYTES() { return (int)11534336L; }

    static final int IMAGE_SCN_ALIGN_2048BYTES() { return (int)12582912L; }

    static final int IMAGE_SCN_ALIGN_4096BYTES() { return (int)13631488L; }

    static final int IMAGE_SCN_ALIGN_8192BYTES() { return (int)14680064L; }

    static final int IMAGE_SCN_ALIGN_MASK() { return (int)15728640L; }

    static final int IMAGE_SCN_LNK_NRELOC_OVFL() { return (int)16777216L; }

    static final int IMAGE_SCN_MEM_DISCARDABLE() { return (int)33554432L; }

    static final int IMAGE_SCN_MEM_NOT_CACHED() { return (int)67108864L; }

    static final int IMAGE_SCN_MEM_NOT_PAGED() { return (int)134217728L; }

    static final int IMAGE_SCN_MEM_SHARED() { return (int)268435456L; }

    static final int IMAGE_SCN_MEM_EXECUTE() { return (int)536870912L; }

    static final int IMAGE_SCN_MEM_READ() { return (int)1073741824L; }

    static final int IMAGE_SCN_SCALE_INDEX() { return (int)1L; }

    static final int IMAGE_SIZEOF_SYMBOL() { return (int)18L; }

    static final int IMAGE_SYM_SECTION_MAX() { return (int)65279L; }

    static final int IMAGE_SYM_TYPE_NULL() { return (int)0L; }

    static final int IMAGE_SYM_TYPE_VOID() { return (int)1L; }

    static final int IMAGE_SYM_TYPE_CHAR() { return (int)2L; }

    static final int IMAGE_SYM_TYPE_SHORT() { return (int)3L; }

    static final int IMAGE_SYM_TYPE_INT() { return (int)4L; }

    static final int IMAGE_SYM_TYPE_LONG() { return (int)5L; }

    static final int IMAGE_SYM_TYPE_FLOAT() { return (int)6L; }

    static final int IMAGE_SYM_TYPE_DOUBLE() { return (int)7L; }

    static final int IMAGE_SYM_TYPE_STRUCT() { return (int)8L; }

    static final int IMAGE_SYM_TYPE_UNION() { return (int)9L; }

    static final int IMAGE_SYM_TYPE_ENUM() { return (int)10L; }

    static final int IMAGE_SYM_TYPE_MOE() { return (int)11L; }

    static final int IMAGE_SYM_TYPE_BYTE() { return (int)12L; }

    static final int IMAGE_SYM_TYPE_WORD() { return (int)13L; }

    static final int IMAGE_SYM_TYPE_UINT() { return (int)14L; }

    static final int IMAGE_SYM_TYPE_DWORD() { return (int)15L; }

    static final int IMAGE_SYM_TYPE_PCODE() { return (int)32768L; }

    static final int IMAGE_SYM_DTYPE_NULL() { return (int)0L; }

    static final int IMAGE_SYM_DTYPE_POINTER() { return (int)1L; }

    static final int IMAGE_SYM_DTYPE_FUNCTION() { return (int)2L; }

    static final int IMAGE_SYM_DTYPE_ARRAY() { return (int)3L; }

    static final int IMAGE_SYM_CLASS_NULL() { return (int)0L; }

    static final int IMAGE_SYM_CLASS_AUTOMATIC() { return (int)1L; }

    static final int IMAGE_SYM_CLASS_EXTERNAL() { return (int)2L; }

    static final int IMAGE_SYM_CLASS_STATIC() { return (int)3L; }

    static final int IMAGE_SYM_CLASS_REGISTER() { return (int)4L; }

    static final int IMAGE_SYM_CLASS_EXTERNAL_DEF() { return (int)5L; }

    static final int IMAGE_SYM_CLASS_LABEL() { return (int)6L; }

    static final int IMAGE_SYM_CLASS_UNDEFINED_LABEL() { return (int)7L; }

    static final int IMAGE_SYM_CLASS_MEMBER_OF_STRUCT() { return (int)8L; }

    static final int IMAGE_SYM_CLASS_ARGUMENT() { return (int)9L; }

    static final int IMAGE_SYM_CLASS_STRUCT_TAG() { return (int)10L; }

    static final int IMAGE_SYM_CLASS_MEMBER_OF_UNION() { return (int)11L; }

    static final int IMAGE_SYM_CLASS_UNION_TAG() { return (int)12L; }

    static final int IMAGE_SYM_CLASS_TYPE_DEFINITION() { return (int)13L; }

    static final int IMAGE_SYM_CLASS_UNDEFINED_STATIC() { return (int)14L; }

    static final int IMAGE_SYM_CLASS_ENUM_TAG() { return (int)15L; }

    static final int IMAGE_SYM_CLASS_MEMBER_OF_ENUM() { return (int)16L; }

    static final int IMAGE_SYM_CLASS_REGISTER_PARAM() { return (int)17L; }

    static final int IMAGE_SYM_CLASS_BIT_FIELD() { return (int)18L; }

    static final int IMAGE_SYM_CLASS_FAR_EXTERNAL() { return (int)68L; }

    static final int IMAGE_SYM_CLASS_BLOCK() { return (int)100L; }

    static final int IMAGE_SYM_CLASS_FUNCTION() { return (int)101L; }

    static final int IMAGE_SYM_CLASS_END_OF_STRUCT() { return (int)102L; }

    static final int IMAGE_SYM_CLASS_FILE() { return (int)103L; }

    static final int IMAGE_SYM_CLASS_SECTION() { return (int)104L; }

    static final int IMAGE_SYM_CLASS_WEAK_EXTERNAL() { return (int)105L; }

    static final int IMAGE_SYM_CLASS_CLR_TOKEN() { return (int)107L; }

    static final int N_BTMASK() { return (int)15L; }

    static final int N_TMASK() { return (int)48L; }

    static final int N_TMASK1() { return (int)192L; }

    static final int N_TMASK2() { return (int)240L; }

    static final int N_BTSHFT() { return (int)4L; }

    static final int N_TSHIFT() { return (int)2L; }

    static final int IMAGE_COMDAT_SELECT_NODUPLICATES() { return (int)1L; }

    static final int IMAGE_COMDAT_SELECT_ANY() { return (int)2L; }

    static final int IMAGE_COMDAT_SELECT_SAME_SIZE() { return (int)3L; }

    static final int IMAGE_COMDAT_SELECT_EXACT_MATCH() { return (int)4L; }

    static final int IMAGE_COMDAT_SELECT_ASSOCIATIVE() { return (int)5L; }

    static final int IMAGE_COMDAT_SELECT_LARGEST() { return (int)6L; }

    static final int IMAGE_COMDAT_SELECT_NEWEST() { return (int)7L; }

    static final int IMAGE_WEAK_EXTERN_SEARCH_NOLIBRARY() { return (int)1L; }

    static final int IMAGE_WEAK_EXTERN_SEARCH_LIBRARY() { return (int)2L; }

    static final int IMAGE_WEAK_EXTERN_SEARCH_ALIAS() { return (int)3L; }

    static final int IMAGE_WEAK_EXTERN_ANTI_DEPENDENCY() { return (int)4L; }

    static final int IMAGE_REL_I386_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_I386_DIR16() { return (int)1L; }

    static final int IMAGE_REL_I386_REL16() { return (int)2L; }

    static final int IMAGE_REL_I386_DIR32() { return (int)6L; }

    static final int IMAGE_REL_I386_DIR32NB() { return (int)7L; }

    static final int IMAGE_REL_I386_SEG12() { return (int)9L; }

    static final int IMAGE_REL_I386_SECTION() { return (int)10L; }

    static final int IMAGE_REL_I386_SECREL() { return (int)11L; }

    static final int IMAGE_REL_I386_TOKEN() { return (int)12L; }

    static final int IMAGE_REL_I386_SECREL7() { return (int)13L; }

    static final int IMAGE_REL_I386_REL32() { return (int)20L; }

    static final int IMAGE_REL_MIPS_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_MIPS_REFHALF() { return (int)1L; }

    static final int IMAGE_REL_MIPS_REFWORD() { return (int)2L; }

    static final int IMAGE_REL_MIPS_JMPADDR() { return (int)3L; }

    static final int IMAGE_REL_MIPS_REFHI() { return (int)4L; }

    static final int IMAGE_REL_MIPS_REFLO() { return (int)5L; }

    static final int IMAGE_REL_MIPS_GPREL() { return (int)6L; }

    static final int IMAGE_REL_MIPS_LITERAL() { return (int)7L; }

    static final int IMAGE_REL_MIPS_SECTION() { return (int)10L; }

    static final int IMAGE_REL_MIPS_SECREL() { return (int)11L; }

    static final int IMAGE_REL_MIPS_SECRELLO() { return (int)12L; }

    static final int IMAGE_REL_MIPS_SECRELHI() { return (int)13L; }

    static final int IMAGE_REL_MIPS_TOKEN() { return (int)14L; }

    static final int IMAGE_REL_MIPS_JMPADDR16() { return (int)16L; }

    static final int IMAGE_REL_MIPS_REFWORDNB() { return (int)34L; }

    static final int IMAGE_REL_MIPS_PAIR() { return (int)37L; }

    static final int IMAGE_REL_ALPHA_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_ALPHA_REFLONG() { return (int)1L; }

    static final int IMAGE_REL_ALPHA_REFQUAD() { return (int)2L; }

    static final int IMAGE_REL_ALPHA_GPREL32() { return (int)3L; }

    static final int IMAGE_REL_ALPHA_LITERAL() { return (int)4L; }

    static final int IMAGE_REL_ALPHA_LITUSE() { return (int)5L; }

    static final int IMAGE_REL_ALPHA_GPDISP() { return (int)6L; }

    static final int IMAGE_REL_ALPHA_BRADDR() { return (int)7L; }

    static final int IMAGE_REL_ALPHA_HINT() { return (int)8L; }

    static final int IMAGE_REL_ALPHA_INLINE_REFLONG() { return (int)9L; }

    static final int IMAGE_REL_ALPHA_REFHI() { return (int)10L; }

    static final int IMAGE_REL_ALPHA_REFLO() { return (int)11L; }

    static final int IMAGE_REL_ALPHA_PAIR() { return (int)12L; }

    static final int IMAGE_REL_ALPHA_MATCH() { return (int)13L; }

    static final int IMAGE_REL_ALPHA_SECTION() { return (int)14L; }

    static final int IMAGE_REL_ALPHA_SECREL() { return (int)15L; }

    static final int IMAGE_REL_ALPHA_REFLONGNB() { return (int)16L; }

    static final int IMAGE_REL_ALPHA_SECRELLO() { return (int)17L; }

    static final int IMAGE_REL_ALPHA_SECRELHI() { return (int)18L; }

    static final int IMAGE_REL_ALPHA_REFQ3() { return (int)19L; }

    static final int IMAGE_REL_ALPHA_REFQ2() { return (int)20L; }

    static final int IMAGE_REL_ALPHA_REFQ1() { return (int)21L; }

    static final int IMAGE_REL_ALPHA_GPRELLO() { return (int)22L; }

    static final int IMAGE_REL_ALPHA_GPRELHI() { return (int)23L; }

    static final int IMAGE_REL_PPC_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_PPC_ADDR64() { return (int)1L; }

    static final int IMAGE_REL_PPC_ADDR32() { return (int)2L; }

    static final int IMAGE_REL_PPC_ADDR24() { return (int)3L; }

    static final int IMAGE_REL_PPC_ADDR16() { return (int)4L; }

    static final int IMAGE_REL_PPC_ADDR14() { return (int)5L; }

    static final int IMAGE_REL_PPC_REL24() { return (int)6L; }

    static final int IMAGE_REL_PPC_REL14() { return (int)7L; }

    static final int IMAGE_REL_PPC_TOCREL16() { return (int)8L; }

    static final int IMAGE_REL_PPC_TOCREL14() { return (int)9L; }

    static final int IMAGE_REL_PPC_ADDR32NB() { return (int)10L; }

    static final int IMAGE_REL_PPC_SECREL() { return (int)11L; }

    static final int IMAGE_REL_PPC_SECTION() { return (int)12L; }

    static final int IMAGE_REL_PPC_IFGLUE() { return (int)13L; }

    static final int IMAGE_REL_PPC_IMGLUE() { return (int)14L; }

    static final int IMAGE_REL_PPC_SECREL16() { return (int)15L; }

    static final int IMAGE_REL_PPC_REFHI() { return (int)16L; }

    static final int IMAGE_REL_PPC_REFLO() { return (int)17L; }

    static final int IMAGE_REL_PPC_PAIR() { return (int)18L; }

    static final int IMAGE_REL_PPC_SECRELLO() { return (int)19L; }

    static final int IMAGE_REL_PPC_SECRELHI() { return (int)20L; }

    static final int IMAGE_REL_PPC_GPREL() { return (int)21L; }

    static final int IMAGE_REL_PPC_TOKEN() { return (int)22L; }

    static final int IMAGE_REL_PPC_TYPEMASK() { return (int)255L; }

    static final int IMAGE_REL_PPC_NEG() { return (int)256L; }

    static final int IMAGE_REL_PPC_BRTAKEN() { return (int)512L; }

    static final int IMAGE_REL_PPC_BRNTAKEN() { return (int)1024L; }

    static final int IMAGE_REL_PPC_TOCDEFN() { return (int)2048L; }

    static final int IMAGE_REL_SH3_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_SH3_DIRECT16() { return (int)1L; }

    static final int IMAGE_REL_SH3_DIRECT32() { return (int)2L; }

    static final int IMAGE_REL_SH3_DIRECT8() { return (int)3L; }

    static final int IMAGE_REL_SH3_DIRECT8_WORD() { return (int)4L; }

    static final int IMAGE_REL_SH3_DIRECT8_LONG() { return (int)5L; }

    static final int IMAGE_REL_SH3_DIRECT4() { return (int)6L; }

    static final int IMAGE_REL_SH3_DIRECT4_WORD() { return (int)7L; }

    static final int IMAGE_REL_SH3_DIRECT4_LONG() { return (int)8L; }

    static final int IMAGE_REL_SH3_PCREL8_WORD() { return (int)9L; }

    static final int IMAGE_REL_SH3_PCREL8_LONG() { return (int)10L; }

    static final int IMAGE_REL_SH3_PCREL12_WORD() { return (int)11L; }

    static final int IMAGE_REL_SH3_STARTOF_SECTION() { return (int)12L; }

    static final int IMAGE_REL_SH3_SIZEOF_SECTION() { return (int)13L; }

    static final int IMAGE_REL_SH3_SECTION() { return (int)14L; }

    static final int IMAGE_REL_SH3_SECREL() { return (int)15L; }

    static final int IMAGE_REL_SH3_DIRECT32_NB() { return (int)16L; }

    static final int IMAGE_REL_SH3_GPREL4_LONG() { return (int)17L; }

    static final int IMAGE_REL_SH3_TOKEN() { return (int)18L; }

    static final int IMAGE_REL_SHM_PCRELPT() { return (int)19L; }

    static final int IMAGE_REL_SHM_REFLO() { return (int)20L; }

    static final int IMAGE_REL_SHM_REFHALF() { return (int)21L; }

    static final int IMAGE_REL_SHM_RELLO() { return (int)22L; }

    static final int IMAGE_REL_SHM_RELHALF() { return (int)23L; }

    static final int IMAGE_REL_SHM_PAIR() { return (int)24L; }

    static final int IMAGE_REL_SH_NOMODE() { return (int)32768L; }

    static final int IMAGE_REL_ARM_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_ARM_ADDR32() { return (int)1L; }

    static final int IMAGE_REL_ARM_ADDR32NB() { return (int)2L; }

    static final int IMAGE_REL_ARM_BRANCH24() { return (int)3L; }

    static final int IMAGE_REL_ARM_BRANCH11() { return (int)4L; }

    static final int IMAGE_REL_ARM_TOKEN() { return (int)5L; }

    static final int IMAGE_REL_ARM_GPREL12() { return (int)6L; }

    static final int IMAGE_REL_ARM_GPREL7() { return (int)7L; }

    static final int IMAGE_REL_ARM_BLX24() { return (int)8L; }

    static final int IMAGE_REL_ARM_BLX11() { return (int)9L; }

    static final int IMAGE_REL_ARM_SECTION() { return (int)14L; }

    static final int IMAGE_REL_ARM_SECREL() { return (int)15L; }

    static final int IMAGE_REL_ARM_MOV32A() { return (int)16L; }

    static final int IMAGE_REL_ARM_MOV32() { return (int)16L; }

    static final int IMAGE_REL_ARM_MOV32T() { return (int)17L; }

    static final int IMAGE_REL_THUMB_MOV32() { return (int)17L; }

    static final int IMAGE_REL_ARM_BRANCH20T() { return (int)18L; }

    static final int IMAGE_REL_THUMB_BRANCH20() { return (int)18L; }

    static final int IMAGE_REL_ARM_BRANCH24T() { return (int)20L; }

    static final int IMAGE_REL_THUMB_BRANCH24() { return (int)20L; }

    static final int IMAGE_REL_ARM_BLX23T() { return (int)21L; }

    static final int IMAGE_REL_THUMB_BLX23() { return (int)21L; }

    static final int IMAGE_REL_AM_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_AM_ADDR32() { return (int)1L; }

    static final int IMAGE_REL_AM_ADDR32NB() { return (int)2L; }

    static final int IMAGE_REL_AM_CALL32() { return (int)3L; }

    static final int IMAGE_REL_AM_FUNCINFO() { return (int)4L; }

    static final int IMAGE_REL_AM_REL32_1() { return (int)5L; }

    static final int IMAGE_REL_AM_REL32_2() { return (int)6L; }

    static final int IMAGE_REL_AM_SECREL() { return (int)7L; }

    static final int IMAGE_REL_AM_SECTION() { return (int)8L; }

    static final int IMAGE_REL_AM_TOKEN() { return (int)9L; }

    static final int IMAGE_REL_ARM64_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_ARM64_ADDR32() { return (int)1L; }

    static final int IMAGE_REL_ARM64_ADDR32NB() { return (int)2L; }

    static final int IMAGE_REL_ARM64_BRANCH26() { return (int)3L; }

    static final int IMAGE_REL_ARM64_PAGEBASE_REL21() { return (int)4L; }

    static final int IMAGE_REL_ARM64_REL21() { return (int)5L; }

    static final int IMAGE_REL_ARM64_PAGEOFFSET_12A() { return (int)6L; }

    static final int IMAGE_REL_ARM64_PAGEOFFSET_12L() { return (int)7L; }

    static final int IMAGE_REL_ARM64_SECREL() { return (int)8L; }

    static final int IMAGE_REL_ARM64_SECREL_LOW12A() { return (int)9L; }

    static final int IMAGE_REL_ARM64_SECREL_HIGH12A() { return (int)10L; }

    static final int IMAGE_REL_ARM64_SECREL_LOW12L() { return (int)11L; }

    static final int IMAGE_REL_ARM64_TOKEN() { return (int)12L; }

    static final int IMAGE_REL_ARM64_SECTION() { return (int)13L; }

    static final int IMAGE_REL_ARM64_ADDR64() { return (int)14L; }

    static final int IMAGE_REL_ARM64_BRANCH19() { return (int)15L; }

    static final int IMAGE_REL_AMD64_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_AMD64_ADDR64() { return (int)1L; }

    static final int IMAGE_REL_AMD64_ADDR32() { return (int)2L; }

    static final int IMAGE_REL_AMD64_ADDR32NB() { return (int)3L; }

    static final int IMAGE_REL_AMD64_REL32() { return (int)4L; }

    static final int IMAGE_REL_AMD64_REL32_1() { return (int)5L; }

    static final int IMAGE_REL_AMD64_REL32_2() { return (int)6L; }

    static final int IMAGE_REL_AMD64_REL32_3() { return (int)7L; }

    static final int IMAGE_REL_AMD64_REL32_4() { return (int)8L; }

    static final int IMAGE_REL_AMD64_REL32_5() { return (int)9L; }

    static final int IMAGE_REL_AMD64_SECTION() { return (int)10L; }

    static final int IMAGE_REL_AMD64_SECREL() { return (int)11L; }

    static final int IMAGE_REL_AMD64_SECREL7() { return (int)12L; }

    static final int IMAGE_REL_AMD64_TOKEN() { return (int)13L; }

    static final int IMAGE_REL_AMD64_SREL32() { return (int)14L; }

    static final int IMAGE_REL_AMD64_PAIR() { return (int)15L; }

    static final int IMAGE_REL_AMD64_SSPAN32() { return (int)16L; }

    static final int IMAGE_REL_AMD64_EHANDLER() { return (int)17L; }

    static final int IMAGE_REL_AMD64_IMPORT_BR() { return (int)18L; }

    static final int IMAGE_REL_AMD64_IMPORT_CALL() { return (int)19L; }

    static final int IMAGE_REL_AMD64_CFG_BR() { return (int)20L; }

    static final int IMAGE_REL_AMD64_CFG_BR_REX() { return (int)21L; }

    static final int IMAGE_REL_AMD64_CFG_CALL() { return (int)22L; }

    static final int IMAGE_REL_AMD64_INDIR_BR() { return (int)23L; }

    static final int IMAGE_REL_AMD64_INDIR_BR_REX() { return (int)24L; }

    static final int IMAGE_REL_AMD64_INDIR_CALL() { return (int)25L; }

    static final int IMAGE_REL_AMD64_INDIR_BR_SWITCHTABLE_FIRST() { return (int)32L; }

    static final int IMAGE_REL_AMD64_INDIR_BR_SWITCHTABLE_LAST() { return (int)47L; }

    static final int IMAGE_REL_IA64_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_IA64_IMM14() { return (int)1L; }

    static final int IMAGE_REL_IA64_IMM22() { return (int)2L; }

    static final int IMAGE_REL_IA64_IMM64() { return (int)3L; }

    static final int IMAGE_REL_IA64_DIR32() { return (int)4L; }

    static final int IMAGE_REL_IA64_DIR64() { return (int)5L; }

    static final int IMAGE_REL_IA64_PCREL21B() { return (int)6L; }

    static final int IMAGE_REL_IA64_PCREL21M() { return (int)7L; }

    static final int IMAGE_REL_IA64_PCREL21F() { return (int)8L; }

    static final int IMAGE_REL_IA64_GPREL22() { return (int)9L; }

    static final int IMAGE_REL_IA64_LTOFF22() { return (int)10L; }

    static final int IMAGE_REL_IA64_SECTION() { return (int)11L; }

    static final int IMAGE_REL_IA64_SECREL22() { return (int)12L; }

    static final int IMAGE_REL_IA64_SECREL64I() { return (int)13L; }

    static final int IMAGE_REL_IA64_SECREL32() { return (int)14L; }

    static final int IMAGE_REL_IA64_DIR32NB() { return (int)16L; }

    static final int IMAGE_REL_IA64_SREL14() { return (int)17L; }

    static final int IMAGE_REL_IA64_SREL22() { return (int)18L; }

    static final int IMAGE_REL_IA64_SREL32() { return (int)19L; }

    static final int IMAGE_REL_IA64_UREL32() { return (int)20L; }

    static final int IMAGE_REL_IA64_PCREL60X() { return (int)21L; }

    static final int IMAGE_REL_IA64_PCREL60B() { return (int)22L; }

    static final int IMAGE_REL_IA64_PCREL60F() { return (int)23L; }

    static final int IMAGE_REL_IA64_PCREL60I() { return (int)24L; }

    static final int IMAGE_REL_IA64_PCREL60M() { return (int)25L; }

    static final int IMAGE_REL_IA64_IMMGPREL64() { return (int)26L; }

    static final int IMAGE_REL_IA64_TOKEN() { return (int)27L; }

    static final int IMAGE_REL_IA64_GPREL32() { return (int)28L; }

    static final int IMAGE_REL_IA64_ADDEND() { return (int)31L; }

    static final int IMAGE_REL_CEF_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_CEF_ADDR32() { return (int)1L; }

    static final int IMAGE_REL_CEF_ADDR64() { return (int)2L; }

    static final int IMAGE_REL_CEF_ADDR32NB() { return (int)3L; }

    static final int IMAGE_REL_CEF_SECTION() { return (int)4L; }

    static final int IMAGE_REL_CEF_SECREL() { return (int)5L; }

    static final int IMAGE_REL_CEF_TOKEN() { return (int)6L; }

    static final int IMAGE_REL_CEE_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_CEE_ADDR32() { return (int)1L; }

    static final int IMAGE_REL_CEE_ADDR64() { return (int)2L; }

    static final int IMAGE_REL_CEE_ADDR32NB() { return (int)3L; }

    static final int IMAGE_REL_CEE_SECTION() { return (int)4L; }

    static final int IMAGE_REL_CEE_SECREL() { return (int)5L; }

    static final int IMAGE_REL_CEE_TOKEN() { return (int)6L; }

    static final int IMAGE_REL_M32R_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_M32R_ADDR32() { return (int)1L; }

    static final int IMAGE_REL_M32R_ADDR32NB() { return (int)2L; }

    static final int IMAGE_REL_M32R_ADDR24() { return (int)3L; }

    static final int IMAGE_REL_M32R_GPREL16() { return (int)4L; }

    static final int IMAGE_REL_M32R_PCREL24() { return (int)5L; }

    static final int IMAGE_REL_M32R_PCREL16() { return (int)6L; }

    static final int IMAGE_REL_M32R_PCREL8() { return (int)7L; }

    static final int IMAGE_REL_M32R_REFHALF() { return (int)8L; }

    static final int IMAGE_REL_M32R_REFHI() { return (int)9L; }

    static final int IMAGE_REL_M32R_REFLO() { return (int)10L; }

    static final int IMAGE_REL_M32R_PAIR() { return (int)11L; }

    static final int IMAGE_REL_M32R_SECTION() { return (int)12L; }

    static final int IMAGE_REL_M32R_SECREL32() { return (int)13L; }

    static final int IMAGE_REL_M32R_TOKEN() { return (int)14L; }

    static final int IMAGE_REL_EBC_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_EBC_ADDR32NB() { return (int)1L; }

    static final int IMAGE_REL_EBC_REL32() { return (int)2L; }

    static final int IMAGE_REL_EBC_SECTION() { return (int)3L; }

    static final int IMAGE_REL_EBC_SECREL() { return (int)4L; }

    static final int EMARCH_ENC_I17_IMM7B_INST_WORD_X() { return (int)3L; }

    static final int EMARCH_ENC_I17_IMM7B_SIZE_X() { return (int)7L; }

    static final int EMARCH_ENC_I17_IMM7B_INST_WORD_POS_X() { return (int)4L; }

    static final int EMARCH_ENC_I17_IMM7B_VAL_POS_X() { return (int)0L; }

    static final int EMARCH_ENC_I17_IMM9D_INST_WORD_X() { return (int)3L; }

    static final int EMARCH_ENC_I17_IMM9D_SIZE_X() { return (int)9L; }

    static final int EMARCH_ENC_I17_IMM9D_INST_WORD_POS_X() { return (int)18L; }

    static final int EMARCH_ENC_I17_IMM9D_VAL_POS_X() { return (int)7L; }

    static final int EMARCH_ENC_I17_IMM5C_INST_WORD_X() { return (int)3L; }

    static final int EMARCH_ENC_I17_IMM5C_SIZE_X() { return (int)5L; }

    static final int EMARCH_ENC_I17_IMM5C_INST_WORD_POS_X() { return (int)13L; }

    static final int EMARCH_ENC_I17_IMM5C_VAL_POS_X() { return (int)16L; }

    static final int EMARCH_ENC_I17_IC_INST_WORD_X() { return (int)3L; }

    static final int EMARCH_ENC_I17_IC_SIZE_X() { return (int)1L; }

    static final int EMARCH_ENC_I17_IC_INST_WORD_POS_X() { return (int)12L; }

    static final int EMARCH_ENC_I17_IC_VAL_POS_X() { return (int)21L; }

    static final int EMARCH_ENC_I17_IMM41a_INST_WORD_X() { return (int)1L; }

    static final int EMARCH_ENC_I17_IMM41a_SIZE_X() { return (int)10L; }

    static final int EMARCH_ENC_I17_IMM41a_INST_WORD_POS_X() { return (int)14L; }

    static final int EMARCH_ENC_I17_IMM41a_VAL_POS_X() { return (int)22L; }

    static final int EMARCH_ENC_I17_IMM41b_INST_WORD_X() { return (int)1L; }

    static final int EMARCH_ENC_I17_IMM41b_SIZE_X() { return (int)8L; }

    static final int EMARCH_ENC_I17_IMM41b_INST_WORD_POS_X() { return (int)24L; }

    static final int EMARCH_ENC_I17_IMM41b_VAL_POS_X() { return (int)32L; }

    static final int EMARCH_ENC_I17_IMM41c_INST_WORD_X() { return (int)2L; }

    static final int EMARCH_ENC_I17_IMM41c_SIZE_X() { return (int)23L; }

    static final int EMARCH_ENC_I17_IMM41c_INST_WORD_POS_X() { return (int)0L; }

    static final int EMARCH_ENC_I17_IMM41c_VAL_POS_X() { return (int)40L; }

    static final int EMARCH_ENC_I17_SIGN_INST_WORD_X() { return (int)3L; }

    static final int EMARCH_ENC_I17_SIGN_SIZE_X() { return (int)1L; }

    static final int EMARCH_ENC_I17_SIGN_INST_WORD_POS_X() { return (int)27L; }

    static final int EMARCH_ENC_I17_SIGN_VAL_POS_X() { return (int)63L; }

    static final int X3_OPCODE_INST_WORD_X() { return (int)3L; }

    static final int X3_OPCODE_SIZE_X() { return (int)4L; }

    static final int X3_OPCODE_INST_WORD_POS_X() { return (int)28L; }

    static final int X3_OPCODE_SIGN_VAL_POS_X() { return (int)0L; }

    static final int X3_I_INST_WORD_X() { return (int)3L; }

    static final int X3_I_SIZE_X() { return (int)1L; }

    static final int X3_I_INST_WORD_POS_X() { return (int)27L; }

    static final int X3_I_SIGN_VAL_POS_X() { return (int)59L; }

    static final int X3_D_WH_INST_WORD_X() { return (int)3L; }

    static final int X3_D_WH_SIZE_X() { return (int)3L; }

    static final int X3_D_WH_INST_WORD_POS_X() { return (int)24L; }

    static final int X3_D_WH_SIGN_VAL_POS_X() { return (int)0L; }

    static final int X3_IMM20_INST_WORD_X() { return (int)3L; }

    static final int X3_IMM20_SIZE_X() { return (int)20L; }

    static final int X3_IMM20_INST_WORD_POS_X() { return (int)4L; }

    static final int X3_IMM20_SIGN_VAL_POS_X() { return (int)0L; }

    static final int X3_IMM39_1_INST_WORD_X() { return (int)2L; }

    static final int X3_IMM39_1_SIZE_X() { return (int)23L; }

    static final int X3_IMM39_1_INST_WORD_POS_X() { return (int)0L; }

    static final int X3_IMM39_1_SIGN_VAL_POS_X() { return (int)36L; }

    static final int X3_IMM39_2_INST_WORD_X() { return (int)1L; }

    static final int X3_IMM39_2_SIZE_X() { return (int)16L; }

    static final int X3_IMM39_2_INST_WORD_POS_X() { return (int)16L; }

    static final int X3_IMM39_2_SIGN_VAL_POS_X() { return (int)20L; }

    static final int X3_P_INST_WORD_X() { return (int)3L; }

    static final int X3_P_SIZE_X() { return (int)4L; }

    static final int X3_P_INST_WORD_POS_X() { return (int)0L; }

    static final int X3_P_SIGN_VAL_POS_X() { return (int)0L; }

    static final int X3_TMPLT_INST_WORD_X() { return (int)0L; }

    static final int X3_TMPLT_SIZE_X() { return (int)4L; }

    static final int X3_TMPLT_INST_WORD_POS_X() { return (int)0L; }

    static final int X3_TMPLT_SIGN_VAL_POS_X() { return (int)0L; }

    static final int X3_BTYPE_QP_INST_WORD_X() { return (int)2L; }

    static final int X3_BTYPE_QP_SIZE_X() { return (int)9L; }

    static final int X3_BTYPE_QP_INST_WORD_POS_X() { return (int)23L; }

    static final int X3_BTYPE_QP_INST_VAL_POS_X() { return (int)0L; }

    static final int X3_EMPTY_INST_WORD_X() { return (int)1L; }

    static final int X3_EMPTY_SIZE_X() { return (int)2L; }

    static final int X3_EMPTY_INST_WORD_POS_X() { return (int)14L; }

    static final int X3_EMPTY_INST_VAL_POS_X() { return (int)0L; }

    static final int IMAGE_REL_BASED_ABSOLUTE() { return (int)0L; }

    static final int IMAGE_REL_BASED_HIGH() { return (int)1L; }

    static final int IMAGE_REL_BASED_LOW() { return (int)2L; }

    static final int IMAGE_REL_BASED_HIGHLOW() { return (int)3L; }

    static final int IMAGE_REL_BASED_HIGHADJ() { return (int)4L; }

    static final int IMAGE_REL_BASED_MACHINE_SPECIFIC_5() { return (int)5L; }

    static final int IMAGE_REL_BASED_RESERVED() { return (int)6L; }

    static final int IMAGE_REL_BASED_MACHINE_SPECIFIC_7() { return (int)7L; }

    static final int IMAGE_REL_BASED_MACHINE_SPECIFIC_8() { return (int)8L; }

    static final int IMAGE_REL_BASED_MACHINE_SPECIFIC_9() { return (int)9L; }

    static final int IMAGE_REL_BASED_DIR64() { return (int)10L; }

    static final int IMAGE_REL_BASED_IA64_IMM64() { return (int)9L; }

    static final int IMAGE_REL_BASED_MIPS_JMPADDR() { return (int)5L; }

    static final int IMAGE_REL_BASED_MIPS_JMPADDR16() { return (int)9L; }

    static final int IMAGE_REL_BASED_ARM_MOV32() { return (int)5L; }

    static final int IMAGE_REL_BASED_THUMB_MOV32() { return (int)7L; }

    static final int IMAGE_ARCHIVE_START_SIZE() { return (int)8L; }

    static final int IMAGE_SIZEOF_ARCHIVE_MEMBER_HDR() { return (int)60L; }

    static final int IMAGE_DYNAMIC_RELOCATION_GUARD_RF_PROLOGUE() { return (int)1L; }

    static final int IMAGE_DYNAMIC_RELOCATION_GUARD_RF_EPILOGUE() { return (int)2L; }

    static final int IMAGE_DYNAMIC_RELOCATION_GUARD_IMPORT_CONTROL_TRANSFER() { return (int)3L; }

    static final int IMAGE_DYNAMIC_RELOCATION_GUARD_INDIR_CONTROL_TRANSFER() { return (int)4L; }

    static final int IMAGE_DYNAMIC_RELOCATION_GUARD_SWITCHTABLE_BRANCH() { return (int)5L; }

    static final int IMAGE_HOT_PATCH_BASE_OBLIGATORY() { return (int)1L; }

    static final int IMAGE_HOT_PATCH_BASE_CAN_ROLL_BACK() { return (int)2L; }

    static final int IMAGE_HOT_PATCH_CHUNK_OBLIGATORY() { return (int)1073741824L; }

    static final int IMAGE_HOT_PATCH_CHUNK_RESERVED() { return (int)1072705536L; }

    static final int IMAGE_HOT_PATCH_CHUNK_TYPE() { return (int)1032192L; }

    static final int IMAGE_HOT_PATCH_CHUNK_SOURCE_RVA() { return (int)32768L; }

    static final int IMAGE_HOT_PATCH_CHUNK_TARGET_RVA() { return (int)16384L; }

    static final int IMAGE_HOT_PATCH_CHUNK_SIZE() { return (int)4095L; }

    static final int IMAGE_HOT_PATCH_NONE() { return (int)0L; }

    static final int IMAGE_HOT_PATCH_FUNCTION() { return (int)114688L; }

    static final int IMAGE_HOT_PATCH_ABSOLUTE() { return (int)180224L; }

    static final int IMAGE_HOT_PATCH_REL32() { return (int)245760L; }

    static final int IMAGE_HOT_PATCH_CALL_TARGET() { return (int)278528L; }

    static final int IMAGE_HOT_PATCH_INDIRECT() { return (int)376832L; }

    static final int IMAGE_HOT_PATCH_NO_CALL_TARGET() { return (int)409600L; }

    static final int IMAGE_HOT_PATCH_DYNAMIC_VALUE() { return (int)491520L; }

    static final int IMAGE_GUARD_CF_INSTRUMENTED() { return (int)256L; }

    static final int IMAGE_GUARD_CFW_INSTRUMENTED() { return (int)512L; }

    static final int IMAGE_GUARD_CF_FUNCTION_TABLE_PRESENT() { return (int)1024L; }

    static final int IMAGE_GUARD_SECURITY_COOKIE_UNUSED() { return (int)2048L; }

    static final int IMAGE_GUARD_PROTECT_DELAYLOAD_IAT() { return (int)4096L; }

    static final int IMAGE_GUARD_DELAYLOAD_IAT_IN_ITS_OWN_SECTION() { return (int)8192L; }

    static final int IMAGE_GUARD_CF_EXPORT_SUPPRESSION_INFO_PRESENT() { return (int)16384L; }

    static final int IMAGE_GUARD_CF_ENABLE_EXPORT_SUPPRESSION() { return (int)32768L; }

    static final int IMAGE_GUARD_CF_LONGJUMP_TABLE_PRESENT() { return (int)65536L; }

    static final int IMAGE_GUARD_RF_INSTRUMENTED() { return (int)131072L; }

    static final int IMAGE_GUARD_RF_ENABLE() { return (int)262144L; }

    static final int IMAGE_GUARD_RF_STRICT() { return (int)524288L; }

    static final int IMAGE_GUARD_RETPOLINE_PRESENT() { return (int)1048576L; }

    static final int IMAGE_GUARD_EH_CONTINUATION_TABLE_PRESENT() { return (int)2097152L; }

    static final int IMAGE_GUARD_CF_FUNCTION_TABLE_SIZE_SHIFT() { return (int)28L; }

    static final int IMAGE_GUARD_FLAG_FID_SUPPRESSED() { return (int)1L; }

    static final int IMAGE_GUARD_FLAG_EXPORT_SUPPRESSED() { return (int)2L; }

    static final int IMAGE_ENCLAVE_POLICY_DEBUGGABLE() { return (int)1L; }

    static final int IMAGE_ENCLAVE_FLAG_PRIMARY_IMAGE() { return (int)1L; }

    static final int IMAGE_ENCLAVE_IMPORT_MATCH_NONE() { return (int)0L; }

    static final int IMAGE_ENCLAVE_IMPORT_MATCH_UNIQUE_ID() { return (int)1L; }

    static final int IMAGE_ENCLAVE_IMPORT_MATCH_AUTHOR_ID() { return (int)2L; }

    static final int IMAGE_ENCLAVE_IMPORT_MATCH_FAMILY_ID() { return (int)3L; }

    static final int IMAGE_ENCLAVE_IMPORT_MATCH_IMAGE_ID() { return (int)4L; }

    static final int IMAGE_DEBUG_TYPE_UNKNOWN() { return (int)0L; }

    static final int IMAGE_DEBUG_TYPE_COFF() { return (int)1L; }

    static final int IMAGE_DEBUG_TYPE_CODEVIEW() { return (int)2L; }

    static final int IMAGE_DEBUG_TYPE_FPO() { return (int)3L; }

    static final int IMAGE_DEBUG_TYPE_MISC() { return (int)4L; }

    static final int IMAGE_DEBUG_TYPE_EXCEPTION() { return (int)5L; }

    static final int IMAGE_DEBUG_TYPE_FIXUP() { return (int)6L; }

    static final int IMAGE_DEBUG_TYPE_OMAP_TO_SRC() { return (int)7L; }

    static final int IMAGE_DEBUG_TYPE_OMAP_FROM_SRC() { return (int)8L; }

    static final int IMAGE_DEBUG_TYPE_BORLAND() { return (int)9L; }

    static final int IMAGE_DEBUG_TYPE_RESERVED10() { return (int)10L; }

    static final int IMAGE_DEBUG_TYPE_CLSID() { return (int)11L; }

    static final int IMAGE_DEBUG_TYPE_VC_FEATURE() { return (int)12L; }

    static final int IMAGE_DEBUG_TYPE_POGO() { return (int)13L; }

    static final int IMAGE_DEBUG_TYPE_ILTCG() { return (int)14L; }

    static final int IMAGE_DEBUG_TYPE_MPX() { return (int)15L; }

    static final int IMAGE_DEBUG_TYPE_REPRO() { return (int)16L; }

    static final int IMAGE_DEBUG_TYPE_EX_DLLCHARACTERISTICS() { return (int)20L; }

    static final int IMAGE_DLLCHARACTERISTICS_EX_CET_COMPAT() { return (int)1L; }

    static final int FRAME_FPO() { return (int)0L; }

    static final int FRAME_TRAP() { return (int)1L; }

    static final int FRAME_TSS() { return (int)2L; }

    static final int FRAME_NONFPO() { return (int)3L; }

    static final int SIZEOF_RFPO_DATA() { return (int)16L; }

    static final int IMAGE_DEBUG_MISC_EXENAME() { return (int)1L; }

    static final int IMAGE_SEPARATE_DEBUG_SIGNATURE() { return (int)18756L; }

    static final int NON_PAGED_DEBUG_SIGNATURE() { return (int)18766L; }

    static final int IMAGE_SEPARATE_DEBUG_FLAGS_MASK() { return (int)32768L; }

    static final int IMAGE_SEPARATE_DEBUG_MISMATCH() { return (int)32768L; }

    static final int IMPORT_OBJECT_HDR_SIG2() { return (int)65535L; }

    static final int RTL_RUN_ONCE_CTX_RESERVED_BITS() { return (int)2L; }

    static final int FAST_FAIL_LEGACY_GS_VIOLATION() { return (int)0L; }

    static final int FAST_FAIL_VTGUARD_CHECK_FAILURE() { return (int)1L; }

    static final int FAST_FAIL_STACK_COOKIE_CHECK_FAILURE() { return (int)2L; }

    static final int FAST_FAIL_CORRUPT_LIST_ENTRY() { return (int)3L; }

    static final int FAST_FAIL_INCORRECT_STACK() { return (int)4L; }

    static final int FAST_FAIL_INVALID_ARG() { return (int)5L; }

    static final int FAST_FAIL_GS_COOKIE_INIT() { return (int)6L; }

    static final int FAST_FAIL_FATAL_APP_EXIT() { return (int)7L; }

    static final int FAST_FAIL_RANGE_CHECK_FAILURE() { return (int)8L; }

    static final int FAST_FAIL_UNSAFE_REGISTRY_ACCESS() { return (int)9L; }

    static final int FAST_FAIL_GUARD_ICALL_CHECK_FAILURE() { return (int)10L; }

}

