// Generated by jextract

package com.github.tornaia.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class cfapi_h$constants$5 extends cfapi_h$constants$4 {

    /* package-private */ cfapi_h$constants$5() {}
    static final int TME_NONCLIENT() { return (int)16L; }

    static final int TME_QUERY() { return (int)1073741824L; }

    static final int WS_EX_LAYERED() { return (int)524288L; }

    static final int CS_VREDRAW() { return (int)1L; }

    static final int CS_HREDRAW() { return (int)2L; }

    static final int CS_DBLCLKS() { return (int)8L; }

    static final int CS_OWNDC() { return (int)32L; }

    static final int CS_CLASSDC() { return (int)64L; }

    static final int CS_PARENTDC() { return (int)128L; }

    static final int CS_NOCLOSE() { return (int)512L; }

    static final int CS_SAVEBITS() { return (int)2048L; }

    static final int CS_BYTEALIGNCLIENT() { return (int)4096L; }

    static final int CS_BYTEALIGNWINDOW() { return (int)8192L; }

    static final int CS_GLOBALCLASS() { return (int)16384L; }

    static final int CS_IME() { return (int)65536L; }

    static final int CS_DROPSHADOW() { return (int)131072L; }

    static final int BDR_RAISEDOUTER() { return (int)1L; }

    static final int BDR_SUNKENOUTER() { return (int)2L; }

    static final int BDR_RAISEDINNER() { return (int)4L; }

    static final int BDR_SUNKENINNER() { return (int)8L; }

    static final int BF_LEFT() { return (int)1L; }

    static final int BF_TOP() { return (int)2L; }

    static final int BF_RIGHT() { return (int)4L; }

    static final int BF_BOTTOM() { return (int)8L; }

    static final int BF_DIAGONAL() { return (int)16L; }

    static final int BF_MIDDLE() { return (int)2048L; }

    static final int BF_SOFT() { return (int)4096L; }

    static final int BF_ADJUST() { return (int)8192L; }

    static final int BF_FLAT() { return (int)16384L; }

    static final int BF_MONO() { return (int)32768L; }

    static final int DFC_CAPTION() { return (int)1L; }

    static final int DFC_MENU() { return (int)2L; }

    static final int DFC_SCROLL() { return (int)3L; }

    static final int DFC_BUTTON() { return (int)4L; }

    static final int DFC_POPUPMENU() { return (int)5L; }

    static final int DFCS_CAPTIONCLOSE() { return (int)0L; }

    static final int DFCS_CAPTIONMIN() { return (int)1L; }

    static final int DFCS_CAPTIONMAX() { return (int)2L; }

    static final int DFCS_CAPTIONRESTORE() { return (int)3L; }

    static final int DFCS_CAPTIONHELP() { return (int)4L; }

    static final int DFCS_MENUARROW() { return (int)0L; }

    static final int DFCS_MENUCHECK() { return (int)1L; }

    static final int DFCS_MENUBULLET() { return (int)2L; }

    static final int DFCS_MENUARROWRIGHT() { return (int)4L; }

    static final int DFCS_SCROLLUP() { return (int)0L; }

    static final int DFCS_SCROLLDOWN() { return (int)1L; }

    static final int DFCS_SCROLLLEFT() { return (int)2L; }

    static final int DFCS_SCROLLRIGHT() { return (int)3L; }

    static final int DFCS_SCROLLCOMBOBOX() { return (int)5L; }

    static final int DFCS_SCROLLSIZEGRIP() { return (int)8L; }

    static final int DFCS_SCROLLSIZEGRIPRIGHT() { return (int)16L; }

    static final int DFCS_BUTTONCHECK() { return (int)0L; }

    static final int DFCS_BUTTONRADIOIMAGE() { return (int)1L; }

    static final int DFCS_BUTTONRADIOMASK() { return (int)2L; }

    static final int DFCS_BUTTONRADIO() { return (int)4L; }

    static final int DFCS_BUTTON3STATE() { return (int)8L; }

    static final int DFCS_BUTTONPUSH() { return (int)16L; }

    static final int DFCS_INACTIVE() { return (int)256L; }

    static final int DFCS_PUSHED() { return (int)512L; }

    static final int DFCS_CHECKED() { return (int)1024L; }

    static final int DFCS_TRANSPARENT() { return (int)2048L; }

    static final int DFCS_HOT() { return (int)4096L; }

    static final int DFCS_ADJUSTRECT() { return (int)8192L; }

    static final int DFCS_FLAT() { return (int)16384L; }

    static final int DFCS_MONO() { return (int)32768L; }

    static final int DC_ACTIVE() { return (int)1L; }

    static final int DC_SMALLCAP() { return (int)2L; }

    static final int DC_ICON() { return (int)4L; }

    static final int DC_TEXT() { return (int)8L; }

    static final int DC_INBUTTON() { return (int)16L; }

    static final int DC_GRADIENT() { return (int)32L; }

    static final int DC_BUTTONS() { return (int)4096L; }

    static final int IDANI_OPEN() { return (int)1L; }

    static final int IDANI_CAPTION() { return (int)3L; }

    static final int CF_TEXT() { return (int)1L; }

    static final int CF_BITMAP() { return (int)2L; }

    static final int CF_METAFILEPICT() { return (int)3L; }

    static final int CF_SYLK() { return (int)4L; }

    static final int CF_DIF() { return (int)5L; }

    static final int CF_TIFF() { return (int)6L; }

    static final int CF_OEMTEXT() { return (int)7L; }

    static final int CF_DIB() { return (int)8L; }

    static final int CF_PALETTE() { return (int)9L; }

    static final int CF_PENDATA() { return (int)10L; }

    static final int CF_RIFF() { return (int)11L; }

    static final int CF_WAVE() { return (int)12L; }

    static final int CF_UNICODETEXT() { return (int)13L; }

    static final int CF_ENHMETAFILE() { return (int)14L; }

    static final int CF_HDROP() { return (int)15L; }

    static final int CF_LOCALE() { return (int)16L; }

    static final int CF_DIBV5() { return (int)17L; }

    static final int CF_MAX() { return (int)18L; }

    static final int CF_OWNERDISPLAY() { return (int)128L; }

    static final int CF_DSPTEXT() { return (int)129L; }

    static final int CF_DSPBITMAP() { return (int)130L; }

    static final int CF_DSPMETAFILEPICT() { return (int)131L; }

    static final int CF_DSPENHMETAFILE() { return (int)142L; }

    static final int CF_PRIVATEFIRST() { return (int)512L; }

    static final int CF_PRIVATELAST() { return (int)767L; }

    static final int CF_GDIOBJFIRST() { return (int)768L; }

    static final int CF_GDIOBJLAST() { return (int)1023L; }

    static final int FNOINVERT() { return (int)2L; }

    static final int FSHIFT() { return (int)4L; }

    static final int FCONTROL() { return (int)8L; }

    static final int FALT() { return (int)16L; }

    static final int WPF_SETMINPOSITION() { return (int)1L; }

    static final int WPF_RESTORETOMAXIMIZED() { return (int)2L; }

    static final int WPF_ASYNCWINDOWPLACEMENT() { return (int)4L; }

    static final int ODT_MENU() { return (int)1L; }

    static final int ODT_LISTBOX() { return (int)2L; }

    static final int ODT_COMBOBOX() { return (int)3L; }

    static final int ODT_BUTTON() { return (int)4L; }

    static final int ODT_STATIC() { return (int)5L; }

    static final int ODA_DRAWENTIRE() { return (int)1L; }

    static final int ODA_SELECT() { return (int)2L; }

    static final int ODA_FOCUS() { return (int)4L; }

    static final int ODS_SELECTED() { return (int)1L; }

    static final int ODS_GRAYED() { return (int)2L; }

    static final int ODS_DISABLED() { return (int)4L; }

    static final int ODS_CHECKED() { return (int)8L; }

    static final int ODS_FOCUS() { return (int)16L; }

    static final int ODS_DEFAULT() { return (int)32L; }

    static final int ODS_COMBOBOXEDIT() { return (int)4096L; }

    static final int ODS_HOTLIGHT() { return (int)64L; }

    static final int ODS_INACTIVE() { return (int)128L; }

    static final int ODS_NOACCEL() { return (int)256L; }

    static final int ODS_NOFOCUSRECT() { return (int)512L; }

    static final int PM_NOREMOVE() { return (int)0L; }

    static final int PM_REMOVE() { return (int)1L; }

    static final int PM_NOYIELD() { return (int)2L; }

    static final int MOD_ALT() { return (int)1L; }

    static final int MOD_CONTROL() { return (int)2L; }

    static final int MOD_SHIFT() { return (int)4L; }

    static final int MOD_WIN() { return (int)8L; }

    static final int MOD_NOREPEAT() { return (int)16384L; }

    static final int ENDSESSION_CLOSEAPP() { return (int)1L; }

    static final int ENDSESSION_CRITICAL() { return (int)1073741824L; }

    static final int EWX_LOGOFF() { return (int)0L; }

    static final int EWX_SHUTDOWN() { return (int)1L; }

    static final int EWX_REBOOT() { return (int)2L; }

    static final int EWX_FORCE() { return (int)4L; }

    static final int EWX_POWEROFF() { return (int)8L; }

    static final int EWX_FORCEIFHUNG() { return (int)16L; }

    static final int EWX_QUICKRESOLVE() { return (int)32L; }

    static final int EWX_RESTARTAPPS() { return (int)64L; }

    static final int EWX_HYBRID_SHUTDOWN() { return (int)4194304L; }

    static final int EWX_BOOTOPTIONS() { return (int)16777216L; }

    static final int EWX_ARSO() { return (int)67108864L; }

    static final int BSM_ALLCOMPONENTS() { return (int)0L; }

    static final int BSM_VXDS() { return (int)1L; }

    static final int BSM_NETDRIVER() { return (int)2L; }

    static final int BSM_INSTALLABLEDRIVERS() { return (int)4L; }

    static final int BSM_APPLICATIONS() { return (int)8L; }

    static final int BSM_ALLDESKTOPS() { return (int)16L; }

    static final int BSF_QUERY() { return (int)1L; }

    static final int BSF_IGNORECURRENTTASK() { return (int)2L; }

    static final int BSF_FLUSHDISK() { return (int)4L; }

    static final int BSF_NOHANG() { return (int)8L; }

    static final int BSF_POSTMESSAGE() { return (int)16L; }

    static final int BSF_FORCEIFHUNG() { return (int)32L; }

    static final int BSF_NOTIMEOUTIFNOTHUNG() { return (int)64L; }

    static final int BSF_ALLOWSFW() { return (int)128L; }

    static final int BSF_SENDNOTIFYMESSAGE() { return (int)256L; }

    static final int BSF_RETURNHDESK() { return (int)512L; }

    static final int BSF_LUID() { return (int)1024L; }

    static final int BROADCAST_QUERY_DENY() { return (int)1112363332L; }

    static final int DEVICE_NOTIFY_WINDOW_HANDLE() { return (int)0L; }

    static final int DEVICE_NOTIFY_SERVICE_HANDLE() { return (int)1L; }

    static final int DEVICE_NOTIFY_ALL_INTERFACE_CLASSES() { return (int)4L; }

    static final int ISMEX_NOSEND() { return (int)0L; }

    static final int ISMEX_SEND() { return (int)1L; }

    static final int ISMEX_NOTIFY() { return (int)2L; }

    static final int ISMEX_CALLBACK() { return (int)4L; }

    static final int ISMEX_REPLIED() { return (int)8L; }

    static final int PW_CLIENTONLY() { return (int)1L; }

    static final int PW_RENDERFULLCONTENT() { return (int)2L; }

    static final int LWA_COLORKEY() { return (int)1L; }

    static final int LWA_ALPHA() { return (int)2L; }

    static final int ULW_COLORKEY() { return (int)1L; }

    static final int ULW_ALPHA() { return (int)2L; }

    static final int ULW_OPAQUE() { return (int)4L; }

    static final int ULW_EX_NORESIZE() { return (int)8L; }

    static final int FLASHW_STOP() { return (int)0L; }

    static final int FLASHW_CAPTION() { return (int)1L; }

    static final int FLASHW_TRAY() { return (int)2L; }

    static final int FLASHW_TIMER() { return (int)4L; }

    static final int FLASHW_TIMERNOFG() { return (int)12L; }

    static final int WDA_NONE() { return (int)0L; }

    static final int WDA_MONITOR() { return (int)1L; }

    static final int WDA_EXCLUDEFROMCAPTURE() { return (int)17L; }

    static final int SWP_NOSIZE() { return (int)1L; }

    static final int SWP_NOMOVE() { return (int)2L; }

    static final int SWP_NOZORDER() { return (int)4L; }

    static final int SWP_NOREDRAW() { return (int)8L; }

    static final int SWP_NOACTIVATE() { return (int)16L; }

    static final int SWP_FRAMECHANGED() { return (int)32L; }

    static final int SWP_SHOWWINDOW() { return (int)64L; }

    static final int SWP_HIDEWINDOW() { return (int)128L; }

    static final int SWP_NOCOPYBITS() { return (int)256L; }

    static final int SWP_NOOWNERZORDER() { return (int)512L; }

    static final int SWP_NOSENDCHANGING() { return (int)1024L; }

    static final int SWP_DEFERERASE() { return (int)8192L; }

    static final int SWP_ASYNCWINDOWPOS() { return (int)16384L; }

    static final int DLGWINDOWEXTRA() { return (int)30L; }

    static final int KEYEVENTF_EXTENDEDKEY() { return (int)1L; }

    static final int KEYEVENTF_KEYUP() { return (int)2L; }

    static final int KEYEVENTF_UNICODE() { return (int)4L; }

    static final int KEYEVENTF_SCANCODE() { return (int)8L; }

    static final int MOUSEEVENTF_MOVE() { return (int)1L; }

    static final int MOUSEEVENTF_LEFTDOWN() { return (int)2L; }

    static final int MOUSEEVENTF_LEFTUP() { return (int)4L; }

    static final int MOUSEEVENTF_RIGHTDOWN() { return (int)8L; }

    static final int MOUSEEVENTF_RIGHTUP() { return (int)16L; }

    static final int MOUSEEVENTF_MIDDLEDOWN() { return (int)32L; }

    static final int MOUSEEVENTF_MIDDLEUP() { return (int)64L; }

    static final int MOUSEEVENTF_XDOWN() { return (int)128L; }

    static final int MOUSEEVENTF_XUP() { return (int)256L; }

    static final int MOUSEEVENTF_WHEEL() { return (int)2048L; }

    static final int MOUSEEVENTF_HWHEEL() { return (int)4096L; }

    static final int MOUSEEVENTF_MOVE_NOCOALESCE() { return (int)8192L; }

    static final int MOUSEEVENTF_VIRTUALDESK() { return (int)16384L; }

    static final int MOUSEEVENTF_ABSOLUTE() { return (int)32768L; }

    static final int INPUT_MOUSE() { return (int)0L; }

    static final int INPUT_KEYBOARD() { return (int)1L; }

    static final int INPUT_HARDWARE() { return (int)2L; }

    static final int TOUCHEVENTF_MOVE() { return (int)1L; }

    static final int TOUCHEVENTF_DOWN() { return (int)2L; }

    static final int TOUCHEVENTF_UP() { return (int)4L; }

    static final int TOUCHEVENTF_INRANGE() { return (int)8L; }

    static final int TOUCHEVENTF_PRIMARY() { return (int)16L; }

    static final int TOUCHEVENTF_NOCOALESCE() { return (int)32L; }

    static final int TOUCHEVENTF_PEN() { return (int)64L; }

    static final int TOUCHEVENTF_PALM() { return (int)128L; }

    static final int TOUCHINPUTMASKF_TIMEFROMSYSTEM() { return (int)1L; }

    static final int TOUCHINPUTMASKF_EXTRAINFO() { return (int)2L; }

    static final int TOUCHINPUTMASKF_CONTACTAREA() { return (int)4L; }

    static final int POINTER_FLAG_NONE() { return (int)0L; }

    static final int POINTER_FLAG_NEW() { return (int)1L; }

    static final int POINTER_FLAG_INRANGE() { return (int)2L; }

    static final int POINTER_FLAG_INCONTACT() { return (int)4L; }

    static final int POINTER_FLAG_FIRSTBUTTON() { return (int)16L; }

    static final int POINTER_FLAG_SECONDBUTTON() { return (int)32L; }

    static final int POINTER_FLAG_THIRDBUTTON() { return (int)64L; }

    static final int POINTER_FLAG_FOURTHBUTTON() { return (int)128L; }

    static final int POINTER_FLAG_FIFTHBUTTON() { return (int)256L; }

    static final int POINTER_FLAG_PRIMARY() { return (int)8192L; }

    static final int POINTER_FLAG_CONFIDENCE() { return (int)16384L; }

    static final int POINTER_FLAG_CANCELED() { return (int)32768L; }

    static final int POINTER_FLAG_DOWN() { return (int)65536L; }

    static final int POINTER_FLAG_UPDATE() { return (int)131072L; }

    static final int POINTER_FLAG_UP() { return (int)262144L; }

    static final int POINTER_FLAG_WHEEL() { return (int)524288L; }

    static final int POINTER_FLAG_HWHEEL() { return (int)1048576L; }

    static final int POINTER_FLAG_CAPTURECHANGED() { return (int)2097152L; }

    static final int POINTER_FLAG_HASTRANSFORM() { return (int)4194304L; }

    static final int TOUCH_FLAG_NONE() { return (int)0L; }

    static final int TOUCH_MASK_NONE() { return (int)0L; }

    static final int TOUCH_MASK_CONTACTAREA() { return (int)1L; }

    static final int TOUCH_MASK_ORIENTATION() { return (int)2L; }

    static final int TOUCH_MASK_PRESSURE() { return (int)4L; }

    static final int PEN_FLAG_NONE() { return (int)0L; }

    static final int PEN_FLAG_BARREL() { return (int)1L; }

    static final int PEN_FLAG_INVERTED() { return (int)2L; }

    static final int PEN_FLAG_ERASER() { return (int)4L; }

    static final int PEN_MASK_NONE() { return (int)0L; }

    static final int PEN_MASK_PRESSURE() { return (int)1L; }

    static final int PEN_MASK_ROTATION() { return (int)2L; }

    static final int PEN_MASK_TILT_X() { return (int)4L; }

    static final int PEN_MASK_TILT_Y() { return (int)8L; }

    static final int POINTER_MESSAGE_FLAG_NEW() { return (int)1L; }

    static final int POINTER_MESSAGE_FLAG_INRANGE() { return (int)2L; }

    static final int POINTER_MESSAGE_FLAG_INCONTACT() { return (int)4L; }

    static final int POINTER_MESSAGE_FLAG_FIRSTBUTTON() { return (int)16L; }

    static final int POINTER_MESSAGE_FLAG_SECONDBUTTON() { return (int)32L; }

    static final int POINTER_MESSAGE_FLAG_THIRDBUTTON() { return (int)64L; }

    static final int POINTER_MESSAGE_FLAG_FOURTHBUTTON() { return (int)128L; }

    static final int POINTER_MESSAGE_FLAG_FIFTHBUTTON() { return (int)256L; }

    static final int POINTER_MESSAGE_FLAG_PRIMARY() { return (int)8192L; }

    static final int POINTER_MESSAGE_FLAG_CONFIDENCE() { return (int)16384L; }

    static final int POINTER_MESSAGE_FLAG_CANCELED() { return (int)32768L; }

    static final int MAX_TOUCH_COUNT() { return (int)256L; }

    static final int TOUCH_FEEDBACK_DEFAULT() { return (int)1L; }

    static final int TOUCH_FEEDBACK_INDIRECT() { return (int)2L; }

    static final int TOUCH_FEEDBACK_NONE() { return (int)3L; }

    static final int TOUCH_HIT_TESTING_DEFAULT() { return (int)0L; }

    static final int TOUCH_HIT_TESTING_CLIENT() { return (int)1L; }

    static final int TOUCH_HIT_TESTING_NONE() { return (int)2L; }

    static final int TOUCH_HIT_TESTING_PROXIMITY_CLOSEST() { return (int)0L; }

    static final int TOUCH_HIT_TESTING_PROXIMITY_FARTHEST() { return (int)4095L; }

    static final int GWFS_INCLUDE_ANCESTORS() { return (int)1L; }

    static final int MWMO_WAITALL() { return (int)1L; }

    static final int MWMO_ALERTABLE() { return (int)2L; }

    static final int MWMO_INPUTAVAILABLE() { return (int)4L; }

    static final int QS_KEY() { return (int)1L; }

    static final int QS_MOUSEMOVE() { return (int)2L; }

    static final int QS_MOUSEBUTTON() { return (int)4L; }

    static final int QS_POSTMESSAGE() { return (int)8L; }

    static final int QS_TIMER() { return (int)16L; }

    static final int QS_PAINT() { return (int)32L; }

    static final int QS_SENDMESSAGE() { return (int)64L; }

    static final int QS_HOTKEY() { return (int)128L; }

    static final int QS_ALLPOSTMESSAGE() { return (int)256L; }

    static final int QS_RAWINPUT() { return (int)1024L; }

    static final int QS_TOUCH() { return (int)2048L; }

    static final int QS_POINTER() { return (int)4096L; }

    static final int USER_TIMER_MAXIMUM() { return (int)2147483647L; }

    static final int USER_TIMER_MINIMUM() { return (int)10L; }

    static final int SM_CXSCREEN() { return (int)0L; }

    static final int SM_CYSCREEN() { return (int)1L; }

    static final int SM_CXVSCROLL() { return (int)2L; }

    static final int SM_CYHSCROLL() { return (int)3L; }

    static final int SM_CYCAPTION() { return (int)4L; }

    static final int SM_CXBORDER() { return (int)5L; }

    static final int SM_CYBORDER() { return (int)6L; }

    static final int SM_CXDLGFRAME() { return (int)7L; }

    static final int SM_CYDLGFRAME() { return (int)8L; }

    static final int SM_CYVTHUMB() { return (int)9L; }

    static final int SM_CXHTHUMB() { return (int)10L; }

    static final int SM_CXICON() { return (int)11L; }

    static final int SM_CYICON() { return (int)12L; }

    static final int SM_CXCURSOR() { return (int)13L; }

    static final int SM_CYCURSOR() { return (int)14L; }

    static final int SM_CYMENU() { return (int)15L; }

    static final int SM_CXFULLSCREEN() { return (int)16L; }

    static final int SM_CYFULLSCREEN() { return (int)17L; }

    static final int SM_CYKANJIWINDOW() { return (int)18L; }

    static final int SM_MOUSEPRESENT() { return (int)19L; }

    static final int SM_CYVSCROLL() { return (int)20L; }

    static final int SM_CXHSCROLL() { return (int)21L; }

    static final int SM_DEBUG() { return (int)22L; }

    static final int SM_SWAPBUTTON() { return (int)23L; }

    static final int SM_RESERVED1() { return (int)24L; }

    static final int SM_RESERVED2() { return (int)25L; }

    static final int SM_RESERVED3() { return (int)26L; }

    static final int SM_RESERVED4() { return (int)27L; }

    static final int SM_CXMIN() { return (int)28L; }

    static final int SM_CYMIN() { return (int)29L; }

    static final int SM_CXSIZE() { return (int)30L; }

    static final int SM_CYSIZE() { return (int)31L; }

    static final int SM_CXFRAME() { return (int)32L; }

    static final int SM_CYFRAME() { return (int)33L; }

    static final int SM_CXMINTRACK() { return (int)34L; }

    static final int SM_CYMINTRACK() { return (int)35L; }

    static final int SM_CXDOUBLECLK() { return (int)36L; }

    static final int SM_CYDOUBLECLK() { return (int)37L; }

    static final int SM_CXICONSPACING() { return (int)38L; }

    static final int SM_CYICONSPACING() { return (int)39L; }

    static final int SM_MENUDROPALIGNMENT() { return (int)40L; }

    static final int SM_PENWINDOWS() { return (int)41L; }

    static final int SM_DBCSENABLED() { return (int)42L; }

    static final int SM_CMOUSEBUTTONS() { return (int)43L; }

    static final int SM_SECURE() { return (int)44L; }

    static final int SM_CXEDGE() { return (int)45L; }

    static final int SM_CYEDGE() { return (int)46L; }

    static final int SM_CXMINSPACING() { return (int)47L; }

    static final int SM_CYMINSPACING() { return (int)48L; }

    static final int SM_CXSMICON() { return (int)49L; }

    static final int SM_CYSMICON() { return (int)50L; }

    static final int SM_CYSMCAPTION() { return (int)51L; }

    static final int SM_CXSMSIZE() { return (int)52L; }

    static final int SM_CYSMSIZE() { return (int)53L; }

    static final int SM_CXMENUSIZE() { return (int)54L; }

    static final int SM_CYMENUSIZE() { return (int)55L; }

    static final int SM_ARRANGE() { return (int)56L; }

    static final int SM_CXMINIMIZED() { return (int)57L; }

    static final int SM_CYMINIMIZED() { return (int)58L; }

    static final int SM_CXMAXTRACK() { return (int)59L; }

    static final int SM_CYMAXTRACK() { return (int)60L; }

    static final int SM_CXMAXIMIZED() { return (int)61L; }

    static final int SM_CYMAXIMIZED() { return (int)62L; }

    static final int SM_NETWORK() { return (int)63L; }

    static final int SM_CLEANBOOT() { return (int)67L; }

    static final int SM_CXDRAG() { return (int)68L; }

    static final int SM_CYDRAG() { return (int)69L; }

    static final int SM_SHOWSOUNDS() { return (int)70L; }

    static final int SM_CXMENUCHECK() { return (int)71L; }

    static final int SM_CYMENUCHECK() { return (int)72L; }

    static final int SM_SLOWMACHINE() { return (int)73L; }

    static final int SM_MIDEASTENABLED() { return (int)74L; }

    static final int SM_MOUSEWHEELPRESENT() { return (int)75L; }

    static final int SM_XVIRTUALSCREEN() { return (int)76L; }

    static final int SM_YVIRTUALSCREEN() { return (int)77L; }

    static final int SM_CXVIRTUALSCREEN() { return (int)78L; }

    static final int SM_CYVIRTUALSCREEN() { return (int)79L; }

    static final int SM_CMONITORS() { return (int)80L; }

    static final int SM_SAMEDISPLAYFORMAT() { return (int)81L; }

    static final int SM_IMMENABLED() { return (int)82L; }

    static final int SM_CXFOCUSBORDER() { return (int)83L; }

    static final int SM_CYFOCUSBORDER() { return (int)84L; }

    static final int SM_TABLETPC() { return (int)86L; }

    static final int SM_MEDIACENTER() { return (int)87L; }

    static final int SM_STARTER() { return (int)88L; }

    static final int SM_SERVERR2() { return (int)89L; }

    static final int SM_MOUSEHORIZONTALWHEELPRESENT() { return (int)91L; }

    static final int SM_CXPADDEDBORDER() { return (int)92L; }

    static final int SM_DIGITIZER() { return (int)94L; }

    static final int SM_MAXIMUMTOUCHES() { return (int)95L; }

    static final int SM_CMETRICS() { return (int)97L; }

    static final int SM_REMOTESESSION() { return (int)4096L; }

    static final int SM_SHUTTINGDOWN() { return (int)8192L; }

    static final int SM_REMOTECONTROL() { return (int)8193L; }

    static final int SM_CARETBLINKINGENABLED() { return (int)8194L; }

    static final int SM_CONVERTIBLESLATEMODE() { return (int)8195L; }

    static final int SM_SYSTEMDOCKED() { return (int)8196L; }

    static final int PMB_ACTIVE() { return (int)1L; }

    static final int MNC_IGNORE() { return (int)0L; }

    static final int MNC_CLOSE() { return (int)1L; }

    static final int MNC_EXECUTE() { return (int)2L; }

    static final int MNC_SELECT() { return (int)3L; }

    static final int MNS_MODELESS() { return (int)1073741824L; }

    static final int MNS_DRAGDROP() { return (int)536870912L; }

    static final int MNS_AUTODISMISS() { return (int)268435456L; }

    static final int MNS_NOTIFYBYPOS() { return (int)134217728L; }

    static final int MNS_CHECKORBMP() { return (int)67108864L; }

    static final int MIM_MAXHEIGHT() { return (int)1L; }

    static final int MIM_BACKGROUND() { return (int)2L; }

    static final int MIM_HELPID() { return (int)4L; }

    static final int MIM_MENUDATA() { return (int)8L; }

    static final int MIM_STYLE() { return (int)16L; }

    static final int MND_CONTINUE() { return (int)0L; }

    static final int MND_ENDMENU() { return (int)1L; }

    static final int MNGOF_TOPGAP() { return (int)1L; }

    static final int MNGOF_BOTTOMGAP() { return (int)2L; }

    static final int MNGO_NOINTERFACE() { return (int)0L; }

    static final int MNGO_NOERROR() { return (int)1L; }

    static final int MIIM_STATE() { return (int)1L; }

    static final int MIIM_ID() { return (int)2L; }

    static final int MIIM_SUBMENU() { return (int)4L; }

    static final int MIIM_CHECKMARKS() { return (int)8L; }

    static final int MIIM_TYPE() { return (int)16L; }

    static final int MIIM_DATA() { return (int)32L; }

    static final int MIIM_STRING() { return (int)64L; }

    static final int MIIM_BITMAP() { return (int)128L; }

    static final int MIIM_FTYPE() { return (int)256L; }

    static final int DOF_EXECUTABLE() { return (int)32769L; }

    static final int DOF_DOCUMENT() { return (int)32770L; }

    static final int DOF_DIRECTORY() { return (int)32771L; }

    static final int DOF_MULTIPLE() { return (int)32772L; }

    static final int DOF_PROGMAN() { return (int)1L; }

    static final int DOF_SHELLDATA() { return (int)2L; }

    static final int DT_TOP() { return (int)0L; }

    static final int DT_LEFT() { return (int)0L; }

    static final int DT_CENTER() { return (int)1L; }

    static final int DT_RIGHT() { return (int)2L; }

    static final int DT_VCENTER() { return (int)4L; }

    static final int DT_BOTTOM() { return (int)8L; }

    static final int DT_WORDBREAK() { return (int)16L; }

    static final int DT_SINGLELINE() { return (int)32L; }

    static final int DT_EXPANDTABS() { return (int)64L; }

    static final int DT_TABSTOP() { return (int)128L; }

    static final int DT_NOCLIP() { return (int)256L; }

    static final int DT_EXTERNALLEADING() { return (int)512L; }

    static final int DT_CALCRECT() { return (int)1024L; }

    static final int DT_NOPREFIX() { return (int)2048L; }

    static final int DT_INTERNAL() { return (int)4096L; }

    static final int DT_EDITCONTROL() { return (int)8192L; }

    static final int DT_PATH_ELLIPSIS() { return (int)16384L; }

    static final int DT_END_ELLIPSIS() { return (int)32768L; }

    static final int DT_MODIFYSTRING() { return (int)65536L; }

    static final int DT_RTLREADING() { return (int)131072L; }

    static final int DT_WORD_ELLIPSIS() { return (int)262144L; }

    static final int DT_NOFULLWIDTHCHARBREAK() { return (int)524288L; }

    static final int DT_HIDEPREFIX() { return (int)1048576L; }

    static final int DT_PREFIXONLY() { return (int)2097152L; }

    static final int DST_COMPLEX() { return (int)0L; }

    static final int DST_TEXT() { return (int)1L; }

    static final int DST_PREFIXTEXT() { return (int)2L; }

    static final int DST_ICON() { return (int)3L; }

    static final int DST_BITMAP() { return (int)4L; }

    static final int DSS_NORMAL() { return (int)0L; }

    static final int DSS_UNION() { return (int)16L; }

    static final int DSS_DISABLED() { return (int)32L; }

    static final int DSS_MONO() { return (int)128L; }

    static final int DSS_HIDEPREFIX() { return (int)512L; }

    static final int DSS_PREFIXONLY() { return (int)1024L; }

    static final int DSS_RIGHT() { return (int)32768L; }

    static final int LSFW_LOCK() { return (int)1L; }

    static final int LSFW_UNLOCK() { return (int)2L; }

    static final int RDW_INVALIDATE() { return (int)1L; }

    static final int RDW_INTERNALPAINT() { return (int)2L; }

    static final int RDW_ERASE() { return (int)4L; }

    static final int RDW_VALIDATE() { return (int)8L; }

    static final int RDW_NOINTERNALPAINT() { return (int)16L; }

    static final int RDW_NOERASE() { return (int)32L; }

    static final int RDW_NOCHILDREN() { return (int)64L; }

    static final int RDW_ALLCHILDREN() { return (int)128L; }

    static final int RDW_UPDATENOW() { return (int)256L; }

    static final int RDW_ERASENOW() { return (int)512L; }

    static final int RDW_FRAME() { return (int)1024L; }

    static final int RDW_NOFRAME() { return (int)2048L; }

    static final int SW_SCROLLCHILDREN() { return (int)1L; }

    static final int SW_INVALIDATE() { return (int)2L; }

    static final int SW_ERASE() { return (int)4L; }

    static final int SW_SMOOTHSCROLL() { return (int)16L; }

    static final int ESB_ENABLE_BOTH() { return (int)0L; }

    static final int ESB_DISABLE_BOTH() { return (int)3L; }

    static final int ESB_DISABLE_LEFT() { return (int)1L; }

    static final int ESB_DISABLE_RIGHT() { return (int)2L; }

    static final int ESB_DISABLE_UP() { return (int)1L; }

    static final int ESB_DISABLE_DOWN() { return (int)2L; }

    static final int HELPINFO_WINDOW() { return (int)1L; }

    static final int HELPINFO_MENUITEM() { return (int)2L; }

    static final int CWP_ALL() { return (int)0L; }

    static final int CWP_SKIPINVISIBLE() { return (int)1L; }

    static final int CWP_SKIPDISABLED() { return (int)2L; }

    static final int CWP_SKIPTRANSPARENT() { return (int)4L; }

    static final int CTLCOLOR_MSGBOX() { return (int)0L; }

    static final int CTLCOLOR_EDIT() { return (int)1L; }

    static final int CTLCOLOR_LISTBOX() { return (int)2L; }

    static final int CTLCOLOR_BTN() { return (int)3L; }

    static final int CTLCOLOR_DLG() { return (int)4L; }

    static final int CTLCOLOR_SCROLLBAR() { return (int)5L; }

    static final int CTLCOLOR_STATIC() { return (int)6L; }

    static final int CTLCOLOR_MAX() { return (int)7L; }

    static final int COLOR_SCROLLBAR() { return (int)0L; }

    static final int COLOR_BACKGROUND() { return (int)1L; }

    static final int COLOR_ACTIVECAPTION() { return (int)2L; }

    static final int COLOR_INACTIVECAPTION() { return (int)3L; }

    static final int COLOR_MENU() { return (int)4L; }

    static final int COLOR_WINDOW() { return (int)5L; }

    static final int COLOR_WINDOWFRAME() { return (int)6L; }

    static final int COLOR_MENUTEXT() { return (int)7L; }

    static final int COLOR_WINDOWTEXT() { return (int)8L; }

    static final int COLOR_CAPTIONTEXT() { return (int)9L; }

    static final int COLOR_ACTIVEBORDER() { return (int)10L; }

    static final int COLOR_INACTIVEBORDER() { return (int)11L; }

    static final int COLOR_APPWORKSPACE() { return (int)12L; }

    static final int COLOR_HIGHLIGHT() { return (int)13L; }

    static final int COLOR_HIGHLIGHTTEXT() { return (int)14L; }

    static final int COLOR_BTNFACE() { return (int)15L; }

    static final int COLOR_BTNSHADOW() { return (int)16L; }

    static final int COLOR_GRAYTEXT() { return (int)17L; }

    static final int COLOR_BTNTEXT() { return (int)18L; }

    static final int COLOR_INACTIVECAPTIONTEXT() { return (int)19L; }

    static final int COLOR_BTNHIGHLIGHT() { return (int)20L; }

    static final int COLOR_3DDKSHADOW() { return (int)21L; }

    static final int COLOR_3DLIGHT() { return (int)22L; }

    static final int COLOR_INFOTEXT() { return (int)23L; }

    static final int COLOR_INFOBK() { return (int)24L; }

    static final int COLOR_HOTLIGHT() { return (int)26L; }

    static final int COLOR_GRADIENTACTIVECAPTION() { return (int)27L; }

    static final int COLOR_GRADIENTINACTIVECAPTION() { return (int)28L; }

    static final int COLOR_MENUHILIGHT() { return (int)29L; }

    static final int COLOR_MENUBAR() { return (int)30L; }

    static final int GW_HWNDFIRST() { return (int)0L; }

    static final int GW_HWNDLAST() { return (int)1L; }

    static final int GW_HWNDNEXT() { return (int)2L; }

    static final int GW_HWNDPREV() { return (int)3L; }

    static final int GW_OWNER() { return (int)4L; }

    static final int GW_CHILD() { return (int)5L; }

    static final int GW_ENABLEDPOPUP() { return (int)6L; }

    static final int GW_MAX() { return (int)6L; }

    static final int SC_SIZE() { return (int)61440L; }

    static final int SC_MOVE() { return (int)61456L; }

    static final int SC_MINIMIZE() { return (int)61472L; }

    static final int SC_MAXIMIZE() { return (int)61488L; }

    static final int SC_NEXTWINDOW() { return (int)61504L; }

    static final int SC_PREVWINDOW() { return (int)61520L; }

    static final int SC_CLOSE() { return (int)61536L; }

    static final int SC_VSCROLL() { return (int)61552L; }

    static final int SC_HSCROLL() { return (int)61568L; }

    static final int SC_MOUSEMENU() { return (int)61584L; }

    static final int SC_KEYMENU() { return (int)61696L; }

    static final int SC_ARRANGE() { return (int)61712L; }

    static final int SC_RESTORE() { return (int)61728L; }

    static final int SC_TASKLIST() { return (int)61744L; }

    static final int SC_SCREENSAVE() { return (int)61760L; }

    static final int SC_HOTKEY() { return (int)61776L; }

    static final int SC_DEFAULT() { return (int)61792L; }

    static final int SC_MONITORPOWER() { return (int)61808L; }

    static final int SC_CONTEXTHELP() { return (int)61824L; }

    static final int SC_SEPARATOR() { return (int)61455L; }

    static final int SCF_ISSECURE() { return (int)1L; }

    static final int IMAGE_BITMAP() { return (int)0L; }

    static final int IMAGE_ICON() { return (int)1L; }

    static final int IMAGE_CURSOR() { return (int)2L; }

    static final int IMAGE_ENHMETAFILE() { return (int)3L; }

    static final int LR_DEFAULTCOLOR() { return (int)0L; }

    static final int LR_MONOCHROME() { return (int)1L; }

    static final int LR_COLOR() { return (int)2L; }

    static final int LR_COPYRETURNORG() { return (int)4L; }

    static final int LR_COPYDELETEORG() { return (int)8L; }

    static final int LR_LOADFROMFILE() { return (int)16L; }

    static final int LR_LOADTRANSPARENT() { return (int)32L; }

    static final int LR_DEFAULTSIZE() { return (int)64L; }

    static final int LR_VGACOLOR() { return (int)128L; }

    static final int LR_LOADMAP3DCOLORS() { return (int)4096L; }

    static final int LR_CREATEDIBSECTION() { return (int)8192L; }

    static final int LR_COPYFROMRESOURCE() { return (int)16384L; }

    static final int LR_SHARED() { return (int)32768L; }

    static final int DI_MASK() { return (int)1L; }

    static final int DI_IMAGE() { return (int)2L; }

    static final int DI_NORMAL() { return (int)3L; }

    static final int DI_COMPAT() { return (int)4L; }

    static final int DI_DEFAULTSIZE() { return (int)8L; }

    static final int DI_NOMIRROR() { return (int)16L; }

    static final int RES_ICON() { return (int)1L; }

    static final int RES_CURSOR() { return (int)2L; }

    static final int ORD_LANGDRIVER() { return (int)1L; }

    static final int IDOK() { return (int)1L; }

    static final int IDCANCEL() { return (int)2L; }

    static final int IDABORT() { return (int)3L; }

    static final int IDRETRY() { return (int)4L; }

    static final int IDIGNORE() { return (int)5L; }

    static final int IDYES() { return (int)6L; }

    static final int IDNO() { return (int)7L; }

    static final int IDCLOSE() { return (int)8L; }

    static final int IDHELP() { return (int)9L; }

    static final int IDTRYAGAIN() { return (int)10L; }

    static final int IDCONTINUE() { return (int)11L; }

    static final int IDTIMEOUT() { return (int)32000L; }

    static final int EN_SETFOCUS() { return (int)256L; }

    static final int EN_KILLFOCUS() { return (int)512L; }

    static final int EN_CHANGE() { return (int)768L; }

    static final int EN_UPDATE() { return (int)1024L; }

    static final int EN_ERRSPACE() { return (int)1280L; }

    static final int EN_MAXTEXT() { return (int)1281L; }

    static final int EN_HSCROLL() { return (int)1537L; }

    static final int EN_VSCROLL() { return (int)1538L; }

    static final int EN_ALIGN_LTR_EC() { return (int)1792L; }

    static final int EN_ALIGN_RTL_EC() { return (int)1793L; }

    static final int EN_BEFORE_PASTE() { return (int)2048L; }

    static final int EN_AFTER_PASTE() { return (int)2049L; }

    static final int EC_LEFTMARGIN() { return (int)1L; }

    static final int EC_RIGHTMARGIN() { return (int)2L; }

    static final int EC_USEFONTINFO() { return (int)65535L; }

    static final int EMSIS_COMPOSITIONSTRING() { return (int)1L; }

    static final int EIMES_GETCOMPSTRATONCE() { return (int)1L; }

    static final int EIMES_CANCELCOMPSTRINFOCUS() { return (int)2L; }

    static final int EIMES_COMPLETECOMPSTRKILLFOCUS() { return (int)4L; }

    static final int EM_GETSEL() { return (int)176L; }

    static final int EM_SETSEL() { return (int)177L; }

    static final int EM_GETRECT() { return (int)178L; }

    static final int EM_SETRECT() { return (int)179L; }

    static final int EM_SETRECTNP() { return (int)180L; }

    static final int EM_SCROLL() { return (int)181L; }

    static final int EM_LINESCROLL() { return (int)182L; }

    static final int EM_SCROLLCARET() { return (int)183L; }

    static final int EM_GETMODIFY() { return (int)184L; }

    static final int EM_SETMODIFY() { return (int)185L; }

    static final int EM_GETLINECOUNT() { return (int)186L; }

    static final int EM_LINEINDEX() { return (int)187L; }

    static final int EM_SETHANDLE() { return (int)188L; }

    static final int EM_GETHANDLE() { return (int)189L; }

    static final int EM_GETTHUMB() { return (int)190L; }

    static final int EM_LINELENGTH() { return (int)193L; }

    static final int EM_REPLACESEL() { return (int)194L; }

    static final int EM_GETLINE() { return (int)196L; }

    static final int EM_LIMITTEXT() { return (int)197L; }

    static final int EM_CANUNDO() { return (int)198L; }

    static final int EM_UNDO() { return (int)199L; }

    static final int EM_FMTLINES() { return (int)200L; }

    static final int EM_LINEFROMCHAR() { return (int)201L; }

    static final int EM_SETTABSTOPS() { return (int)203L; }

    static final int EM_SETPASSWORDCHAR() { return (int)204L; }

    static final int EM_EMPTYUNDOBUFFER() { return (int)205L; }

    static final int EM_GETFIRSTVISIBLELINE() { return (int)206L; }

    static final int EM_SETREADONLY() { return (int)207L; }

    static final int EM_SETWORDBREAKPROC() { return (int)208L; }

    static final int EM_GETWORDBREAKPROC() { return (int)209L; }

    static final int EM_GETPASSWORDCHAR() { return (int)210L; }

    static final int EM_SETMARGINS() { return (int)211L; }

    static final int EM_GETMARGINS() { return (int)212L; }

    static final int EM_GETLIMITTEXT() { return (int)213L; }

    static final int EM_POSFROMCHAR() { return (int)214L; }

    static final int EM_CHARFROMPOS() { return (int)215L; }

    static final int EM_SETIMESTATUS() { return (int)216L; }

    static final int EM_GETIMESTATUS() { return (int)217L; }

    static final int EM_ENABLEFEATURE() { return (int)218L; }

    static final int WB_LEFT() { return (int)0L; }

    static final int WB_RIGHT() { return (int)1L; }

    static final int WB_ISDELIMITER() { return (int)2L; }

    static final int BN_CLICKED() { return (int)0L; }

    static final int BN_PAINT() { return (int)1L; }

    static final int BN_HILITE() { return (int)2L; }

    static final int BN_UNHILITE() { return (int)3L; }

    static final int BN_DISABLE() { return (int)4L; }

    static final int BN_DOUBLECLICKED() { return (int)5L; }

    static final int BN_SETFOCUS() { return (int)6L; }

    static final int BN_KILLFOCUS() { return (int)7L; }

    static final int BM_GETCHECK() { return (int)240L; }

    static final int BM_SETCHECK() { return (int)241L; }

    static final int BM_GETSTATE() { return (int)242L; }

    static final int BM_SETSTATE() { return (int)243L; }

    static final int BM_SETSTYLE() { return (int)244L; }

    static final int BM_CLICK() { return (int)245L; }

    static final int BM_GETIMAGE() { return (int)246L; }

    static final int BM_SETIMAGE() { return (int)247L; }

    static final int BM_SETDONTCLICK() { return (int)248L; }

    static final int BST_UNCHECKED() { return (int)0L; }

    static final int BST_CHECKED() { return (int)1L; }

    static final int BST_INDETERMINATE() { return (int)2L; }

    static final int BST_PUSHED() { return (int)4L; }

    static final int BST_FOCUS() { return (int)8L; }

    static final int STM_SETICON() { return (int)368L; }

    static final int STM_GETICON() { return (int)369L; }

    static final int STM_SETIMAGE() { return (int)370L; }

    static final int STM_GETIMAGE() { return (int)371L; }

    static final int STN_CLICKED() { return (int)0L; }

    static final int STN_DBLCLK() { return (int)1L; }

    static final int STN_ENABLE() { return (int)2L; }

    static final int STN_DISABLE() { return (int)3L; }

    static final int STM_MSGMAX() { return (int)372L; }

    static final int DWL_MSGRESULT() { return (int)0L; }

    static final int DWL_DLGPROC() { return (int)4L; }

    static final int DWL_USER() { return (int)8L; }

    static final int DWLP_MSGRESULT() { return (int)0L; }

    static final int DDL_READWRITE() { return (int)0L; }

    static final int DDL_READONLY() { return (int)1L; }

    static final int DDL_HIDDEN() { return (int)2L; }

    static final int DDL_SYSTEM() { return (int)4L; }

    static final int DDL_DIRECTORY() { return (int)16L; }

    static final int DDL_ARCHIVE() { return (int)32L; }

    static final int DDL_POSTMSGS() { return (int)8192L; }

    static final int DDL_DRIVES() { return (int)16384L; }

    static final int DDL_EXCLUSIVE() { return (int)32768L; }

    static final int DC_HASDEFID() { return (int)21323L; }

    static final int DLGC_WANTARROWS() { return (int)1L; }

    static final int DLGC_WANTTAB() { return (int)2L; }

    static final int DLGC_WANTALLKEYS() { return (int)4L; }

    static final int DLGC_WANTMESSAGE() { return (int)4L; }

    static final int DLGC_HASSETSEL() { return (int)8L; }

    static final int DLGC_DEFPUSHBUTTON() { return (int)16L; }

    static final int DLGC_UNDEFPUSHBUTTON() { return (int)32L; }

    static final int DLGC_RADIOBUTTON() { return (int)64L; }

    static final int DLGC_WANTCHARS() { return (int)128L; }

    static final int DLGC_STATIC() { return (int)256L; }

    static final int DLGC_BUTTON() { return (int)8192L; }

    static final int LB_OKAY() { return (int)0L; }

    static final int LBN_SELCHANGE() { return (int)1L; }

    static final int LBN_DBLCLK() { return (int)2L; }

    static final int LBN_SELCANCEL() { return (int)3L; }

    static final int LBN_SETFOCUS() { return (int)4L; }

    static final int LBN_KILLFOCUS() { return (int)5L; }

    static final int LB_ADDSTRING() { return (int)384L; }

    static final int LB_INSERTSTRING() { return (int)385L; }

    static final int LB_DELETESTRING() { return (int)386L; }

    static final int LB_SELITEMRANGEEX() { return (int)387L; }

    static final int LB_RESETCONTENT() { return (int)388L; }

    static final int LB_SETSEL() { return (int)389L; }

    static final int LB_SETCURSEL() { return (int)390L; }

    static final int LB_GETSEL() { return (int)391L; }

    static final int LB_GETCURSEL() { return (int)392L; }

    static final int LB_GETTEXT() { return (int)393L; }

    static final int LB_GETTEXTLEN() { return (int)394L; }

    static final int LB_GETCOUNT() { return (int)395L; }

    static final int LB_SELECTSTRING() { return (int)396L; }

    static final int LB_DIR() { return (int)397L; }

    static final int LB_GETTOPINDEX() { return (int)398L; }

    static final int LB_FINDSTRING() { return (int)399L; }

    static final int LB_GETSELCOUNT() { return (int)400L; }

    static final int LB_GETSELITEMS() { return (int)401L; }

    static final int LB_SETTABSTOPS() { return (int)402L; }

    static final int LB_GETHORIZONTALEXTENT() { return (int)403L; }

    static final int LB_SETHORIZONTALEXTENT() { return (int)404L; }

    static final int LB_SETCOLUMNWIDTH() { return (int)405L; }

    static final int LB_ADDFILE() { return (int)406L; }

    static final int LB_SETTOPINDEX() { return (int)407L; }

    static final int LB_GETITEMRECT() { return (int)408L; }

    static final int LB_GETITEMDATA() { return (int)409L; }

    static final int LB_SETITEMDATA() { return (int)410L; }

    static final int LB_SELITEMRANGE() { return (int)411L; }

    static final int LB_SETANCHORINDEX() { return (int)412L; }

    static final int LB_GETANCHORINDEX() { return (int)413L; }

    static final int LB_SETCARETINDEX() { return (int)414L; }

    static final int LB_GETCARETINDEX() { return (int)415L; }

    static final int LB_SETITEMHEIGHT() { return (int)416L; }

    static final int LB_GETITEMHEIGHT() { return (int)417L; }

    static final int LB_FINDSTRINGEXACT() { return (int)418L; }

    static final int LB_SETLOCALE() { return (int)421L; }

    static final int LB_GETLOCALE() { return (int)422L; }

    static final int LB_SETCOUNT() { return (int)423L; }

    static final int LB_INITSTORAGE() { return (int)424L; }

    static final int LB_ITEMFROMPOINT() { return (int)425L; }

    static final int LB_GETLISTBOXINFO() { return (int)434L; }

    static final int LB_MSGMAX() { return (int)435L; }

    static final int CB_OKAY() { return (int)0L; }

    static final int CBN_SELCHANGE() { return (int)1L; }

    static final int CBN_DBLCLK() { return (int)2L; }

    static final int CBN_SETFOCUS() { return (int)3L; }

    static final int CBN_KILLFOCUS() { return (int)4L; }

    static final int CBN_EDITCHANGE() { return (int)5L; }

    static final int CBN_EDITUPDATE() { return (int)6L; }

    static final int CBN_DROPDOWN() { return (int)7L; }

    static final int CBN_CLOSEUP() { return (int)8L; }

    static final int CBN_SELENDOK() { return (int)9L; }

    static final int CBN_SELENDCANCEL() { return (int)10L; }

    static final int CB_GETEDITSEL() { return (int)320L; }

    static final int CB_LIMITTEXT() { return (int)321L; }

    static final int CB_SETEDITSEL() { return (int)322L; }

    static final int CB_ADDSTRING() { return (int)323L; }

    static final int CB_DELETESTRING() { return (int)324L; }

    static final int CB_DIR() { return (int)325L; }

    static final int CB_GETCOUNT() { return (int)326L; }

    static final int CB_GETCURSEL() { return (int)327L; }

    static final int CB_GETLBTEXT() { return (int)328L; }

    static final int CB_GETLBTEXTLEN() { return (int)329L; }

    static final int CB_INSERTSTRING() { return (int)330L; }

    static final int CB_RESETCONTENT() { return (int)331L; }

    static final int CB_FINDSTRING() { return (int)332L; }

    static final int CB_SELECTSTRING() { return (int)333L; }

    static final int CB_SETCURSEL() { return (int)334L; }

    static final int CB_SHOWDROPDOWN() { return (int)335L; }

    static final int CB_GETITEMDATA() { return (int)336L; }

    static final int CB_SETITEMDATA() { return (int)337L; }

    static final int CB_GETDROPPEDCONTROLRECT() { return (int)338L; }

    static final int CB_SETITEMHEIGHT() { return (int)339L; }

    static final int CB_GETITEMHEIGHT() { return (int)340L; }

    static final int CB_SETEXTENDEDUI() { return (int)341L; }

    static final int CB_GETEXTENDEDUI() { return (int)342L; }

    static final int CB_GETDROPPEDSTATE() { return (int)343L; }

    static final int CB_FINDSTRINGEXACT() { return (int)344L; }

    static final int CB_SETLOCALE() { return (int)345L; }

    static final int CB_GETLOCALE() { return (int)346L; }

    static final int CB_GETTOPINDEX() { return (int)347L; }

    static final int CB_SETTOPINDEX() { return (int)348L; }

    static final int CB_GETHORIZONTALEXTENT() { return (int)349L; }

    static final int CB_SETHORIZONTALEXTENT() { return (int)350L; }

    static final int CB_GETDROPPEDWIDTH() { return (int)351L; }

    static final int CB_SETDROPPEDWIDTH() { return (int)352L; }

    static final int CB_INITSTORAGE() { return (int)353L; }

    static final int CB_GETCOMBOBOXINFO() { return (int)356L; }

    static final int CB_MSGMAX() { return (int)357L; }

    static final int SBM_SETPOS() { return (int)224L; }

    static final int SBM_GETPOS() { return (int)225L; }

    static final int SBM_SETRANGE() { return (int)226L; }

    static final int SBM_SETRANGEREDRAW() { return (int)230L; }

    static final int SBM_GETRANGE() { return (int)227L; }

    static final int SBM_ENABLE_ARROWS() { return (int)228L; }

    static final int SBM_SETSCROLLINFO() { return (int)233L; }

    static final int SBM_GETSCROLLINFO() { return (int)234L; }

    static final int SBM_GETSCROLLBARINFO() { return (int)235L; }

    static final int SIF_RANGE() { return (int)1L; }

    static final int SIF_PAGE() { return (int)2L; }

    static final int SIF_POS() { return (int)4L; }

    static final int SIF_DISABLENOSCROLL() { return (int)8L; }

    static final int SIF_TRACKPOS() { return (int)16L; }

    static final int MDIS_ALLCHILDSTYLES() { return (int)1L; }

    static final int MDITILE_VERTICAL() { return (int)0L; }

    static final int MDITILE_HORIZONTAL() { return (int)1L; }

    static final int MDITILE_SKIPDISABLED() { return (int)2L; }

    static final int MDITILE_ZORDER() { return (int)4L; }

    static final int HELP_CONTEXTMENU() { return (int)10L; }

    static final int HELP_FINDER() { return (int)11L; }

    static final int HELP_WM_HELP() { return (int)12L; }

    static final int HELP_SETPOPUP_POS() { return (int)13L; }

    static final int HELP_TCARD() { return (int)32768L; }

    static final int HELP_TCARD_DATA() { return (int)16L; }

    static final int HELP_TCARD_OTHER_CALLER() { return (int)17L; }

    static final int IDH_NO_HELP() { return (int)28440L; }

    static final int IDH_MISSING_CONTEXT() { return (int)28441L; }

    static final int IDH_GENERIC_HELP_BUTTON() { return (int)28442L; }

    static final int IDH_OK() { return (int)28443L; }

    static final int IDH_CANCEL() { return (int)28444L; }

    static final int IDH_HELP() { return (int)28445L; }

    static final int GR_GDIOBJECTS() { return (int)0L; }

    static final int GR_USEROBJECTS() { return (int)1L; }

    static final int GR_GDIOBJECTS_PEAK() { return (int)2L; }

    static final int GR_USEROBJECTS_PEAK() { return (int)4L; }

    static final int SPI_GETBEEP() { return (int)1L; }

    static final int SPI_SETBEEP() { return (int)2L; }

    static final int SPI_GETMOUSE() { return (int)3L; }

    static final int SPI_SETMOUSE() { return (int)4L; }

    static final int SPI_GETBORDER() { return (int)5L; }

    static final int SPI_SETBORDER() { return (int)6L; }

    static final int SPI_GETKEYBOARDSPEED() { return (int)10L; }

    static final int SPI_SETKEYBOARDSPEED() { return (int)11L; }

    static final int SPI_LANGDRIVER() { return (int)12L; }

    static final int SPI_ICONHORIZONTALSPACING() { return (int)13L; }

    static final int SPI_GETSCREENSAVETIMEOUT() { return (int)14L; }

    static final int SPI_SETSCREENSAVETIMEOUT() { return (int)15L; }

    static final int SPI_GETSCREENSAVEACTIVE() { return (int)16L; }

    static final int SPI_SETSCREENSAVEACTIVE() { return (int)17L; }

    static final int SPI_GETGRIDGRANULARITY() { return (int)18L; }

    static final int SPI_SETGRIDGRANULARITY() { return (int)19L; }

    static final int SPI_SETDESKWALLPAPER() { return (int)20L; }

    static final int SPI_SETDESKPATTERN() { return (int)21L; }

    static final int SPI_GETKEYBOARDDELAY() { return (int)22L; }

    static final int SPI_SETKEYBOARDDELAY() { return (int)23L; }

    static final int SPI_ICONVERTICALSPACING() { return (int)24L; }

    static final int SPI_GETICONTITLEWRAP() { return (int)25L; }

    static final int SPI_SETICONTITLEWRAP() { return (int)26L; }

    static final int SPI_GETMENUDROPALIGNMENT() { return (int)27L; }

    static final int SPI_SETMENUDROPALIGNMENT() { return (int)28L; }

    static final int SPI_SETDOUBLECLKWIDTH() { return (int)29L; }

    static final int SPI_SETDOUBLECLKHEIGHT() { return (int)30L; }

    static final int SPI_GETICONTITLELOGFONT() { return (int)31L; }

    static final int SPI_SETDOUBLECLICKTIME() { return (int)32L; }

    static final int SPI_SETMOUSEBUTTONSWAP() { return (int)33L; }

    static final int SPI_SETICONTITLELOGFONT() { return (int)34L; }

    static final int SPI_GETFASTTASKSWITCH() { return (int)35L; }

    static final int SPI_SETFASTTASKSWITCH() { return (int)36L; }

    static final int SPI_SETDRAGFULLWINDOWS() { return (int)37L; }

    static final int SPI_GETDRAGFULLWINDOWS() { return (int)38L; }

    static final int SPI_GETNONCLIENTMETRICS() { return (int)41L; }

    static final int SPI_SETNONCLIENTMETRICS() { return (int)42L; }

    static final int SPI_GETMINIMIZEDMETRICS() { return (int)43L; }

    static final int SPI_SETMINIMIZEDMETRICS() { return (int)44L; }

    static final int SPI_GETICONMETRICS() { return (int)45L; }

    static final int SPI_SETICONMETRICS() { return (int)46L; }

    static final int SPI_SETWORKAREA() { return (int)47L; }

    static final int SPI_GETWORKAREA() { return (int)48L; }

    static final int SPI_SETPENWINDOWS() { return (int)49L; }

    static final int SPI_GETHIGHCONTRAST() { return (int)66L; }

    static final int SPI_SETHIGHCONTRAST() { return (int)67L; }

    static final int SPI_GETKEYBOARDPREF() { return (int)68L; }

    static final int SPI_SETKEYBOARDPREF() { return (int)69L; }

    static final int SPI_GETSCREENREADER() { return (int)70L; }

    static final int SPI_SETSCREENREADER() { return (int)71L; }

    static final int SPI_GETANIMATION() { return (int)72L; }

    static final int SPI_SETANIMATION() { return (int)73L; }

    static final int SPI_GETFONTSMOOTHING() { return (int)74L; }

    static final int SPI_SETFONTSMOOTHING() { return (int)75L; }

    static final int SPI_SETDRAGWIDTH() { return (int)76L; }

    static final int SPI_SETDRAGHEIGHT() { return (int)77L; }

    static final int SPI_SETHANDHELD() { return (int)78L; }

    static final int SPI_GETLOWPOWERTIMEOUT() { return (int)79L; }

    static final int SPI_GETPOWEROFFTIMEOUT() { return (int)80L; }

    static final int SPI_SETLOWPOWERTIMEOUT() { return (int)81L; }

    static final int SPI_SETPOWEROFFTIMEOUT() { return (int)82L; }

    static final int SPI_GETLOWPOWERACTIVE() { return (int)83L; }

    static final int SPI_GETPOWEROFFACTIVE() { return (int)84L; }

    static final int SPI_SETLOWPOWERACTIVE() { return (int)85L; }

    static final int SPI_SETPOWEROFFACTIVE() { return (int)86L; }

    static final int SPI_SETCURSORS() { return (int)87L; }

    static final int SPI_SETICONS() { return (int)88L; }

    static final int SPI_GETDEFAULTINPUTLANG() { return (int)89L; }

    static final int SPI_SETDEFAULTINPUTLANG() { return (int)90L; }

    static final int SPI_SETLANGTOGGLE() { return (int)91L; }

    static final int SPI_GETWINDOWSEXTENSION() { return (int)92L; }

    static final int SPI_SETMOUSETRAILS() { return (int)93L; }

    static final int SPI_GETMOUSETRAILS() { return (int)94L; }

    static final int SPI_SETSCREENSAVERRUNNING() { return (int)97L; }

    static final int SPI_GETFILTERKEYS() { return (int)50L; }

    static final int SPI_SETFILTERKEYS() { return (int)51L; }

    static final int SPI_GETTOGGLEKEYS() { return (int)52L; }

    static final int SPI_SETTOGGLEKEYS() { return (int)53L; }

    static final int SPI_GETMOUSEKEYS() { return (int)54L; }

    static final int SPI_SETMOUSEKEYS() { return (int)55L; }

    static final int SPI_GETSHOWSOUNDS() { return (int)56L; }

    static final int SPI_SETSHOWSOUNDS() { return (int)57L; }

    static final int SPI_GETSTICKYKEYS() { return (int)58L; }

    static final int SPI_SETSTICKYKEYS() { return (int)59L; }

    static final int SPI_GETACCESSTIMEOUT() { return (int)60L; }

    static final int SPI_SETACCESSTIMEOUT() { return (int)61L; }

    static final int SPI_GETSERIALKEYS() { return (int)62L; }

    static final int SPI_SETSERIALKEYS() { return (int)63L; }

    static final int SPI_GETSOUNDSENTRY() { return (int)64L; }

    static final int SPI_SETSOUNDSENTRY() { return (int)65L; }

    static final int SPI_GETSNAPTODEFBUTTON() { return (int)95L; }

    static final int SPI_SETSNAPTODEFBUTTON() { return (int)96L; }

    static final int SPI_GETMOUSEHOVERWIDTH() { return (int)98L; }

    static final int SPI_SETMOUSEHOVERWIDTH() { return (int)99L; }

    static final int SPI_GETMOUSEHOVERHEIGHT() { return (int)100L; }

    static final int SPI_SETMOUSEHOVERHEIGHT() { return (int)101L; }

    static final int SPI_GETMOUSEHOVERTIME() { return (int)102L; }

    static final int SPI_SETMOUSEHOVERTIME() { return (int)103L; }

    static final int SPI_GETWHEELSCROLLLINES() { return (int)104L; }

    static final int SPI_SETWHEELSCROLLLINES() { return (int)105L; }

    static final int SPI_GETMENUSHOWDELAY() { return (int)106L; }

    static final int SPI_SETMENUSHOWDELAY() { return (int)107L; }

    static final int SPI_GETWHEELSCROLLCHARS() { return (int)108L; }

    static final int SPI_SETWHEELSCROLLCHARS() { return (int)109L; }

    static final int SPI_GETSHOWIMEUI() { return (int)110L; }

    static final int SPI_SETSHOWIMEUI() { return (int)111L; }

    static final int SPI_GETMOUSESPEED() { return (int)112L; }

    static final int SPI_SETMOUSESPEED() { return (int)113L; }

    static final int SPI_GETSCREENSAVERRUNNING() { return (int)114L; }

    static final int SPI_GETDESKWALLPAPER() { return (int)115L; }

    static final int SPI_GETAUDIODESCRIPTION() { return (int)116L; }

    static final int SPI_SETAUDIODESCRIPTION() { return (int)117L; }

    static final int SPI_GETSCREENSAVESECURE() { return (int)118L; }

    static final int SPI_SETSCREENSAVESECURE() { return (int)119L; }

    static final int SPI_GETHUNGAPPTIMEOUT() { return (int)120L; }

    static final int SPI_SETHUNGAPPTIMEOUT() { return (int)121L; }

    static final int SPI_GETWAITTOKILLTIMEOUT() { return (int)122L; }

    static final int SPI_SETWAITTOKILLTIMEOUT() { return (int)123L; }

    static final int SPI_GETWAITTOKILLSERVICETIMEOUT() { return (int)124L; }

    static final int SPI_SETWAITTOKILLSERVICETIMEOUT() { return (int)125L; }

    static final int SPI_GETMOUSEDOCKTHRESHOLD() { return (int)126L; }

    static final int SPI_SETMOUSEDOCKTHRESHOLD() { return (int)127L; }

    static final int SPI_GETPENDOCKTHRESHOLD() { return (int)128L; }

    static final int SPI_SETPENDOCKTHRESHOLD() { return (int)129L; }

    static final int SPI_GETWINARRANGING() { return (int)130L; }

    static final int SPI_SETWINARRANGING() { return (int)131L; }

    static final int SPI_GETMOUSEDRAGOUTTHRESHOLD() { return (int)132L; }

    static final int SPI_SETMOUSEDRAGOUTTHRESHOLD() { return (int)133L; }

    static final int SPI_GETPENDRAGOUTTHRESHOLD() { return (int)134L; }

    static final int SPI_SETPENDRAGOUTTHRESHOLD() { return (int)135L; }

    static final int SPI_GETMOUSESIDEMOVETHRESHOLD() { return (int)136L; }

    static final int SPI_SETMOUSESIDEMOVETHRESHOLD() { return (int)137L; }

    static final int SPI_GETPENSIDEMOVETHRESHOLD() { return (int)138L; }

    static final int SPI_SETPENSIDEMOVETHRESHOLD() { return (int)139L; }

    static final int SPI_GETDRAGFROMMAXIMIZE() { return (int)140L; }

    static final int SPI_SETDRAGFROMMAXIMIZE() { return (int)141L; }

    static final int SPI_GETSNAPSIZING() { return (int)142L; }

    static final int SPI_SETSNAPSIZING() { return (int)143L; }

    static final int SPI_GETDOCKMOVING() { return (int)144L; }

    static final int SPI_SETDOCKMOVING() { return (int)145L; }

    static final int MAX_TOUCH_PREDICTION_FILTER_TAPS() { return (int)3L; }

    static final int TOUCHPREDICTIONPARAMETERS_DEFAULT_LATENCY() { return (int)8L; }

}

