// Generated by jextract

package com.github.tornaia.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class cfapi_h$constants$102 extends cfapi_h$constants$101 {

    /* package-private */ cfapi_h$constants$102() {}
    static final int ERROR_DBG_TERMINATE_THREAD() { return (int)691L; }

    static final int ERROR_DBG_TERMINATE_PROCESS() { return (int)692L; }

    static final int ERROR_DBG_CONTROL_C() { return (int)693L; }

    static final int ERROR_DBG_PRINTEXCEPTION_C() { return (int)694L; }

    static final int ERROR_DBG_RIPEXCEPTION() { return (int)695L; }

    static final int ERROR_DBG_CONTROL_BREAK() { return (int)696L; }

    static final int ERROR_DBG_COMMAND_EXCEPTION() { return (int)697L; }

    static final int ERROR_OBJECT_NAME_EXISTS() { return (int)698L; }

    static final int ERROR_THREAD_WAS_SUSPENDED() { return (int)699L; }

    static final int ERROR_IMAGE_NOT_AT_BASE() { return (int)700L; }

    static final int ERROR_RXACT_STATE_CREATED() { return (int)701L; }

    static final int ERROR_SEGMENT_NOTIFICATION() { return (int)702L; }

    static final int ERROR_BAD_CURRENT_DIRECTORY() { return (int)703L; }

    static final int ERROR_FT_READ_RECOVERY_FROM_BACKUP() { return (int)704L; }

    static final int ERROR_FT_WRITE_RECOVERY() { return (int)705L; }

    static final int ERROR_IMAGE_MACHINE_TYPE_MISMATCH() { return (int)706L; }

    static final int ERROR_RECEIVE_PARTIAL() { return (int)707L; }

    static final int ERROR_RECEIVE_EXPEDITED() { return (int)708L; }

    static final int ERROR_RECEIVE_PARTIAL_EXPEDITED() { return (int)709L; }

    static final int ERROR_EVENT_DONE() { return (int)710L; }

    static final int ERROR_EVENT_PENDING() { return (int)711L; }

    static final int ERROR_CHECKING_FILE_SYSTEM() { return (int)712L; }

    static final int ERROR_FATAL_APP_EXIT() { return (int)713L; }

    static final int ERROR_PREDEFINED_HANDLE() { return (int)714L; }

    static final int ERROR_WAS_UNLOCKED() { return (int)715L; }

    static final int ERROR_SERVICE_NOTIFICATION() { return (int)716L; }

    static final int ERROR_WAS_LOCKED() { return (int)717L; }

    static final int ERROR_LOG_HARD_ERROR() { return (int)718L; }

    static final int ERROR_ALREADY_WIN32() { return (int)719L; }

    static final int ERROR_IMAGE_MACHINE_TYPE_MISMATCH_EXE() { return (int)720L; }

    static final int ERROR_NO_YIELD_PERFORMED() { return (int)721L; }

    static final int ERROR_TIMER_RESUME_IGNORED() { return (int)722L; }

    static final int ERROR_ARBITRATION_UNHANDLED() { return (int)723L; }

    static final int ERROR_CARDBUS_NOT_SUPPORTED() { return (int)724L; }

    static final int ERROR_MP_PROCESSOR_MISMATCH() { return (int)725L; }

    static final int ERROR_HIBERNATED() { return (int)726L; }

    static final int ERROR_RESUME_HIBERNATION() { return (int)727L; }

    static final int ERROR_FIRMWARE_UPDATED() { return (int)728L; }

    static final int ERROR_DRIVERS_LEAKING_LOCKED_PAGES() { return (int)729L; }

    static final int ERROR_WAKE_SYSTEM() { return (int)730L; }

    static final int ERROR_WAIT_1() { return (int)731L; }

    static final int ERROR_WAIT_2() { return (int)732L; }

    static final int ERROR_WAIT_3() { return (int)733L; }

    static final int ERROR_WAIT_63() { return (int)734L; }

    static final int ERROR_ABANDONED_WAIT_0() { return (int)735L; }

    static final int ERROR_ABANDONED_WAIT_63() { return (int)736L; }

    static final int ERROR_USER_APC() { return (int)737L; }

    static final int ERROR_KERNEL_APC() { return (int)738L; }

    static final int ERROR_ALERTED() { return (int)739L; }

    static final int ERROR_ELEVATION_REQUIRED() { return (int)740L; }

    static final int ERROR_REPARSE() { return (int)741L; }

    static final int ERROR_OPLOCK_BREAK_IN_PROGRESS() { return (int)742L; }

    static final int ERROR_VOLUME_MOUNTED() { return (int)743L; }

    static final int ERROR_RXACT_COMMITTED() { return (int)744L; }

    static final int ERROR_NOTIFY_CLEANUP() { return (int)745L; }

    static final int ERROR_PRIMARY_TRANSPORT_CONNECT_FAILED() { return (int)746L; }

    static final int ERROR_PAGE_FAULT_TRANSITION() { return (int)747L; }

    static final int ERROR_PAGE_FAULT_DEMAND_ZERO() { return (int)748L; }

    static final int ERROR_PAGE_FAULT_COPY_ON_WRITE() { return (int)749L; }

    static final int ERROR_PAGE_FAULT_GUARD_PAGE() { return (int)750L; }

    static final int ERROR_PAGE_FAULT_PAGING_FILE() { return (int)751L; }

    static final int ERROR_CACHE_PAGE_LOCKED() { return (int)752L; }

    static final int ERROR_CRASH_DUMP() { return (int)753L; }

    static final int ERROR_BUFFER_ALL_ZEROS() { return (int)754L; }

    static final int ERROR_REPARSE_OBJECT() { return (int)755L; }

    static final int ERROR_RESOURCE_REQUIREMENTS_CHANGED() { return (int)756L; }

    static final int ERROR_TRANSLATION_COMPLETE() { return (int)757L; }

    static final int ERROR_NOTHING_TO_TERMINATE() { return (int)758L; }

    static final int ERROR_PROCESS_NOT_IN_JOB() { return (int)759L; }

    static final int ERROR_PROCESS_IN_JOB() { return (int)760L; }

    static final int ERROR_VOLSNAP_HIBERNATE_READY() { return (int)761L; }

    static final int ERROR_FSFILTER_OP_COMPLETED_SUCCESSFULLY() { return (int)762L; }

    static final int ERROR_INTERRUPT_VECTOR_ALREADY_CONNECTED() { return (int)763L; }

    static final int ERROR_INTERRUPT_STILL_CONNECTED() { return (int)764L; }

    static final int ERROR_WAIT_FOR_OPLOCK() { return (int)765L; }

    static final int ERROR_DBG_EXCEPTION_HANDLED() { return (int)766L; }

    static final int ERROR_DBG_CONTINUE() { return (int)767L; }

    static final int ERROR_CALLBACK_POP_STACK() { return (int)768L; }

    static final int ERROR_COMPRESSION_DISABLED() { return (int)769L; }

    static final int ERROR_CANTFETCHBACKWARDS() { return (int)770L; }

    static final int ERROR_CANTSCROLLBACKWARDS() { return (int)771L; }

    static final int ERROR_ROWSNOTRELEASED() { return (int)772L; }

    static final int ERROR_BAD_ACCESSOR_FLAGS() { return (int)773L; }

    static final int ERROR_ERRORS_ENCOUNTERED() { return (int)774L; }

    static final int ERROR_NOT_CAPABLE() { return (int)775L; }

    static final int ERROR_REQUEST_OUT_OF_SEQUENCE() { return (int)776L; }

    static final int ERROR_VERSION_PARSE_ERROR() { return (int)777L; }

    static final int ERROR_BADSTARTPOSITION() { return (int)778L; }

    static final int ERROR_MEMORY_HARDWARE() { return (int)779L; }

    static final int ERROR_DISK_REPAIR_DISABLED() { return (int)780L; }

    static final int ERROR_INSUFFICIENT_RESOURCE_FOR_SPECIFIED_SHARED_SECTION_SIZE() { return (int)781L; }

    static final int ERROR_SYSTEM_POWERSTATE_TRANSITION() { return (int)782L; }

    static final int ERROR_SYSTEM_POWERSTATE_COMPLEX_TRANSITION() { return (int)783L; }

    static final int ERROR_MCA_EXCEPTION() { return (int)784L; }

    static final int ERROR_ACCESS_AUDIT_BY_POLICY() { return (int)785L; }

    static final int ERROR_ACCESS_DISABLED_NO_SAFER_UI_BY_POLICY() { return (int)786L; }

    static final int ERROR_ABANDON_HIBERFILE() { return (int)787L; }

    static final int ERROR_LOST_WRITEBEHIND_DATA_NETWORK_DISCONNECTED() { return (int)788L; }

    static final int ERROR_LOST_WRITEBEHIND_DATA_NETWORK_SERVER_ERROR() { return (int)789L; }

    static final int ERROR_LOST_WRITEBEHIND_DATA_LOCAL_DISK_ERROR() { return (int)790L; }

    static final int ERROR_BAD_MCFG_TABLE() { return (int)791L; }

    static final int ERROR_DISK_REPAIR_REDIRECTED() { return (int)792L; }

    static final int ERROR_DISK_REPAIR_UNSUCCESSFUL() { return (int)793L; }

    static final int ERROR_CORRUPT_LOG_OVERFULL() { return (int)794L; }

    static final int ERROR_CORRUPT_LOG_CORRUPTED() { return (int)795L; }

    static final int ERROR_CORRUPT_LOG_UNAVAILABLE() { return (int)796L; }

    static final int ERROR_CORRUPT_LOG_DELETED_FULL() { return (int)797L; }

    static final int ERROR_CORRUPT_LOG_CLEARED() { return (int)798L; }

    static final int ERROR_ORPHAN_NAME_EXHAUSTED() { return (int)799L; }

    static final int ERROR_OPLOCK_SWITCHED_TO_NEW_HANDLE() { return (int)800L; }

    static final int ERROR_CANNOT_GRANT_REQUESTED_OPLOCK() { return (int)801L; }

    static final int ERROR_CANNOT_BREAK_OPLOCK() { return (int)802L; }

    static final int ERROR_OPLOCK_HANDLE_CLOSED() { return (int)803L; }

    static final int ERROR_NO_ACE_CONDITION() { return (int)804L; }

    static final int ERROR_INVALID_ACE_CONDITION() { return (int)805L; }

    static final int ERROR_FILE_HANDLE_REVOKED() { return (int)806L; }

    static final int ERROR_IMAGE_AT_DIFFERENT_BASE() { return (int)807L; }

    static final int ERROR_ENCRYPTED_IO_NOT_POSSIBLE() { return (int)808L; }

    static final int ERROR_FILE_METADATA_OPTIMIZATION_IN_PROGRESS() { return (int)809L; }

    static final int ERROR_QUOTA_ACTIVITY() { return (int)810L; }

    static final int ERROR_HANDLE_REVOKED() { return (int)811L; }

    static final int ERROR_CALLBACK_INVOKE_INLINE() { return (int)812L; }

    static final int ERROR_CPU_SET_INVALID() { return (int)813L; }

    static final int ERROR_ENCLAVE_NOT_TERMINATED() { return (int)814L; }

    static final int ERROR_ENCLAVE_VIOLATION() { return (int)815L; }

    static final int ERROR_EA_ACCESS_DENIED() { return (int)994L; }

    static final int ERROR_OPERATION_ABORTED() { return (int)995L; }

    static final int ERROR_IO_INCOMPLETE() { return (int)996L; }

    static final int ERROR_IO_PENDING() { return (int)997L; }

    static final int ERROR_NOACCESS() { return (int)998L; }

    static final int ERROR_SWAPERROR() { return (int)999L; }

    static final int ERROR_STACK_OVERFLOW() { return (int)1001L; }

    static final int ERROR_INVALID_MESSAGE() { return (int)1002L; }

    static final int ERROR_CAN_NOT_COMPLETE() { return (int)1003L; }

    static final int ERROR_INVALID_FLAGS() { return (int)1004L; }

    static final int ERROR_UNRECOGNIZED_VOLUME() { return (int)1005L; }

    static final int ERROR_FILE_INVALID() { return (int)1006L; }

    static final int ERROR_FULLSCREEN_MODE() { return (int)1007L; }

    static final int ERROR_NO_TOKEN() { return (int)1008L; }

    static final int ERROR_BADDB() { return (int)1009L; }

    static final int ERROR_BADKEY() { return (int)1010L; }

    static final int ERROR_CANTOPEN() { return (int)1011L; }

    static final int ERROR_CANTREAD() { return (int)1012L; }

    static final int ERROR_CANTWRITE() { return (int)1013L; }

    static final int ERROR_REGISTRY_RECOVERED() { return (int)1014L; }

    static final int ERROR_REGISTRY_CORRUPT() { return (int)1015L; }

    static final int ERROR_REGISTRY_IO_FAILED() { return (int)1016L; }

    static final int ERROR_NOT_REGISTRY_FILE() { return (int)1017L; }

    static final int ERROR_KEY_DELETED() { return (int)1018L; }

    static final int ERROR_NO_LOG_SPACE() { return (int)1019L; }

    static final int ERROR_KEY_HAS_CHILDREN() { return (int)1020L; }

    static final int ERROR_CHILD_MUST_BE_VOLATILE() { return (int)1021L; }

    static final int ERROR_NOTIFY_ENUM_DIR() { return (int)1022L; }

    static final int ERROR_DEPENDENT_SERVICES_RUNNING() { return (int)1051L; }

    static final int ERROR_INVALID_SERVICE_CONTROL() { return (int)1052L; }

    static final int ERROR_SERVICE_REQUEST_TIMEOUT() { return (int)1053L; }

    static final int ERROR_SERVICE_NO_THREAD() { return (int)1054L; }

    static final int ERROR_SERVICE_DATABASE_LOCKED() { return (int)1055L; }

    static final int ERROR_SERVICE_ALREADY_RUNNING() { return (int)1056L; }

    static final int ERROR_INVALID_SERVICE_ACCOUNT() { return (int)1057L; }

    static final int ERROR_SERVICE_DISABLED() { return (int)1058L; }

    static final int ERROR_CIRCULAR_DEPENDENCY() { return (int)1059L; }

    static final int ERROR_SERVICE_DOES_NOT_EXIST() { return (int)1060L; }

    static final int ERROR_SERVICE_CANNOT_ACCEPT_CTRL() { return (int)1061L; }

    static final int ERROR_SERVICE_NOT_ACTIVE() { return (int)1062L; }

    static final int ERROR_FAILED_SERVICE_CONTROLLER_CONNECT() { return (int)1063L; }

    static final int ERROR_EXCEPTION_IN_SERVICE() { return (int)1064L; }

    static final int ERROR_DATABASE_DOES_NOT_EXIST() { return (int)1065L; }

    static final int ERROR_SERVICE_SPECIFIC_ERROR() { return (int)1066L; }

    static final int ERROR_PROCESS_ABORTED() { return (int)1067L; }

    static final int ERROR_SERVICE_DEPENDENCY_FAIL() { return (int)1068L; }

    static final int ERROR_SERVICE_LOGON_FAILED() { return (int)1069L; }

    static final int ERROR_SERVICE_START_HANG() { return (int)1070L; }

    static final int ERROR_INVALID_SERVICE_LOCK() { return (int)1071L; }

    static final int ERROR_SERVICE_MARKED_FOR_DELETE() { return (int)1072L; }

    static final int ERROR_SERVICE_EXISTS() { return (int)1073L; }

    static final int ERROR_ALREADY_RUNNING_LKG() { return (int)1074L; }

    static final int ERROR_SERVICE_DEPENDENCY_DELETED() { return (int)1075L; }

    static final int ERROR_BOOT_ALREADY_ACCEPTED() { return (int)1076L; }

    static final int ERROR_SERVICE_NEVER_STARTED() { return (int)1077L; }

    static final int ERROR_DUPLICATE_SERVICE_NAME() { return (int)1078L; }

    static final int ERROR_DIFFERENT_SERVICE_ACCOUNT() { return (int)1079L; }

    static final int ERROR_CANNOT_DETECT_DRIVER_FAILURE() { return (int)1080L; }

    static final int ERROR_CANNOT_DETECT_PROCESS_ABORT() { return (int)1081L; }

    static final int ERROR_NO_RECOVERY_PROGRAM() { return (int)1082L; }

    static final int ERROR_SERVICE_NOT_IN_EXE() { return (int)1083L; }

    static final int ERROR_NOT_SAFEBOOT_SERVICE() { return (int)1084L; }

    static final int ERROR_END_OF_MEDIA() { return (int)1100L; }

    static final int ERROR_FILEMARK_DETECTED() { return (int)1101L; }

    static final int ERROR_BEGINNING_OF_MEDIA() { return (int)1102L; }

    static final int ERROR_SETMARK_DETECTED() { return (int)1103L; }

    static final int ERROR_NO_DATA_DETECTED() { return (int)1104L; }

    static final int ERROR_PARTITION_FAILURE() { return (int)1105L; }

    static final int ERROR_INVALID_BLOCK_LENGTH() { return (int)1106L; }

    static final int ERROR_DEVICE_NOT_PARTITIONED() { return (int)1107L; }

    static final int ERROR_UNABLE_TO_LOCK_MEDIA() { return (int)1108L; }

    static final int ERROR_UNABLE_TO_UNLOAD_MEDIA() { return (int)1109L; }

    static final int ERROR_MEDIA_CHANGED() { return (int)1110L; }

    static final int ERROR_BUS_RESET() { return (int)1111L; }

    static final int ERROR_NO_MEDIA_IN_DRIVE() { return (int)1112L; }

    static final int ERROR_NO_UNICODE_TRANSLATION() { return (int)1113L; }

    static final int ERROR_DLL_INIT_FAILED() { return (int)1114L; }

    static final int ERROR_SHUTDOWN_IN_PROGRESS() { return (int)1115L; }

    static final int ERROR_NO_SHUTDOWN_IN_PROGRESS() { return (int)1116L; }

    static final int ERROR_IO_DEVICE() { return (int)1117L; }

    static final int ERROR_SERIAL_NO_DEVICE() { return (int)1118L; }

    static final int ERROR_IRQ_BUSY() { return (int)1119L; }

    static final int ERROR_MORE_WRITES() { return (int)1120L; }

    static final int ERROR_COUNTER_TIMEOUT() { return (int)1121L; }

    static final int ERROR_FLOPPY_ID_MARK_NOT_FOUND() { return (int)1122L; }

    static final int ERROR_FLOPPY_WRONG_CYLINDER() { return (int)1123L; }

    static final int ERROR_FLOPPY_UNKNOWN_ERROR() { return (int)1124L; }

    static final int ERROR_FLOPPY_BAD_REGISTERS() { return (int)1125L; }

    static final int ERROR_DISK_RECALIBRATE_FAILED() { return (int)1126L; }

    static final int ERROR_DISK_OPERATION_FAILED() { return (int)1127L; }

    static final int ERROR_DISK_RESET_FAILED() { return (int)1128L; }

    static final int ERROR_EOM_OVERFLOW() { return (int)1129L; }

    static final int ERROR_NOT_ENOUGH_SERVER_MEMORY() { return (int)1130L; }

    static final int ERROR_POSSIBLE_DEADLOCK() { return (int)1131L; }

    static final int ERROR_MAPPED_ALIGNMENT() { return (int)1132L; }

    static final int ERROR_SET_POWER_STATE_VETOED() { return (int)1140L; }

    static final int ERROR_SET_POWER_STATE_FAILED() { return (int)1141L; }

    static final int ERROR_TOO_MANY_LINKS() { return (int)1142L; }

    static final int ERROR_OLD_WIN_VERSION() { return (int)1150L; }

    static final int ERROR_APP_WRONG_OS() { return (int)1151L; }

    static final int ERROR_SINGLE_INSTANCE_APP() { return (int)1152L; }

    static final int ERROR_RMODE_APP() { return (int)1153L; }

    static final int ERROR_INVALID_DLL() { return (int)1154L; }

    static final int ERROR_NO_ASSOCIATION() { return (int)1155L; }

    static final int ERROR_DDE_FAIL() { return (int)1156L; }

    static final int ERROR_DLL_NOT_FOUND() { return (int)1157L; }

    static final int ERROR_NO_MORE_USER_HANDLES() { return (int)1158L; }

    static final int ERROR_MESSAGE_SYNC_ONLY() { return (int)1159L; }

    static final int ERROR_SOURCE_ELEMENT_EMPTY() { return (int)1160L; }

    static final int ERROR_DESTINATION_ELEMENT_FULL() { return (int)1161L; }

    static final int ERROR_ILLEGAL_ELEMENT_ADDRESS() { return (int)1162L; }

    static final int ERROR_MAGAZINE_NOT_PRESENT() { return (int)1163L; }

    static final int ERROR_DEVICE_REINITIALIZATION_NEEDED() { return (int)1164L; }

    static final int ERROR_DEVICE_REQUIRES_CLEANING() { return (int)1165L; }

    static final int ERROR_DEVICE_DOOR_OPEN() { return (int)1166L; }

    static final int ERROR_DEVICE_NOT_CONNECTED() { return (int)1167L; }

    static final int ERROR_NOT_FOUND() { return (int)1168L; }

    static final int ERROR_NO_MATCH() { return (int)1169L; }

    static final int ERROR_SET_NOT_FOUND() { return (int)1170L; }

    static final int ERROR_POINT_NOT_FOUND() { return (int)1171L; }

    static final int ERROR_NO_TRACKING_SERVICE() { return (int)1172L; }

    static final int ERROR_NO_VOLUME_ID() { return (int)1173L; }

    static final int ERROR_UNABLE_TO_REMOVE_REPLACED() { return (int)1175L; }

    static final int ERROR_UNABLE_TO_MOVE_REPLACEMENT() { return (int)1176L; }

    static final int ERROR_UNABLE_TO_MOVE_REPLACEMENT_2() { return (int)1177L; }

    static final int ERROR_JOURNAL_DELETE_IN_PROGRESS() { return (int)1178L; }

    static final int ERROR_JOURNAL_NOT_ACTIVE() { return (int)1179L; }

    static final int ERROR_POTENTIAL_FILE_FOUND() { return (int)1180L; }

    static final int ERROR_JOURNAL_ENTRY_DELETED() { return (int)1181L; }

    static final int ERROR_SHUTDOWN_IS_SCHEDULED() { return (int)1190L; }

    static final int ERROR_SHUTDOWN_USERS_LOGGED_ON() { return (int)1191L; }

    static final int ERROR_BAD_DEVICE() { return (int)1200L; }

    static final int ERROR_CONNECTION_UNAVAIL() { return (int)1201L; }

    static final int ERROR_DEVICE_ALREADY_REMEMBERED() { return (int)1202L; }

    static final int ERROR_NO_NET_OR_BAD_PATH() { return (int)1203L; }

    static final int ERROR_BAD_PROVIDER() { return (int)1204L; }

    static final int ERROR_CANNOT_OPEN_PROFILE() { return (int)1205L; }

    static final int ERROR_BAD_PROFILE() { return (int)1206L; }

    static final int ERROR_NOT_CONTAINER() { return (int)1207L; }

    static final int ERROR_EXTENDED_ERROR() { return (int)1208L; }

    static final int ERROR_INVALID_GROUPNAME() { return (int)1209L; }

    static final int ERROR_INVALID_COMPUTERNAME() { return (int)1210L; }

    static final int ERROR_INVALID_EVENTNAME() { return (int)1211L; }

    static final int ERROR_INVALID_DOMAINNAME() { return (int)1212L; }

    static final int ERROR_INVALID_SERVICENAME() { return (int)1213L; }

    static final int ERROR_INVALID_NETNAME() { return (int)1214L; }

    static final int ERROR_INVALID_SHARENAME() { return (int)1215L; }

    static final int ERROR_INVALID_PASSWORDNAME() { return (int)1216L; }

    static final int ERROR_INVALID_MESSAGENAME() { return (int)1217L; }

    static final int ERROR_INVALID_MESSAGEDEST() { return (int)1218L; }

    static final int ERROR_SESSION_CREDENTIAL_CONFLICT() { return (int)1219L; }

    static final int ERROR_REMOTE_SESSION_LIMIT_EXCEEDED() { return (int)1220L; }

    static final int ERROR_DUP_DOMAINNAME() { return (int)1221L; }

    static final int ERROR_NO_NETWORK() { return (int)1222L; }

    static final int ERROR_CANCELLED() { return (int)1223L; }

    static final int ERROR_USER_MAPPED_FILE() { return (int)1224L; }

    static final int ERROR_CONNECTION_REFUSED() { return (int)1225L; }

    static final int ERROR_GRACEFUL_DISCONNECT() { return (int)1226L; }

    static final int ERROR_ADDRESS_ALREADY_ASSOCIATED() { return (int)1227L; }

    static final int ERROR_ADDRESS_NOT_ASSOCIATED() { return (int)1228L; }

    static final int ERROR_CONNECTION_INVALID() { return (int)1229L; }

    static final int ERROR_CONNECTION_ACTIVE() { return (int)1230L; }

    static final int ERROR_NETWORK_UNREACHABLE() { return (int)1231L; }

    static final int ERROR_HOST_UNREACHABLE() { return (int)1232L; }

    static final int ERROR_PROTOCOL_UNREACHABLE() { return (int)1233L; }

    static final int ERROR_PORT_UNREACHABLE() { return (int)1234L; }

    static final int ERROR_REQUEST_ABORTED() { return (int)1235L; }

    static final int ERROR_CONNECTION_ABORTED() { return (int)1236L; }

    static final int ERROR_RETRY() { return (int)1237L; }

    static final int ERROR_CONNECTION_COUNT_LIMIT() { return (int)1238L; }

    static final int ERROR_LOGIN_TIME_RESTRICTION() { return (int)1239L; }

    static final int ERROR_LOGIN_WKSTA_RESTRICTION() { return (int)1240L; }

    static final int ERROR_INCORRECT_ADDRESS() { return (int)1241L; }

    static final int ERROR_ALREADY_REGISTERED() { return (int)1242L; }

    static final int ERROR_SERVICE_NOT_FOUND() { return (int)1243L; }

    static final int ERROR_NOT_AUTHENTICATED() { return (int)1244L; }

    static final int ERROR_NOT_LOGGED_ON() { return (int)1245L; }

    static final int ERROR_CONTINUE() { return (int)1246L; }

    static final int ERROR_ALREADY_INITIALIZED() { return (int)1247L; }

    static final int ERROR_NO_MORE_DEVICES() { return (int)1248L; }

    static final int ERROR_NO_SUCH_SITE() { return (int)1249L; }

    static final int ERROR_DOMAIN_CONTROLLER_EXISTS() { return (int)1250L; }

    static final int ERROR_ONLY_IF_CONNECTED() { return (int)1251L; }

    static final int ERROR_OVERRIDE_NOCHANGES() { return (int)1252L; }

    static final int ERROR_BAD_USER_PROFILE() { return (int)1253L; }

    static final int ERROR_NOT_SUPPORTED_ON_SBS() { return (int)1254L; }

    static final int ERROR_SERVER_SHUTDOWN_IN_PROGRESS() { return (int)1255L; }

    static final int ERROR_HOST_DOWN() { return (int)1256L; }

    static final int ERROR_NON_ACCOUNT_SID() { return (int)1257L; }

    static final int ERROR_NON_DOMAIN_SID() { return (int)1258L; }

    static final int ERROR_APPHELP_BLOCK() { return (int)1259L; }

    static final int ERROR_ACCESS_DISABLED_BY_POLICY() { return (int)1260L; }

    static final int ERROR_REG_NAT_CONSUMPTION() { return (int)1261L; }

    static final int ERROR_CSCSHARE_OFFLINE() { return (int)1262L; }

    static final int ERROR_PKINIT_FAILURE() { return (int)1263L; }

    static final int ERROR_SMARTCARD_SUBSYSTEM_FAILURE() { return (int)1264L; }

    static final int ERROR_DOWNGRADE_DETECTED() { return (int)1265L; }

    static final int ERROR_MACHINE_LOCKED() { return (int)1271L; }

    static final int ERROR_SMB_GUEST_LOGON_BLOCKED() { return (int)1272L; }

    static final int ERROR_CALLBACK_SUPPLIED_INVALID_DATA() { return (int)1273L; }

    static final int ERROR_SYNC_FOREGROUND_REFRESH_REQUIRED() { return (int)1274L; }

    static final int ERROR_DRIVER_BLOCKED() { return (int)1275L; }

    static final int ERROR_INVALID_IMPORT_OF_NON_DLL() { return (int)1276L; }

    static final int ERROR_ACCESS_DISABLED_WEBBLADE() { return (int)1277L; }

    static final int ERROR_ACCESS_DISABLED_WEBBLADE_TAMPER() { return (int)1278L; }

    static final int ERROR_RECOVERY_FAILURE() { return (int)1279L; }

    static final int ERROR_ALREADY_FIBER() { return (int)1280L; }

    static final int ERROR_ALREADY_THREAD() { return (int)1281L; }

    static final int ERROR_STACK_BUFFER_OVERRUN() { return (int)1282L; }

    static final int ERROR_PARAMETER_QUOTA_EXCEEDED() { return (int)1283L; }

    static final int ERROR_DEBUGGER_INACTIVE() { return (int)1284L; }

    static final int ERROR_DELAY_LOAD_FAILED() { return (int)1285L; }

    static final int ERROR_VDM_DISALLOWED() { return (int)1286L; }

    static final int ERROR_UNIDENTIFIED_ERROR() { return (int)1287L; }

    static final int ERROR_INVALID_CRUNTIME_PARAMETER() { return (int)1288L; }

    static final int ERROR_BEYOND_VDL() { return (int)1289L; }

    static final int ERROR_INCOMPATIBLE_SERVICE_SID_TYPE() { return (int)1290L; }

    static final int ERROR_DRIVER_PROCESS_TERMINATED() { return (int)1291L; }

    static final int ERROR_IMPLEMENTATION_LIMIT() { return (int)1292L; }

    static final int ERROR_PROCESS_IS_PROTECTED() { return (int)1293L; }

    static final int ERROR_SERVICE_NOTIFY_CLIENT_LAGGING() { return (int)1294L; }

    static final int ERROR_DISK_QUOTA_EXCEEDED() { return (int)1295L; }

    static final int ERROR_CONTENT_BLOCKED() { return (int)1296L; }

    static final int ERROR_INCOMPATIBLE_SERVICE_PRIVILEGE() { return (int)1297L; }

    static final int ERROR_APP_HANG() { return (int)1298L; }

    static final int ERROR_INVALID_LABEL() { return (int)1299L; }

    static final int ERROR_NOT_ALL_ASSIGNED() { return (int)1300L; }

    static final int ERROR_SOME_NOT_MAPPED() { return (int)1301L; }

    static final int ERROR_NO_QUOTAS_FOR_ACCOUNT() { return (int)1302L; }

    static final int ERROR_LOCAL_USER_SESSION_KEY() { return (int)1303L; }

    static final int ERROR_NULL_LM_PASSWORD() { return (int)1304L; }

    static final int ERROR_UNKNOWN_REVISION() { return (int)1305L; }

    static final int ERROR_REVISION_MISMATCH() { return (int)1306L; }

    static final int ERROR_INVALID_OWNER() { return (int)1307L; }

    static final int ERROR_INVALID_PRIMARY_GROUP() { return (int)1308L; }

    static final int ERROR_NO_IMPERSONATION_TOKEN() { return (int)1309L; }

    static final int ERROR_CANT_DISABLE_MANDATORY() { return (int)1310L; }

    static final int ERROR_NO_LOGON_SERVERS() { return (int)1311L; }

    static final int ERROR_NO_SUCH_LOGON_SESSION() { return (int)1312L; }

    static final int ERROR_NO_SUCH_PRIVILEGE() { return (int)1313L; }

    static final int ERROR_PRIVILEGE_NOT_HELD() { return (int)1314L; }

    static final int ERROR_INVALID_ACCOUNT_NAME() { return (int)1315L; }

    static final int ERROR_USER_EXISTS() { return (int)1316L; }

    static final int ERROR_NO_SUCH_USER() { return (int)1317L; }

    static final int ERROR_GROUP_EXISTS() { return (int)1318L; }

    static final int ERROR_NO_SUCH_GROUP() { return (int)1319L; }

    static final int ERROR_MEMBER_IN_GROUP() { return (int)1320L; }

    static final int ERROR_MEMBER_NOT_IN_GROUP() { return (int)1321L; }

    static final int ERROR_LAST_ADMIN() { return (int)1322L; }

    static final int ERROR_WRONG_PASSWORD() { return (int)1323L; }

    static final int ERROR_ILL_FORMED_PASSWORD() { return (int)1324L; }

    static final int ERROR_PASSWORD_RESTRICTION() { return (int)1325L; }

    static final int ERROR_LOGON_FAILURE() { return (int)1326L; }

    static final int ERROR_ACCOUNT_RESTRICTION() { return (int)1327L; }

    static final int ERROR_INVALID_LOGON_HOURS() { return (int)1328L; }

    static final int ERROR_INVALID_WORKSTATION() { return (int)1329L; }

    static final int ERROR_PASSWORD_EXPIRED() { return (int)1330L; }

    static final int ERROR_ACCOUNT_DISABLED() { return (int)1331L; }

    static final int ERROR_NONE_MAPPED() { return (int)1332L; }

    static final int ERROR_TOO_MANY_LUIDS_REQUESTED() { return (int)1333L; }

    static final int ERROR_LUIDS_EXHAUSTED() { return (int)1334L; }

    static final int ERROR_INVALID_SUB_AUTHORITY() { return (int)1335L; }

    static final int ERROR_INVALID_ACL() { return (int)1336L; }

    static final int ERROR_INVALID_SID() { return (int)1337L; }

    static final int ERROR_INVALID_SECURITY_DESCR() { return (int)1338L; }

    static final int ERROR_BAD_INHERITANCE_ACL() { return (int)1340L; }

    static final int ERROR_SERVER_DISABLED() { return (int)1341L; }

    static final int ERROR_SERVER_NOT_DISABLED() { return (int)1342L; }

    static final int ERROR_INVALID_ID_AUTHORITY() { return (int)1343L; }

    static final int ERROR_ALLOTTED_SPACE_EXCEEDED() { return (int)1344L; }

    static final int ERROR_INVALID_GROUP_ATTRIBUTES() { return (int)1345L; }

    static final int ERROR_BAD_IMPERSONATION_LEVEL() { return (int)1346L; }

    static final int ERROR_CANT_OPEN_ANONYMOUS() { return (int)1347L; }

    static final int ERROR_BAD_VALIDATION_CLASS() { return (int)1348L; }

    static final int ERROR_BAD_TOKEN_TYPE() { return (int)1349L; }

    static final int ERROR_NO_SECURITY_ON_OBJECT() { return (int)1350L; }

    static final int ERROR_CANT_ACCESS_DOMAIN_INFO() { return (int)1351L; }

    static final int ERROR_INVALID_SERVER_STATE() { return (int)1352L; }

    static final int ERROR_INVALID_DOMAIN_STATE() { return (int)1353L; }

    static final int ERROR_INVALID_DOMAIN_ROLE() { return (int)1354L; }

    static final int ERROR_NO_SUCH_DOMAIN() { return (int)1355L; }

    static final int ERROR_DOMAIN_EXISTS() { return (int)1356L; }

    static final int ERROR_DOMAIN_LIMIT_EXCEEDED() { return (int)1357L; }

    static final int ERROR_INTERNAL_DB_CORRUPTION() { return (int)1358L; }

    static final int ERROR_INTERNAL_ERROR() { return (int)1359L; }

    static final int ERROR_GENERIC_NOT_MAPPED() { return (int)1360L; }

    static final int ERROR_BAD_DESCRIPTOR_FORMAT() { return (int)1361L; }

    static final int ERROR_NOT_LOGON_PROCESS() { return (int)1362L; }

    static final int ERROR_LOGON_SESSION_EXISTS() { return (int)1363L; }

    static final int ERROR_NO_SUCH_PACKAGE() { return (int)1364L; }

    static final int ERROR_BAD_LOGON_SESSION_STATE() { return (int)1365L; }

    static final int ERROR_LOGON_SESSION_COLLISION() { return (int)1366L; }

    static final int ERROR_INVALID_LOGON_TYPE() { return (int)1367L; }

    static final int ERROR_CANNOT_IMPERSONATE() { return (int)1368L; }

    static final int ERROR_RXACT_INVALID_STATE() { return (int)1369L; }

    static final int ERROR_RXACT_COMMIT_FAILURE() { return (int)1370L; }

    static final int ERROR_SPECIAL_ACCOUNT() { return (int)1371L; }

    static final int ERROR_SPECIAL_GROUP() { return (int)1372L; }

    static final int ERROR_SPECIAL_USER() { return (int)1373L; }

    static final int ERROR_MEMBERS_PRIMARY_GROUP() { return (int)1374L; }

    static final int ERROR_TOKEN_ALREADY_IN_USE() { return (int)1375L; }

    static final int ERROR_NO_SUCH_ALIAS() { return (int)1376L; }

    static final int ERROR_MEMBER_NOT_IN_ALIAS() { return (int)1377L; }

    static final int ERROR_MEMBER_IN_ALIAS() { return (int)1378L; }

    static final int ERROR_ALIAS_EXISTS() { return (int)1379L; }

    static final int ERROR_LOGON_NOT_GRANTED() { return (int)1380L; }

    static final int ERROR_TOO_MANY_SECRETS() { return (int)1381L; }

    static final int ERROR_SECRET_TOO_LONG() { return (int)1382L; }

    static final int ERROR_INTERNAL_DB_ERROR() { return (int)1383L; }

    static final int ERROR_TOO_MANY_CONTEXT_IDS() { return (int)1384L; }

    static final int ERROR_LOGON_TYPE_NOT_GRANTED() { return (int)1385L; }

    static final int ERROR_NT_CROSS_ENCRYPTION_REQUIRED() { return (int)1386L; }

    static final int ERROR_NO_SUCH_MEMBER() { return (int)1387L; }

    static final int ERROR_INVALID_MEMBER() { return (int)1388L; }

    static final int ERROR_TOO_MANY_SIDS() { return (int)1389L; }

    static final int ERROR_LM_CROSS_ENCRYPTION_REQUIRED() { return (int)1390L; }

    static final int ERROR_NO_INHERITANCE() { return (int)1391L; }

    static final int ERROR_FILE_CORRUPT() { return (int)1392L; }

    static final int ERROR_DISK_CORRUPT() { return (int)1393L; }

    static final int ERROR_NO_USER_SESSION_KEY() { return (int)1394L; }

    static final int ERROR_LICENSE_QUOTA_EXCEEDED() { return (int)1395L; }

    static final int ERROR_WRONG_TARGET_NAME() { return (int)1396L; }

    static final int ERROR_MUTUAL_AUTH_FAILED() { return (int)1397L; }

    static final int ERROR_TIME_SKEW() { return (int)1398L; }

    static final int ERROR_CURRENT_DOMAIN_NOT_ALLOWED() { return (int)1399L; }

    static final int ERROR_INVALID_WINDOW_HANDLE() { return (int)1400L; }

    static final int ERROR_INVALID_MENU_HANDLE() { return (int)1401L; }

    static final int ERROR_INVALID_CURSOR_HANDLE() { return (int)1402L; }

    static final int ERROR_INVALID_ACCEL_HANDLE() { return (int)1403L; }

    static final int ERROR_INVALID_HOOK_HANDLE() { return (int)1404L; }

    static final int ERROR_INVALID_DWP_HANDLE() { return (int)1405L; }

    static final int ERROR_TLW_WITH_WSCHILD() { return (int)1406L; }

    static final int ERROR_CANNOT_FIND_WND_CLASS() { return (int)1407L; }

    static final int ERROR_WINDOW_OF_OTHER_THREAD() { return (int)1408L; }

    static final int ERROR_HOTKEY_ALREADY_REGISTERED() { return (int)1409L; }

    static final int ERROR_CLASS_ALREADY_EXISTS() { return (int)1410L; }

    static final int ERROR_CLASS_DOES_NOT_EXIST() { return (int)1411L; }

    static final int ERROR_CLASS_HAS_WINDOWS() { return (int)1412L; }

    static final int ERROR_INVALID_INDEX() { return (int)1413L; }

    static final int ERROR_INVALID_ICON_HANDLE() { return (int)1414L; }

    static final int ERROR_PRIVATE_DIALOG_INDEX() { return (int)1415L; }

    static final int ERROR_LISTBOX_ID_NOT_FOUND() { return (int)1416L; }

    static final int ERROR_NO_WILDCARD_CHARACTERS() { return (int)1417L; }

    static final int ERROR_CLIPBOARD_NOT_OPEN() { return (int)1418L; }

    static final int ERROR_HOTKEY_NOT_REGISTERED() { return (int)1419L; }

    static final int ERROR_WINDOW_NOT_DIALOG() { return (int)1420L; }

    static final int ERROR_CONTROL_ID_NOT_FOUND() { return (int)1421L; }

    static final int ERROR_INVALID_COMBOBOX_MESSAGE() { return (int)1422L; }

    static final int ERROR_WINDOW_NOT_COMBOBOX() { return (int)1423L; }

    static final int ERROR_INVALID_EDIT_HEIGHT() { return (int)1424L; }

    static final int ERROR_DC_NOT_FOUND() { return (int)1425L; }

    static final int ERROR_INVALID_HOOK_FILTER() { return (int)1426L; }

    static final int ERROR_INVALID_FILTER_PROC() { return (int)1427L; }

    static final int ERROR_HOOK_NEEDS_HMOD() { return (int)1428L; }

    static final int ERROR_GLOBAL_ONLY_HOOK() { return (int)1429L; }

    static final int ERROR_JOURNAL_HOOK_SET() { return (int)1430L; }

    static final int ERROR_HOOK_NOT_INSTALLED() { return (int)1431L; }

    static final int ERROR_INVALID_LB_MESSAGE() { return (int)1432L; }

    static final int ERROR_SETCOUNT_ON_BAD_LB() { return (int)1433L; }

    static final int ERROR_LB_WITHOUT_TABSTOPS() { return (int)1434L; }

    static final int ERROR_DESTROY_OBJECT_OF_OTHER_THREAD() { return (int)1435L; }

    static final int ERROR_CHILD_WINDOW_MENU() { return (int)1436L; }

    static final int ERROR_NO_SYSTEM_MENU() { return (int)1437L; }

    static final int ERROR_INVALID_MSGBOX_STYLE() { return (int)1438L; }

    static final int ERROR_INVALID_SPI_VALUE() { return (int)1439L; }

    static final int ERROR_SCREEN_ALREADY_LOCKED() { return (int)1440L; }

    static final int ERROR_HWNDS_HAVE_DIFF_PARENT() { return (int)1441L; }

    static final int ERROR_NOT_CHILD_WINDOW() { return (int)1442L; }

    static final int ERROR_INVALID_GW_COMMAND() { return (int)1443L; }

    static final int ERROR_INVALID_THREAD_ID() { return (int)1444L; }

    static final int ERROR_NON_MDICHILD_WINDOW() { return (int)1445L; }

    static final int ERROR_POPUP_ALREADY_ACTIVE() { return (int)1446L; }

    static final int ERROR_NO_SCROLLBARS() { return (int)1447L; }

    static final int ERROR_INVALID_SCROLLBAR_RANGE() { return (int)1448L; }

    static final int ERROR_INVALID_SHOWWIN_COMMAND() { return (int)1449L; }

    static final int ERROR_NO_SYSTEM_RESOURCES() { return (int)1450L; }

    static final int ERROR_NONPAGED_SYSTEM_RESOURCES() { return (int)1451L; }

    static final int ERROR_PAGED_SYSTEM_RESOURCES() { return (int)1452L; }

    static final int ERROR_WORKING_SET_QUOTA() { return (int)1453L; }

    static final int ERROR_PAGEFILE_QUOTA() { return (int)1454L; }

    static final int ERROR_COMMITMENT_LIMIT() { return (int)1455L; }

    static final int ERROR_MENU_ITEM_NOT_FOUND() { return (int)1456L; }

    static final int ERROR_INVALID_KEYBOARD_HANDLE() { return (int)1457L; }

    static final int ERROR_HOOK_TYPE_NOT_ALLOWED() { return (int)1458L; }

    static final int ERROR_REQUIRES_INTERACTIVE_WINDOWSTATION() { return (int)1459L; }

    static final int ERROR_TIMEOUT() { return (int)1460L; }

    static final int ERROR_INVALID_MONITOR_HANDLE() { return (int)1461L; }

    static final int ERROR_INCORRECT_SIZE() { return (int)1462L; }

    static final int ERROR_SYMLINK_CLASS_DISABLED() { return (int)1463L; }

    static final int ERROR_SYMLINK_NOT_SUPPORTED() { return (int)1464L; }

    static final int ERROR_XML_PARSE_ERROR() { return (int)1465L; }

    static final int ERROR_XMLDSIG_ERROR() { return (int)1466L; }

    static final int ERROR_RESTART_APPLICATION() { return (int)1467L; }

    static final int ERROR_WRONG_COMPARTMENT() { return (int)1468L; }

    static final int ERROR_AUTHIP_FAILURE() { return (int)1469L; }

    static final int ERROR_NO_NVRAM_RESOURCES() { return (int)1470L; }

    static final int ERROR_NOT_GUI_PROCESS() { return (int)1471L; }

    static final int ERROR_EVENTLOG_FILE_CORRUPT() { return (int)1500L; }

    static final int ERROR_EVENTLOG_CANT_START() { return (int)1501L; }

    static final int ERROR_LOG_FILE_FULL() { return (int)1502L; }

    static final int ERROR_EVENTLOG_FILE_CHANGED() { return (int)1503L; }

    static final int ERROR_CONTAINER_ASSIGNED() { return (int)1504L; }

    static final int ERROR_JOB_NO_CONTAINER() { return (int)1505L; }

    static final int ERROR_INVALID_TASK_NAME() { return (int)1550L; }

    static final int ERROR_INVALID_TASK_INDEX() { return (int)1551L; }

    static final int ERROR_THREAD_ALREADY_IN_TASK() { return (int)1552L; }

    static final int ERROR_INSTALL_SERVICE_FAILURE() { return (int)1601L; }

    static final int ERROR_INSTALL_USEREXIT() { return (int)1602L; }

    static final int ERROR_INSTALL_FAILURE() { return (int)1603L; }

    static final int ERROR_INSTALL_SUSPEND() { return (int)1604L; }

    static final int ERROR_UNKNOWN_PRODUCT() { return (int)1605L; }

    static final int ERROR_UNKNOWN_FEATURE() { return (int)1606L; }

    static final int ERROR_UNKNOWN_COMPONENT() { return (int)1607L; }

    static final int ERROR_UNKNOWN_PROPERTY() { return (int)1608L; }

    static final int ERROR_INVALID_HANDLE_STATE() { return (int)1609L; }

    static final int ERROR_BAD_CONFIGURATION() { return (int)1610L; }

    static final int ERROR_INDEX_ABSENT() { return (int)1611L; }

    static final int ERROR_INSTALL_SOURCE_ABSENT() { return (int)1612L; }

    static final int ERROR_INSTALL_PACKAGE_VERSION() { return (int)1613L; }

    static final int ERROR_PRODUCT_UNINSTALLED() { return (int)1614L; }

    static final int ERROR_BAD_QUERY_SYNTAX() { return (int)1615L; }

    static final int ERROR_INVALID_FIELD() { return (int)1616L; }

    static final int ERROR_DEVICE_REMOVED() { return (int)1617L; }

    static final int ERROR_INSTALL_ALREADY_RUNNING() { return (int)1618L; }

    static final int ERROR_INSTALL_PACKAGE_OPEN_FAILED() { return (int)1619L; }

    static final int ERROR_INSTALL_PACKAGE_INVALID() { return (int)1620L; }

    static final int ERROR_INSTALL_UI_FAILURE() { return (int)1621L; }

    static final int ERROR_INSTALL_LOG_FAILURE() { return (int)1622L; }

    static final int ERROR_INSTALL_LANGUAGE_UNSUPPORTED() { return (int)1623L; }

    static final int ERROR_INSTALL_TRANSFORM_FAILURE() { return (int)1624L; }

    static final int ERROR_INSTALL_PACKAGE_REJECTED() { return (int)1625L; }

    static final int ERROR_FUNCTION_NOT_CALLED() { return (int)1626L; }

    static final int ERROR_FUNCTION_FAILED() { return (int)1627L; }

    static final int ERROR_INVALID_TABLE() { return (int)1628L; }

    static final int ERROR_DATATYPE_MISMATCH() { return (int)1629L; }

    static final int ERROR_UNSUPPORTED_TYPE() { return (int)1630L; }

    static final int ERROR_CREATE_FAILED() { return (int)1631L; }

    static final int ERROR_INSTALL_TEMP_UNWRITABLE() { return (int)1632L; }

    static final int ERROR_INSTALL_PLATFORM_UNSUPPORTED() { return (int)1633L; }

    static final int ERROR_INSTALL_NOTUSED() { return (int)1634L; }

    static final int ERROR_PATCH_PACKAGE_OPEN_FAILED() { return (int)1635L; }

    static final int ERROR_PATCH_PACKAGE_INVALID() { return (int)1636L; }

    static final int ERROR_PATCH_PACKAGE_UNSUPPORTED() { return (int)1637L; }

    static final int ERROR_PRODUCT_VERSION() { return (int)1638L; }

    static final int ERROR_INVALID_COMMAND_LINE() { return (int)1639L; }

    static final int ERROR_INSTALL_REMOTE_DISALLOWED() { return (int)1640L; }

    static final int ERROR_SUCCESS_REBOOT_INITIATED() { return (int)1641L; }

    static final int ERROR_PATCH_TARGET_NOT_FOUND() { return (int)1642L; }

    static final int ERROR_PATCH_PACKAGE_REJECTED() { return (int)1643L; }

    static final int ERROR_INSTALL_TRANSFORM_REJECTED() { return (int)1644L; }

    static final int ERROR_INSTALL_REMOTE_PROHIBITED() { return (int)1645L; }

    static final int ERROR_PATCH_REMOVAL_UNSUPPORTED() { return (int)1646L; }

    static final int ERROR_UNKNOWN_PATCH() { return (int)1647L; }

    static final int ERROR_PATCH_NO_SEQUENCE() { return (int)1648L; }

    static final int ERROR_PATCH_REMOVAL_DISALLOWED() { return (int)1649L; }

    static final int ERROR_INVALID_PATCH_XML() { return (int)1650L; }

    static final int ERROR_PATCH_MANAGED_ADVERTISED_PRODUCT() { return (int)1651L; }

    static final int ERROR_INSTALL_SERVICE_SAFEBOOT() { return (int)1652L; }

    static final int ERROR_FAIL_FAST_EXCEPTION() { return (int)1653L; }

    static final int ERROR_INSTALL_REJECTED() { return (int)1654L; }

    static final int ERROR_DYNAMIC_CODE_BLOCKED() { return (int)1655L; }

    static final int ERROR_NOT_SAME_OBJECT() { return (int)1656L; }

    static final int ERROR_STRICT_CFG_VIOLATION() { return (int)1657L; }

    static final int ERROR_SET_CONTEXT_DENIED() { return (int)1660L; }

    static final int ERROR_CROSS_PARTITION_VIOLATION() { return (int)1661L; }

    static final int ERROR_RETURN_ADDRESS_HIJACK_ATTEMPT() { return (int)1662L; }

    static final int RPC_S_INVALID_STRING_BINDING() { return (int)1700L; }

    static final int RPC_S_WRONG_KIND_OF_BINDING() { return (int)1701L; }

    static final int RPC_S_INVALID_BINDING() { return (int)1702L; }

    static final int RPC_S_PROTSEQ_NOT_SUPPORTED() { return (int)1703L; }

    static final int RPC_S_INVALID_RPC_PROTSEQ() { return (int)1704L; }

    static final int RPC_S_INVALID_STRING_UUID() { return (int)1705L; }

    static final int RPC_S_INVALID_ENDPOINT_FORMAT() { return (int)1706L; }

    static final int RPC_S_INVALID_NET_ADDR() { return (int)1707L; }

    static final int RPC_S_NO_ENDPOINT_FOUND() { return (int)1708L; }

    static final int RPC_S_INVALID_TIMEOUT() { return (int)1709L; }

    static final int RPC_S_OBJECT_NOT_FOUND() { return (int)1710L; }

    static final int RPC_S_ALREADY_REGISTERED() { return (int)1711L; }

    static final int RPC_S_TYPE_ALREADY_REGISTERED() { return (int)1712L; }

    static final int RPC_S_ALREADY_LISTENING() { return (int)1713L; }

    static final int RPC_S_NO_PROTSEQS_REGISTERED() { return (int)1714L; }

    static final int RPC_S_NOT_LISTENING() { return (int)1715L; }

    static final int RPC_S_UNKNOWN_MGR_TYPE() { return (int)1716L; }

    static final int RPC_S_UNKNOWN_IF() { return (int)1717L; }

    static final int RPC_S_NO_BINDINGS() { return (int)1718L; }

    static final int RPC_S_NO_PROTSEQS() { return (int)1719L; }

    static final int RPC_S_CANT_CREATE_ENDPOINT() { return (int)1720L; }

    static final int RPC_S_OUT_OF_RESOURCES() { return (int)1721L; }

    static final int RPC_S_SERVER_UNAVAILABLE() { return (int)1722L; }

    static final int RPC_S_SERVER_TOO_BUSY() { return (int)1723L; }

    static final int RPC_S_INVALID_NETWORK_OPTIONS() { return (int)1724L; }

    static final int RPC_S_NO_CALL_ACTIVE() { return (int)1725L; }

    static final int RPC_S_CALL_FAILED() { return (int)1726L; }

    static final int RPC_S_CALL_FAILED_DNE() { return (int)1727L; }

    static final int RPC_S_PROTOCOL_ERROR() { return (int)1728L; }

    static final int RPC_S_PROXY_ACCESS_DENIED() { return (int)1729L; }

    static final int RPC_S_UNSUPPORTED_TRANS_SYN() { return (int)1730L; }

    static final int RPC_S_UNSUPPORTED_TYPE() { return (int)1732L; }

    static final int RPC_S_INVALID_TAG() { return (int)1733L; }

    static final int RPC_S_INVALID_BOUND() { return (int)1734L; }

    static final int RPC_S_NO_ENTRY_NAME() { return (int)1735L; }

    static final int RPC_S_INVALID_NAME_SYNTAX() { return (int)1736L; }

    static final int RPC_S_UNSUPPORTED_NAME_SYNTAX() { return (int)1737L; }

    static final int RPC_S_UUID_NO_ADDRESS() { return (int)1739L; }

    static final int RPC_S_DUPLICATE_ENDPOINT() { return (int)1740L; }

    static final int RPC_S_UNKNOWN_AUTHN_TYPE() { return (int)1741L; }

    static final int RPC_S_MAX_CALLS_TOO_SMALL() { return (int)1742L; }

    static final int RPC_S_STRING_TOO_LONG() { return (int)1743L; }

    static final int RPC_S_PROTSEQ_NOT_FOUND() { return (int)1744L; }

    static final int RPC_S_PROCNUM_OUT_OF_RANGE() { return (int)1745L; }

    static final int RPC_S_BINDING_HAS_NO_AUTH() { return (int)1746L; }

    static final int RPC_S_UNKNOWN_AUTHN_SERVICE() { return (int)1747L; }

    static final int RPC_S_UNKNOWN_AUTHN_LEVEL() { return (int)1748L; }

    static final int RPC_S_INVALID_AUTH_IDENTITY() { return (int)1749L; }

    static final int RPC_S_UNKNOWN_AUTHZ_SERVICE() { return (int)1750L; }

    static final int EPT_S_INVALID_ENTRY() { return (int)1751L; }

    static final int EPT_S_CANT_PERFORM_OP() { return (int)1752L; }

    static final int EPT_S_NOT_REGISTERED() { return (int)1753L; }

    static final int RPC_S_NOTHING_TO_EXPORT() { return (int)1754L; }

    static final int RPC_S_INCOMPLETE_NAME() { return (int)1755L; }

    static final int RPC_S_INVALID_VERS_OPTION() { return (int)1756L; }

    static final int RPC_S_NO_MORE_MEMBERS() { return (int)1757L; }

    static final int RPC_S_NOT_ALL_OBJS_UNEXPORTED() { return (int)1758L; }

    static final int RPC_S_INTERFACE_NOT_FOUND() { return (int)1759L; }

    static final int RPC_S_ENTRY_ALREADY_EXISTS() { return (int)1760L; }

    static final int RPC_S_ENTRY_NOT_FOUND() { return (int)1761L; }

    static final int RPC_S_NAME_SERVICE_UNAVAILABLE() { return (int)1762L; }

    static final int RPC_S_INVALID_NAF_ID() { return (int)1763L; }

    static final int RPC_S_CANNOT_SUPPORT() { return (int)1764L; }

    static final int RPC_S_NO_CONTEXT_AVAILABLE() { return (int)1765L; }

    static final int RPC_S_INTERNAL_ERROR() { return (int)1766L; }

    static final int RPC_S_ZERO_DIVIDE() { return (int)1767L; }

    static final int RPC_S_ADDRESS_ERROR() { return (int)1768L; }

    static final int RPC_S_FP_DIV_ZERO() { return (int)1769L; }

    static final int RPC_S_FP_UNDERFLOW() { return (int)1770L; }

    static final int RPC_S_FP_OVERFLOW() { return (int)1771L; }

    static final int RPC_X_NO_MORE_ENTRIES() { return (int)1772L; }

    static final int RPC_X_SS_CHAR_TRANS_OPEN_FAIL() { return (int)1773L; }

    static final int RPC_X_SS_CHAR_TRANS_SHORT_FILE() { return (int)1774L; }

    static final int RPC_X_SS_IN_NULL_CONTEXT() { return (int)1775L; }

    static final int RPC_X_SS_CONTEXT_DAMAGED() { return (int)1777L; }

    static final int RPC_X_SS_HANDLES_MISMATCH() { return (int)1778L; }

    static final int RPC_X_SS_CANNOT_GET_CALL_HANDLE() { return (int)1779L; }

    static final int RPC_X_NULL_REF_POINTER() { return (int)1780L; }

    static final int RPC_X_ENUM_VALUE_OUT_OF_RANGE() { return (int)1781L; }

    static final int RPC_X_BYTE_COUNT_TOO_SMALL() { return (int)1782L; }

    static final int RPC_X_BAD_STUB_DATA() { return (int)1783L; }

    static final int ERROR_INVALID_USER_BUFFER() { return (int)1784L; }

    static final int ERROR_UNRECOGNIZED_MEDIA() { return (int)1785L; }

    static final int ERROR_NO_TRUST_LSA_SECRET() { return (int)1786L; }

    static final int ERROR_NO_TRUST_SAM_ACCOUNT() { return (int)1787L; }

    static final int ERROR_TRUSTED_DOMAIN_FAILURE() { return (int)1788L; }

    static final int ERROR_TRUSTED_RELATIONSHIP_FAILURE() { return (int)1789L; }

    static final int ERROR_TRUST_FAILURE() { return (int)1790L; }

    static final int RPC_S_CALL_IN_PROGRESS() { return (int)1791L; }

    static final int ERROR_NETLOGON_NOT_STARTED() { return (int)1792L; }

    static final int ERROR_ACCOUNT_EXPIRED() { return (int)1793L; }

    static final int ERROR_REDIRECTOR_HAS_OPEN_HANDLES() { return (int)1794L; }

    static final int ERROR_PRINTER_DRIVER_ALREADY_INSTALLED() { return (int)1795L; }

    static final int ERROR_UNKNOWN_PORT() { return (int)1796L; }

    static final int ERROR_UNKNOWN_PRINTER_DRIVER() { return (int)1797L; }

    static final int ERROR_UNKNOWN_PRINTPROCESSOR() { return (int)1798L; }

    static final int ERROR_INVALID_SEPARATOR_FILE() { return (int)1799L; }

    static final int ERROR_INVALID_PRIORITY() { return (int)1800L; }

    static final int ERROR_INVALID_PRINTER_NAME() { return (int)1801L; }

    static final int ERROR_PRINTER_ALREADY_EXISTS() { return (int)1802L; }

    static final int ERROR_INVALID_PRINTER_COMMAND() { return (int)1803L; }

    static final int ERROR_INVALID_DATATYPE() { return (int)1804L; }

    static final int ERROR_INVALID_ENVIRONMENT() { return (int)1805L; }

    static final int RPC_S_NO_MORE_BINDINGS() { return (int)1806L; }

    static final int ERROR_NOLOGON_INTERDOMAIN_TRUST_ACCOUNT() { return (int)1807L; }

    static final int ERROR_NOLOGON_WORKSTATION_TRUST_ACCOUNT() { return (int)1808L; }

    static final int ERROR_NOLOGON_SERVER_TRUST_ACCOUNT() { return (int)1809L; }

    static final int ERROR_DOMAIN_TRUST_INCONSISTENT() { return (int)1810L; }

    static final int ERROR_SERVER_HAS_OPEN_HANDLES() { return (int)1811L; }

    static final int ERROR_RESOURCE_DATA_NOT_FOUND() { return (int)1812L; }

    static final int ERROR_RESOURCE_TYPE_NOT_FOUND() { return (int)1813L; }

    static final int ERROR_RESOURCE_NAME_NOT_FOUND() { return (int)1814L; }

    static final int ERROR_RESOURCE_LANG_NOT_FOUND() { return (int)1815L; }

    static final int ERROR_NOT_ENOUGH_QUOTA() { return (int)1816L; }

    static final int RPC_S_NO_INTERFACES() { return (int)1817L; }

    static final int RPC_S_CALL_CANCELLED() { return (int)1818L; }

    static final int RPC_S_BINDING_INCOMPLETE() { return (int)1819L; }

    static final int RPC_S_COMM_FAILURE() { return (int)1820L; }

    static final int RPC_S_UNSUPPORTED_AUTHN_LEVEL() { return (int)1821L; }

    static final int RPC_S_NO_PRINC_NAME() { return (int)1822L; }

    static final int RPC_S_NOT_RPC_ERROR() { return (int)1823L; }

    static final int RPC_S_UUID_LOCAL_ONLY() { return (int)1824L; }

    static final int RPC_S_SEC_PKG_ERROR() { return (int)1825L; }

    static final int RPC_S_NOT_CANCELLED() { return (int)1826L; }

    static final int RPC_X_INVALID_ES_ACTION() { return (int)1827L; }

    static final int RPC_X_WRONG_ES_VERSION() { return (int)1828L; }

    static final int RPC_X_WRONG_STUB_VERSION() { return (int)1829L; }

    static final int RPC_X_INVALID_PIPE_OBJECT() { return (int)1830L; }

    static final int RPC_X_WRONG_PIPE_ORDER() { return (int)1831L; }

    static final int RPC_X_WRONG_PIPE_VERSION() { return (int)1832L; }

    static final int RPC_S_COOKIE_AUTH_FAILED() { return (int)1833L; }

    static final int RPC_S_DO_NOT_DISTURB() { return (int)1834L; }

    static final int RPC_S_SYSTEM_HANDLE_COUNT_EXCEEDED() { return (int)1835L; }

    static final int RPC_S_SYSTEM_HANDLE_TYPE_MISMATCH() { return (int)1836L; }

    static final int RPC_S_GROUP_MEMBER_NOT_FOUND() { return (int)1898L; }

    static final int EPT_S_CANT_CREATE() { return (int)1899L; }

    static final int RPC_S_INVALID_OBJECT() { return (int)1900L; }

    static final int ERROR_INVALID_TIME() { return (int)1901L; }

    static final int ERROR_INVALID_FORM_NAME() { return (int)1902L; }

    static final int ERROR_INVALID_FORM_SIZE() { return (int)1903L; }

    static final int ERROR_ALREADY_WAITING() { return (int)1904L; }

    static final int ERROR_PRINTER_DELETED() { return (int)1905L; }

    static final int ERROR_INVALID_PRINTER_STATE() { return (int)1906L; }

    static final int ERROR_PASSWORD_MUST_CHANGE() { return (int)1907L; }

    static final int ERROR_DOMAIN_CONTROLLER_NOT_FOUND() { return (int)1908L; }

    static final int ERROR_ACCOUNT_LOCKED_OUT() { return (int)1909L; }

    static final int OR_INVALID_OXID() { return (int)1910L; }

    static final int OR_INVALID_OID() { return (int)1911L; }

    static final int OR_INVALID_SET() { return (int)1912L; }

    static final int RPC_S_SEND_INCOMPLETE() { return (int)1913L; }

    static final int RPC_S_INVALID_ASYNC_HANDLE() { return (int)1914L; }

    static final int RPC_S_INVALID_ASYNC_CALL() { return (int)1915L; }

    static final int RPC_X_PIPE_CLOSED() { return (int)1916L; }

    static final int RPC_X_PIPE_DISCIPLINE_ERROR() { return (int)1917L; }

    static final int RPC_X_PIPE_EMPTY() { return (int)1918L; }

    static final int ERROR_NO_SITENAME() { return (int)1919L; }

    static final int ERROR_CANT_ACCESS_FILE() { return (int)1920L; }

    static final int ERROR_CANT_RESOLVE_FILENAME() { return (int)1921L; }

    static final int RPC_S_ENTRY_TYPE_MISMATCH() { return (int)1922L; }

    static final int RPC_S_NOT_ALL_OBJS_EXPORTED() { return (int)1923L; }

    static final int RPC_S_INTERFACE_NOT_EXPORTED() { return (int)1924L; }

    static final int RPC_S_PROFILE_NOT_ADDED() { return (int)1925L; }

    static final int RPC_S_PRF_ELT_NOT_ADDED() { return (int)1926L; }

    static final int RPC_S_PRF_ELT_NOT_REMOVED() { return (int)1927L; }

    static final int RPC_S_GRP_ELT_NOT_ADDED() { return (int)1928L; }

    static final int RPC_S_GRP_ELT_NOT_REMOVED() { return (int)1929L; }

    static final int ERROR_KM_DRIVER_BLOCKED() { return (int)1930L; }

    static final int ERROR_CONTEXT_EXPIRED() { return (int)1931L; }

    static final int ERROR_PER_USER_TRUST_QUOTA_EXCEEDED() { return (int)1932L; }

    static final int ERROR_ALL_USER_TRUST_QUOTA_EXCEEDED() { return (int)1933L; }

    static final int ERROR_USER_DELETE_TRUST_QUOTA_EXCEEDED() { return (int)1934L; }

    static final int ERROR_AUTHENTICATION_FIREWALL_FAILED() { return (int)1935L; }

    static final int ERROR_REMOTE_PRINT_CONNECTIONS_BLOCKED() { return (int)1936L; }

    static final int ERROR_NTLM_BLOCKED() { return (int)1937L; }

    static final int ERROR_PASSWORD_CHANGE_REQUIRED() { return (int)1938L; }

    static final int ERROR_LOST_MODE_LOGON_RESTRICTION() { return (int)1939L; }

    static final int ERROR_INVALID_PIXEL_FORMAT() { return (int)2000L; }

    static final int ERROR_BAD_DRIVER() { return (int)2001L; }

    static final int ERROR_INVALID_WINDOW_STYLE() { return (int)2002L; }

    static final int ERROR_METAFILE_NOT_SUPPORTED() { return (int)2003L; }

    static final int ERROR_TRANSFORM_NOT_SUPPORTED() { return (int)2004L; }

    static final int ERROR_CLIPPING_NOT_SUPPORTED() { return (int)2005L; }

    static final int ERROR_INVALID_CMM() { return (int)2010L; }

    static final int ERROR_INVALID_PROFILE() { return (int)2011L; }

    static final int ERROR_TAG_NOT_FOUND() { return (int)2012L; }

    static final int ERROR_TAG_NOT_PRESENT() { return (int)2013L; }

    static final int ERROR_DUPLICATE_TAG() { return (int)2014L; }

    static final int ERROR_PROFILE_NOT_ASSOCIATED_WITH_DEVICE() { return (int)2015L; }

    static final int ERROR_PROFILE_NOT_FOUND() { return (int)2016L; }

    static final int ERROR_INVALID_COLORSPACE() { return (int)2017L; }

    static final int ERROR_ICM_NOT_ENABLED() { return (int)2018L; }

    static final int ERROR_DELETING_ICM_XFORM() { return (int)2019L; }

    static final int ERROR_INVALID_TRANSFORM() { return (int)2020L; }

    static final int ERROR_COLORSPACE_MISMATCH() { return (int)2021L; }

    static final int ERROR_INVALID_COLORINDEX() { return (int)2022L; }

    static final int ERROR_PROFILE_DOES_NOT_MATCH_DEVICE() { return (int)2023L; }

    static final int ERROR_CONNECTED_OTHER_PASSWORD() { return (int)2108L; }

    static final int ERROR_CONNECTED_OTHER_PASSWORD_DEFAULT() { return (int)2109L; }

    static final int ERROR_BAD_USERNAME() { return (int)2202L; }

    static final int ERROR_NOT_CONNECTED() { return (int)2250L; }

    static final int ERROR_OPEN_FILES() { return (int)2401L; }

    static final int ERROR_ACTIVE_CONNECTIONS() { return (int)2402L; }

    static final int ERROR_DEVICE_IN_USE() { return (int)2404L; }

    static final int ERROR_UNKNOWN_PRINT_MONITOR() { return (int)3000L; }

    static final int ERROR_PRINTER_DRIVER_IN_USE() { return (int)3001L; }

    static final int ERROR_SPOOL_FILE_NOT_FOUND() { return (int)3002L; }

    static final int ERROR_SPL_NO_STARTDOC() { return (int)3003L; }

    static final int ERROR_SPL_NO_ADDJOB() { return (int)3004L; }

    static final int ERROR_PRINT_PROCESSOR_ALREADY_INSTALLED() { return (int)3005L; }

    static final int ERROR_PRINT_MONITOR_ALREADY_INSTALLED() { return (int)3006L; }

    static final int ERROR_INVALID_PRINT_MONITOR() { return (int)3007L; }

    static final int ERROR_PRINT_MONITOR_IN_USE() { return (int)3008L; }

    static final int ERROR_PRINTER_HAS_JOBS_QUEUED() { return (int)3009L; }

    static final int ERROR_SUCCESS_REBOOT_REQUIRED() { return (int)3010L; }

    static final int ERROR_SUCCESS_RESTART_REQUIRED() { return (int)3011L; }

    static final int ERROR_PRINTER_NOT_FOUND() { return (int)3012L; }

    static final int ERROR_PRINTER_DRIVER_WARNED() { return (int)3013L; }

    static final int ERROR_PRINTER_DRIVER_BLOCKED() { return (int)3014L; }

    static final int ERROR_PRINTER_DRIVER_PACKAGE_IN_USE() { return (int)3015L; }

    static final int ERROR_CORE_DRIVER_PACKAGE_NOT_FOUND() { return (int)3016L; }

    static final int ERROR_FAIL_REBOOT_REQUIRED() { return (int)3017L; }

    static final int ERROR_FAIL_REBOOT_INITIATED() { return (int)3018L; }

    static final int ERROR_PRINTER_DRIVER_DOWNLOAD_NEEDED() { return (int)3019L; }

    static final int ERROR_PRINT_JOB_RESTART_REQUIRED() { return (int)3020L; }

    static final int ERROR_INVALID_PRINTER_DRIVER_MANIFEST() { return (int)3021L; }

    static final int ERROR_PRINTER_NOT_SHAREABLE() { return (int)3022L; }

    static final int ERROR_REQUEST_PAUSED() { return (int)3050L; }

    static final int ERROR_APPEXEC_CONDITION_NOT_SATISFIED() { return (int)3060L; }

    static final int ERROR_APPEXEC_HANDLE_INVALIDATED() { return (int)3061L; }

    static final int ERROR_APPEXEC_INVALID_HOST_GENERATION() { return (int)3062L; }

    static final int ERROR_APPEXEC_UNEXPECTED_PROCESS_REGISTRATION() { return (int)3063L; }

    static final int ERROR_APPEXEC_INVALID_HOST_STATE() { return (int)3064L; }

    static final int ERROR_APPEXEC_NO_DONOR() { return (int)3065L; }

    static final int ERROR_APPEXEC_HOST_ID_MISMATCH() { return (int)3066L; }

    static final int ERROR_APPEXEC_UNKNOWN_USER() { return (int)3067L; }

    static final int ERROR_IO_REISSUE_AS_CACHED() { return (int)3950L; }

    static final int ERROR_WINS_INTERNAL() { return (int)4000L; }

    static final int ERROR_CAN_NOT_DEL_LOCAL_WINS() { return (int)4001L; }

    static final int ERROR_STATIC_INIT() { return (int)4002L; }

    static final int ERROR_INC_BACKUP() { return (int)4003L; }

    static final int ERROR_FULL_BACKUP() { return (int)4004L; }

    static final int ERROR_REC_NON_EXISTENT() { return (int)4005L; }

    static final int ERROR_RPL_NOT_ALLOWED() { return (int)4006L; }

    static final int PEERDIST_ERROR_CONTENTINFO_VERSION_UNSUPPORTED() { return (int)4050L; }

    static final int PEERDIST_ERROR_CANNOT_PARSE_CONTENTINFO() { return (int)4051L; }

    static final int PEERDIST_ERROR_MISSING_DATA() { return (int)4052L; }

    static final int PEERDIST_ERROR_NO_MORE() { return (int)4053L; }

    static final int PEERDIST_ERROR_NOT_INITIALIZED() { return (int)4054L; }

    static final int PEERDIST_ERROR_ALREADY_INITIALIZED() { return (int)4055L; }

    static final int PEERDIST_ERROR_SHUTDOWN_IN_PROGRESS() { return (int)4056L; }

    static final int PEERDIST_ERROR_INVALIDATED() { return (int)4057L; }

    static final int PEERDIST_ERROR_ALREADY_EXISTS() { return (int)4058L; }

    static final int PEERDIST_ERROR_OPERATION_NOTFOUND() { return (int)4059L; }

    static final int PEERDIST_ERROR_ALREADY_COMPLETED() { return (int)4060L; }

    static final int PEERDIST_ERROR_OUT_OF_BOUNDS() { return (int)4061L; }

    static final int PEERDIST_ERROR_VERSION_UNSUPPORTED() { return (int)4062L; }

    static final int PEERDIST_ERROR_INVALID_CONFIGURATION() { return (int)4063L; }

    static final int PEERDIST_ERROR_NOT_LICENSED() { return (int)4064L; }

    static final int PEERDIST_ERROR_SERVICE_UNAVAILABLE() { return (int)4065L; }

    static final int PEERDIST_ERROR_TRUST_FAILURE() { return (int)4066L; }

    static final int ERROR_DHCP_ADDRESS_CONFLICT() { return (int)4100L; }

    static final int ERROR_WMI_GUID_NOT_FOUND() { return (int)4200L; }

    static final int ERROR_WMI_INSTANCE_NOT_FOUND() { return (int)4201L; }

    static final int ERROR_WMI_ITEMID_NOT_FOUND() { return (int)4202L; }

    static final int ERROR_WMI_TRY_AGAIN() { return (int)4203L; }

    static final int ERROR_WMI_DP_NOT_FOUND() { return (int)4204L; }

    static final int ERROR_WMI_UNRESOLVED_INSTANCE_REF() { return (int)4205L; }

    static final int ERROR_WMI_ALREADY_ENABLED() { return (int)4206L; }

    static final int ERROR_WMI_GUID_DISCONNECTED() { return (int)4207L; }

    static final int ERROR_WMI_SERVER_UNAVAILABLE() { return (int)4208L; }

    static final int ERROR_WMI_DP_FAILED() { return (int)4209L; }

    static final int ERROR_WMI_INVALID_MOF() { return (int)4210L; }

    static final int ERROR_WMI_INVALID_REGINFO() { return (int)4211L; }

    static final int ERROR_WMI_ALREADY_DISABLED() { return (int)4212L; }

    static final int ERROR_WMI_READ_ONLY() { return (int)4213L; }

    static final int ERROR_WMI_SET_FAILURE() { return (int)4214L; }

    static final int ERROR_NOT_APPCONTAINER() { return (int)4250L; }

    static final int ERROR_APPCONTAINER_REQUIRED() { return (int)4251L; }

    static final int ERROR_NOT_SUPPORTED_IN_APPCONTAINER() { return (int)4252L; }

    static final int ERROR_INVALID_PACKAGE_SID_LENGTH() { return (int)4253L; }

    static final int ERROR_INVALID_MEDIA() { return (int)4300L; }

    static final int ERROR_INVALID_LIBRARY() { return (int)4301L; }

    static final int ERROR_INVALID_MEDIA_POOL() { return (int)4302L; }

    static final int ERROR_DRIVE_MEDIA_MISMATCH() { return (int)4303L; }

    static final int ERROR_MEDIA_OFFLINE() { return (int)4304L; }

    static final int ERROR_LIBRARY_OFFLINE() { return (int)4305L; }

    static final int ERROR_EMPTY() { return (int)4306L; }

    static final int ERROR_NOT_EMPTY() { return (int)4307L; }

    static final int ERROR_MEDIA_UNAVAILABLE() { return (int)4308L; }

    static final int ERROR_RESOURCE_DISABLED() { return (int)4309L; }

    static final int ERROR_INVALID_CLEANER() { return (int)4310L; }

    static final int ERROR_UNABLE_TO_CLEAN() { return (int)4311L; }

    static final int ERROR_OBJECT_NOT_FOUND() { return (int)4312L; }

    static final int ERROR_DATABASE_FAILURE() { return (int)4313L; }

    static final int ERROR_DATABASE_FULL() { return (int)4314L; }

    static final int ERROR_MEDIA_INCOMPATIBLE() { return (int)4315L; }

    static final int ERROR_RESOURCE_NOT_PRESENT() { return (int)4316L; }

    static final int ERROR_INVALID_OPERATION() { return (int)4317L; }

    static final int ERROR_MEDIA_NOT_AVAILABLE() { return (int)4318L; }

    static final int ERROR_DEVICE_NOT_AVAILABLE() { return (int)4319L; }

    static final int ERROR_REQUEST_REFUSED() { return (int)4320L; }

    static final int ERROR_INVALID_DRIVE_OBJECT() { return (int)4321L; }

    static final int ERROR_LIBRARY_FULL() { return (int)4322L; }

    static final int ERROR_MEDIUM_NOT_ACCESSIBLE() { return (int)4323L; }

    static final int ERROR_UNABLE_TO_LOAD_MEDIUM() { return (int)4324L; }

    static final int ERROR_UNABLE_TO_INVENTORY_DRIVE() { return (int)4325L; }

    static final int ERROR_UNABLE_TO_INVENTORY_SLOT() { return (int)4326L; }

    static final int ERROR_UNABLE_TO_INVENTORY_TRANSPORT() { return (int)4327L; }

    static final int ERROR_TRANSPORT_FULL() { return (int)4328L; }

    static final int ERROR_CONTROLLING_IEPORT() { return (int)4329L; }

    static final int ERROR_UNABLE_TO_EJECT_MOUNTED_MEDIA() { return (int)4330L; }

    static final int ERROR_CLEANER_SLOT_SET() { return (int)4331L; }

    static final int ERROR_CLEANER_SLOT_NOT_SET() { return (int)4332L; }

    static final int ERROR_CLEANER_CARTRIDGE_SPENT() { return (int)4333L; }

    static final int ERROR_UNEXPECTED_OMID() { return (int)4334L; }

    static final int ERROR_CANT_DELETE_LAST_ITEM() { return (int)4335L; }

    static final int ERROR_MESSAGE_EXCEEDS_MAX_SIZE() { return (int)4336L; }

    static final int ERROR_VOLUME_CONTAINS_SYS_FILES() { return (int)4337L; }

    static final int ERROR_INDIGENOUS_TYPE() { return (int)4338L; }

    static final int ERROR_NO_SUPPORTING_DRIVES() { return (int)4339L; }

    static final int ERROR_CLEANER_CARTRIDGE_INSTALLED() { return (int)4340L; }

    static final int ERROR_IEPORT_FULL() { return (int)4341L; }

    static final int ERROR_FILE_OFFLINE() { return (int)4350L; }

    static final int ERROR_REMOTE_STORAGE_NOT_ACTIVE() { return (int)4351L; }

    static final int ERROR_REMOTE_STORAGE_MEDIA_ERROR() { return (int)4352L; }

    static final int ERROR_NOT_A_REPARSE_POINT() { return (int)4390L; }

    static final int ERROR_REPARSE_ATTRIBUTE_CONFLICT() { return (int)4391L; }

    static final int ERROR_INVALID_REPARSE_DATA() { return (int)4392L; }

    static final int ERROR_REPARSE_TAG_INVALID() { return (int)4393L; }

    static final int ERROR_REPARSE_TAG_MISMATCH() { return (int)4394L; }

    static final int ERROR_REPARSE_POINT_ENCOUNTERED() { return (int)4395L; }

    static final int ERROR_APP_DATA_NOT_FOUND() { return (int)4400L; }

    static final int ERROR_APP_DATA_EXPIRED() { return (int)4401L; }

    static final int ERROR_APP_DATA_CORRUPT() { return (int)4402L; }

    static final int ERROR_APP_DATA_LIMIT_EXCEEDED() { return (int)4403L; }

    static final int ERROR_APP_DATA_REBOOT_REQUIRED() { return (int)4404L; }

    static final int ERROR_SECUREBOOT_ROLLBACK_DETECTED() { return (int)4420L; }

    static final int ERROR_SECUREBOOT_POLICY_VIOLATION() { return (int)4421L; }

    static final int ERROR_SECUREBOOT_INVALID_POLICY() { return (int)4422L; }

    static final int ERROR_SECUREBOOT_POLICY_PUBLISHER_NOT_FOUND() { return (int)4423L; }

    static final int ERROR_SECUREBOOT_POLICY_NOT_SIGNED() { return (int)4424L; }

    static final int ERROR_SECUREBOOT_NOT_ENABLED() { return (int)4425L; }

    static final int ERROR_SECUREBOOT_FILE_REPLACED() { return (int)4426L; }

    static final int ERROR_SECUREBOOT_POLICY_NOT_AUTHORIZED() { return (int)4427L; }

    static final int ERROR_SECUREBOOT_POLICY_UNKNOWN() { return (int)4428L; }

    static final int ERROR_SECUREBOOT_POLICY_MISSING_ANTIROLLBACKVERSION() { return (int)4429L; }

    static final int ERROR_SECUREBOOT_PLATFORM_ID_MISMATCH() { return (int)4430L; }

    static final int ERROR_SECUREBOOT_POLICY_ROLLBACK_DETECTED() { return (int)4431L; }

    static final int ERROR_SECUREBOOT_POLICY_UPGRADE_MISMATCH() { return (int)4432L; }

    static final int ERROR_SECUREBOOT_REQUIRED_POLICY_FILE_MISSING() { return (int)4433L; }

    static final int ERROR_SECUREBOOT_NOT_BASE_POLICY() { return (int)4434L; }

    static final int ERROR_SECUREBOOT_NOT_SUPPLEMENTAL_POLICY() { return (int)4435L; }

    static final int ERROR_OFFLOAD_READ_FLT_NOT_SUPPORTED() { return (int)4440L; }

    static final int ERROR_OFFLOAD_WRITE_FLT_NOT_SUPPORTED() { return (int)4441L; }

    static final int ERROR_OFFLOAD_READ_FILE_NOT_SUPPORTED() { return (int)4442L; }

    static final int ERROR_OFFLOAD_WRITE_FILE_NOT_SUPPORTED() { return (int)4443L; }

    static final int ERROR_ALREADY_HAS_STREAM_ID() { return (int)4444L; }

    static final int ERROR_SMR_GARBAGE_COLLECTION_REQUIRED() { return (int)4445L; }

    static final int ERROR_WOF_WIM_HEADER_CORRUPT() { return (int)4446L; }

    static final int ERROR_WOF_WIM_RESOURCE_TABLE_CORRUPT() { return (int)4447L; }

    static final int ERROR_WOF_FILE_RESOURCE_TABLE_CORRUPT() { return (int)4448L; }

    static final int ERROR_VOLUME_NOT_SIS_ENABLED() { return (int)4500L; }

    static final int ERROR_SYSTEM_INTEGRITY_ROLLBACK_DETECTED() { return (int)4550L; }

    static final int ERROR_SYSTEM_INTEGRITY_POLICY_VIOLATION() { return (int)4551L; }

    static final int ERROR_SYSTEM_INTEGRITY_INVALID_POLICY() { return (int)4552L; }

    static final int ERROR_SYSTEM_INTEGRITY_POLICY_NOT_SIGNED() { return (int)4553L; }

    static final int ERROR_SYSTEM_INTEGRITY_TOO_MANY_POLICIES() { return (int)4554L; }

    static final int ERROR_SYSTEM_INTEGRITY_SUPPLEMENTAL_POLICY_NOT_AUTHORIZED() { return (int)4555L; }

    static final int ERROR_VSM_NOT_INITIALIZED() { return (int)4560L; }

    static final int ERROR_VSM_DMA_PROTECTION_NOT_IN_USE() { return (int)4561L; }

    static final int ERROR_PLATFORM_MANIFEST_NOT_AUTHORIZED() { return (int)4570L; }

    static final int ERROR_PLATFORM_MANIFEST_INVALID() { return (int)4571L; }

    static final int ERROR_PLATFORM_MANIFEST_FILE_NOT_AUTHORIZED() { return (int)4572L; }

    static final int ERROR_PLATFORM_MANIFEST_CATALOG_NOT_AUTHORIZED() { return (int)4573L; }

    static final int ERROR_PLATFORM_MANIFEST_BINARY_ID_NOT_FOUND() { return (int)4574L; }

    static final int ERROR_PLATFORM_MANIFEST_NOT_ACTIVE() { return (int)4575L; }

    static final int ERROR_PLATFORM_MANIFEST_NOT_SIGNED() { return (int)4576L; }

    static final int ERROR_DEPENDENT_RESOURCE_EXISTS() { return (int)5001L; }

    static final int ERROR_DEPENDENCY_NOT_FOUND() { return (int)5002L; }

    static final int ERROR_DEPENDENCY_ALREADY_EXISTS() { return (int)5003L; }

    static final int ERROR_RESOURCE_NOT_ONLINE() { return (int)5004L; }

    static final int ERROR_HOST_NODE_NOT_AVAILABLE() { return (int)5005L; }

    static final int ERROR_RESOURCE_NOT_AVAILABLE() { return (int)5006L; }

    static final int ERROR_RESOURCE_NOT_FOUND() { return (int)5007L; }

    static final int ERROR_SHUTDOWN_CLUSTER() { return (int)5008L; }

    static final int ERROR_CANT_EVICT_ACTIVE_NODE() { return (int)5009L; }

    static final int ERROR_OBJECT_ALREADY_EXISTS() { return (int)5010L; }

    static final int ERROR_OBJECT_IN_LIST() { return (int)5011L; }

    static final int ERROR_GROUP_NOT_AVAILABLE() { return (int)5012L; }

    static final int ERROR_GROUP_NOT_FOUND() { return (int)5013L; }

    static final int ERROR_GROUP_NOT_ONLINE() { return (int)5014L; }

    static final int ERROR_HOST_NODE_NOT_RESOURCE_OWNER() { return (int)5015L; }

    static final int ERROR_HOST_NODE_NOT_GROUP_OWNER() { return (int)5016L; }

    static final int ERROR_RESMON_CREATE_FAILED() { return (int)5017L; }

    static final int ERROR_RESMON_ONLINE_FAILED() { return (int)5018L; }

    static final int ERROR_RESOURCE_ONLINE() { return (int)5019L; }

    static final int ERROR_QUORUM_RESOURCE() { return (int)5020L; }

    static final int ERROR_NOT_QUORUM_CAPABLE() { return (int)5021L; }

    static final int ERROR_CLUSTER_SHUTTING_DOWN() { return (int)5022L; }

    static final int ERROR_INVALID_STATE() { return (int)5023L; }

    static final int ERROR_RESOURCE_PROPERTIES_STORED() { return (int)5024L; }

    static final int ERROR_NOT_QUORUM_CLASS() { return (int)5025L; }

    static final int ERROR_CORE_RESOURCE() { return (int)5026L; }

    static final int ERROR_QUORUM_RESOURCE_ONLINE_FAILED() { return (int)5027L; }

    static final int ERROR_QUORUMLOG_OPEN_FAILED() { return (int)5028L; }

    static final int ERROR_CLUSTERLOG_CORRUPT() { return (int)5029L; }

    static final int ERROR_CLUSTERLOG_RECORD_EXCEEDS_MAXSIZE() { return (int)5030L; }

    static final int ERROR_CLUSTERLOG_EXCEEDS_MAXSIZE() { return (int)5031L; }

    static final int ERROR_CLUSTERLOG_CHKPOINT_NOT_FOUND() { return (int)5032L; }

    static final int ERROR_CLUSTERLOG_NOT_ENOUGH_SPACE() { return (int)5033L; }

}

