// Generated by jextract

package com.github.tornaia.win.cfapi;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import jdk.incubator.foreign.*;
import jdk.incubator.foreign.MemoryLayout.PathElement;
import static jdk.incubator.foreign.CLinker.*;
class cfapi_h$constants$3 extends cfapi_h$constants$2 {

    /* package-private */ cfapi_h$constants$3() {}
    static final int RPI_FLAG_SMB2_SHARECAP_DFS() { return (int)8L; }

    static final int RPI_FLAG_SMB2_SHARECAP_CONTINUOUS_AVAILABILITY() { return (int)16L; }

    static final int RPI_FLAG_SMB2_SHARECAP_SCALEOUT() { return (int)32L; }

    static final int RPI_FLAG_SMB2_SHARECAP_CLUSTER() { return (int)64L; }

    static final int RPI_SMB2_FLAG_SERVERCAP_DFS() { return (int)1L; }

    static final int RPI_SMB2_FLAG_SERVERCAP_LEASING() { return (int)2L; }

    static final int RPI_SMB2_FLAG_SERVERCAP_LARGEMTU() { return (int)4L; }

    static final int RPI_SMB2_FLAG_SERVERCAP_MULTICHANNEL() { return (int)8L; }

    static final int RPI_SMB2_FLAG_SERVERCAP_PERSISTENT_HANDLES() { return (int)16L; }

    static final int RPI_SMB2_FLAG_SERVERCAP_DIRECTORY_LEASING() { return (int)32L; }

    static final int MICROSOFT_WINBASE_H_DEFINE_INTERLOCKED_CPLUSPLUS_OVERLOADS() { return (int)0L; }

    static final int R2_BLACK() { return (int)1L; }

    static final int R2_NOTMERGEPEN() { return (int)2L; }

    static final int R2_MASKNOTPEN() { return (int)3L; }

    static final int R2_NOTCOPYPEN() { return (int)4L; }

    static final int R2_MASKPENNOT() { return (int)5L; }

    static final int R2_NOT() { return (int)6L; }

    static final int R2_XORPEN() { return (int)7L; }

    static final int R2_NOTMASKPEN() { return (int)8L; }

    static final int R2_MASKPEN() { return (int)9L; }

    static final int R2_NOTXORPEN() { return (int)10L; }

    static final int R2_NOP() { return (int)11L; }

    static final int R2_MERGENOTPEN() { return (int)12L; }

    static final int R2_COPYPEN() { return (int)13L; }

    static final int R2_MERGEPENNOT() { return (int)14L; }

    static final int R2_MERGEPEN() { return (int)15L; }

    static final int R2_WHITE() { return (int)16L; }

    static final int R2_LAST() { return (int)16L; }

    static final int ERROR() { return (int)0L; }

    static final int NULLREGION() { return (int)1L; }

    static final int SIMPLEREGION() { return (int)2L; }

    static final int COMPLEXREGION() { return (int)3L; }

    static final int RGN_AND() { return (int)1L; }

    static final int RGN_OR() { return (int)2L; }

    static final int RGN_XOR() { return (int)3L; }

    static final int RGN_DIFF() { return (int)4L; }

    static final int RGN_COPY() { return (int)5L; }

    static final int BLACKONWHITE() { return (int)1L; }

    static final int WHITEONBLACK() { return (int)2L; }

    static final int COLORONCOLOR() { return (int)3L; }

    static final int HALFTONE() { return (int)4L; }

    static final int MAXSTRETCHBLTMODE() { return (int)4L; }

    static final int ALTERNATE() { return (int)1L; }

    static final int WINDING() { return (int)2L; }

    static final int POLYFILL_LAST() { return (int)2L; }

    static final int LAYOUT_RTL() { return (int)1L; }

    static final int LAYOUT_BTT() { return (int)2L; }

    static final int LAYOUT_VBH() { return (int)4L; }

    static final int LAYOUT_BITMAPORIENTATIONPRESERVED() { return (int)8L; }

    static final int TA_NOUPDATECP() { return (int)0L; }

    static final int TA_UPDATECP() { return (int)1L; }

    static final int TA_LEFT() { return (int)0L; }

    static final int TA_RIGHT() { return (int)2L; }

    static final int TA_CENTER() { return (int)6L; }

    static final int TA_TOP() { return (int)0L; }

    static final int TA_BOTTOM() { return (int)8L; }

    static final int TA_BASELINE() { return (int)24L; }

    static final int TA_RTLREADING() { return (int)256L; }

    static final int ETO_OPAQUE() { return (int)2L; }

    static final int ETO_CLIPPED() { return (int)4L; }

    static final int ETO_GLYPH_INDEX() { return (int)16L; }

    static final int ETO_RTLREADING() { return (int)128L; }

    static final int ETO_NUMERICSLOCAL() { return (int)1024L; }

    static final int ETO_NUMERICSLATIN() { return (int)2048L; }

    static final int ETO_IGNORELANGUAGE() { return (int)4096L; }

    static final int ETO_PDY() { return (int)8192L; }

    static final int ETO_REVERSE_INDEX_MAP() { return (int)65536L; }

    static final int ASPECT_FILTERING() { return (int)1L; }

    static final int DCB_RESET() { return (int)1L; }

    static final int DCB_ACCUMULATE() { return (int)2L; }

    static final int DCB_ENABLE() { return (int)4L; }

    static final int DCB_DISABLE() { return (int)8L; }

    static final int META_SETBKCOLOR() { return (int)513L; }

    static final int META_SETBKMODE() { return (int)258L; }

    static final int META_SETMAPMODE() { return (int)259L; }

    static final int META_SETROP2() { return (int)260L; }

    static final int META_SETRELABS() { return (int)261L; }

    static final int META_SETPOLYFILLMODE() { return (int)262L; }

    static final int META_SETSTRETCHBLTMODE() { return (int)263L; }

    static final int META_SETTEXTCHAREXTRA() { return (int)264L; }

    static final int META_SETTEXTCOLOR() { return (int)521L; }

    static final int META_SETTEXTJUSTIFICATION() { return (int)522L; }

    static final int META_SETWINDOWORG() { return (int)523L; }

    static final int META_SETWINDOWEXT() { return (int)524L; }

    static final int META_SETVIEWPORTORG() { return (int)525L; }

    static final int META_SETVIEWPORTEXT() { return (int)526L; }

    static final int META_OFFSETWINDOWORG() { return (int)527L; }

    static final int META_SCALEWINDOWEXT() { return (int)1040L; }

    static final int META_OFFSETVIEWPORTORG() { return (int)529L; }

    static final int META_SCALEVIEWPORTEXT() { return (int)1042L; }

    static final int META_LINETO() { return (int)531L; }

    static final int META_MOVETO() { return (int)532L; }

    static final int META_EXCLUDECLIPRECT() { return (int)1045L; }

    static final int META_INTERSECTCLIPRECT() { return (int)1046L; }

    static final int META_ARC() { return (int)2071L; }

    static final int META_ELLIPSE() { return (int)1048L; }

    static final int META_FLOODFILL() { return (int)1049L; }

    static final int META_PIE() { return (int)2074L; }

    static final int META_RECTANGLE() { return (int)1051L; }

    static final int META_ROUNDRECT() { return (int)1564L; }

    static final int META_PATBLT() { return (int)1565L; }

    static final int META_SAVEDC() { return (int)30L; }

    static final int META_SETPIXEL() { return (int)1055L; }

    static final int META_OFFSETCLIPRGN() { return (int)544L; }

    static final int META_TEXTOUT() { return (int)1313L; }

    static final int META_BITBLT() { return (int)2338L; }

    static final int META_STRETCHBLT() { return (int)2851L; }

    static final int META_POLYGON() { return (int)804L; }

    static final int META_POLYLINE() { return (int)805L; }

    static final int META_ESCAPE() { return (int)1574L; }

    static final int META_RESTOREDC() { return (int)295L; }

    static final int META_FILLREGION() { return (int)552L; }

    static final int META_FRAMEREGION() { return (int)1065L; }

    static final int META_INVERTREGION() { return (int)298L; }

    static final int META_PAINTREGION() { return (int)299L; }

    static final int META_SELECTCLIPREGION() { return (int)300L; }

    static final int META_SELECTOBJECT() { return (int)301L; }

    static final int META_SETTEXTALIGN() { return (int)302L; }

    static final int META_CHORD() { return (int)2096L; }

    static final int META_SETMAPPERFLAGS() { return (int)561L; }

    static final int META_EXTTEXTOUT() { return (int)2610L; }

    static final int META_SETDIBTODEV() { return (int)3379L; }

    static final int META_SELECTPALETTE() { return (int)564L; }

    static final int META_REALIZEPALETTE() { return (int)53L; }

    static final int META_ANIMATEPALETTE() { return (int)1078L; }

    static final int META_SETPALENTRIES() { return (int)55L; }

    static final int META_POLYPOLYGON() { return (int)1336L; }

    static final int META_RESIZEPALETTE() { return (int)313L; }

    static final int META_DIBBITBLT() { return (int)2368L; }

    static final int META_DIBSTRETCHBLT() { return (int)2881L; }

    static final int META_DIBCREATEPATTERNBRUSH() { return (int)322L; }

    static final int META_STRETCHDIB() { return (int)3907L; }

    static final int META_EXTFLOODFILL() { return (int)1352L; }

    static final int META_SETLAYOUT() { return (int)329L; }

    static final int META_DELETEOBJECT() { return (int)496L; }

    static final int META_CREATEPALETTE() { return (int)247L; }

    static final int META_CREATEPATTERNBRUSH() { return (int)505L; }

    static final int META_CREATEPENINDIRECT() { return (int)762L; }

    static final int META_CREATEFONTINDIRECT() { return (int)763L; }

    static final int META_CREATEBRUSHINDIRECT() { return (int)764L; }

    static final int META_CREATEREGION() { return (int)1791L; }

    static final int NEWFRAME() { return (int)1L; }

    static final int ABORTDOC() { return (int)2L; }

    static final int NEXTBAND() { return (int)3L; }

    static final int SETCOLORTABLE() { return (int)4L; }

    static final int GETCOLORTABLE() { return (int)5L; }

    static final int FLUSHOUTPUT() { return (int)6L; }

    static final int DRAFTMODE() { return (int)7L; }

    static final int QUERYESCSUPPORT() { return (int)8L; }

    static final int SETABORTPROC() { return (int)9L; }

    static final int STARTDOC() { return (int)10L; }

    static final int ENDDOC() { return (int)11L; }

    static final int GETPHYSPAGESIZE() { return (int)12L; }

    static final int GETPRINTINGOFFSET() { return (int)13L; }

    static final int GETSCALINGFACTOR() { return (int)14L; }

    static final int MFCOMMENT() { return (int)15L; }

    static final int GETPENWIDTH() { return (int)16L; }

    static final int SETCOPYCOUNT() { return (int)17L; }

    static final int SELECTPAPERSOURCE() { return (int)18L; }

    static final int DEVICEDATA() { return (int)19L; }

    static final int PASSTHROUGH() { return (int)19L; }

    static final int GETTECHNOLGY() { return (int)20L; }

    static final int GETTECHNOLOGY() { return (int)20L; }

    static final int SETLINECAP() { return (int)21L; }

    static final int SETLINEJOIN() { return (int)22L; }

    static final int SETMITERLIMIT() { return (int)23L; }

    static final int BANDINFO() { return (int)24L; }

    static final int DRAWPATTERNRECT() { return (int)25L; }

    static final int GETVECTORPENSIZE() { return (int)26L; }

    static final int GETVECTORBRUSHSIZE() { return (int)27L; }

    static final int ENABLEDUPLEX() { return (int)28L; }

    static final int GETSETPAPERBINS() { return (int)29L; }

    static final int GETSETPRINTORIENT() { return (int)30L; }

    static final int ENUMPAPERBINS() { return (int)31L; }

    static final int SETDIBSCALING() { return (int)32L; }

    static final int EPSPRINTING() { return (int)33L; }

    static final int ENUMPAPERMETRICS() { return (int)34L; }

    static final int GETSETPAPERMETRICS() { return (int)35L; }

    static final int POSTSCRIPT_DATA() { return (int)37L; }

    static final int POSTSCRIPT_IGNORE() { return (int)38L; }

    static final int MOUSETRAILS() { return (int)39L; }

    static final int GETDEVICEUNITS() { return (int)42L; }

    static final int GETEXTENDEDTEXTMETRICS() { return (int)256L; }

    static final int GETEXTENTTABLE() { return (int)257L; }

    static final int GETPAIRKERNTABLE() { return (int)258L; }

    static final int GETTRACKKERNTABLE() { return (int)259L; }

    static final int EXTTEXTOUT() { return (int)512L; }

    static final int GETFACENAME() { return (int)513L; }

    static final int DOWNLOADFACE() { return (int)514L; }

    static final int ENABLERELATIVEWIDTHS() { return (int)768L; }

    static final int ENABLEPAIRKERNING() { return (int)769L; }

    static final int SETKERNTRACK() { return (int)770L; }

    static final int SETALLJUSTVALUES() { return (int)771L; }

    static final int SETCHARSET() { return (int)772L; }

    static final int STRETCHBLT() { return (int)2048L; }

    static final int METAFILE_DRIVER() { return (int)2049L; }

    static final int GETSETSCREENPARAMS() { return (int)3072L; }

    static final int QUERYDIBSUPPORT() { return (int)3073L; }

    static final int BEGIN_PATH() { return (int)4096L; }

    static final int CLIP_TO_PATH() { return (int)4097L; }

    static final int END_PATH() { return (int)4098L; }

    static final int EXT_DEVICE_CAPS() { return (int)4099L; }

    static final int RESTORE_CTM() { return (int)4100L; }

    static final int SAVE_CTM() { return (int)4101L; }

    static final int SET_ARC_DIRECTION() { return (int)4102L; }

    static final int SET_BACKGROUND_COLOR() { return (int)4103L; }

    static final int SET_POLY_MODE() { return (int)4104L; }

    static final int SET_SCREEN_ANGLE() { return (int)4105L; }

    static final int SET_SPREAD() { return (int)4106L; }

    static final int TRANSFORM_CTM() { return (int)4107L; }

    static final int SET_CLIP_BOX() { return (int)4108L; }

    static final int SET_BOUNDS() { return (int)4109L; }

    static final int SET_MIRROR_MODE() { return (int)4110L; }

    static final int OPENCHANNEL() { return (int)4110L; }

    static final int DOWNLOADHEADER() { return (int)4111L; }

    static final int CLOSECHANNEL() { return (int)4112L; }

    static final int POSTSCRIPT_PASSTHROUGH() { return (int)4115L; }

    static final int ENCAPSULATED_POSTSCRIPT() { return (int)4116L; }

    static final int POSTSCRIPT_IDENTIFY() { return (int)4117L; }

    static final int POSTSCRIPT_INJECTION() { return (int)4118L; }

    static final int CHECKJPEGFORMAT() { return (int)4119L; }

    static final int CHECKPNGFORMAT() { return (int)4120L; }

    static final int GET_PS_FEATURESETTING() { return (int)4121L; }

    static final int GDIPLUS_TS_QUERYVER() { return (int)4122L; }

    static final int GDIPLUS_TS_RECORD() { return (int)4123L; }

    static final int MILCORE_TS_QUERYVER_RESULT_FALSE() { return (int)0L; }

    static final int MILCORE_TS_QUERYVER_RESULT_TRUE() { return (int)2147483647L; }

    static final int SPCLPASSTHROUGH2() { return (int)4568L; }

    static final int PSIDENT_GDICENTRIC() { return (int)0L; }

    static final int PSIDENT_PSCENTRIC() { return (int)1L; }

    static final int PSINJECT_BEGINSTREAM() { return (int)1L; }

    static final int PSINJECT_PSADOBE() { return (int)2L; }

    static final int PSINJECT_PAGESATEND() { return (int)3L; }

    static final int PSINJECT_PAGES() { return (int)4L; }

    static final int PSINJECT_DOCNEEDEDRES() { return (int)5L; }

    static final int PSINJECT_DOCSUPPLIEDRES() { return (int)6L; }

    static final int PSINJECT_PAGEORDER() { return (int)7L; }

    static final int PSINJECT_ORIENTATION() { return (int)8L; }

    static final int PSINJECT_BOUNDINGBOX() { return (int)9L; }

    static final int PSINJECT_DOCUMENTPROCESSCOLORS() { return (int)10L; }

    static final int PSINJECT_COMMENTS() { return (int)11L; }

    static final int PSINJECT_BEGINDEFAULTS() { return (int)12L; }

    static final int PSINJECT_ENDDEFAULTS() { return (int)13L; }

    static final int PSINJECT_BEGINPROLOG() { return (int)14L; }

    static final int PSINJECT_ENDPROLOG() { return (int)15L; }

    static final int PSINJECT_BEGINSETUP() { return (int)16L; }

    static final int PSINJECT_ENDSETUP() { return (int)17L; }

    static final int PSINJECT_TRAILER() { return (int)18L; }

    static final int PSINJECT_EOF() { return (int)19L; }

    static final int PSINJECT_ENDSTREAM() { return (int)20L; }

    static final int PSINJECT_DOCUMENTPROCESSCOLORSATEND() { return (int)21L; }

    static final int PSINJECT_PAGENUMBER() { return (int)100L; }

    static final int PSINJECT_BEGINPAGESETUP() { return (int)101L; }

    static final int PSINJECT_ENDPAGESETUP() { return (int)102L; }

    static final int PSINJECT_PAGETRAILER() { return (int)103L; }

    static final int PSINJECT_PLATECOLOR() { return (int)104L; }

    static final int PSINJECT_SHOWPAGE() { return (int)105L; }

    static final int PSINJECT_PAGEBBOX() { return (int)106L; }

    static final int PSINJECT_ENDPAGECOMMENTS() { return (int)107L; }

    static final int PSINJECT_VMSAVE() { return (int)200L; }

    static final int PSINJECT_VMRESTORE() { return (int)201L; }

    static final int FEATURESETTING_NUP() { return (int)0L; }

    static final int FEATURESETTING_OUTPUT() { return (int)1L; }

    static final int FEATURESETTING_PSLEVEL() { return (int)2L; }

    static final int FEATURESETTING_CUSTPAPER() { return (int)3L; }

    static final int FEATURESETTING_MIRROR() { return (int)4L; }

    static final int FEATURESETTING_NEGATIVE() { return (int)5L; }

    static final int FEATURESETTING_PROTOCOL() { return (int)6L; }

    static final int FEATURESETTING_PRIVATE_BEGIN() { return (int)4096L; }

    static final int FEATURESETTING_PRIVATE_END() { return (int)8191L; }

    static final int PSPROTOCOL_ASCII() { return (int)0L; }

    static final int PSPROTOCOL_BCP() { return (int)1L; }

    static final int PSPROTOCOL_TBCP() { return (int)2L; }

    static final int PSPROTOCOL_BINARY() { return (int)3L; }

    static final int QDI_SETDIBITS() { return (int)1L; }

    static final int QDI_GETDIBITS() { return (int)2L; }

    static final int QDI_DIBTOSCREEN() { return (int)4L; }

    static final int QDI_STRETCHDIB() { return (int)8L; }

    static final int SP_NOTREPORTED() { return (int)16384L; }

    static final int PR_JOBSTATUS() { return (int)0L; }

    static final int OBJ_PEN() { return (int)1L; }

    static final int OBJ_BRUSH() { return (int)2L; }

    static final int OBJ_DC() { return (int)3L; }

    static final int OBJ_METADC() { return (int)4L; }

    static final int OBJ_PAL() { return (int)5L; }

    static final int OBJ_FONT() { return (int)6L; }

    static final int OBJ_BITMAP() { return (int)7L; }

    static final int OBJ_REGION() { return (int)8L; }

    static final int OBJ_METAFILE() { return (int)9L; }

    static final int OBJ_MEMDC() { return (int)10L; }

    static final int OBJ_EXTPEN() { return (int)11L; }

    static final int OBJ_ENHMETADC() { return (int)12L; }

    static final int OBJ_ENHMETAFILE() { return (int)13L; }

    static final int OBJ_COLORSPACE() { return (int)14L; }

    static final int MWT_IDENTITY() { return (int)1L; }

    static final int MWT_LEFTMULTIPLY() { return (int)2L; }

    static final int MWT_RIGHTMULTIPLY() { return (int)3L; }

    static final int CM_OUT_OF_GAMUT() { return (int)255L; }

    static final int CM_IN_GAMUT() { return (int)0L; }

    static final int ICM_ADDPROFILE() { return (int)1L; }

    static final int ICM_DELETEPROFILE() { return (int)2L; }

    static final int ICM_QUERYPROFILE() { return (int)3L; }

    static final int ICM_SETDEFAULTPROFILE() { return (int)4L; }

    static final int ICM_REGISTERICMATCHER() { return (int)5L; }

    static final int ICM_UNREGISTERICMATCHER() { return (int)6L; }

    static final int ICM_QUERYMATCH() { return (int)7L; }

    static final int TCI_SRCCHARSET() { return (int)1L; }

    static final int TCI_SRCCODEPAGE() { return (int)2L; }

    static final int TCI_SRCFONTSIG() { return (int)3L; }

    static final int TCI_SRCLOCALE() { return (int)4096L; }

    static final int TMPF_FIXED_PITCH() { return (int)1L; }

    static final int TMPF_VECTOR() { return (int)2L; }

    static final int TMPF_DEVICE() { return (int)8L; }

    static final int TMPF_TRUETYPE() { return (int)4L; }

    static final int NTM_NONNEGATIVE_AC() { return (int)65536L; }

    static final int NTM_PS_OPENTYPE() { return (int)131072L; }

    static final int NTM_TT_OPENTYPE() { return (int)262144L; }

    static final int NTM_MULTIPLEMASTER() { return (int)524288L; }

    static final int NTM_TYPE1() { return (int)1048576L; }

    static final int NTM_DSIG() { return (int)2097152L; }

    static final int LF_FACESIZE() { return (int)32L; }

    static final int LF_FULLFACESIZE() { return (int)64L; }

    static final int OUT_DEFAULT_PRECIS() { return (int)0L; }

    static final int OUT_STRING_PRECIS() { return (int)1L; }

    static final int OUT_CHARACTER_PRECIS() { return (int)2L; }

    static final int OUT_STROKE_PRECIS() { return (int)3L; }

    static final int OUT_TT_PRECIS() { return (int)4L; }

    static final int OUT_DEVICE_PRECIS() { return (int)5L; }

    static final int OUT_RASTER_PRECIS() { return (int)6L; }

    static final int OUT_TT_ONLY_PRECIS() { return (int)7L; }

    static final int OUT_OUTLINE_PRECIS() { return (int)8L; }

    static final int OUT_SCREEN_OUTLINE_PRECIS() { return (int)9L; }

    static final int OUT_PS_ONLY_PRECIS() { return (int)10L; }

    static final int CLIP_DEFAULT_PRECIS() { return (int)0L; }

    static final int CLIP_CHARACTER_PRECIS() { return (int)1L; }

    static final int CLIP_STROKE_PRECIS() { return (int)2L; }

    static final int CLIP_MASK() { return (int)15L; }

    static final int DEFAULT_QUALITY() { return (int)0L; }

    static final int DRAFT_QUALITY() { return (int)1L; }

    static final int PROOF_QUALITY() { return (int)2L; }

    static final int NONANTIALIASED_QUALITY() { return (int)3L; }

    static final int ANTIALIASED_QUALITY() { return (int)4L; }

    static final int CLEARTYPE_QUALITY() { return (int)5L; }

    static final int CLEARTYPE_NATURAL_QUALITY() { return (int)6L; }

    static final int DEFAULT_PITCH() { return (int)0L; }

    static final int FIXED_PITCH() { return (int)1L; }

    static final int VARIABLE_PITCH() { return (int)2L; }

    static final int MONO_FONT() { return (int)8L; }

    static final int ANSI_CHARSET() { return (int)0L; }

    static final int DEFAULT_CHARSET() { return (int)1L; }

    static final int SYMBOL_CHARSET() { return (int)2L; }

    static final int SHIFTJIS_CHARSET() { return (int)128L; }

    static final int HANGEUL_CHARSET() { return (int)129L; }

    static final int HANGUL_CHARSET() { return (int)129L; }

    static final int GB2312_CHARSET() { return (int)134L; }

    static final int CHINESEBIG5_CHARSET() { return (int)136L; }

    static final int OEM_CHARSET() { return (int)255L; }

    static final int JOHAB_CHARSET() { return (int)130L; }

    static final int HEBREW_CHARSET() { return (int)177L; }

    static final int ARABIC_CHARSET() { return (int)178L; }

    static final int GREEK_CHARSET() { return (int)161L; }

    static final int TURKISH_CHARSET() { return (int)162L; }

    static final int VIETNAMESE_CHARSET() { return (int)163L; }

    static final int THAI_CHARSET() { return (int)222L; }

    static final int EASTEUROPE_CHARSET() { return (int)238L; }

    static final int RUSSIAN_CHARSET() { return (int)204L; }

    static final int MAC_CHARSET() { return (int)77L; }

    static final int BALTIC_CHARSET() { return (int)186L; }

    static final int FW_DONTCARE() { return (int)0L; }

    static final int FW_THIN() { return (int)100L; }

    static final int FW_EXTRALIGHT() { return (int)200L; }

    static final int FW_LIGHT() { return (int)300L; }

    static final int FW_NORMAL() { return (int)400L; }

    static final int FW_MEDIUM() { return (int)500L; }

    static final int FW_SEMIBOLD() { return (int)600L; }

    static final int FW_BOLD() { return (int)700L; }

    static final int FW_EXTRABOLD() { return (int)800L; }

    static final int FW_HEAVY() { return (int)900L; }

    static final int PANOSE_COUNT() { return (int)10L; }

    static final int PAN_FAMILYTYPE_INDEX() { return (int)0L; }

    static final int PAN_SERIFSTYLE_INDEX() { return (int)1L; }

    static final int PAN_WEIGHT_INDEX() { return (int)2L; }

    static final int PAN_PROPORTION_INDEX() { return (int)3L; }

    static final int PAN_CONTRAST_INDEX() { return (int)4L; }

    static final int PAN_STROKEVARIATION_INDEX() { return (int)5L; }

    static final int PAN_ARMSTYLE_INDEX() { return (int)6L; }

    static final int PAN_LETTERFORM_INDEX() { return (int)7L; }

    static final int PAN_MIDLINE_INDEX() { return (int)8L; }

    static final int PAN_XHEIGHT_INDEX() { return (int)9L; }

    static final int PAN_CULTURE_LATIN() { return (int)0L; }

    static final int PAN_ANY() { return (int)0L; }

    static final int PAN_NO_FIT() { return (int)1L; }

    static final int PAN_FAMILY_TEXT_DISPLAY() { return (int)2L; }

    static final int PAN_FAMILY_SCRIPT() { return (int)3L; }

    static final int PAN_FAMILY_DECORATIVE() { return (int)4L; }

    static final int PAN_FAMILY_PICTORIAL() { return (int)5L; }

    static final int PAN_SERIF_COVE() { return (int)2L; }

    static final int PAN_SERIF_OBTUSE_COVE() { return (int)3L; }

    static final int PAN_SERIF_SQUARE_COVE() { return (int)4L; }

    static final int PAN_SERIF_OBTUSE_SQUARE_COVE() { return (int)5L; }

    static final int PAN_SERIF_SQUARE() { return (int)6L; }

    static final int PAN_SERIF_THIN() { return (int)7L; }

    static final int PAN_SERIF_BONE() { return (int)8L; }

    static final int PAN_SERIF_EXAGGERATED() { return (int)9L; }

    static final int PAN_SERIF_TRIANGLE() { return (int)10L; }

    static final int PAN_SERIF_NORMAL_SANS() { return (int)11L; }

    static final int PAN_SERIF_OBTUSE_SANS() { return (int)12L; }

    static final int PAN_SERIF_PERP_SANS() { return (int)13L; }

    static final int PAN_SERIF_FLARED() { return (int)14L; }

    static final int PAN_SERIF_ROUNDED() { return (int)15L; }

    static final int PAN_WEIGHT_VERY_LIGHT() { return (int)2L; }

    static final int PAN_WEIGHT_LIGHT() { return (int)3L; }

    static final int PAN_WEIGHT_THIN() { return (int)4L; }

    static final int PAN_WEIGHT_BOOK() { return (int)5L; }

    static final int PAN_WEIGHT_MEDIUM() { return (int)6L; }

    static final int PAN_WEIGHT_DEMI() { return (int)7L; }

    static final int PAN_WEIGHT_BOLD() { return (int)8L; }

    static final int PAN_WEIGHT_HEAVY() { return (int)9L; }

    static final int PAN_WEIGHT_BLACK() { return (int)10L; }

    static final int PAN_WEIGHT_NORD() { return (int)11L; }

    static final int PAN_PROP_OLD_STYLE() { return (int)2L; }

    static final int PAN_PROP_MODERN() { return (int)3L; }

    static final int PAN_PROP_EVEN_WIDTH() { return (int)4L; }

    static final int PAN_PROP_EXPANDED() { return (int)5L; }

    static final int PAN_PROP_CONDENSED() { return (int)6L; }

    static final int PAN_PROP_VERY_EXPANDED() { return (int)7L; }

    static final int PAN_PROP_VERY_CONDENSED() { return (int)8L; }

    static final int PAN_PROP_MONOSPACED() { return (int)9L; }

    static final int PAN_CONTRAST_NONE() { return (int)2L; }

    static final int PAN_CONTRAST_VERY_LOW() { return (int)3L; }

    static final int PAN_CONTRAST_LOW() { return (int)4L; }

    static final int PAN_CONTRAST_MEDIUM_LOW() { return (int)5L; }

    static final int PAN_CONTRAST_MEDIUM() { return (int)6L; }

    static final int PAN_CONTRAST_MEDIUM_HIGH() { return (int)7L; }

    static final int PAN_CONTRAST_HIGH() { return (int)8L; }

    static final int PAN_CONTRAST_VERY_HIGH() { return (int)9L; }

    static final int PAN_STROKE_GRADUAL_DIAG() { return (int)2L; }

    static final int PAN_STROKE_GRADUAL_TRAN() { return (int)3L; }

    static final int PAN_STROKE_GRADUAL_VERT() { return (int)4L; }

    static final int PAN_STROKE_GRADUAL_HORZ() { return (int)5L; }

    static final int PAN_STROKE_RAPID_VERT() { return (int)6L; }

    static final int PAN_STROKE_RAPID_HORZ() { return (int)7L; }

    static final int PAN_STROKE_INSTANT_VERT() { return (int)8L; }

    static final int PAN_STRAIGHT_ARMS_HORZ() { return (int)2L; }

    static final int PAN_STRAIGHT_ARMS_WEDGE() { return (int)3L; }

    static final int PAN_STRAIGHT_ARMS_VERT() { return (int)4L; }

    static final int PAN_STRAIGHT_ARMS_SINGLE_SERIF() { return (int)5L; }

    static final int PAN_STRAIGHT_ARMS_DOUBLE_SERIF() { return (int)6L; }

    static final int PAN_BENT_ARMS_HORZ() { return (int)7L; }

    static final int PAN_BENT_ARMS_WEDGE() { return (int)8L; }

    static final int PAN_BENT_ARMS_VERT() { return (int)9L; }

    static final int PAN_BENT_ARMS_SINGLE_SERIF() { return (int)10L; }

    static final int PAN_BENT_ARMS_DOUBLE_SERIF() { return (int)11L; }

    static final int PAN_LETT_NORMAL_CONTACT() { return (int)2L; }

    static final int PAN_LETT_NORMAL_WEIGHTED() { return (int)3L; }

    static final int PAN_LETT_NORMAL_BOXED() { return (int)4L; }

    static final int PAN_LETT_NORMAL_FLATTENED() { return (int)5L; }

    static final int PAN_LETT_NORMAL_ROUNDED() { return (int)6L; }

    static final int PAN_LETT_NORMAL_OFF_CENTER() { return (int)7L; }

    static final int PAN_LETT_NORMAL_SQUARE() { return (int)8L; }

    static final int PAN_LETT_OBLIQUE_CONTACT() { return (int)9L; }

    static final int PAN_LETT_OBLIQUE_WEIGHTED() { return (int)10L; }

    static final int PAN_LETT_OBLIQUE_BOXED() { return (int)11L; }

    static final int PAN_LETT_OBLIQUE_FLATTENED() { return (int)12L; }

    static final int PAN_LETT_OBLIQUE_ROUNDED() { return (int)13L; }

    static final int PAN_LETT_OBLIQUE_OFF_CENTER() { return (int)14L; }

    static final int PAN_LETT_OBLIQUE_SQUARE() { return (int)15L; }

    static final int PAN_MIDLINE_STANDARD_TRIMMED() { return (int)2L; }

    static final int PAN_MIDLINE_STANDARD_POINTED() { return (int)3L; }

    static final int PAN_MIDLINE_STANDARD_SERIFED() { return (int)4L; }

    static final int PAN_MIDLINE_HIGH_TRIMMED() { return (int)5L; }

    static final int PAN_MIDLINE_HIGH_POINTED() { return (int)6L; }

    static final int PAN_MIDLINE_HIGH_SERIFED() { return (int)7L; }

    static final int PAN_MIDLINE_CONSTANT_TRIMMED() { return (int)8L; }

    static final int PAN_MIDLINE_CONSTANT_POINTED() { return (int)9L; }

    static final int PAN_MIDLINE_CONSTANT_SERIFED() { return (int)10L; }

    static final int PAN_MIDLINE_LOW_TRIMMED() { return (int)11L; }

    static final int PAN_MIDLINE_LOW_POINTED() { return (int)12L; }

    static final int PAN_MIDLINE_LOW_SERIFED() { return (int)13L; }

    static final int PAN_XHEIGHT_CONSTANT_SMALL() { return (int)2L; }

    static final int PAN_XHEIGHT_CONSTANT_STD() { return (int)3L; }

    static final int PAN_XHEIGHT_CONSTANT_LARGE() { return (int)4L; }

    static final int PAN_XHEIGHT_DUCKING_SMALL() { return (int)5L; }

    static final int PAN_XHEIGHT_DUCKING_STD() { return (int)6L; }

    static final int PAN_XHEIGHT_DUCKING_LARGE() { return (int)7L; }

    static final int ELF_VENDOR_SIZE() { return (int)4L; }

    static final int ELF_VERSION() { return (int)0L; }

    static final int ELF_CULTURE_LATIN() { return (int)0L; }

    static final int RASTER_FONTTYPE() { return (int)1L; }

    static final int DEVICE_FONTTYPE() { return (int)2L; }

    static final int TRUETYPE_FONTTYPE() { return (int)4L; }

    static final int PC_RESERVED() { return (int)1L; }

    static final int PC_EXPLICIT() { return (int)2L; }

    static final int PC_NOCOLLAPSE() { return (int)4L; }

    static final int TRANSPARENT() { return (int)1L; }

    static final int OPAQUE() { return (int)2L; }

    static final int BKMODE_LAST() { return (int)2L; }

    static final int GM_COMPATIBLE() { return (int)1L; }

    static final int GM_ADVANCED() { return (int)2L; }

    static final int GM_LAST() { return (int)2L; }

    static final int PT_CLOSEFIGURE() { return (int)1L; }

    static final int PT_LINETO() { return (int)2L; }

    static final int PT_BEZIERTO() { return (int)4L; }

    static final int PT_MOVETO() { return (int)6L; }

    static final int MM_TEXT() { return (int)1L; }

    static final int MM_LOMETRIC() { return (int)2L; }

    static final int MM_HIMETRIC() { return (int)3L; }

    static final int MM_LOENGLISH() { return (int)4L; }

    static final int MM_HIENGLISH() { return (int)5L; }

    static final int MM_TWIPS() { return (int)6L; }

    static final int MM_ISOTROPIC() { return (int)7L; }

    static final int MM_ANISOTROPIC() { return (int)8L; }

    static final int ABSOLUTE() { return (int)1L; }

    static final int RELATIVE() { return (int)2L; }

    static final int WHITE_BRUSH() { return (int)0L; }

    static final int LTGRAY_BRUSH() { return (int)1L; }

    static final int GRAY_BRUSH() { return (int)2L; }

    static final int DKGRAY_BRUSH() { return (int)3L; }

    static final int BLACK_BRUSH() { return (int)4L; }

    static final int NULL_BRUSH() { return (int)5L; }

    static final int WHITE_PEN() { return (int)6L; }

    static final int BLACK_PEN() { return (int)7L; }

    static final int NULL_PEN() { return (int)8L; }

    static final int OEM_FIXED_FONT() { return (int)10L; }

    static final int ANSI_FIXED_FONT() { return (int)11L; }

    static final int ANSI_VAR_FONT() { return (int)12L; }

    static final int SYSTEM_FONT() { return (int)13L; }

    static final int DEVICE_DEFAULT_FONT() { return (int)14L; }

    static final int DEFAULT_PALETTE() { return (int)15L; }

    static final int SYSTEM_FIXED_FONT() { return (int)16L; }

    static final int DEFAULT_GUI_FONT() { return (int)17L; }

    static final int DC_BRUSH() { return (int)18L; }

    static final int DC_PEN() { return (int)19L; }

    static final int STOCK_LAST() { return (int)19L; }

    static final int BS_SOLID() { return (int)0L; }

    static final int BS_NULL() { return (int)1L; }

    static final int BS_HATCHED() { return (int)2L; }

    static final int BS_PATTERN() { return (int)3L; }

    static final int BS_INDEXED() { return (int)4L; }

    static final int BS_DIBPATTERN() { return (int)5L; }

    static final int BS_DIBPATTERNPT() { return (int)6L; }

    static final int BS_PATTERN8X8() { return (int)7L; }

    static final int BS_DIBPATTERN8X8() { return (int)8L; }

    static final int BS_MONOPATTERN() { return (int)9L; }

    static final int HS_HORIZONTAL() { return (int)0L; }

    static final int HS_VERTICAL() { return (int)1L; }

    static final int HS_FDIAGONAL() { return (int)2L; }

    static final int HS_BDIAGONAL() { return (int)3L; }

    static final int HS_CROSS() { return (int)4L; }

    static final int HS_DIAGCROSS() { return (int)5L; }

    static final int HS_API_MAX() { return (int)12L; }

    static final int PS_SOLID() { return (int)0L; }

    static final int PS_DASH() { return (int)1L; }

    static final int PS_DOT() { return (int)2L; }

    static final int PS_DASHDOT() { return (int)3L; }

    static final int PS_DASHDOTDOT() { return (int)4L; }

    static final int PS_NULL() { return (int)5L; }

    static final int PS_INSIDEFRAME() { return (int)6L; }

    static final int PS_USERSTYLE() { return (int)7L; }

    static final int PS_ALTERNATE() { return (int)8L; }

    static final int PS_STYLE_MASK() { return (int)15L; }

    static final int PS_ENDCAP_ROUND() { return (int)0L; }

    static final int PS_ENDCAP_SQUARE() { return (int)256L; }

    static final int PS_ENDCAP_FLAT() { return (int)512L; }

    static final int PS_ENDCAP_MASK() { return (int)3840L; }

    static final int PS_JOIN_ROUND() { return (int)0L; }

    static final int PS_JOIN_BEVEL() { return (int)4096L; }

    static final int PS_JOIN_MITER() { return (int)8192L; }

    static final int PS_JOIN_MASK() { return (int)61440L; }

    static final int PS_COSMETIC() { return (int)0L; }

    static final int PS_GEOMETRIC() { return (int)65536L; }

    static final int PS_TYPE_MASK() { return (int)983040L; }

    static final int AD_COUNTERCLOCKWISE() { return (int)1L; }

    static final int AD_CLOCKWISE() { return (int)2L; }

    static final int DRIVERVERSION() { return (int)0L; }

    static final int TECHNOLOGY() { return (int)2L; }

    static final int HORZSIZE() { return (int)4L; }

    static final int VERTSIZE() { return (int)6L; }

    static final int HORZRES() { return (int)8L; }

    static final int VERTRES() { return (int)10L; }

    static final int BITSPIXEL() { return (int)12L; }

    static final int PLANES() { return (int)14L; }

    static final int NUMBRUSHES() { return (int)16L; }

    static final int NUMPENS() { return (int)18L; }

    static final int NUMMARKERS() { return (int)20L; }

    static final int NUMFONTS() { return (int)22L; }

    static final int NUMCOLORS() { return (int)24L; }

    static final int PDEVICESIZE() { return (int)26L; }

    static final int CURVECAPS() { return (int)28L; }

    static final int LINECAPS() { return (int)30L; }

    static final int POLYGONALCAPS() { return (int)32L; }

    static final int TEXTCAPS() { return (int)34L; }

    static final int CLIPCAPS() { return (int)36L; }

    static final int RASTERCAPS() { return (int)38L; }

    static final int ASPECTX() { return (int)40L; }

    static final int ASPECTY() { return (int)42L; }

    static final int ASPECTXY() { return (int)44L; }

    static final int LOGPIXELSX() { return (int)88L; }

    static final int LOGPIXELSY() { return (int)90L; }

    static final int SIZEPALETTE() { return (int)104L; }

    static final int NUMRESERVED() { return (int)106L; }

    static final int COLORRES() { return (int)108L; }

    static final int PHYSICALWIDTH() { return (int)110L; }

    static final int PHYSICALHEIGHT() { return (int)111L; }

    static final int PHYSICALOFFSETX() { return (int)112L; }

    static final int PHYSICALOFFSETY() { return (int)113L; }

    static final int SCALINGFACTORX() { return (int)114L; }

    static final int SCALINGFACTORY() { return (int)115L; }

    static final int VREFRESH() { return (int)116L; }

    static final int DESKTOPVERTRES() { return (int)117L; }

    static final int DESKTOPHORZRES() { return (int)118L; }

    static final int BLTALIGNMENT() { return (int)119L; }

    static final int SHADEBLENDCAPS() { return (int)120L; }

    static final int COLORMGMTCAPS() { return (int)121L; }

    static final int DT_PLOTTER() { return (int)0L; }

    static final int DT_RASDISPLAY() { return (int)1L; }

    static final int DT_RASPRINTER() { return (int)2L; }

    static final int DT_RASCAMERA() { return (int)3L; }

    static final int DT_CHARSTREAM() { return (int)4L; }

    static final int DT_METAFILE() { return (int)5L; }

    static final int DT_DISPFILE() { return (int)6L; }

    static final int CC_NONE() { return (int)0L; }

    static final int CC_CIRCLES() { return (int)1L; }

    static final int CC_PIE() { return (int)2L; }

    static final int CC_CHORD() { return (int)4L; }

    static final int CC_ELLIPSES() { return (int)8L; }

    static final int CC_WIDE() { return (int)16L; }

    static final int CC_STYLED() { return (int)32L; }

    static final int CC_WIDESTYLED() { return (int)64L; }

    static final int CC_INTERIORS() { return (int)128L; }

    static final int CC_ROUNDRECT() { return (int)256L; }

    static final int LC_NONE() { return (int)0L; }

    static final int LC_POLYLINE() { return (int)2L; }

    static final int LC_MARKER() { return (int)4L; }

    static final int LC_POLYMARKER() { return (int)8L; }

    static final int LC_WIDE() { return (int)16L; }

    static final int LC_STYLED() { return (int)32L; }

    static final int LC_WIDESTYLED() { return (int)64L; }

    static final int LC_INTERIORS() { return (int)128L; }

    static final int PC_NONE() { return (int)0L; }

    static final int PC_POLYGON() { return (int)1L; }

    static final int PC_RECTANGLE() { return (int)2L; }

    static final int PC_WINDPOLYGON() { return (int)4L; }

    static final int PC_TRAPEZOID() { return (int)4L; }

    static final int PC_SCANLINE() { return (int)8L; }

    static final int PC_WIDE() { return (int)16L; }

    static final int PC_STYLED() { return (int)32L; }

    static final int PC_WIDESTYLED() { return (int)64L; }

    static final int PC_INTERIORS() { return (int)128L; }

    static final int PC_POLYPOLYGON() { return (int)256L; }

    static final int PC_PATHS() { return (int)512L; }

    static final int CP_NONE() { return (int)0L; }

    static final int CP_RECTANGLE() { return (int)1L; }

    static final int CP_REGION() { return (int)2L; }

    static final int TC_OP_CHARACTER() { return (int)1L; }

    static final int TC_OP_STROKE() { return (int)2L; }

    static final int TC_CP_STROKE() { return (int)4L; }

    static final int TC_CR_90() { return (int)8L; }

    static final int TC_CR_ANY() { return (int)16L; }

    static final int TC_SF_X_YINDEP() { return (int)32L; }

    static final int TC_SA_DOUBLE() { return (int)64L; }

    static final int TC_SA_INTEGER() { return (int)128L; }

    static final int TC_SA_CONTIN() { return (int)256L; }

    static final int TC_EA_DOUBLE() { return (int)512L; }

    static final int TC_IA_ABLE() { return (int)1024L; }

    static final int TC_UA_ABLE() { return (int)2048L; }

    static final int TC_SO_ABLE() { return (int)4096L; }

    static final int TC_RA_ABLE() { return (int)8192L; }

    static final int TC_VA_ABLE() { return (int)16384L; }

    static final int TC_RESERVED() { return (int)32768L; }

    static final int TC_SCROLLBLT() { return (int)65536L; }

    static final int RC_BITBLT() { return (int)1L; }

    static final int RC_BANDING() { return (int)2L; }

    static final int RC_SCALING() { return (int)4L; }

    static final int RC_BITMAP64() { return (int)8L; }

    static final int RC_GDI20_OUTPUT() { return (int)16L; }

    static final int RC_GDI20_STATE() { return (int)32L; }

    static final int RC_SAVEBITMAP() { return (int)64L; }

    static final int RC_DI_BITMAP() { return (int)128L; }

    static final int RC_PALETTE() { return (int)256L; }

    static final int RC_DIBTODEV() { return (int)512L; }

    static final int RC_BIGFONT() { return (int)1024L; }

    static final int RC_STRETCHBLT() { return (int)2048L; }

    static final int RC_FLOODFILL() { return (int)4096L; }

    static final int RC_STRETCHDIB() { return (int)8192L; }

    static final int RC_OP_DX_OUTPUT() { return (int)16384L; }

    static final int RC_DEVBITS() { return (int)32768L; }

    static final int SB_NONE() { return (int)0L; }

    static final int SB_CONST_ALPHA() { return (int)1L; }

    static final int SB_PIXEL_ALPHA() { return (int)2L; }

    static final int SB_PREMULT_ALPHA() { return (int)4L; }

    static final int SB_GRAD_RECT() { return (int)16L; }

    static final int SB_GRAD_TRI() { return (int)32L; }

    static final int CM_NONE() { return (int)0L; }

    static final int CM_DEVICE_ICM() { return (int)1L; }

    static final int CM_GAMMA_RAMP() { return (int)2L; }

    static final int CM_CMYK_COLOR() { return (int)4L; }

    static final int DIB_RGB_COLORS() { return (int)0L; }

    static final int DIB_PAL_COLORS() { return (int)1L; }

    static final int SYSPAL_ERROR() { return (int)0L; }

    static final int SYSPAL_STATIC() { return (int)1L; }

    static final int SYSPAL_NOSTATIC() { return (int)2L; }

    static final int SYSPAL_NOSTATIC256() { return (int)3L; }

    static final int FLOODFILLBORDER() { return (int)0L; }

    static final int FLOODFILLSURFACE() { return (int)1L; }

    static final int CCHDEVICENAME() { return (int)32L; }

    static final int CCHFORMNAME() { return (int)32L; }

    static final int DM_SPECVERSION() { return (int)1025L; }

    static final int DMORIENT_PORTRAIT() { return (int)1L; }

    static final int DMORIENT_LANDSCAPE() { return (int)2L; }

    static final int DMPAPER_LETTER() { return (int)1L; }

    static final int DMPAPER_LETTERSMALL() { return (int)2L; }

    static final int DMPAPER_TABLOID() { return (int)3L; }

    static final int DMPAPER_LEDGER() { return (int)4L; }

    static final int DMPAPER_LEGAL() { return (int)5L; }

    static final int DMPAPER_STATEMENT() { return (int)6L; }

    static final int DMPAPER_EXECUTIVE() { return (int)7L; }

    static final int DMPAPER_A3() { return (int)8L; }

    static final int DMPAPER_A4() { return (int)9L; }

    static final int DMPAPER_A4SMALL() { return (int)10L; }

    static final int DMPAPER_A5() { return (int)11L; }

    static final int DMPAPER_B4() { return (int)12L; }

    static final int DMPAPER_B5() { return (int)13L; }

    static final int DMPAPER_FOLIO() { return (int)14L; }

    static final int DMPAPER_QUARTO() { return (int)15L; }

    static final int DMPAPER_10X14() { return (int)16L; }

    static final int DMPAPER_11X17() { return (int)17L; }

    static final int DMPAPER_NOTE() { return (int)18L; }

    static final int DMPAPER_ENV_9() { return (int)19L; }

    static final int DMPAPER_ENV_10() { return (int)20L; }

    static final int DMPAPER_ENV_11() { return (int)21L; }

    static final int DMPAPER_ENV_12() { return (int)22L; }

    static final int DMPAPER_ENV_14() { return (int)23L; }

    static final int DMPAPER_CSHEET() { return (int)24L; }

    static final int DMPAPER_DSHEET() { return (int)25L; }

    static final int DMPAPER_ESHEET() { return (int)26L; }

    static final int DMPAPER_ENV_DL() { return (int)27L; }

    static final int DMPAPER_ENV_C5() { return (int)28L; }

    static final int DMPAPER_ENV_C3() { return (int)29L; }

    static final int DMPAPER_ENV_C4() { return (int)30L; }

    static final int DMPAPER_ENV_C6() { return (int)31L; }

    static final int DMPAPER_ENV_C65() { return (int)32L; }

    static final int DMPAPER_ENV_B4() { return (int)33L; }

    static final int DMPAPER_ENV_B5() { return (int)34L; }

    static final int DMPAPER_ENV_B6() { return (int)35L; }

    static final int DMPAPER_ENV_ITALY() { return (int)36L; }

    static final int DMPAPER_ENV_MONARCH() { return (int)37L; }

    static final int DMPAPER_ENV_PERSONAL() { return (int)38L; }

    static final int DMPAPER_FANFOLD_US() { return (int)39L; }

    static final int DMPAPER_FANFOLD_STD_GERMAN() { return (int)40L; }

    static final int DMPAPER_FANFOLD_LGL_GERMAN() { return (int)41L; }

    static final int DMPAPER_ISO_B4() { return (int)42L; }

    static final int DMPAPER_JAPANESE_POSTCARD() { return (int)43L; }

    static final int DMPAPER_9X11() { return (int)44L; }

    static final int DMPAPER_10X11() { return (int)45L; }

    static final int DMPAPER_15X11() { return (int)46L; }

    static final int DMPAPER_ENV_INVITE() { return (int)47L; }

    static final int DMPAPER_RESERVED_48() { return (int)48L; }

    static final int DMPAPER_RESERVED_49() { return (int)49L; }

    static final int DMPAPER_LETTER_EXTRA() { return (int)50L; }

    static final int DMPAPER_LEGAL_EXTRA() { return (int)51L; }

    static final int DMPAPER_TABLOID_EXTRA() { return (int)52L; }

    static final int DMPAPER_A4_EXTRA() { return (int)53L; }

    static final int DMPAPER_LETTER_TRANSVERSE() { return (int)54L; }

    static final int DMPAPER_A4_TRANSVERSE() { return (int)55L; }

    static final int DMPAPER_LETTER_EXTRA_TRANSVERSE() { return (int)56L; }

    static final int DMPAPER_A_PLUS() { return (int)57L; }

    static final int DMPAPER_B_PLUS() { return (int)58L; }

    static final int DMPAPER_LETTER_PLUS() { return (int)59L; }

    static final int DMPAPER_A4_PLUS() { return (int)60L; }

    static final int DMPAPER_A5_TRANSVERSE() { return (int)61L; }

    static final int DMPAPER_B5_TRANSVERSE() { return (int)62L; }

    static final int DMPAPER_A3_EXTRA() { return (int)63L; }

    static final int DMPAPER_A5_EXTRA() { return (int)64L; }

    static final int DMPAPER_B5_EXTRA() { return (int)65L; }

    static final int DMPAPER_A2() { return (int)66L; }

    static final int DMPAPER_A3_TRANSVERSE() { return (int)67L; }

    static final int DMPAPER_A3_EXTRA_TRANSVERSE() { return (int)68L; }

    static final int DMPAPER_DBL_JAPANESE_POSTCARD() { return (int)69L; }

    static final int DMPAPER_A6() { return (int)70L; }

    static final int DMPAPER_JENV_KAKU2() { return (int)71L; }

    static final int DMPAPER_JENV_KAKU3() { return (int)72L; }

    static final int DMPAPER_JENV_CHOU3() { return (int)73L; }

    static final int DMPAPER_JENV_CHOU4() { return (int)74L; }

    static final int DMPAPER_LETTER_ROTATED() { return (int)75L; }

    static final int DMPAPER_A3_ROTATED() { return (int)76L; }

    static final int DMPAPER_A4_ROTATED() { return (int)77L; }

    static final int DMPAPER_A5_ROTATED() { return (int)78L; }

    static final int DMPAPER_B4_JIS_ROTATED() { return (int)79L; }

    static final int DMPAPER_B5_JIS_ROTATED() { return (int)80L; }

    static final int DMPAPER_JAPANESE_POSTCARD_ROTATED() { return (int)81L; }

    static final int DMPAPER_DBL_JAPANESE_POSTCARD_ROTATED() { return (int)82L; }

    static final int DMPAPER_A6_ROTATED() { return (int)83L; }

    static final int DMPAPER_JENV_KAKU2_ROTATED() { return (int)84L; }

    static final int DMPAPER_JENV_KAKU3_ROTATED() { return (int)85L; }

    static final int DMPAPER_JENV_CHOU3_ROTATED() { return (int)86L; }

    static final int DMPAPER_JENV_CHOU4_ROTATED() { return (int)87L; }

    static final int DMPAPER_B6_JIS() { return (int)88L; }

    static final int DMPAPER_B6_JIS_ROTATED() { return (int)89L; }

    static final int DMPAPER_12X11() { return (int)90L; }

    static final int DMPAPER_JENV_YOU4() { return (int)91L; }

    static final int DMPAPER_JENV_YOU4_ROTATED() { return (int)92L; }

    static final int DMPAPER_P16K() { return (int)93L; }

    static final int DMPAPER_P32K() { return (int)94L; }

    static final int DMPAPER_P32KBIG() { return (int)95L; }

    static final int DMPAPER_PENV_1() { return (int)96L; }

    static final int DMPAPER_PENV_2() { return (int)97L; }

    static final int DMPAPER_PENV_3() { return (int)98L; }

    static final int DMPAPER_PENV_4() { return (int)99L; }

    static final int DMPAPER_PENV_5() { return (int)100L; }

    static final int DMPAPER_PENV_6() { return (int)101L; }

    static final int DMPAPER_PENV_7() { return (int)102L; }

    static final int DMPAPER_PENV_8() { return (int)103L; }

    static final int DMPAPER_PENV_9() { return (int)104L; }

    static final int DMPAPER_PENV_10() { return (int)105L; }

    static final int DMPAPER_P16K_ROTATED() { return (int)106L; }

    static final int DMPAPER_P32K_ROTATED() { return (int)107L; }

    static final int DMPAPER_P32KBIG_ROTATED() { return (int)108L; }

    static final int DMPAPER_PENV_1_ROTATED() { return (int)109L; }

    static final int DMPAPER_PENV_2_ROTATED() { return (int)110L; }

    static final int DMPAPER_PENV_3_ROTATED() { return (int)111L; }

    static final int DMPAPER_PENV_4_ROTATED() { return (int)112L; }

    static final int DMPAPER_PENV_5_ROTATED() { return (int)113L; }

    static final int DMPAPER_PENV_6_ROTATED() { return (int)114L; }

    static final int DMPAPER_PENV_7_ROTATED() { return (int)115L; }

    static final int DMPAPER_PENV_8_ROTATED() { return (int)116L; }

    static final int DMPAPER_PENV_9_ROTATED() { return (int)117L; }

    static final int DMPAPER_PENV_10_ROTATED() { return (int)118L; }

    static final int DMPAPER_USER() { return (int)256L; }

    static final int DMBIN_UPPER() { return (int)1L; }

    static final int DMBIN_ONLYONE() { return (int)1L; }

    static final int DMBIN_LOWER() { return (int)2L; }

    static final int DMBIN_MIDDLE() { return (int)3L; }

    static final int DMBIN_MANUAL() { return (int)4L; }

    static final int DMBIN_ENVELOPE() { return (int)5L; }

    static final int DMBIN_ENVMANUAL() { return (int)6L; }

    static final int DMBIN_AUTO() { return (int)7L; }

    static final int DMBIN_TRACTOR() { return (int)8L; }

    static final int DMBIN_SMALLFMT() { return (int)9L; }

    static final int DMBIN_LARGEFMT() { return (int)10L; }

    static final int DMBIN_LARGECAPACITY() { return (int)11L; }

    static final int DMBIN_CASSETTE() { return (int)14L; }

    static final int DMBIN_FORMSOURCE() { return (int)15L; }

    static final int DMBIN_USER() { return (int)256L; }

    static final int DMCOLOR_MONOCHROME() { return (int)1L; }

    static final int DMCOLOR_COLOR() { return (int)2L; }

    static final int DMDUP_SIMPLEX() { return (int)1L; }

    static final int DMDUP_VERTICAL() { return (int)2L; }

    static final int DMDUP_HORIZONTAL() { return (int)3L; }

    static final int DMTT_BITMAP() { return (int)1L; }

    static final int DMTT_DOWNLOAD() { return (int)2L; }

    static final int DMTT_SUBDEV() { return (int)3L; }

    static final int DMTT_DOWNLOAD_OUTLINE() { return (int)4L; }

    static final int DMCOLLATE_FALSE() { return (int)0L; }

    static final int DMCOLLATE_TRUE() { return (int)1L; }

    static final int DMDO_DEFAULT() { return (int)0L; }

    static final int DMDO_90() { return (int)1L; }

    static final int DMDO_180() { return (int)2L; }

    static final int DMDO_270() { return (int)3L; }

    static final int DMDFO_DEFAULT() { return (int)0L; }

    static final int DMDFO_STRETCH() { return (int)1L; }

    static final int DMDFO_CENTER() { return (int)2L; }

    static final int DM_INTERLACED() { return (int)2L; }

    static final int DMDISPLAYFLAGS_TEXTMODE() { return (int)4L; }

    static final int DMNUP_SYSTEM() { return (int)1L; }

    static final int DMNUP_ONEUP() { return (int)2L; }

    static final int DMICMMETHOD_NONE() { return (int)1L; }

    static final int DMICMMETHOD_SYSTEM() { return (int)2L; }

    static final int DMICMMETHOD_DRIVER() { return (int)3L; }

    static final int DMICMMETHOD_DEVICE() { return (int)4L; }

    static final int DMICMMETHOD_USER() { return (int)256L; }

    static final int DMICM_SATURATE() { return (int)1L; }

    static final int DMICM_CONTRAST() { return (int)2L; }

    static final int DMICM_COLORIMETRIC() { return (int)3L; }

    static final int DMICM_ABS_COLORIMETRIC() { return (int)4L; }

    static final int DMICM_USER() { return (int)256L; }

    static final int DMMEDIA_STANDARD() { return (int)1L; }

    static final int DMMEDIA_TRANSPARENCY() { return (int)2L; }

    static final int DMMEDIA_GLOSSY() { return (int)3L; }

    static final int DMMEDIA_USER() { return (int)256L; }

    static final int DMDITHER_NONE() { return (int)1L; }

    static final int DMDITHER_COARSE() { return (int)2L; }

    static final int DMDITHER_FINE() { return (int)3L; }

    static final int DMDITHER_LINEART() { return (int)4L; }

    static final int DMDITHER_ERRORDIFFUSION() { return (int)5L; }

    static final int DMDITHER_RESERVED6() { return (int)6L; }

    static final int DMDITHER_RESERVED7() { return (int)7L; }

    static final int DMDITHER_RESERVED8() { return (int)8L; }

    static final int DMDITHER_RESERVED9() { return (int)9L; }

    static final int DMDITHER_GRAYSCALE() { return (int)10L; }

    static final int DMDITHER_USER() { return (int)256L; }

    static final int DISPLAY_DEVICE_ATTACHED_TO_DESKTOP() { return (int)1L; }

    static final int DISPLAY_DEVICE_MULTI_DRIVER() { return (int)2L; }

    static final int DISPLAY_DEVICE_PRIMARY_DEVICE() { return (int)4L; }

    static final int DISPLAY_DEVICE_MIRRORING_DRIVER() { return (int)8L; }

    static final int DISPLAY_DEVICE_VGA_COMPATIBLE() { return (int)16L; }

    static final int DISPLAY_DEVICE_REMOVABLE() { return (int)32L; }

    static final int DISPLAY_DEVICE_ACC_DRIVER() { return (int)64L; }

    static final int DISPLAY_DEVICE_MODESPRUNED() { return (int)134217728L; }

    static final int DISPLAY_DEVICE_RDPUDD() { return (int)16777216L; }

    static final int DISPLAY_DEVICE_REMOTE() { return (int)67108864L; }

    static final int DISPLAY_DEVICE_DISCONNECT() { return (int)33554432L; }

    static final int DISPLAY_DEVICE_TS_COMPATIBLE() { return (int)2097152L; }

    static final int DISPLAY_DEVICE_UNSAFE_MODES_ON() { return (int)524288L; }

    static final int DISPLAY_DEVICE_ACTIVE() { return (int)1L; }

    static final int DISPLAY_DEVICE_ATTACHED() { return (int)2L; }

    static final int DISPLAYCONFIG_MAXPATH() { return (int)1024L; }

    static final int DISPLAYCONFIG_PATH_TARGET_MODE_IDX_INVALID() { return (int)65535L; }

    static final int DISPLAYCONFIG_PATH_DESKTOP_IMAGE_IDX_INVALID() { return (int)65535L; }

    static final int DISPLAYCONFIG_PATH_SOURCE_MODE_IDX_INVALID() { return (int)65535L; }

    static final int DISPLAYCONFIG_PATH_CLONE_GROUP_INVALID() { return (int)65535L; }

    static final int DISPLAYCONFIG_SOURCE_IN_USE() { return (int)1L; }

    static final int DISPLAYCONFIG_TARGET_IN_USE() { return (int)1L; }

    static final int DISPLAYCONFIG_TARGET_FORCIBLE() { return (int)2L; }

    static final int DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_BOOT() { return (int)4L; }

    static final int DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_PATH() { return (int)8L; }

    static final int DISPLAYCONFIG_TARGET_FORCED_AVAILABILITY_SYSTEM() { return (int)16L; }

    static final int DISPLAYCONFIG_TARGET_IS_HMD() { return (int)32L; }

    static final int DISPLAYCONFIG_PATH_ACTIVE() { return (int)1L; }

    static final int DISPLAYCONFIG_PATH_PREFERRED_UNSCALED() { return (int)4L; }

    static final int DISPLAYCONFIG_PATH_SUPPORT_VIRTUAL_MODE() { return (int)8L; }

    static final int DISPLAYCONFIG_PATH_VALID_FLAGS() { return (int)13L; }

    static final int QDC_ALL_PATHS() { return (int)1L; }

    static final int QDC_ONLY_ACTIVE_PATHS() { return (int)2L; }

    static final int QDC_DATABASE_CURRENT() { return (int)4L; }

    static final int QDC_VIRTUAL_MODE_AWARE() { return (int)16L; }

    static final int QDC_INCLUDE_HMD() { return (int)32L; }

    static final int SDC_TOPOLOGY_INTERNAL() { return (int)1L; }

    static final int SDC_TOPOLOGY_CLONE() { return (int)2L; }

    static final int SDC_TOPOLOGY_EXTEND() { return (int)4L; }

    static final int SDC_TOPOLOGY_EXTERNAL() { return (int)8L; }

    static final int SDC_TOPOLOGY_SUPPLIED() { return (int)16L; }

    static final int SDC_USE_SUPPLIED_DISPLAY_CONFIG() { return (int)32L; }

    static final int SDC_VALIDATE() { return (int)64L; }

    static final int SDC_APPLY() { return (int)128L; }

    static final int SDC_NO_OPTIMIZATION() { return (int)256L; }

    static final int SDC_SAVE_TO_DATABASE() { return (int)512L; }

    static final int SDC_ALLOW_CHANGES() { return (int)1024L; }

    static final int SDC_PATH_PERSIST_IF_REQUIRED() { return (int)2048L; }

    static final int SDC_FORCE_MODE_ENUMERATION() { return (int)4096L; }

    static final int SDC_ALLOW_PATH_ORDER_CHANGES() { return (int)8192L; }

    static final int SDC_VIRTUAL_MODE_AWARE() { return (int)32768L; }

    static final int RDH_RECTANGLES() { return (int)1L; }

    static final int SYSRGN() { return (int)4L; }

    static final int GGO_METRICS() { return (int)0L; }

    static final int GGO_BITMAP() { return (int)1L; }

    static final int GGO_NATIVE() { return (int)2L; }

    static final int GGO_BEZIER() { return (int)3L; }

    static final int GGO_GRAY2_BITMAP() { return (int)4L; }

    static final int GGO_GRAY4_BITMAP() { return (int)5L; }

    static final int GGO_GRAY8_BITMAP() { return (int)6L; }

    static final int GGO_GLYPH_INDEX() { return (int)128L; }

    static final int GGO_UNHINTED() { return (int)256L; }

    static final int TT_POLYGON_TYPE() { return (int)24L; }

    static final int TT_PRIM_LINE() { return (int)1L; }

    static final int TT_PRIM_QSPLINE() { return (int)2L; }

    static final int TT_PRIM_CSPLINE() { return (int)3L; }

    static final int GCP_DBCS() { return (int)1L; }

    static final int GCP_REORDER() { return (int)2L; }

    static final int GCP_USEKERNING() { return (int)8L; }

    static final int GCP_GLYPHSHAPE() { return (int)16L; }

    static final int GCP_LIGATE() { return (int)32L; }

    static final int GCP_DIACRITIC() { return (int)256L; }

    static final int GCP_KASHIDA() { return (int)1024L; }

    static final int GCP_ERROR() { return (int)32768L; }

    static final int FLI_MASK() { return (int)4155L; }

    static final int GCPCLASS_LATIN() { return (int)1L; }

    static final int GCPCLASS_HEBREW() { return (int)2L; }

    static final int GCPCLASS_ARABIC() { return (int)2L; }

    static final int GCPCLASS_NEUTRAL() { return (int)3L; }

    static final int GCPCLASS_LOCALNUMBER() { return (int)4L; }

    static final int GCPCLASS_LATINNUMBER() { return (int)5L; }

    static final int GCPCLASS_LATINNUMERICTERMINATOR() { return (int)6L; }

    static final int GCPCLASS_LATINNUMERICSEPARATOR() { return (int)7L; }

    static final int GCPCLASS_NUMERICSEPARATOR() { return (int)8L; }

    static final int GCPCLASS_PREBOUNDLTR() { return (int)128L; }

    static final int GCPCLASS_PREBOUNDRTL() { return (int)64L; }

    static final int GCPCLASS_POSTBOUNDLTR() { return (int)32L; }

    static final int GCPCLASS_POSTBOUNDRTL() { return (int)16L; }

    static final int GCPGLYPH_LINKBEFORE() { return (int)32768L; }

    static final int GCPGLYPH_LINKAFTER() { return (int)16384L; }

    static final int TT_AVAILABLE() { return (int)1L; }

    static final int TT_ENABLED() { return (int)2L; }

    static final int PFD_TYPE_RGBA() { return (int)0L; }

    static final int PFD_TYPE_COLORINDEX() { return (int)1L; }

    static final int PFD_MAIN_PLANE() { return (int)0L; }

    static final int PFD_OVERLAY_PLANE() { return (int)1L; }

    static final int PFD_DOUBLEBUFFER() { return (int)1L; }

    static final int PFD_STEREO() { return (int)2L; }

    static final int PFD_DRAW_TO_WINDOW() { return (int)4L; }

    static final int PFD_DRAW_TO_BITMAP() { return (int)8L; }

    static final int PFD_SUPPORT_GDI() { return (int)16L; }

    static final int PFD_SUPPORT_OPENGL() { return (int)32L; }

    static final int PFD_GENERIC_FORMAT() { return (int)64L; }

    static final int PFD_NEED_PALETTE() { return (int)128L; }

    static final int PFD_NEED_SYSTEM_PALETTE() { return (int)256L; }

    static final int PFD_SWAP_EXCHANGE() { return (int)512L; }

    static final int PFD_SWAP_COPY() { return (int)1024L; }

    static final int PFD_SWAP_LAYER_BUFFERS() { return (int)2048L; }

    static final int PFD_GENERIC_ACCELERATED() { return (int)4096L; }

    static final int PFD_SUPPORT_DIRECTDRAW() { return (int)8192L; }

}

